export const YOUR_PROFILE_URL = '/profile';

export const RELATIONSHIP = {
  CHILD: 'Child',
  SPOUSE: 'Spouse',
};

export const newFormPages = {
  newApplicantInformation: 'newApplicantInformation',
  newContactInformation: {
    newContactInformation: 'newContactInformation',
    newMailingAddress: 'newMailingAddress',
    newPreferredContactMethod: 'newPreferredContactMethod',
  },
  newServiceHistory: 'newServiceHistory',
  newBenefitSelection: 'newBenefitSelection',
  newDirectDeposit: 'newDirectDeposit',
  newFirstSponsorSelection: 'newFirstSponsorSelection',
  newSponsorInformation: 'newSponsorInformation',
  newSponsorHighSchool: 'newSponsorHighSchool',
  newSponsorSelection: 'newSponsorSelection',
  newSponsorSelectionReview: 'newSponsorSelectionReview',
  newVerifyHighSchool: 'newVerifyHighSchool',
};

export const newFormFields = {
  newAccountNumber: 'newAccountNumber',
  newAccountType: 'newAccountType',
  newActiveDutyKicker: 'newActiveDutyKicker',
  newAdditionalConsiderationsNote: 'newAdditionalConsiderationsNote',
  newAddress: 'newAddress',
  newBankAccount: 'newBankAccount',
  newContactMethod: 'newContactMethod',
  newConfirmEmail: 'newConfirmEmail',
  newDateOfBirth: 'newDateOfBirth',
  newEmail: 'newEmail',
  newFederallySponsoredAcademy: 'newFederallySponsoredAcademy',
  firstSponsor: 'firstSponsor',
  newFullName: 'newFullName',
  newHasDoDLoanPaymentPeriod: 'newHasDoDLoanPaymentPeriod',
  newHighSchoolDiploma: 'newHighSchoolDiploma',
  newHighSchoolDiplomaDate: 'newHighSchoolDiplomaDate',
  newIncorrectServiceHistoryExplanation:
    'newIncorrectServiceHistoryExplanation',
  newLoanPayment: 'newLoanPayment',
  newMobilePhoneNumber: 'newMobilePhoneNumber',
  newMobilePhoneNumberInternational: 'newMobilePhoneNumberInternational',
  newParentGuardianSponsor: 'newParentGuardianSponsor',
  newPhoneNumber: 'newPhoneNumber',
  newPhoneNumberInternational: 'newPhoneNumberInternational',
  newRelationshipToServiceMember: 'newRelationshipToServiceMember',
  newReceiveTextMessages: 'newReceiveTextMessages',
  newRoutingNumber: 'newRoutingNumber',
  newServiceHistoryIncorrect: 'newServiceHistoryIncorrect',
  selectedSponsors: 'selectedSponsors',
  newSponsorDateOfBirth: 'newSponsorDateOfBirth',
  newSponsorFullName: 'newSponsorFullName',
  newSsn: 'newSsn',
  newToursOfDuty: 'newToursOfDuty',
  newUserFullName: 'newUserFullName',
  newViewBenefitSelection: 'view:newBenefitSelection',
  newViewNoDirectDeposit: 'view:newNoDirectDeposit',
  newViewPhoneNumbers: 'view:newPhoneNumbers',
  newViewSelectedSponsor: 'view:newSelectedSponsor',
  newViewStopWarning: 'view:newStopWarning',
};
