export const SEARCH_QUERY_UPDATED = 'SEARCH_QUERY_UPDATED';
export const FETCH_LOCATION_DETAIL = 'FETCH_LOCATION_DETAIL';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';

export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_COMPLETE = 'SEARCH_COMPLETE';
