export const SEARCH_QUERY_UPDATED = 'SEARCH_QUERY_UPDATED';
export const LOCATION_UPDATED = 'LOCATION_UPDATED';
export const FETCH_VA_FACILITY = 'FETCH_VA_FACILITY';
export const FETCH_VA_FACILITIES = 'FETCH_VA_FACILITIES';
export const FETCH_CC_PROVIDERS = 'FETCH_CC_PROVIDERS';

export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_FAILED = 'SEARCH_FAILED';
