export const FETCH_FORMS = 'findVAForms/FETCH_FORMS';
export const FETCH_FORMS_FAILURE = 'findVAForms/FETCH_FORMS_FAILURE';
export const FETCH_FORMS_SUCCESS = 'findVAForms/FETCH_FORMS_SUCCESS';
export const UPDATE_PAGINATION = 'findVAForms/UPDATE_PAGINATION';
export const SORT_OPTIONS = ['Last Updated (Newest)', 'Last Updated (Oldest)'];
export const INITIAL_SORT_STATE = 'Last Updated (Newest)';
export const FORM_MOMENT_DATE_FORMAT = 'MM-DD-YYYY';
export const UPDATE_HOW_TO_SORT = 'findVAForms/UPDATE_HOW_TO_SORT';
export const UPDATE_RESULTS = 'findVAForms/UPDATE_RESULTS';
