export const FETCH_FORMS = 'findVAForms/FETCH_FORMS';
export const FETCH_FORMS_FAILURE = 'findVAForms/FETCH_FORMS_FAILURE';
export const FETCH_FORMS_SUCCESS = 'findVAForms/FETCH_FORMS_SUCCESS';
export const UPDATE_PAGINATION = 'findVAForms/UPDATE_PAGINATION';
