export const SELECTORS = {
  APP: '[data-e2e-id="find-form-search-form"]',
  WIDGET: '[data-widget-type="find-va-forms"]',
  FINDFORM_INPUT_ROOT: 'va-search-input',
  FINDFORM_INPUT: 'input',
  FINDFORM_SEARCH: 'button',
  FINDFORM_ERROR_BODY: '[data-e2e-id="find-form-error-body"]',
  FINDFORM_REQUIRED: '[data-e2e-id="find-form-required"]',
  FINDFORM_ERROR_MSG: '[data-e2e-id="find-form-error-message"]',
  SEARCH_RESULT_TITLE: '[data-e2e-id="result-title"]',
  NEXT_PAGE: '.usa-pagination__list > li[aria-label="Next page"] > a',
  SORT_SELECT_WIDGET: 'va-select[name="findFormsSortBySelect"]',
  ADOBE_LINK: '[data-e2e-id="adobe-link"]',
  MODAL_DOWNLOAD_LINK: '[data-e2e-id="modal-download-link"]',
  MODAL_CLOSE_BUTTON: '.va-modal-close',
  MODAL: 'va-modal',
  FORM_DETAIL_HEADER: '[data-testid="va_form--downloadable-pdf"]',
};
