export const DEPENDENT_AGE_LABELS = {
  1: "First dependent's age",
  2: "Second dependent's age",
  3: "Third dependent's age",
  4: "Fourth dependent's age",
  5: "Fifth dependent's age",
  6: "Sixth dependent's age",
  7: "Seventh dependent's age",
  8: "Eighth dependent's age",
  9: "Ninth dependent's age",
  10: "Tenth dependent's age",
  11: "11th dependent's age",
  12: "12th dependent's age",
  13: "13th dependent's age",
  14: "14th dependent's age",
  15: "15th dependent's age",
  16: "16th dependent's age",
  17: "17th dependent's age",
  18: "18th dependent's age",
  19: "19th dependent's age",
  20: "20th dependent's age",
  21: "21st dependent's age",
  22: "22nd dependent's age",
  23: "23rd dependent's age",
  24: "24th dependent's age",
  25: "25th dependent's age",
};
