export const DEPENDENT_AGE_LABELS = {
  1: `First dependent's age`,
  2: `Second dependent's age`,
  3: `Third dependent's age`,
  4: `Fourth dependent's age`,
  5: `Fifth dependent's age`,
  6: `Sixth dependent's age`,
  7: `Seventh dependent's age`,
  8: `Eighth dependent's age`,
  9: `Ninth dependent's  age`,
  10: `Tenth dependent's age`,
  11: `Eleventh dependent's age`,
  12: `Twelfth dependent's age`,
  13: `Thirteenth dependent's age`,
  14: `Fourteenth dependent's age`,
  15: `Fifteenth dependent's age`,
  16: `Sixteenth dependent's age`,
  17: `Seventeenth dependent's age`,
  18: `Eighteenth dependent's age`,
  19: `Nineteenth dependent's age`,
  20: `Twentieth dependent's age`,
};
