export const formatOptions = options => {
  return options
    .sort((a, b) => (a > b ? 1 : -1))
    .map(item => ({
      label: item,
    }));
};

export const utilityTypes = [
  'Electricity',
  'Gas',
  'Water',
  'Sewer',
  'Internet',
  'Cell phone',
  'Telephone',
  'Cable',
  'Heating fuel',
  'Kerosene',
  'Wood pellets',
  'Corn',
  'Coal',
  'Propane',
  'Trash',
];

export const deductionTypes = [
  'State tax',
  'Federal tax',
  'Local tax',
  'Garnishment',
  'Life insurance',
  'Health insurance',
  '401K',
  'IRA',
  'Pension',
  'FICA (Social Security and Medicare)',
  'Allotment',
];

export const incomeTypes = [
  'Bonus payment',
  'Alimony payment',
  'Child support payment',
  'Rental property income',
  'Leased acreage or land income',
  'Child care income',
  'Caretaker income',
  'Babysitting income',
  'Mowing or yard care service',
  'Handyman service',
  'Freelance service',
  'Car washing and detailing service',
  'Pet sitting service',
  'House sitting service',
  'Housekeeping service',
  'Maid service',
  'House painting service',
  'Substitute teaching',
  'Postmates service',
  'DoorDash service',
  'Waiter service',
  'InstaCart service',
  'AirBnB service',
  'GetAround service',
  'Uber service',
  'Lyft service',
  'Retirement payments',
  'Non-VA pension payments',
  'Unemployment payments',
  'Dividend income',
];

export const realEstateTypes = [
  'Single-family home',
  'Multi-family dwelling',
  'Vacation property',
  'Apartment',
  'Condominium',
  'Townhouse',
  'Mobile home',
  'Business property',
  'Farm',
  'Hobby farm',
  'Acreage or land',
];

export const recreationalVehicleTypes = [
  'Recreational vehicle (RV)',
  'Motorhome',
  'Boat',
  'Kayak',
  'Raft',
  'Canoe',
  'Gondola',
  'Rowboat',
  'Paddle boat',
  'Inflatable boat',
  'Sailboat',
  'Monohull sailboat',
  'Catamaran sailboat',
  'Trimaran sailboat',
  'Sloop',
  'Schooner',
  'Cutter',
  'Ketch',
  'Yawl',
  'Catboat',
  'Motorboat',
  'Fishing boat',
  'Deep sea boat',
  'Yacht',
  'Deck boat',
  'Trawler',
  'Cabin cruiser',
  'Swamp boat',
  'Runabout boat',
  'Wakeboard boat',
  'Ski boat',
  'Pontoon',
  'Houseboat',
  'Camper',
  'All-terrain vehicle (ATV)',
  'Four-wheeler',
  'Bus',
  'Golf cart',
  'Moped',
  'Scooter',
  'Jet ski',
  'Airplane',
  'Helicopter',
  'Snowmobile',
];

export const assetTypes = [
  'Treasury bills (T-bills)',
  'Money market accounts',
  'Investment funds',
  'Certificates of deposit (CD)',
  'Insurance policies and annuities',
  '401K',
  'Pension',
  'Gambling earning',
  'Inheritance',
  'Legal settlement',
  'Patent, license or permit holdings',
  'Retirement funds',
  'Royalties, copyrights and trademarks',
  'Oil or mineral rights or leases',
  'Air, water or land rights',
  'Precious metals ',
  'Gold',
  'Silver',
  'Franchise agreements',
  'Bitcoin',
  'Jewelry (based on appraised value)',
  'Antiques (based on appraised value)',
  'Furniture (based on appraised value)',
  'Artwork (based on appraised value)',
  'Collectibles or collections (based on appraised value)',
];

export const expenseTypes = [
  'Clothes',
  'Hair styling (barber, beauty)',
  'Dry cleaning/laundry',
  'Diapers, formula and baby food',
  'Tithes',
  'Charitable giving',
  'Lawn service',
  'Pool service',
  'Household maintenance',
  'Extermination ',
  'Cleaning service',
  'Home repair',
  'Child care services',
  'Elder care services',
  'Home health care services',
  'Disability care services',
  'Nursing home services',
  'Rehabilitation services',
  'Rehabilitation home services',
  'Babysitting services',
  'School meals',
  'School supplies',
  'School uniforms',
  'Special education program',
  'Prescriptions/medications',
  'Public transportation',
  'Ferry charge',
  'Car rental service',
  'Gasoline/diesel fuel',
  'Animal/pet care',
];

export const installmentTypes = [
  'Car payment/lease',
  'Truck payment/lease',
  'Motorcycle payment/lease',
  'Moped or scooter payment',
  'Recreational vehicle (RV)/camper payment',
  'Boat payment',
  'Trailer payment',
  'All-terrain vehicle (ATV) payment',
  'Snowmobile payment',
  'Airplane payment',
  'Helicopter payment',
  'Appliance payment',
  'Credit card payments',
  'Court-imposed legal fees ',
  'Legal fines or assessments',
  'Probation fees',
  'Victim restitution',
  'Attorney costs',
  'Child support payments',
  'Alimony payments',
  'Hangar rental',
  'Slip or dock rental',
  'Storage unit(s)',
  'Doctor payment',
  'Outpatient surgery payment',
  'Hospital payment',
  'Medical transportation',
  'Medical devices',
  'Medical accessories',
  'Dentist payment',
  'Vision payment',
  'Student loans',
  'School or college endowment',
  'College savings plan',
  'School tuition',
  'Homeowner insurance',
  'Private mortgage insurance',
  'Vehicle(s) insurance',
  'Uninsured motorist insurance',
  'Renters’ insurance',
  'Flood insurance',
  'Earthquake insurance',
  'Agriculture/farm/crop insurance',
  'Liability/umbrella insurance',
  'Health insurance',
  'Life insurance',
  'Disability/illness insurance',
  'Medicare payment',
  'Medicare supplemental insurance',
  'Gym or fitness membership payment',
  'Parking',
  'Tolls',
  'Veterinary bill',
];
