version: "2"         # required to adjust maintainability checks
plugins:
  eslint:
    enabled: false
exclude_patterns:
- 'config/'
- 'db/'
- 'dist/'
- 'features/'
- '**/node_modules/'
- 'script/'
- '**/vendor/'
- '**/*_test.go'
- '**/*.d.ts'
