apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: VA.gov
  name: vets-website
  description: This is the front end for VA.gov.
  annotations:
    github.com/project-slug: department-of-veterans-affairs/vets-website
  tags:
    - javascript
    - sass
  links:
    - url: https://va-gov.domo.com/page/426422632
      title: Content KPIs (Domo)
      icon: dashboard
    - url: https://va-gov.domo.com/page/447193050
      title: Forms KPIs (Domo)
      icon: dashboard
    - url: https://va-gov.domo.com/page/1964748112
      title: Search KPIs (Domo)
      icon: dashboard
    - url: https://tud.vfs.va.gov
      title: Test User Dashboard
      icon: dashboard
spec:
  owner: va-platform-cop-frontend
  domain: vfs
