apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: VA.gov
  name: vets-website
  description: This is the front end for VA.gov.
  annotations:
    github.com/project-slug: department-of-veterans-affairs/vets-website
  tags:
    - javascript
    - sass
spec:
  owner: platform-release-tools
  domain: vfs
