version: '3'
services:
  vets-website:
    image: vets-website:${IMAGE_TAG:-latest}
    build:
      context: .
    volumes:
      - .:/application
    environment:
      WEB_HOST: 'vets-website'
      WEB_PORT: 3001
      API_HOST: 'vets-website'
    expose:
      - 3001
      - 3000
      - 9515
    command: ./script/run-docker-test-server.sh
    ipc: host
