export const AXE_CONTEXT = '.secure-messaging-container';

export const Paths = {
  UI_MAIN: '/my-health/secure-messages',
  SM_API_BASE: '/my_health/v1/messaging',
  SM_API_EXTENDED: '/my_health/v1/messaging/messages',
  INBOX: '/inbox/',
  SENT: '/sent/',
  DRAFTS: '/drafts/',
  DRAFT: '/draft/',
  DELETED: '/trash/',
  COMPOSE: '/new-message/',
  MESSAGE: '/message/',
  MESSAGE_THREAD: '/thread/',
  FOLDERS: '/folders',
  SEARCH: '/search/',
  SEARCH_RESULTS: '/search/results/',
  REPLY: '/reply/',
  CATEGORIES: '/categories',
  RECIPIENTS: '/allrecipients',
  SIGNATURE: '/signature',
};

export const Locators = {
  HEADER_FOLDER: '[data-testid*=folder-header]',
  ATTACH_FILE_INPUT: '[data-testid="attach-file-input"]',
  ATTACHMENT_COUNT: '[data-testid="attachments-count"]',
  MESSAGE_SUBJECT: '[data-testid="message-subject-field"]',
  MESSAGES_BODY: '[data-testid="message-body-field"]',
  DROPDOWN: '#sort-order-dropdown',
  SELECT: '#select',
  HEADER: 'h1',
  FOLDERS_LIST: '[data-testid ="my-folders-sidebar"]',
  MESSAGES: '[data-testid="message-list-item"]',
  THREADS: '[data-testid="thread-list-item"]',
  FOLDERS: {
    INBOX: '[data-testid="inbox-sidebar"] > a',
    DRAFTS: '[data-testid="drafts-sidebar"]',
    SENT: '[data-testid="sent-sidebar"]',
    TRASH: '[data-testid="trash-sidebar"]',
    CUSTOM: '[data-testid="my-folders-sidebar"]',
    SIDEBAR: '[data-testid=my-folders-sidebar]',
  },
  BUTTONS: {
    REPLY: '[data-testid="reply-button-body"]',
    CONTINUE: '[data-testid="continue-button"]',
    BUTTON_MOVE: 'button:contains("Move")',
    BUTTON_TRASH: 'button:contains("Trash")',
    BUTTON_TEXT: '[data-testid="trash-button-text"]',
    FILTER: '[data-testid="filter-messages-button"]',
    SEND: '[data-testid="Send-Button"]',
    SAVE_DRAFT: '#save-draft-button',
    DELETE_DRAFT: '#delete-draft-button',
    CREATE_FOLDER_BUTTON: '[data-testid="create-folder-button"]',
    EDIT_FOLDER: '[data-testid="edit-folder-button"]',
    PRINT: '[data-testid="print-button"]',
    BUTTON_SORT: '[data-testid="sort-button"]',
    ATTACH_FILE_BUTTON: '[data-testid="attach-file-button"]',
    REMOVE_ATTACHMENT: '.remove-attachment-button',
    CONTINUE_EDITING: 'va-button[text="Continue editing"]',
    CATEGORY_RADIO_BUTTON: '[data-testid="compose-category-radio-button"]',
  },
  LINKS: {
    GO_TO_INBOX: '[data-testid="inbox-link"]',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
  },
  ALERTS: {
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DRAFT_MESSAGE: '@draft_message',
    MAIN_CONTENT: '.va-alert',
    PAGE_TITLE: '.page-title',
    EXPANDABLE_TITLE: '[class="alert-expandable-title"]',
    SAVE_DRAFT: '#messagetext',
    SIDEBAR_NAV: '[class="sidebar-navigation-messages-list-header"]',
    INBOX_TEXT: '[text="Go to your inbox"]',
    WELCOME_MESSAGE: '.welcome-message',
    BACK_TOP: 'va-back-to-top',
    ACC_ITEM: '[data-testid="faq-accordion-item"]',
    BLOCKED_GROUP: '[data-testid="blocked-triage-group-alert"]',
    REPT_SELECT: '[data-testid="compose-recipient-select"]',
    MESS_CATAGO: '[data-testid="compose-message-categories"]',
    LIST_HEADER: '.sidebar-navigation-messages-list-header > a',
    SUCCESS_ALERT: '[data-testid="close-success-alert-button"]',
    DELETE_MESSAGE: '[data-testid=delete-message-modal]',
    ERROR_MESSAGE: '[data-testid="file-input-error-message"]',
    ERROR_MODAL: '[data-testid="attach-file-error-modal"]',
  },
  FIELDS: {
    RECIPIENT: '#select',
    SUBJECT: '#inputField',
    MESSAGE: '#textarea',
  },
  INFO: {
    SUBJECT_LIMIT: '#charcount-message',
  },
};

export const Alerts = {
  NO_ASSOCIATION: {
    AT_ALL_HEADER: `You're not connected to any care teams in this messaging tool`,
    HEADER: 'Your account is no longer connected to',
    PARAGRAPH:
      'If you need to contact your care team, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  BLOCKED: {
    HEADER: `You can't send messages to`,
    PARAGRAPH:
      'If you need to contact this care team, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
};
