export const ACTIONS = {
  DELETE_FILE: 'DELETE_FILE',
  DOC_DESC: 'DOC_DESC',
  DOC_TYPE: 'DOC_TYPE',
  FILE_DESCRIPTION_REQUIRED: 'FILE_DESCRIPTION_REQUIRED',
  FILE_UPLOAD_FAIL: 'FILE_UPLOAD_FAIL',
  FILE_UPLOAD_PENDING: 'FILE_UPLOAD_PENDING',
  FILE_UPLOAD_SUCESS: 'FILE_UPLOAD_SUCCESS',
  FORM_SUBMIT_FAIL: 'FORM_SUBMIT_FAIL',
  FORM_SUBMIT_PENDING: 'FORM_SUBMIT_PENDING',
  FORM_SUBMIT_SUCCESS: 'FORM_SUBMIT_SUCCESS',
};

export const CALLSTATUS = {
  failed: 'failed',
  idle: 'idle',
  pending: 'pending',
  skip: 'skipped',
  success: 'success',
};

export const COE_ELIGIBILITY_STATUS = {
  available: 'AVAILABLE',
  denied: 'DENIED',
  eligible: 'ELIGIBLE',
  pending: 'PENDING',
  pendingUpload: 'PENDING_UPLOAD',
  unableToDetermine: 'UNABLE_TO_DETERMINE_AUTOMATICALLY',
};
