export const vetFields = {
  address: 'veteranAddress',
  alternativePhoneNumber: 'veteranAlternativePhoneNumber',
  dateOfBirth: 'veteranDateOfBirth',
  email: 'veteranEmail',
  verifyEmail: 'view:veteranEmail',
  facilityType: 'veteranFacilityType',
  fullName: 'veteranFullName',
  gender: 'veteranGender',
  plannedClinic: 'veteranPlannedClinic',
  preferredFacilityInfoView: 'view:preferredFacilityInfo',
  preferredFacilityStateView: 'view:facilityState',
  preferredFacilityView: 'view:preferredFacility',
  previousTreatmentFacility: 'veteranLastTreatmentFacility',
  primaryPhoneNumber: 'veteranPrimaryPhoneNumber',
  ssn: 'veteranSsnOrTin',
};

export const primaryCaregiverFields = {
  address: 'primaryAddress',
  alternativePhoneNumber: 'primaryAlternativePhoneNumber',
  champvaEnrolled: 'primaryChampvaEnrolled',
  dateOfBirth: 'primaryDateOfBirth',
  email: 'primaryEmail',
  verifyEmail: 'view:primaryEmail',
  fullName: 'primaryFullName',
  gender: 'primaryGender',
  hasSecondaryCaregiverOneView: 'view:hasSecondaryCaregiverOne',
  medicaidEnrolled: 'primaryMedicaidEnrolled',
  medicareEnrolled: 'primaryMedicareEnrolled',
  otherHealthInsurance: 'view:otherHealthInsurance',
  otherHealthInsuranceName: 'primaryOtherHealthInsuranceName',
  primaryHealthCareEnrollmentView: 'view:primaryHealthCareEnrollment',
  primaryPhoneNumber: 'primaryPrimaryPhoneNumber',
  ssn: 'primarySsnOrTin',
  tricareEnrolled: 'primaryTricareEnrolled',
  vetRelationship: 'primaryVetRelationship',
};

export const secondaryCaregiverFields = {
  secondaryOne: {
    address: 'secondaryOneAddress',
    alternativePhoneNumber: 'secondaryOneAlternativePhoneNumber',
    dateOfBirth: 'secondaryOneDateOfBirth',
    email: 'secondaryOneEmail',
    verifyEmail: 'view:secondaryOneEmail',
    fullName: 'secondaryOneFullName',
    gender: 'secondaryOneGender',
    hasSecondaryCaregiverTwoView: 'view:hassecondaryCaregiverTwo',
    primaryPhoneNumber: 'secondaryOnePrimaryPhoneNumber',
    ssn: 'secondaryOneSsnOrTin',
    vetRelationship: 'secondaryOneVetRelationship',
  },
  secondaryTwo: {
    address: 'secondaryTwoAddress',
    alternativePhoneNumber: 'secondaryTwoAlternativePhoneNumber',
    dateOfBirth: 'secondaryTwoDateOfBirth',
    email: 'secondaryTwoEmail',
    verifyEmail: 'view:secondaryTwoEmail',
    fullName: 'secondaryTwoFullName',
    gender: 'secondaryTwoGender',
    primaryPhoneNumber: 'secondaryTwoPrimaryPhoneNumber',
    ssn: 'secondaryTwoSsnOrTin',
    vetRelationship: 'secondaryTwoVetRelationship',
  },
};
