export const vetFields = {
  address: 'veteranAddress',
  alternativePhoneNumber: 'veteranAlternativeCellNumber',
  dateOfBirth: 'veteranDateOfBirth',
  email: 'veteranEmail',
  facilityType: 'veteranFacilityType',
  fullName: 'veteranFullName',
  gender: 'veteranGender',
  medicaidEnrolled: 'veteranMedicaidEnrolled',
  plannedClinic: 'veteranPlannedClinic',
  previousTreatmentFacility: 'veteranPreviousTreatmentFacility',
  primaryPhoneNumber: 'veteranPrimaryPhoneNumber',
  ssn: 'veteranSsn',
  vaEnrolled: 'veteranVaEnrolled',
  privacyAgreement: 'veteranPrivacyAgreement',
};

export const primaryCaregiverFields = {
  address: 'primaryAddress',
  alternativePhoneNumber: 'primaryAlternativePhoneNumber',
  champvaEnrolled: 'primaryChampvaEnrolled',
  dateOfBirth: 'primaryDateOfBirth',
  email: 'primaryEmail',
  fullName: 'primaryFullName',
  gender: 'primaryGender',
  hasSecondaryOneCaregiverView: 'view:hasSecondaryOneCaregiver',
  medicaidEnrolled: 'primaryMedicaidEnrolled',
  medicareEnrolled: 'primaryMedicareEnrolled',
  otherHealthInsurance: 'primaryOtherHealthInsurance',
  otherHealthInsuranceName: 'primaryOtherHealthInsuranceName',
  primaryPhoneNumber: 'primaryPrimaryPhoneNumber',
  ssn: 'primarySsn',
  tricareEnrolled: 'primaryMedicareEnrolled',
  vetRelationship: 'primaryVetRelationship',
};

export const secondaryCaregiverFields = {
  secondaryOne: {
    address: 'secondaryOneAddress',
    alternativePhoneNumber: 'secondaryOneAlternativePhoneNumber',
    dateOfBirth: 'secondaryOneDateOfBirth',
    email: 'secondaryOneEmail',
    fullName: 'secondaryOneFullName',
    gender: 'secondaryOneGender',
    hasSecondaryTwoCaregiverView: 'view:hasSecondaryTwoCaregiver',
    primaryPhoneNumber: 'secondaryOnePrimaryPhoneNumber',
    ssn: 'secondaryOneSsn',
    vetRelationship: 'secondaryOneVetRelationship',
  },
  secondaryTwo: {
    address: 'secondaryTwoAddress',
    alternativePhoneNumber: 'secondaryTwoAlternativePhoneNumber',
    dateOfBirth: 'secondaryTwoDateOfBirth',
    email: 'secondaryTwoEmail',
    fullName: 'secondaryTwoFullName',
    gender: 'secondaryTwoGender',
    primaryPhoneNumber: 'secondaryTwoPrimaryPhoneNumber',
    ssn: 'secondaryTwoSsn',
    vetRelationship: 'secondaryTwoVetRelationship',
  },
};
