/**
 * To update this list, run the following code in the console on any va.gov page
 * ```
 const text = document.head.querySelector('style[data-styles]')?.textContent || '';
 const start = text.indexOf('}va-') + 1;
 const end = text.lastIndexOf('{visibility:hidden}');
 console.log(end - start > 500 ? text.slice(start, end).split(',').sort() : '');
 * ```
 */
export const webComponentList = [
  'va-accordion',
  'va-accordion-item',
  'va-additional-info',
  'va-alert',
  'va-alert-expandable',
  'va-alert-sign-in',
  'va-back-to-top',
  'va-banner',
  'va-breadcrumbs',
  'va-button',
  'va-button-icon',
  'va-button-pair',
  'va-button-segmented',
  'va-card',
  'va-card-status',
  'va-checkbox',
  'va-checkbox-group',
  'va-combo-box',
  'va-crisis-line-modal',
  'va-critical-action',
  'va-date',
  'va-file-input',
  'va-file-input-multiple',
  'va-header-minimal',
  'va-icon',
  'va-language-toggle',
  'va-link',
  'va-link-action',
  'va-loading-indicator',
  'va-maintenance-banner',
  'va-memorable-date',
  'va-minimal-footer',
  'va-modal',
  'va-need-help',
  'va-notification',
  'va-official-gov-banner',
  'va-omb-info',
  'va-on-this-page',
  'va-pagination',
  'va-privacy-agreement',
  'va-process-list',
  'va-process-list-item',
  'va-progress-bar',
  'va-promo-banner',
  'va-radio',
  'va-radio-option',
  'va-search-filter',
  'va-search-input',
  'va-segmented-progress-bar',
  'va-select',
  'va-service-list-item',
  'va-sidenav',
  'va-sidenav-item',
  'va-sidenav-submenu',
  'va-sort',
  'va-statement-of-truth',
  'va-summary-box',
  'va-tab-item',
  'va-tab-panel',
  'va-table',
  'va-table-inner',
  'va-table-row',
  'va-tabs',
  'va-tag-status',
  'va-telephone',
  'va-telephone-input',
  'va-text-input',
  'va-textarea',
];

// Commented out components are wrappers that have an open shadow DOM
export const focusableWebComponentList = [
  'va-accordion-item',
  // 'va-accordion',
  'va-alert:not([visible="false"])',
  // 'va-breadcrumbs',
  // 'va-button-pair',
  'va-button',
  // 'va-checkbox-group',
  'va-checkbox',
  'va-combo-box',
  'va-file-input',
  'va-file-input-multiple',
  // 'va-memorable-date',
  'va-number-input',
  // 'va-privacy-agreement',
  'va-radio-option',
  // 'va-radio',
  'va-select',
  'va-text-input',
  'va-textarea',
];

// Web components with a `label-header-level` property
export const webComponentsWithHeaders = [
  'va-checkbox-group',
  'va-radio',
  'va-textarea',
  'va-alert:not([visible="false"])',
];
