export const DEPENDENCY_VERIFICATION_CALL_SUCCESS =
  'DEPENDENCY_VERIFICATION_CALL_SUCCESS';
export const DEPENDENCY_VERIFICATION_CALL_FAILED =
  'DEPENDENCY_VERIFICATION_CALL_FAILED';
export const UPDATE_DIARIES_STARTED = 'UPDATE_DIARIES_STARTED';
export const UPDATE_DIARIES_SUCCESS = 'UPDATE_DIARIES_SUCCESS';
export const UPDATE_DIARIES_FAILED = 'UPDATE_DIARIES_FAILED';
export const UPDATE_DIARIES_SKIP = 'UPDATE_DIARIES_SKIP';
