name: Pension Benefits
appliesTo:
  - pension/how-to-apply/fully-developed-claim
backLink:
  label: How to Apply
  destination: pension/how-to-apply
links:
  - label: Fully Developed Claim Program
    destination: pension/how-to-apply/fully-developed-claim
