export const formData = {
  secondaryOneFullName: {
    first: 'John',
    last: 'Doe',
    suffix: 'Jr.',
  },
  secondaryOneDateOfBirth: '1995-04-09',
  secondaryOneGender: 'Male',
  secondaryOneAddress: {
    street: '111 1st St N',
    city: 'Somewhere',
    country: 'USA',
    state: 'AZ',
    postalCode: '88501',
  },
  secondaryOnePrimaryPhoneNumber: '8286908070',
  secondaryOneAlternativePhoneNumber: '8286908070',
  secondaryOneEmail: 'email@email.com',
  secondaryOneVetRelationship: 'Son',
  hasSecondaryTwoCaregiver: true,
  secondaryTwoFullName: {
    first: 'Jane',
    last: 'Doe',
    suffix: 'Jr.',
  },
  secondaryTwoDateOfBirth: '1996-05-07',
  secondaryTwoGender: 'Male',
  secondaryTwoAddress: {
    street: '111 1st St N',
    city: 'Somewhere',
    country: 'USA',
    state: 'FL',
    postalCode: '88501',
  },
  secondaryTwoPrimaryPhoneNumber: '8286908070',
  secondaryTwoAlternativePhoneNumber: '8286908070',
  secondaryTwoEmail: 'email@email.com',
  secondaryTwoVetRelationship: 'Sister',
  primaryAddress: {
    street: '111 1st St N',
    city: 'Somwhere',
    country: 'USA',
    state: 'AE',
    postalCode: '88501',
  },
  primaryPrimaryPhoneNumber: '8286908070',
  primaryAlternativePhoneNumber: '8286908070',
  primaryEmail: 'email@email.com',
  primaryVetRelationship: 'Spouse',
  primaryChampvaEnrolled: true,
  primaryOtherHealthInsurance: false,
  hasSecondaryOneCaregiver: true,
  primaryFullName: {
    first: 'Jane',
    last: 'Doe',
  },
  primaryDateOfBirth: '1982-04-05',
  primaryGender: 'Female',
  veteranAddress: {
    street: '111 1st St N',
    city: 'Somewhere',
    country: 'USA',
    state: 'AA',
    postalCode: '88501',
  },
  veteranPrimaryPhoneNumber: '8286908070',
  veteranAlternativeCellNumber: '8286908070',
  veteranEmail: 'email@email.com',
  veteranVaEnrolled: true,
  veteranPlannedClinic: 'asd',
  veteranFacilityType: 'clinic',
  veteranPreviousTreatmentFacility: 'asd',
  veteranFullName: {
    first: 'John',
    last: 'Doe',
    suffix: 'Sr.',
  },
  veteranDateOfBirth: '1980-03-03',
  veteranGender: 'Male',
};
