# This script uses Apple's opendiff tool to provide a diff between
# two files sharing the same HTML file path
# one generated by cms-export, the other by graphql.
# It assumes you are at the project root, and ran `compare.sh` previously.

if [ $# -eq 0 ]; then
    echo "Please provide a file path, e.g. outreach-and-events/events/index.html "
    exit 1
fi

opendiff ./build/cms-export-localhost/$1 ./build/graphql-localhost/$1