"use strict";
  /**
   * Generate the node files from the grapQl output in the pages.json file
   * so we can compare them to the node files that we generate
   */

const _ = require('lodash');
const fs = require('fs');

// file generated by graphql
const graphqlFile = '../../.cache/localhost/drupal/pages.json'; 
const graphqlDir =  'graphqlout'; // where we put the graphql nodes

function load() {
  const stringData = fs.readFileSync(graphqlFile);
  const data = JSON.parse(stringData);
  const entities = data.data.nodeQuery.entities;
  console.log(`${entities.length} entities`);
  _.map(entities, (value, key) => {
      saveNode(value);
  });
}

function saveNode(node) {
  let prettyOutJson = JSON.stringify(node, null, 2);
  if(node.entityId) {
  const id = `node.${node.entityId}`;
  console.log(id);
  const fileName = `${graphqlDir}/${id}.json`;
  fs.writeFileSync(fileName, prettyOutJson);
  } else {
    console.error('Node Does not have an entityId');
  }
}

load();
