import { useCallback, useMemo, useState } from 'react';
import { DATETIME_FORMATS } from '../util/constants';
import {
  buildPrescriptionsPDFList,
  buildAllergiesPDFList,
} from '../util/pdfConfigs';
import { buildPrescriptionsTXT, buildAllergiesTXT } from '../util/txtConfigs';
import {
  dateFormat,
  displayHeaderPrefaceText,
  displayMedicationsListHeader,
  generateTextFile,
  generateTimestampForFilename,
} from '../util/helpers';
import { buildPdfData } from '../util/buildPdfData';
import { generateMedicationsPdfFile } from '../util/generateMedicationsPdfFile';
import useExportFile from './useExportFile';

/**
 * Hook to manage generating PDF/TXT/print exports for prescriptions list.
 * Consumers supply user info, allergies data, feature flags, and a fetcher for the export list.
 *
 * This hook builds the list-specific export payloads and delegates the
 * shared export flow (status, async handling, print trigger) to useExportFile.
 */
const useRxListExport = ({
  user,
  allergies,
  allergiesError,
  selectedFilterOption,
  selectedSortOption,
  currentFilterOptions = {},
  features = {},
  fetchExportList,
}) => {
  const { isCernerPilot = false, isV2StatusMapping = false } = features;

  const [exportList, setExportList] = useState([]);
  const [printList, setPrintList] = useState([]);
  const [exportListError, setExportListError] = useState(false);
  const [exportListErrorFormat, setExportListErrorFormat] = useState(undefined);

  const resetExportState = useCallback(() => {
    setExportList([]);
    setPrintList([]);
    setExportListError(false);
    setExportListErrorFormat(undefined);
  }, []);

  const buildTxtData = useCallback(
    (rxList, allergiesList) => {
      return (
        `${
          "\nIf you're ever in crisis and need to talk with someone right away, call the Veterans Crisis Line at 988. Then select 1.\n\n\n" +
          'Medications\n\n'
        }${user.first ? `${user.last}, ${user.first}` : user.last || ' '}\n\n` +
        `Date of birth: ${dateFormat(
          user.dob,
          DATETIME_FORMATS.longMonthDate,
        )}\n\n` +
        `Report generated by My HealtheVet on VA.gov on ${dateFormat(
          Date.now(),
          DATETIME_FORMATS.longMonthDate,
        )}\n\n` +
        `${displayHeaderPrefaceText(
          selectedFilterOption,
          selectedSortOption,
          rxList?.length,
          false,
        )}\n\n\n` +
        `${displayMedicationsListHeader(
          selectedFilterOption,
          isCernerPilot,
          isV2StatusMapping,
          currentFilterOptions,
        )}\n\n` +
        `${rxList}${allergiesList ?? ''}`
      );
    },
    [
      user,
      selectedFilterOption,
      selectedSortOption,
      isCernerPilot,
      isV2StatusMapping,
      currentFilterOptions,
    ],
  );

  const isReady = useMemo(() => !!exportList?.length, [exportList]);

  const exportFlow = useExportFile({
    allergies,
    allergiesError,
    isReady,
    error: exportListError,

    // Prepare step: fetch export list (if needed) on download.
    prepare: async format => {
      setExportListError(false);
      setExportListErrorFormat(undefined);

      if (exportList.length) return;

      if (!fetchExportList) {
        setExportListError(true);
        setExportListErrorFormat(format);
        return;
      }

      const { data, isError } = await fetchExportList();
      if (isError) {
        setExportListError(true);
        setExportListErrorFormat(format);
        return;
      }

      if (data?.prescriptions) {
        setExportList(data.prescriptions);
      } else {
        setExportListError(true);
        setExportListErrorFormat(format);
      }
    },

    onBeforePrint: () => {
      setPrintList(exportList);
    },

    onGeneratePdf: async () => {
      const pdfDataObj = buildPdfData({
        userName: user,
        dob: user.dob,
        selectedFilterOption,
        selectedSortOption,
        rxList: buildPrescriptionsPDFList(
          exportList,
          isCernerPilot,
          isV2StatusMapping,
        ),
        allergiesList: buildAllergiesPDFList(allergies),
      });

      await generateMedicationsPdfFile({ userName: user, pdfData: pdfDataObj });
    },

    onGenerateTxt: async () => {
      generateTextFile(
        buildTxtData(
          buildPrescriptionsTXT(exportList, isCernerPilot, isV2StatusMapping),
          buildAllergiesTXT(allergies),
        ),
        `VA-medications-list-${
          user.first ? `${user.first}-${user.last}` : user.last
        }-${generateTimestampForFilename()}`,
      );
    },
  });

  // Prefer export-list-specific error format if present; otherwise fall back to exportFlow's.
  const effectiveErrorFormat = useMemo(() => {
    return exportListErrorFormat || exportFlow.errorFormat;
  }, [exportListErrorFormat, exportFlow.errorFormat]);

  return {
    onDownload: exportFlow.onDownload,
    status: exportFlow.status,
    isLoading: exportFlow.isLoading,
    isSuccess: exportFlow.isSuccess,
    hasError: exportFlow.hasError,
    errorFormat: effectiveErrorFormat,
    shouldPrint: exportFlow.shouldPrint,
    printList,
    exportList,

    resetExportState: () => {
      resetExportState();
      exportFlow.resetExportFlow();
    },
    clearPrintTrigger: exportFlow.clearPrintTrigger,
  };
};

export default useRxListExport;
