export const DirectDepositVeteranStatus = {
  VETERAN: 'VETERAN',
  DEPENDENT: 'DEPENDENT',
  NEITHER_VETERAN_NOR_DEPENDENT: 'NEITHER_VETERAN_NOR_DEPENDENT',
  COULD_NOT_DETERMINE_DUE_TO_EXCEPTION: 'COULD_NOT_DETERMINE_DUE_TO_EXCEPTION',
};
