export const jurisdictions = [
  { jurisdiction: 'Alabama', website: 'https://www.alabar.org/' },
  { jurisdiction: 'Alaska', website: 'https://alaskabar.org/' },
  { jurisdiction: 'American Samoa', website: 'https://asbar.org/' },
  { jurisdiction: 'Arizona', website: 'https://www.azbar.org/' },
  { jurisdiction: 'Arkansas', website: 'https://www.arkbar.com/home' },
  { jurisdiction: 'California', website: 'https://www.calbar.ca.gov/' },
  { jurisdiction: 'Colorado', website: 'https://www.cobar.org/' },
  { jurisdiction: 'Connecticut', website: 'https://www.ctbar.org/' },
  { jurisdiction: 'Delaware', website: 'https://www.dsba.org/' },
  { jurisdiction: 'District of Columbia', website: 'https://www.dcbar.org/' },
  { jurisdiction: 'Florida', website: 'https://www.floridabar.org/' },
  { jurisdiction: 'Georgia', website: 'https://www.gabar.org/' },
  { jurisdiction: 'Guam', website: 'https://guambar.org/' },
  { jurisdiction: 'Hawaii', website: 'https://hsba.org/' },
  { jurisdiction: 'Idaho', website: 'https://isb.idaho.gov/' },
  { jurisdiction: 'Illinois', website: 'https://www.isba.org/' },
  { jurisdiction: 'Indiana', website: 'https://www.inbar.org/' },
  { jurisdiction: 'Iowa', website: 'https://www.iowabar.org/' },
  { jurisdiction: 'Kansas', website: 'https://ksbar.org/' },
  { jurisdiction: 'Kentucky', website: 'https://www.kybar.org/' },
  { jurisdiction: 'Louisiana', website: 'https://www.lsba.org/' },
  { jurisdiction: 'Maine', website: 'https://www.mainebar.org/' },
  { jurisdiction: 'Maryland', website: 'https://www.msba.org/' },
  { jurisdiction: 'Massachusetts', website: 'https://www.massbar.org/' },
  { jurisdiction: 'Michigan', website: 'https://www.michbar.org/' },
  { jurisdiction: 'Minnesota', website: 'https://www.mnbar.org/' },
  { jurisdiction: 'Mississippi', website: 'https://www.msbar.org/' },
  { jurisdiction: 'Missouri', website: 'https://mobar.org/' },
  { jurisdiction: 'Montana', website: 'https://www.montanabar.org/' },
  { jurisdiction: 'Nebraska', website: 'https://www.nebar.com/' },
  { jurisdiction: 'Nevada', website: 'https://nvbar.org/' },
  { jurisdiction: 'New Hampshire', website: 'https://www.nhbar.org/' },
  { jurisdiction: 'New Jersey', website: 'https://tcms.njsba.com/' },
  { jurisdiction: 'New Mexico', website: 'https://www.sbnm.org/' },
  { jurisdiction: 'New York', website: 'https://nysba.org/' },
  { jurisdiction: 'North Carolina', website: 'https://www.ncbar.org/' },
  { jurisdiction: 'North Dakota', website: 'https://www.sband.org/' },
  {
    jurisdiction: 'Northern Mariana Islands',
    website: 'https://www.cnmibar.com/',
  },
  { jurisdiction: 'Ohio', website: 'https://www.ohiobar.org/' },
  { jurisdiction: 'Oklahoma', website: 'https://www.okbar.org/' },
  { jurisdiction: 'Oregon', website: 'https://www.osbar.org/' },
  { jurisdiction: 'Pennsylvania', website: 'https://www.pabar.org/' },
  { jurisdiction: 'Puerto Rico', website: 'https://capr.org/' },
  { jurisdiction: 'Rhode Island', website: 'https://ribar.com/' },
  { jurisdiction: 'South Carolina', website: 'https://www.scbar.org/' },
  {
    jurisdiction: 'South Dakota',
    website: 'https://www.statebarofsouthdakota.com/',
  },
  { jurisdiction: 'Tennessee', website: 'https://www.tba.org/' },
  { jurisdiction: 'Texas', website: 'https://www.texasbar.com/' },
  { jurisdiction: 'Utah', website: 'https://www.utahbar.org/' },
  { jurisdiction: 'Vermont', website: 'https://www.vtbar.org/' },
  { jurisdiction: 'Virgin Islands', website: 'https://www.usvibar.org/' },
  { jurisdiction: 'Virginia', website: 'https://www.vsb.org/' },
  { jurisdiction: 'Washington', website: 'https://www.wsba.org/' },
  { jurisdiction: 'West Virginia', website: 'https://wvbar.org/' },
  { jurisdiction: 'Wisconsin', website: 'https://wisbar.org' },
  { jurisdiction: 'Wyoming', website: 'https://www.wyomingbar.org/' },
  { jurisdiction: 'Other', website: '' },
];

export const jurisdictionOptions = jurisdictions.map(
  jurisdiction => jurisdiction.jurisdiction,
);
