export const initialValues = {
  relationship: {
    type: '',
    other: '',
    isEntity: null,
  },
  locationOfDeath: {
    location: '',
    other: '',
  },
  toursOfDuty: [
    {
      dateRange: {
        from: '',
        to: '',
      },
      serviceBranch: '',
      rank: '',
      serviceNumber: '',
      placeOfEntry: '',
      placeOfSeparation: '',
    },
  ],
  veteranServedUnderAnotherName: null,
  previousNames: [
    {
      first: '',
      middle: '',
      last: '',
      suffix: '',
    },
  ],
  claimantEmail: '',
  benefitsSelection: {
    burialAllowance: null,
    plotAllowance: null,
    transportation: null,
  },
  burialAllowance: null,
  plotAllowance: null,
  transportation: null,
  amountIncurred: 0,
  burialAllowanceRequested: '',
  burialCost: 0,
  placeOfRemains: '',
  federalCemetery: null,
  stateCemetery: null,
  govtContributions: null,
  amountGovtContribution: 0,
  placeOfBirth: '',
  officialPosition: '',
  firmName: '',
  privacyAgreementAccepted: null,
  claimantAddress: {
    isMilitaryBaseOutside: null,
    streetAddress: '',
    streetAddressLine2: '',
    streetAddressLine3: '',
    city: '',
    state: '',
    country: '',
    postalCode: '',
  },
  claimantPhone: '',
  claimantFullName: {
    first: '',
    middle: '',
    last: '',
    suffix: '',
  },
  veteranFullName: {
    first: '',
    middle: '',
    last: '',
    suffix: '',
  },
  veteranSocialSecurityNumber: '',
  vaFileNumber: '',
  burialDate: '',
  deathDate: '',
  veteranDateOfBirth: '',
  deathCertificate: [
    {
      name: '',
      size: '',
      confirmationCode: '',
    },
  ],
  transportationReceipts: [
    {
      name: '',
      size: '',
      confirmationCode: '',
    },
  ],
};
