export const FORM_ACTION_TYPES = {
  ONRAMP_VIEWED_INTRO_PAGE: 'ONRAMP_VIEWED_INTRO_PAGE',
  ONRAMP_UPDATE_FORM_STORE: 'ONRAMP_UPDATE_FORM_STORE',
};

export const QUESTION_ACTION_TYPES = {
  ONRAMP_UPDATE_Q_1_1_CLAIM_DECISION: 'ONRAMP_UPDATE_Q_1_1_CLAIM_DECISION',
  ONRAMP_UPDATE_Q_1_1A_SUBMITTED_526: 'ONRAMP_UPDATE_Q_1_1A_SUBMITTED_526',
  ONRAMP_UPDATE_Q_1_2_CLAIM_DECISION: 'ONRAMP_UPDATE_Q_1_2_CLAIM_DECISION',
  ONRAMP_UPDATE_Q_1_2A_CONDITION_WORSENED:
    'ONRAMP_UPDATE_Q_1_2A_CONDITION_WORSENED',
  ONRAMP_UPDATE_Q_1_2B_LAW_POLICY_CHANGE:
    'ONRAMP_UPDATE_Q_1_2B_LAW_POLICY_CHANGE',
  ONRAMP_UPDATE_Q_1_2C_NEW_EVIDENCE: 'ONRAMP_UPDATE_Q_1_2C_NEW_EVIDENCE',
  ONRAMP_UPDATE_Q_1_3_CLAIM_CONTESTED: 'ONRAMP_UPDATE_Q_1_3_CLAIM_CONTESTED',
  ONRAMP_UPDATE_Q_1_3A_FEWER_60_DAYS: 'ONRAMP_UPDATE_Q_1_3A_FEWER_60_DAYS',
  ONRAMP_UPDATE_Q_2_0_CLAIM_TYPE: 'ONRAMP_UPDATE_Q_2_0_CLAIM_TYPE',
  ONRAMP_UPDATE_Q_2_IS_1_SERVICE_CONNECTED:
    'ONRAMP_UPDATE_Q_2_IS_1_SERVICE_CONNECTED',
  ONRAMP_UPDATE_Q_2_IS_1A_LAW_POLICY_CHANGE:
    'ONRAMP_UPDATE_Q_2_IS_1A_LAW_POLICY_CHANGE',
  ONRAMP_UPDATE_Q_2_IS_1B_NEW_EVIDENCE: 'ONRAMP_UPDATE_Q_2_IS_1B_NEW_EVIDENCE',
  ONRAMP_UPDATE_Q_2_IS_2_CONDITION_WORSENED:
    'ONRAMP_UPDATE_Q_2_IS_2_CONDITION_WORSENED',
  ONRAMP_UPDATE_Q_2_S_1_NEW_EVIDENCE: 'ONRAMP_UPDATE_Q_2_S_1_NEW_EVIDENCE',
  ONRAMP_UPDATE_Q_2_H_1_EXISTING_BOARD_APPEAL:
    'ONRAMP_UPDATE_Q_2_H_1_EXISTING_BOARD_APPEAL',
  ONRAMP_UPDATE_Q_2_H_2_NEW_EVIDENCE: 'ONRAMP_UPDATE_Q_2_H_2_NEW_EVIDENCE',
  ONRAMP_UPDATE_Q_2_H_2A_JUDGE_HEARING: 'ONRAMP_UPDATE_Q_2_H_2A_JUDGE_HEARING',
  ONRAMP_UPDATE_Q_2_H_2B_JUDGE_HEARING: 'ONRAMP_UPDATE_Q_2_H_2B_JUDGE_HEARING',
};

export const updateIntroPageViewed = value => {
  return {
    type: FORM_ACTION_TYPES.ONRAMP_VIEWED_INTRO_PAGE,
    payload: value,
  };
};

export const updateFormStore = value => {
  return {
    type: FORM_ACTION_TYPES.ONRAMP_UPDATE_FORM_STORE,
    payload: value,
  };
};

export const updateQuestionValue = (SHORT_NAME, value) => {
  return {
    type: QUESTION_ACTION_TYPES[`ONRAMP_UPDATE_${SHORT_NAME}`],
    payload: value,
  };
};
