const oneDayInMS = 24 * 60 * 60 * 1000;
const oneWeekInMS = oneDayInMS * 7;
const twentyDaysInMS = oneDayInMS * 20;
const fourtyDaysInMS = oneDayInMS * 40;
const oneYearInMS = oneDayInMS * 365;

export const prescriptions = {
  data: [
    {
      id: '17927538',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17927538,
        prescriptionNumber: '2720040',
        prescriptionName: 'DAPSONE 25MG TAB',
        refillStatus: 'submitted',
        refillSubmitDate: Date.now() - oneDayInMS,
        refillDate: Date.now(),
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - oneWeekInMS,
        quantity: 10,
        expirationDate: Date.now + oneYearInMS,
        dispensedDate: Date.now(),
        stationNumber: '989',
        isRefillable: false,
        isTrackable: true,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17927538',
        tracking: 'https://www.example.com/v0/prescriptions/17927538/trackings',
      },
    },
    {
      id: '17927540',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17927540,
        prescriptionNumber: '2720042',
        prescriptionName: 'PROBENECID 500MG TAB',
        refillStatus: 'submitted',
        refillSubmitDate: Date.now() - oneDayInMS,
        refillDate: Date.now(),
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - oneWeekInMS,
        quantity: 10,
        expirationDate: Date.now + oneYearInMS,
        dispensedDate: Date.now(),
        stationNumber: '989',
        isRefillable: false,
        isTrackable: true,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17927540',
        tracking: 'https://www.example.com/v0/prescriptions/17927540/trackings',
      },
    },
    {
      id: '17991837',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17991837,
        prescriptionNumber: '2720052',
        prescriptionName: 'ACEBUTOLOL HCL 400MG CAP',
        refillStatus: 'submitted',
        refillSubmitDate: Date.now() - oneDayInMS,
        refillDate: Date.now(),
        refillRemaining: 8,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - twentyDaysInMS,
        quantity: 10,
        expirationDate: Date.now + twentyDaysInMS,
        dispensedDate: Date.now(),
        stationNumber: '989',
        isRefillable: false,
        isTrackable: true,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17991837',
        tracking: 'https://www.example.com/v0/prescriptions/17991837/trackings',
      },
    },
    {
      id: '19434500',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 19434500,
        prescriptionNumber: '2720152',
        prescriptionName: 'RALOXIFENE HCL 60MG TAB',
        refillStatus: 'submitted',
        refillSubmitDate: Date.now() - oneDayInMS,
        refillDate: Date.now(),
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - fourtyDaysInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: Date.now(),
        stationNumber: '989',
        isRefillable: false,
        isTrackable: true,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/19434500',
        tracking: 'https://www.example.com/v0/prescriptions/19434500/trackings',
      },
    },
    {
      id: '19434501',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 19434501,
        prescriptionNumber: '2720153',
        prescriptionName: 'VALSARTAN 160MG TAB',
        refillStatus: 'submitted',
        refillSubmitDate: Date.now() - oneDayInMS,
        refillDate: Date.now(),
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - fourtyDaysInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: Date.now(),
        stationNumber: '989',
        isRefillable: false,
        isTrackable: true,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/19434501',
        tracking: 'https://www.example.com/v0/prescriptions/19434501/trackings',
      },
    },
    {
      id: '17927539',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17927539,
        prescriptionNumber: '2720041',
        prescriptionName: 'NORFLOXACIN 400MG TAB',
        refillStatus: 'refillinprocess',
        refillSubmitDate: Date.now() - fourtyDaysInMS,
        refillDate: Date.now() - fourtyDaysInMS,
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - oneYearInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: null,
        stationNumber: '989',
        isRefillable: false,
        isTrackable: false,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17927539',
      },
    },
    {
      id: '17927537',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17927537,
        prescriptionNumber: '2720039',
        prescriptionName: 'ADEFOVIR DIPIVOXIL 10MG TAB',
        refillStatus: 'refillinprocess',
        refillSubmitDate: Date.now() - oneWeekInMS,
        refillDate: Date.now() - oneWeekInMS,
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - twentyDaysInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: null,
        stationNumber: '989',
        isRefillable: false,
        isTrackable: false,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17927537',
      },
    },
    {
      id: '19434499',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 19434499,
        prescriptionNumber: '2720151',
        prescriptionName: 'KETOPROFEN 50MG CAP',
        refillStatus: 'active',
        refillSubmitDate: null,
        refillDate: Date.now() - oneWeekInMS,
        refillRemaining: 11,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - twentyDaysInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: null,
        stationNumber: '989',
        isRefillable: true,
        isTrackable: false,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/19434499',
      },
    },
  ],
  links: {
    self:
      'https://www.example.com/v0/prescriptions/active?sort=-refill_submit_date',
    first:
      'https://www.example.com/v0/prescriptions/active?page=1&per_page=10&sort=-refill_submit_date',
    prev: null,
    next: null,
    last:
      'https://www.example.com/v0/prescriptions/active?page=1&per_page=10&sort=-refill_submit_date',
  },
  meta: {
    updatedAt: Date.now(),
    failedStationList: '',
    sort: {
      refillSubmitDate: 'DESC',
    },
    pagination: {
      currentPage: 1,
      perPage: 10,
      totalPages: 1,
      totalEntries: 10,
    },
  },
};

export const onePrescription = {
  data: [
    {
      id: '17927538',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17927538,
        prescriptionNumber: '2720040',
        prescriptionName: 'DAPSONE 25MG TAB',
        refillStatus: 'submitted',
        refillSubmitDate: Date.now() - oneDayInMS,
        refillDate: Date.now() - oneDayInMS,
        refillRemaining: 10,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - oneWeekInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: Date.now(),
        stationNumber: '989',
        isRefillable: false,
        isTrackable: true,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17927538',
        tracking: 'https://www.example.com/v0/prescriptions/17927538/trackings',
      },
    },
  ],
};

export const noRefilledPrescriptions = {
  data: [
    {
      id: '19434499',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 19434499,
        prescriptionNumber: '2720151',
        prescriptionName: 'KETOPROFEN 50MG CAP',
        refillStatus: 'active',
        refillSubmitDate: null,
        refillDate: Date.now() - oneDayInMS,
        refillRemaining: 11,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - fourtyDaysInMS,
        quantity: 10,
        expirationDate: Date.now() + oneYearInMS,
        dispensedDate: null,
        stationNumber: '989',
        isRefillable: true,
        isTrackable: false,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/19434499',
      },
    },
    {
      id: '17991836',
      type: 'prescriptions',
      attributes: {
        prescriptionId: 17991836,
        prescriptionNumber: '2720051',
        prescriptionName: 'VERAPAMIL HCL 120MG TAB',
        refillStatus: 'active',
        refillSubmitDate: Date.now() - oneWeekInMS,
        refillDate: Date.now() - oneDayInMS,
        refillRemaining: 7,
        facilityName: 'DAYT29',
        orderedDate: Date.now() - twentyDaysInMS,
        quantity: 10,
        expirationDate: Date.now() + twentyDaysInMS,
        dispensedDate: null,
        stationNumber: '989',
        isRefillable: false,
        isTrackable: false,
      },
      links: {
        self: 'https://www.example.com/v0/prescriptions/17991836',
      },
    },
  ],
};
