name: Checkout
description: Checkout

inputs:
  key:
    description: keys for actions/cache@v4
    required: false
    default: ''
  restore-keys:
    description: restore-keys for actions/cache@v4
    required: false
    default: ''
  yarn_cache_folder:
    description: path for yarn cache
    required: false
    default: ''
  path:
    description: path for actions/cache@v4
    required: false
    default: ''

runs:
  using: composite
  steps:
    uses: actions/checkout@v4
    with:
      fetch-depth: 0