import { pageNotFoundHeading } from '@department-of-veterans-affairs/platform-site-wide/PageNotFound';

export const AXE_CONTEXT = '.secure-messaging-container';

export const Paths = {
  MHV_MAIN: '/my-health/',
  UI_MAIN: '/my-health/secure-messages',
  UI_PILOT: '/my-health/secure-messages-pilot',
  SM_API_BASE: '/my_health/v1/messaging',
  SM_API_EXTENDED: '/my_health/v1/messaging/messages',
  INBOX: '/inbox/',
  SENT: '/sent/',
  DRAFTS: '/drafts/',
  DRAFT: '/draft/',
  DELETED: '/trash/',
  COMPOSE: '/new-message/',
  MESSAGE: '/message/',
  MESSAGE_THREAD: '/thread/',
  FOLDERS: '/folders',
  SEARCH: '/search/',
  SEARCH_RESULTS: '/search/results/',
  REPLY: '/reply/',
  CATEGORIES: '/categories',
  RECIPIENTS: '/allrecipients',
  SIGNATURE: '/signature',
  FIND_LOCATIONS: '/find-locations/',
  FIND_LOCATION: '/find-locations',
  HEALTH_CARE_SEND_RECEIVE_MSG: '/health-care/send-receive-messages/',
  MHV_LANDING_PAGE: '/my-health',
  MHV_SM: '/secure-messages',
  THREAD: '/thread',
  CONTACT_LIST: '/contact-list',
  NEW_MESSAGE: '/my-health/secure-messages/new-message/',
  INTERCEPT: {
    MESSAGE_RECIPIENT: '/my_health/v1/messaging/recipients*',
    MESSAGE_CATEGORY: '/my_health/v1/messaging/messages/categories',
    MESSAGE_FOLDER: '/my_health/v1/messaging/folders*',
    MESSAGE_FOLDERS: '/my_health/v1/messaging/folders',
    MESSAGE_FOLDER_THREAD: '/my_health/v1/messaging/folders/0/threads?*',
    MESSAGE_FOLDER_MESS: '/my_health/v1/messaging//folders/0/messages*',
    MESSAGE_DRAFTS: '/my_health/v1/messaging/message_drafts',
    MESSAGE_FOLDERS_SEARCH: '/my_health/v1/messaging/folders/*/search',
    MESSAGE_FOLDERS_2: '/my_health/v1/messaging/folders/-2*',
    FEATURE_TOGGLES: '/v0/feature_toggles?*',
    MESSAGE_THREADS: '/my_health/v1/messaging/threads/',
    MESSAGE_SIGNATURE: '/my_health/v1/messaging/preferences/signature',
    MESSAGE_ALLRECIPIENTS: '/my_health/v1/messaging/allrecipients',
    MESSAGES: '/my_health/v1/messaging/messages',
    SELECTED_RECIPIENTS: `/my_health/v1/messaging/preferences/recipients`,
    MAINTENANCE_WINDOWS: `/v0/maintenance_windows/`,
  },
};

export const Locators = {
  FROM_TO_DATES_CONTAINER: '.fromToDatesContainer',
  MESSAGE_FAQ: '.secure-messaging-faq',
  MESSAGES: '[data-testid="message-list-item"]',
  TO: '[data-testid="to"]',
  FROM: '[data-testid="from"]',
  MSG_ID: '[data-testid="message-id"]',
  MSG_DATE: '[data-testid="message-date"]',
  DATE_RECEIVED: '[data-testid="received-date"]',
  HEADER_FOLDER: '[data-testid*=folder-header]',
  ATTACH_FILE_INPUT: '[data-testid="attach-file-input"]',
  ATTACHMENT_COUNT: '[data-testid="attachments-count"]',
  MESSAGES_BODY_DRAFT: '.message-body-draft-preview',
  CERNER: '[data-testid="cerner-facility"]',
  CERNER_TEXT: '[data-testid="single-cerner-facility-text"]',
  DELETE_MES_CONFIRM: '[data-testid="delete-message-confirm-note"] p',
  SELECT: '#select',
  HEADER: 'h1',
  HEADER2: 'h2',
  HEADLINE: 'h1[slot="headline"]',
  KEYWORD_SEARCH: '[data-testid="keyword-search-input"]',
  NO_MESS: '[data-testid=alert-no-messages] p',
  FOLDER_NAME: '[data-testid="folder-name"]',
  FOLDERS_LIST: '[data-testid ="my-folders-sidebar"]',
  MESS_LIST: '[data-testid="message-list-item"]',
  THREAD_LIST: '.thread-list-item',
  THREADS: '[data-testid="thread-list-item"]',
  MES_COUNT: '[data-testid="message-count"]',
  REPLY_FORM: '[data-testid="reply-form"]',
  CLEAR_FILTERS: '[text="Clear Filters"]',
  FILTER_INPUT: '#filter-input',
  ADDITIONAL_FILTER: '#additional-filter-accordion',
  ACCORDIONS: '[data-testid="faq-accordion-item"]',
  MESSAGE_THREAD_META: '.message-thread-meta',
  SPINNER: `[data-testid="loading-indicator"]`,
  BACK_TO: '.sm-breadcrumb-list-item > a',
  FAQ_ACC_ITEM: '[data-testid="faq-accordion-item"]',
  INBOX_FOOTER: `[data-testid="inbox-footer"]`,
  COMBO_BOX: '.usa-combo-box',
  FOLDERS: {
    FOLDER_NAME: '[label="Folder name"]',
    FOLDER_REMOVE: '[text="Yes, remove this folder"]',
    FOLDER_HEADER: '[data-testid="folder-header"]',
    INBOX: '[data-testid="inbox-sidebar"] > a',
    DRAFTS: '[data-testid="drafts-sidebar"]',
    SENT: '[data-testid="sent-sidebar"]',
    TRASH: '[data-testid="trash-sidebar"]',
    CUSTOM: '[data-testid="my-folders-sidebar"]',
    SIDEBAR: '[data-testid=my-folders-sidebar]',
    NOT_EMP_FOLDER: '[data-testid="error-folder-not-empty"] p',
    FOLDER_INPUT_LABEL: '[data-testid="search-message-folder-input-label"]',
    FOLDER_DROPDOWN: '[data-testid="folder-dropdown"]',
    FOLDER_NOT_EMPTY: 'va-modal[data-testid="error-folder-not-empty"]',
  },
  BUTTONS: {
    SECURE_MESSAGING: '[data-testid="secure-messaging"]',
    THREAD_EXPAND: '[data-testid="thread-expand-all"]',
    THREAD_EXPAND_MESSAGES:
      '[data-testid="thread-expand-all"] va-accordion-item',
    ADDITIONAL_FILTER: `.va-accordion__header`,
    TRASH_TEXT: '[data-testid=trash-button-text]',
    TEXT_CONFIRM: 'va-button[text="Confirm"]',
    // check if below are duplicates
    REPLY_BTN: '#reply-button',
    REPLY: '[data-testid="reply-button-body"]',
    CONTINUE: '[data-testid="continue-button"]',
    TEST2: '[data-testid=radiobutton-TEST2]',
    TESTAGAIN: '[data-testid=radiobutton-TESTAGAIN]',
    NEW_FOLDER_RADIOBTN: '[data-testid=folder-list-radio-button]',
    DELETE_RADIOBTN: '[data-testid=radiobutton-Deleted]',
    MOVE: `#move-button`,
    TRASH: `#trash-button`,
    BUTTON_TEXT: '[data-testid="trash-button-text"]',
    MOVE_BUTTON_TEXT: '[data-testid="move-button-text"]',
    FILTER: '[data-testid="filter-messages-button"]',
    SEND: '[data-testid="send-button"]',
    SAVE_DRAFT: '[data-testid="save-draft-button"]',
    PRINT_ONE_MESS: '[data-testid="radio-print-one-message"]',
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DELETE_DRAFT: '[data-testid="delete-draft-button"]',
    EDIT_FOLDER: '[data-testid="edit-folder-button"]',
    DELETE_FOLDER: '[data-testid="remove-folder-button"]',
    PRINT: '[data-testid="print-button"]',
    SORT: '[data-testid="sort-button"]',
    ATTACH_FILE: '[data-testid="attach-file-button"]',
    REMOVE_ATTACHMENT: '[data-testid="remove-attachment-button"]',
    REMOVE_ALL_ATTCH: `[data-testid="remove-all-attachments-button"]`,
    CONFIRM_REMOVE_ATTACHMENT:
      '[data-testid="confirm-remove-attachment-button"]',
    CONTINUE_EDITING: 'va-button[text="Continue editing"]',
    CREATE_FOLDER: '[data-testid="create-folder-button"]',
    REMOVE_FOLDER: '[data-testid="remove-folder-button"]',
    PREFERENCES: '[data-testid="edit-preferences-button"]',
    CATEGORY_RADIOBTN: '[data-testid="compose-category-radio-button"]',
    DELETE_CANCEL: '#delete-cancel',
    DELETE_CONFIRM: '#delete-draft',
    EDIT_DRAFT: `[data-testid="edit-draft-button-body"]`,
    EDIT_DRAFTS: '[data-testid="edit-draft-button-body-text"]',
    CL_SAVE: `[data-testid="contact-list-save"]`,
    CL_GO_BACK: '[data-testid="contact-list-go-back"]',
    ALERT_CLOSE: `.first-focusable-child`,
  },
  LINKS: {
    GO_TO_INBOX: '[data-testid="inbox-link"]',
    PREFER_LINK: '[data-testid="edit-preferences-link"]',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
    CRUMB: 'ol[role="list"] > li',
    CRUMB_LIST: '[data-testid="sm-breadcrumbs"]',
    BACK_TO_DRAFTS: '.sm-breadcrumb-list-item>a',
    CRUMBS_BACK: '.sm-breadcrumb-list-item',
    OLD_VERSION: `.welcome-message > p > a`,
    EDIT_SIGNATURE: `div.vads-u-margin-top--2`,
  },
  ALERTS: {
    HEADER: `#heading`,
    MODEL_TITLE_ALERT: '.va-modal-alert-title',
    TRIAGE_ALERT: '[data-testid="blocked-triage-group-alert"] > div > a',
    CLOSE_NOTIFICATION: '.va-alert',
    REPT_SELECT: '[data-testid="compose-recipient-select"]',
    DRAFT_MODAL: '[data-testid="delete-draft-modal"]',
    THREAD_EXPAND: '[data-testid="thread-expand-all"]',
    SEARCH_DROPDOWN: '#select-search-folder-dropdown',
    TEXT_INPUT: '[data-testid="search-keyword-text-input"]',
    PAGIN_LIST: '.usa-pagination__list li',
    UNREAD_MESS: '[data-testid="unread-messages"]',
    MODAL_POPUP: '[data-testid="print-modal-popup"]',
    CREAT_NEW_TEXT_FOLD: '[text="Create new folder"]',
    LAST_EDIT_DATE: '[data-testid="last-edit-date"]',
    MOVE_MODAL: '[data-testid="move-to-modal"]',
    DELETE_MES_MODAL: '[data-testid="delete-message-modal"]',
    NO_MESS: '[data-testid=alert-no-messages] p',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DRAFT_MESSAGE: '@draft_message',
    MAIN_CONTENT: '.va-alert',
    PAGE_TITLE: '.page-title',
    EXPANDABLE_TITLE: '[class="alert-expandable-title"]',
    NOTIFICATION: '[close-btn-aria-label*="Close notification"]',
    VA_CRISIS_LINE: '[text="Connect with the Veterans Crisis Line"]',
    SAVE_DRAFT: '#messagetext',
    HIGHLIGHTED: '[data-testid="highlighted-text"]',
    SIDEBAR_NAV: '[class="sidebar-navigation-messages-list-header"]',
    INBOX_TEXT: '[text="Go to your inbox"]',
    EDIT_DRAFT: '#edit-draft-button',
    WELCOME_MESSAGE: '.welcome-message',
    BACK_TOP: 'va-back-to-top',
    CERNER_ALERT: '[data-testid="cerner-facilities-alert"]',
    BLOCKED_GROUP: '[data-testid="blocked-triage-group-alert"]',
    RECIP_SELECT: '[data-testid="compose-recipient-select"]',
    MESS_CATAGO: '[data-testid="compose-message-categories"]',
    LIST_HEADER: '.sidebar-navigation-messages-list-header > a',
    SUCCESS_ALERT: '[data-testid="close-success-alert-button"]',
    DELETE_MESSAGE: '[data-testid=delete-message-modal]',
    ERROR_MESSAGE: '[data-testid="file-input-error-message"]',
    ERROR_MODAL: '[data-testid="attach-file-error-modal"]',
    VA_ALERT_WARNING: 'va-alert[status="warning"]',
    GEN_ALERT: '[data-testid="alert-text"]',
    CANCEL: '[text="Cancel"]',
    EXPIRED_MESSAGE: '[data-testid="expired-alert-message"]',
    ES_ALERT: '[data-testid="quit-compose-double-dare"]',
    ALERT_MODAL: `[data-testid="navigation-warning-modal"]`,
    SAVE_ALERT: `[data-test-id="save-alert-message"]`,
    CL_SAVE: `[data-testid="sm-route-navigation-guard-confirm-button"]`,
    CL_DELETE_AND_EXIT: `[data-testid="sm-route-navigation-guard-cancel-button"]`,
    ALERT_TEXT: `[data-testid="alert-text"]`,
    ATTCH_VIRUS: `[data-testid="attachment-virus-alert"]`,
    VA_ALERT: `va-alert`,
    FIELD_ERROR: `#input-error-message`,
    REMOVE_THIS_FOLDER: `[data-testid="remove-this-folder"]`,
    OLD_MSG_HEAD: `[data-testid=expired-alert-message]`,
    NO_ASSOCIATION: '[data-testid="not-connected-alert"]',
  },
  FIELDS: {
    RECIPIENT: '#select',
    SUBJECT: '#inputField',
    MESSAGE: '#textarea',
    VISIBLE_P: '[visible=""] > p',
    CATEGORY_DROPDOWN: '[data-testid="category-dropdown"]',
    DATE_RANGE_DROPDOWN: '#date-range-dropdown',
    CATEGORY_OPTION: `[data-testid="category-dropdown"]>option`,
    DATE_RANGE_OPTION: '[data-testid="date-range-dropdown"]>option',
    SEARCH_MESSAGE_HEADING: '[data-testid="search-messages"] h2',
    SEARCH_MESSAGE: '[data-testid="search-messages"] [aria-live="polite"]',
    FILTER_MESSAGE_TEXT: '[data-testid="search-form"] h2',
    NOT_FOR_PRINT_HEADER: '[data-testid="not-for-print-header"]',
    EL_SIGN: `[message-aria-describedby="Electronic signature"]`,
    MESSAGE_SUBJECT: '[data-testid="message-subject-field"]',
    MESSAGE_BODY: `[data-testid="message-body-field"]`,
    RECIPIENTS_COMBO: `#options`,
  },
  INFO: {
    SUBJECT_LIMIT: '#charcount-message',
    ADDITIONAL_INFO: '[class="additional-info-title"]',
    ATTACH_OPT: '[class="how-to-attach-files"] li',
  },
  BLOCKS: {
    ATTACHMENTS: '.attachments-list',
    FILTER_START_DATE: `[data-testid="date-start"]`,
    FILTER_END_DATE: `[data-testid="date-end"]`,
  },
  CHECKBOX: {
    CL_ALL: '[data-testid*="select-all"]',
    CL_SINGLE: '[data-testid*="contact-list-select-team"]',
  },
  HEADERS: {
    DRAFTS_HEADER: '#draft-reply-header',
  },
  SUBHEADERS: {
    NUMBER_OF_THREADS: `[data-testid="displaying-number-of-threads"]`,
  },
  DROPDOWN: {
    RECIPIENTS: `select#options`,
    ADD_INFO: `va-additional-info[trigger^="If you"]`,
    SORT: '#sort-order-dropdown',
    RECIPIENTS_COMBO: `#options--list`,
  },
  ICONS: {
    ATTCH_ICON: '[data-testid="attachment-icon"]',
  },
};

export const Alerts = {
  NO_ASSOCIATION: {
    AT_ALL_HEADER: `You're not connected to any care teams in this messaging tool`,
    HEADER: 'Your account is no longer connected to',
    PARAGRAPH:
      'If you need to contact your care team, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  BLOCKED: {
    HEADER: `You can't send messages to`,
    PARAGRAPH:
      'If you need to contact this care team, call your VA health facility.',
    ALL_PARAGRAPH:
      'If you need to contact your care teams, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  CONTACT_LIST: {
    SAVE: 'Do you want to save your changes to your contact list?',
    SAVED: 'Contact list changes saved',
    EMPTY: `Select at least one team`,
    SAVE_API_ERROR: `We're sorry. We couldn't save your changes. Try saving again.`,
    LOAD_API_ERROR: `We can’t load your contact list right now`,
  },
  ATTACHMENT: {
    TYPES: `We can't attach this file type. Try attaching a DOC, DOCX, GIF, JPG, PDF, PNG, RTF, TXT, XLS XLSX, JPEG, JFIF, PJPEG, or PJP.`,
    EMPTY: `Your file is empty. Try attaching a different file.`,
    FILE_IS_TOO_LARGE_TEXT:
      'Your file is too large. Try attaching a file smaller than 6MB.',
    ALREADY_ATTACHED_FILE: 'You have already attached this file.',
  },
  MAINTENANCE: {
    ACTIVE: `Maintenance on My HealtheVet`,
    UPCOMING: `Upcoming maintenance on My HealtheVet`,
  },
  DATE_FILTER: {
    EMPTY_START_DATE: `Error Please enter a start date.`,
    EMPTY_END_DATE: `Error Please enter an end date.`,
    INVALID_START_DATE: `Start date must be on or before end date.`,
    INVALID_END_DATE: `End date must be on or after start date.`,
  },
  OUTAGE: 'We’re sorry. We couldn’t load this page. Try again later.',
  OLD_MSG_HEAD: 'This conversation is too old for new replies',
  OLD_MSG_SUBHEAD:
    "The last message in this conversation is more than 45 days old. If you want to continue this conversation, you'll need to start a new message.",
  PAGE_NOT_FOUND: pageNotFoundHeading,
  TRY_SEARCH: 'Try the search box or one of the common questions below.',
  SAVE_ATTCH: `We can't save attachments in a draft message`,
  EL_SIGN: `Messages to this team require a signature. We added a signature box to this page.`,
  EL_SIGN_NAME: `Enter your full name`,
  EL_SIGN_CHECK: `You must certify by checking the box.`,
  SAVE_SIGN: `We can't save your signature in a draft message`,
  SAVE_SIGN_ATTCH: `We can't save your signature or attachments in a draft message`,
  VIRUS_ATTCH: `Our file scanner found a problem with your attachment. To send your message, remove this attachment.`,
  VIRUS_MULTI_ATTCH: `Our file scanner found a problem with your attachments. To send your message, remove the attachments.`,
  SAVE_DRAFT: `Do you want to save your draft message?`,
  SAVE_CHANGES: `Do you want to save your changes to this draft?`,
};

export const Data = {
  TEST_MESSAGE_BODY: '\nTest message body',
  TEST_SUBJECT: 'Test Subject',
  TEST_IMAGE: 'test_image.jpg',
  TEST_LARGE_IMAGE: 'test_image_10mb.jpg',
  MESSAGE_WAS_SAVED: 'message was saved',
  TEST_MESSAGE_SUBJECT: 'Test Message Subject',
  SAMPLE_DOC: 'sample_docx.docx',
  SAMPLE_PDF: 'sample_pdf.pdf',
  SAMPLE_XLS: 'sample_XLS.xls',
  SAMPLE_IMG: 'test_image.gif',
  START_NEW_MSG: 'Start a new message',
  EDIT_DRAFT: 'Edit draft',
  GO_YOUR_INBOX: 'Go to your inbox',
  BACK_TO_MSG: 'Back to messages',
  FOLDER_NAME_CANNOT_BLANK: 'Folder name cannot be blank',
  FOLDER_REMOVED_SUCCESSFULLY: 'Folder was successfully removed.',
  FOLDER_CREATED_SUCCESSFULLY: 'Folder was successfully created.',
  FOLDER_RENAMED_SUCCESSFULLY: 'Folder was successfully renamed.',
  SECURE_MSG_SENT_SUCCESSFULLY: 'Message Sent.',
  PLEASE_SELECT_RECIPIENT: 'Please select a recipient.',
  PLEASE_SELECT_CATEGORY: 'Please select a category.',
  SUBJECT_CANNOT_BLANK: 'Subject cannot be blank.',
  BODY_CANNOT_BLANK: 'Message body cannot be blank.',
  ATTACH_ADDITIONAL_FILE: 'Attach additional file',
  MESSAGE_CANNOT_SAVE_YET: "We can't save this message yet",
  CONTINUE_EDITING: 'Continue editing',
  MESSAGE_MOVED_TO_TRASH:
    'Message conversation was successfully moved to Trash.',
  TEST_VIDEO: 'test_video.mp4',
  CREATE_FOLDER_TEST: 'create folder test',
  IS_ACTIVE: 'is-active',
  END_CONVERSATION_IN_FOLDER: 'End of conversations in this folder',
  SAVE_MEG_AS_DRAFT: 'If you save this message as a draft',
  EDIT_YOUR_MSG_PREFRENCES: 'Edit your message preferences',
  NO_MSG_IN_FOLDER: 'There are no messages in this folder.',
  WHAT_SECURE_MSG_PILOT: 'What is Secure Messaging Pilot?',
  CANNOT_SEND_MSG_TO_CARE_TEAM:
    "You can't send messages to your care teams right now",
  REMOVE_FOLDER: 'Remove folder',
  CANNOT_REMOVE_FOLDER: `You can't remove a folder with messages in it. Move all the messages to another folder. Then try removing it again.`,
  ATTACH_INFO: [
    'You may attach up to 4 files to each message',
    'You can attach only these file types: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx, jpeg, jfif, pjpeg, pjp',
    'The maximum size for each file is 6 MB',
    'The maximum total size for all files attached to 1 message is 10 MB',
  ],
  EL_SIGN_CHECK: `I certify that the above is correct and true to the best of my knowledge and belief.`,
  EDIT_SIGNATURE: `Edit signature for all messages`,
  BUTTONS: {
    ATTACH_FILE: 'Attach file',
    SEND: `Send`,
    SAVE_DRAFT: `Save draft`,
    SAVE_DRAFT_WO_SIGN: 'Save draft without signature',
    SAVE_DRAFT_WO_SIGN_ATTCH: 'Save draft without signature or attachments',
    SAVE_AND_EXIT: `Save contact list`,
    EDIT_DRAFT: `Edit draft`,
    EDIT_DRAFT_REPLY: `Edit draft reply`,
    DELETE_DRAFT: `Delete draft`,
    GO_BACK: `Go back`,
    SAVE_CHANGES: 'Save changes',
    DELETE_CHANGES: 'Delete changes',
    KEEP_EDITING: 'Keep editing',
    SAVE_DRAFT_WO_ATTCH: `Save draft without attachments`,
  },
  LINKS: {
    PROFILE_SIGNATURE: `/profile/personal-information#messaging-signature`,
    LEGACY_PREFERENCES: 'mhv-portal-web/preferences',
  },
  CL_LINK_TEXT: 'Show more teams in your contact list',
  URL: {
    LANDING_PAGE: `http://localhost:3001/my-health/secure-messages/`,
  },
  FAQ_LINK: {
    URL: {
      FACILITY: `/find-locations/`,
      EMRG: `tel:911`,
      SETTINGS: `/mhv-portal-web/preferences`,
      PAY: `/health-care/pay-copay-bill/dispute-charges/`,
    },
    TEXT: {
      FACILITY: `Find your nearest VA health facility`,
      EMRG_BTN: `Connect with the Veterans Crisis Line`,
      EMRG: `911`,
      SETTINGS: `My HealtheVet (opens in new tab)`,
      PAY: `Learn how to dispute your VA copay charges`,
    },
  },
  DATE_RANGE: {
    THREE_MONTHS: `Last 3 months`,
    SIX_MONTHS: `Last 6 months`,
    TWELVE_MONTHS: `Last 12 months`,
  },
  INBOX_FOOTER: {
    HEADER: `Need help?`,
    PARAGRAPH_1: `Have questions about how messages works?`,
    PARAGRAPH_2: `Want to send a message to a care team that’s not on your list? Contact your VA health facility. Ask for the My HealtheVet coordinator or secure messaging administrator.`,

    LINK_1: `Learn more about messages`,
    LINK_2: `Find your VA health facility`,
  },
};
export const Assertions = {
  MESSAGES: 'Messages',
  FOLDER_RENAMED_SUCCESS: 'Folder was successfully renamed.',
  MESSAGE_CONVERSATION_SUCCESS: 'Message conversation was successfully moved.',
  MESSAGE_CONVERSATION_SUCCESS_TRASH:
    'Message conversation was successfully moved to Trash.',
  SELECT_RECIPIENT: ' Please select a recipient.',
  DRAFT_DELETED_SUCCESS: 'Draft was successfully deleted.',
  CANT_SAVE_MESSAGE_YET: "We can't save this message yet",
  CONTINUE_EDITING: 'Continue editing',
  INBOX: 'Inbox',
  DRAFT: 'Draft',
  EDITED: 'edited',
  ACTIVE: 'is-active',
  MESSAGE_PREFERENCES: 'Edit your message preferences',
  NO_MESSAGE_FOLDER: 'There are no messages in this folder.',
  CODE_STATUS: 'statusCode',
  SECURE_MESSAGE_PILOT: 'What is Secure Messaging Pilot?',
  NEW_MESSAGE: 'new-message',
  ARIA_EXPANDED: 'aria-expanded',
  EMPTY_THIS_FOLDER: 'Empty this folder',
  NO_MATCHES_SEARCH: 'We didn’t find any matches for these filters',
};

export const Arrays = {
  FilterDateRange: [
    'ANY',
    'LAST 3 MONTHS',
    'LAST 6 MONTHS',
    'LAST 12 MONTHS',
    'CUSTOM',
  ],

  Categories: [
    'OTHER',
    'COVID',
    'APPOINTMENT',
    'MEDICATION',
    'TEST_RESULT',
    'EDUCATION',
    'GENERAL',
    'TEST',
  ],
};
