import { pageNotFoundHeading } from '@department-of-veterans-affairs/platform-site-wide/PageNotFound';

export const AXE_CONTEXT = '.secure-messaging-container';

export const Paths = {
  MHV_MAIN: '/my-health/',
  UI_MAIN: '/my-health/secure-messages',
  SM_API_BASE: '/my_health/v1/messaging',
  SM_API_EXTENDED: '/my_health/v1/messaging/messages',
  INBOX: '/inbox/',
  SENT: '/sent/',
  DRAFTS: '/drafts/',
  DRAFT: '/draft/',
  DELETED: '/trash/',
  COMPOSE: '/new-message/',
  RECENT_CARE_TEAMS: 'recent/',
  START_MESSAGE: '/start-message',
  SELECT_CARE_TEAM: '/select-care-team',
  MESSAGE: '/message/',
  MESSAGE_THREAD: '/thread/',
  FOLDERS: '/folders',
  SEARCH: '/search/',
  SEARCH_RESULTS: '/search/results/',
  REPLY: '/reply/',
  CATEGORIES: '/categories',
  RECIPIENTS: '/allrecipients',
  SIGNATURE: '/signature',
  FIND_LOCATIONS: '/find-locations/',
  FIND_LOCATION: '/find-locations',
  HEALTH_CARE_SEND_RECEIVE_MSG: '/health-care/send-receive-messages/',
  MHV_LANDING_PAGE: '/my-health',
  MHV_SM: '/secure-messages',
  THREAD: '/thread',
  CONTACT_LIST: '/contact-list',
  NEW_MESSAGE: '/my-health/secure-messages/new-message/',
  AAL: '/my_health/v1/aal',
  INTERCEPT: {
    MESSAGE_RECIPIENT: '/my_health/v1/messaging/recipients*',
    MESSAGE_CATEGORY: '/my_health/v1/messaging/messages/categories',
    MESSAGE_FOLDER: '/my_health/v1/messaging/folders*',
    MESSAGE_FOLDERS: '/my_health/v1/messaging/folders',
    MESSAGE_FOLDER_THREAD: '/my_health/v1/messaging/folders/0/threads?*',
    MESSAGE_FOLDER_MESS: '/my_health/v1/messaging//folders/0/messages*',
    MESSAGE_DRAFTS: '/my_health/v1/messaging/message_drafts',
    MESSAGE_FOLDERS_SEARCH: '/my_health/v1/messaging/folders/*/search',
    MESSAGE_FOLDERS_2: '/my_health/v1/messaging/folders/-2*',
    FEATURE_TOGGLES: '/v0/feature_toggles?*',
    MESSAGE_THREADS: '/my_health/v1/messaging/threads/',
    MESSAGE_SIGNATURE: '/my_health/v1/messaging/preferences/signature',
    MESSAGE_ALLRECIPIENTS: '/my_health/v1/messaging/allrecipients',
    MESSAGES: '/my_health/v1/messaging/messages',
    SELECTED_RECIPIENTS: `/my_health/v1/messaging/preferences/recipients`,
    MAINTENANCE_WINDOWS: `/v0/maintenance_windows/`,
    DRAFT_AUTO_SAVE: `/my_health/v1/messaging/message_drafts`,
    SENT_THREADS: '/my_health/v1/messaging/folders/-1/threads*',
    SENT_SEARCH: '/my_health/v1/messaging/folders/-1/search*',
    PRESCRIPTIONS: '/my_health/v1/prescriptions/',
  },
};

export const Locators = {
  FROM_TO_DATES_CONTAINER: '.fromToDatesContainer',
  MESSAGE_FAQ: '.secure-messaging-faq',
  MESSAGES: '[data-testid="message-list-item"]',
  TO: '[data-testid="to"]',
  FROM: '[data-testid="from"]',
  MSG_ID: '[data-testid="message-id"]',
  MSG_DATE: '[data-testid="message-date"]',
  DATE_RECEIVED: '[data-testid="received-date"]',
  HEADER_FOLDER: '[data-testid*=folder-header]',
  ATTACH_FILE_INPUT: '[data-testid="attach-file-input"]',
  ATTACHMENT_COUNT: '[data-testid="attachments-count"]',
  MESSAGES_BODY_DRAFT: '.message-body-draft-preview',
  CERNER: '[data-testid="cerner-facility"]',
  CERNER_TEXT: '[data-testid="single-cerner-facility-text"]',
  DELETE_MES_CONFIRM: '[data-testid="delete-message-confirm-note"] p',
  SELECT: '#select',
  HEADER: 'h1',
  HEADER2: 'h2',
  HEADLINE: 'h1[slot="headline"]',
  KEYWORD_SEARCH: '[data-testid="keyword-search-input"]',
  NO_MESS: '[data-testid=alert-no-messages] p',
  FOLDER_NAME: '[data-testid="folder-name"]',
  FOLDERS_LIST: '[data-testid ="my-folders-sidebar"]',
  MESS_LIST: '[data-testid="message-list-item"]',
  THREAD_LIST: '.thread-list-item',
  THREADS: '[data-testid="thread-list-item"]',
  MES_COUNT: '[data-testid="message-count"]',
  REPLY_FORM: '[data-testid="reply-form"]',
  REPLY_TO: '[data-testid="draft-reply-to"]',
  CLEAR_FILTERS: '[text="Clear Filters"]',
  FILTER_INPUT: '#filter-input',
  ADDITIONAL_FILTER: '#additional-filter-accordion',
  ACCORDIONS: '[data-testid="faq-accordion-item"]',
  ACCORDION_ITEM_OPEN: 'va-accordion-item[open]:not([open="false"])',
  MESSAGE_THREAD_META: '.message-thread-meta',
  SPINNER: 'va-loading-indicator',
  BACK_BREADCRUMB_DATA_TEST_ID: 'sm-breadcrumbs-back',
  FAQ_ACC_ITEM: '[data-testid="faq-accordion-item"]',
  INBOX_FOOTER: `[data-testid="inbox-footer"]`,
  COMBO_BOX: '.usa-combo-box',
  SEARCH_RESULT: `[data-testid="search-messages"]`,
  PAGE_NOT_FOUND: `mhv-page-not-found`,
  CARE_SYSTEM: '[data-testid^="care-system-"]',
  EMERGENCY_USE_EXPANDABLE_DATA_TEST_ID: 'emergency-use-only-expandable',
  RECENT_CARE_TEAMS_RADIO_GROUP_TEST_ID: 'recent-care-teams-radio-group',
  RECENT_CARE_TEAMS_CONTINUE_BUTTON_DATA_TEST_ID:
    'recent-care-teams-continue-button',
  COMPOSE_RECIPIENT_TITLE: 'compose-recipient-title',
  COMPOSE_CATEGORY_DROPDOWN: 'compose-message-categories',
  LOCKED_CATEGORY_DISPLAY: 'locked-category-display',
  INTERSTITIAL_CONTINUE_BUTTON: 'continue-button',
  FOLDERS: {
    FOLDER_NAME: '[label="Folder name"]',
    FOLDER_REMOVE: 'va-button[text="Yes, remove this folder"]',
    FOLDER_REMOVE_DATA_TEST_ID: 'confirm-remove-folder',
    FOLDER_HEADER: '[data-testid="folder-header"]',
    INBOX: '[data-testid="inbox-sidebar"] > a',
    DRAFTS: '[data-testid="drafts-sidebar"]',
    SENT: '[data-testid="sent-sidebar"]',
    TRASH: '[data-testid="trash-sidebar"]',
    CUSTOM: '[data-testid="my-folders-sidebar"]',
    SIDEBAR: '[data-testid=my-folders-sidebar]',
    NOT_EMP_FOLDER: '[data-testid="error-folder-not-empty"] p',
    FOLDER_INPUT_LABEL: '[data-testid="search-message-folder-input-label"]',
    FOLDER_DROPDOWN: '[data-testid="folder-dropdown"]',
    FOLDER_NOT_EMPTY: 'va-modal[data-testid="error-folder-not-empty"]',
  },
  BUTTONS: {
    SECURE_MESSAGING: '[data-testid="secure-messaging"]',
    THREAD_EXPAND: 'thread-expand-all',
    THREAD_EXPAND_MESSAGES:
      '[data-testid="thread-expand-all"] va-accordion-item',
    ADDITIONAL_FILTER: `.va-accordion__header`,
    TRASH_TEXT: '[data-testid=trash-button-text]',
    TEXT_CONFIRM: 'va-button[text="Confirm"]',
    // check if below are duplicates
    REPLY_BTN: '#reply-button',
    REPLY: '[data-testid="reply-button-body"]',
    CONTINUE: 'continue-button',
    TEST2: '[data-testid=radiobutton-TEST2]',
    TESTAGAIN: '[data-testid=radiobutton-TESTAGAIN]',
    NEW_FOLDER_RADIOBTN: '[data-testid=folder-list-radio-button]',
    DELETE_RADIOBTN: '[data-testid=radiobutton-Deleted]',
    MOVE: `#move-button`,
    TRASH: `#trash-button`,
    BUTTON_TEXT: '[data-testid="trash-button-text"]',
    MOVE_BUTTON_TEST_ID: 'move-button-text',
    MOVE_MODAL_TEST_ID: 'move-to-modal',
    FILTER: '[data-testid="filter-messages-button"]',
    SEND: '[data-testid="send-button"]',
    SEND_TEST_ID: 'send-button',
    SAVE_DRAFT: '[data-testid="save-draft-button"]',
    PRINT_ONE_MESS: '[data-testid="radio-print-one-message"]',
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DELETE_DRAFT: '[data-testid="delete-draft-button"]',
    EDIT_FOLDER: '[data-testid="edit-folder-button"]',
    DELETE_FOLDER: '[data-testid="remove-folder-button"]',
    PRINT: '[data-testid="print-button"]',
    SORT: '[data-testid="sort-button"]',
    ATTACH_FILE: 'attach-file-button',
    REMOVE_ATTACHMENT: '[data-testid="remove-attachment-button"]',
    REMOVE_ALL_ATTCH: `[data-testid="remove-all-attachments-button"]`,
    CONFIRM_REMOVE_ATTACHMENT:
      '[data-testid="confirm-remove-attachment-button"]',
    CONTINUE_EDITING: 'va-button[text="Continue editing"]',
    CREATE_FOLDER: '[data-testid="create-folder-button"]',
    REMOVE_FOLDER: '[data-testid="remove-folder-button"]',
    CATEGORY_RADIOBTN: '[data-testid="compose-category-radio-button"]',
    DELETE_CANCEL: '#delete-cancel',
    DELETE_CONFIRM: '#delete-draft',
    EDIT_DRAFT: `[data-testid="edit-draft-button-body"]`,
    EDIT_DRAFTS: '[data-testid="edit-draft-button-body-text"]',
    CL_SAVE: `[data-testid="contact-list-save"]`,
    CL_GO_BACK: 'contact-list-go-back',
    ALERT_CLOSE: `.first-focusable-child`,
  },
  LINKS: {
    GO_TO_INBOX: '[data-testid="inbox-link"]',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
    CREATE_NEW_MESSAGE_DATA_TEST_ID: 'compose-message-link',
    CRUMB: 'ol[role="list"] > li',
    CRUMB_LIST: '[data-testid="sm-breadcrumbs"]',
    OLD_VERSION: `.welcome-message > p > a`,
    EDIT_SIGNATURE: `div.vads-u-margin-top--2`,
    REPLY: `reply-to-message-link`,
    START_NEW_MESSAGE: 'start-message-link',
  },
  ALERTS: {
    HEADER: `[data-testid="error-folder-not-empty"]`,
    MODEL_TITLE_ALERT: '.va-modal-alert-title',
    TRIAGE_ALERT: '[data-testid="blocked-triage-group-alert"] va-link-action',
    CLOSE_NOTIFICATION: '.va-alert',
    REPT_SELECT: '[data-testid="compose-recipient-select"]',
    DRAFT_MODAL: '[data-testid="delete-draft-modal"]',
    THREAD_EXPAND: 'thread-expand-all',
    SEARCH_DROPDOWN: '#select-search-folder-dropdown',
    TEXT_INPUT: '[data-testid="search-keyword-text-input"]',
    PAGIN_LIST: '.usa-pagination__list li',
    UNREAD_MESS: '[data-testid="unread-messages"]',
    MODAL_POPUP: '[data-testid="print-modal-popup"]',
    CREAT_NEW_TEXT_FOLD: '[text="Create new folder"]',
    LAST_EDIT_DATE: '[data-testid="last-edit-date"]',
    MOVE_MODAL: '[data-testid="move-to-modal"]',
    DELETE_MES_MODAL: '[data-testid="delete-message-modal"]',
    NO_MESS: '[data-testid=alert-no-messages] p',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DRAFT_MESSAGE: '@draft_message',
    MAIN_CONTENT: '.va-alert',
    PAGE_TITLE: '.page-title',
    EXPANDABLE_TITLE: '[class="alert-expandable-title"]',
    NOTIFICATION: '[close-btn-aria-label*="Close notification"]',
    VA_CRISIS_LINE: '[text="Connect with the Veterans Crisis Line"]',
    SAVE_DRAFT: '#messagetext',
    HIGHLIGHTED: '[data-testid="highlighted-text"]',
    SIDEBAR_NAV: '[class="sidebar-navigation-messages-list-header"]',
    INBOX_TEXT: '[text="Go to your inbox"]',
    EDIT_DRAFT: '#edit-draft-button',
    WELCOME_MESSAGE: '.welcome-message',
    BACK_TOP: 'va-back-to-top',
    CERNER_ALERT: '[data-testid="cerner-facilities-alert"]',
    BLOCKED_GROUP: '[data-testid="blocked-triage-group-alert"]',
    RECIPIENTS_ERROR: 'recipients-error-alert',
    RECIP_SELECT: '[data-testid="compose-recipient-select"]',
    MESS_CATAGO: '[data-testid="compose-message-categories"]',
    LIST_HEADER: '.sidebar-navigation-messages-list-header > a',
    SUCCESS_ALERT: '[data-testid="close-success-alert-button"]',
    DELETE_MESSAGE: '[data-testid=delete-message-modal]',
    ERROR_MESSAGE: '[data-testid="file-input-error-message"]',
    ERROR_MODAL: '[data-testid="attach-file-error-modal"]',
    VA_ALERT_WARNING: 'va-alert[status="warning"]',
    GEN_ALERT: '[data-testid="alert-text"]',
    CANCEL: '[text="Cancel"]',
    EXPIRED_MESSAGE: '[data-testid="expired-alert-message"]',
    ES_ALERT: '[data-testid="quit-compose-double-dare"]',
    ALERT_MODAL: `[data-testid="navigation-warning-modal"]`,
    SAVE_ALERT: `[data-test-id="save-alert-message"]`,
    CL_SAVE: `[data-testid="sm-route-navigation-guard-confirm-button"]`,
    CL_DELETE_AND_EXIT: `[data-testid="sm-route-navigation-guard-cancel-button"]`,
    ALERT_TEXT: `[data-testid="alert-text"]`,
    ATTCH_VIRUS: `[data-testid="attachment-virus-alert"]`,
    VA_ALERT: `va-alert`,
    FIELD_ERROR: `#input-error-message`,
    REMOVE_THIS_FOLDER: `[data-testid="remove-this-folder"]`,
    OLD_MSG_HEAD: `[data-testid=expired-alert-message]`,
    NO_ASSOCIATION: '[data-testid="not-connected-alert"]',
    COMBO_BOX: '.usa-error-message',
    EL_SIGN_NAME: '#input-error-message .usa-error-message',
    EL_SIGN_CHECK: `#checkbox-error-message .usa-error-message`,
    ADD_MEDICATION_INFO_WARNING: 'add-medication-info-warning',
  },
  FIELDS: {
    RECIPIENT: '#select',
    SUBJECT: '#inputField',
    MESSAGE: '#textarea',
    VISIBLE_P: '[visible=""] > p',
    CATEGORY_DROPDOWN: '[data-testid="category-dropdown"]',
    DATE_RANGE_DROPDOWN: '#date-range-dropdown',
    CATEGORY_OPTION: `[data-testid="category-dropdown"]>option`,
    DATE_RANGE_OPTION: '[data-testid="date-range-dropdown"]>option',
    SEARCH_MESSAGE_HEADING: '[data-testid="search-messages"] h2',
    SEARCH_MESSAGE: '[data-testid="search-messages"] [aria-live="polite"]',
    FILTER_MESSAGE_TEXT: '[data-testid="search-form"] h2',
    NOT_FOR_PRINT_HEADER: '[data-testid="not-for-print-header"]',
    EL_SIGN: `[message-aria-describedby="Electronic signature"]`,
    MESSAGE_SUBJECT: '[data-testid="message-subject-field"]',
    MESSAGE_SUBJECT_DATA_TEST_ID: 'message-subject-field',
    MESSAGE_BODY: 'message-body-field',
    RECIPIENTS_COMBO: `#options`,
  },
  INFO: {
    SUBJECT_LIMIT: '#charcount-message',
    ADDITIONAL_INFO: '[class="additional-info-title"]',
    ATTACH_OPT: '[class="how-to-attach-files"] li',
  },
  BLOCKS: {
    ATTACHMENTS: '.attachments-list',
    FILTER_START_DATE: `[data-testid="date-start"]`,
    FILTER_KEYWORD_INPUT: `[data-testid="keyword-search-input"]`,
    FILTER_END_DATE: `[data-testid="date-end"]`,
  },
  CHECKBOX: {
    CL_ALL: '[data-testid*="select-all"]',
    CL_SINGLE: '[data-testid*="contact-list-select-team"]',
  },
  HEADERS: {
    DRAFTS_HEADER: '#draft-reply-header',
  },
  SUBHEADERS: {
    NUMBER_OF_THREADS: `[data-testid="displaying-number-of-threads"]`,
  },
  DROPDOWN: {
    RECIPIENTS: `select#options`,
    ADD_INFO: `va-additional-info[trigger^="If you"]`,
    SORT: '#sort-order-dropdown',
    RECIPIENTS_COMBO: `#options--list`,
  },
  ICONS: {
    ATTCH_ICON: '[data-testid="attachment-icon"]',
  },
};

export const Alerts = {
  NO_ASSOCIATION: {
    AT_ALL_HEADER: `You're not connected to any care teams in this messaging tool`,
    HEADER: 'Your account is no longer connected to',
    PARAGRAPH:
      'If you need to contact your care team, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  BLOCKED: {
    HEADER: `You can't send messages to`,
    PARAGRAPH:
      'If you need to contact this care team, call your VA health facility.',
    ALL_PARAGRAPH:
      'If you need to contact your care teams, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  CONTACT_LIST: {
    SAVE: 'Do you want to save your changes to your contact list?',
    SAVED: 'Contact list changes saved',
    EMPTY: `Select at least one team`,
    SAVE_API_ERROR: `We're sorry. We couldn't save your changes. Try saving again.`,
    LOAD_API_ERROR: `We can’t load your contact list right now`,
  },
  ATTACHMENT: {
    TYPES: `We can't attach this file type. Try attaching a DOC, DOCX, GIF, JPG, JPEG, PDF, PNG, RTF, TXT, XLS, XLSX, JFIF, PJPEG, or PJP.`,
    TYPES_EXPANDED: `We can't attach this file type. Try attaching a DOC, DOCX, GIF, JPG, JPEG, PDF, PNG, RTF, TXT, XLS, XLSX, BMP, TIFF, TIF, PPT, PPTX, PPS, PPSX, ODT, MP4, M4V, MOV, WMV, MPG, JFIF, PJPEG, or PJP.`,
    EMPTY: `Your file is empty. Try attaching a different file.`,
    VISTA_TOO_LARGE:
      'Your file is too large. Try attaching a file smaller than 6MB.',
    VISTA_ALL_FILES_TOO_LARGE:
      'Your files are too large. The total size of all files must be smaller than 10MB.',
    LARGE_UPLOAD_FILE_TOO_LARGE:
      'Your file is too large. Try attaching a file smaller than 25MB.',
    LARGE_UPLOAD_TOTAL_TOO_LARGE:
      'Your files are too large. The total size of all files must be smaller than 25MB.',
    ALREADY_ATTACHED: 'You have already attached this file.',
  },
  MAINTENANCE: {
    ACTIVE: `Maintenance on My HealtheVet`,
    UPCOMING: `Upcoming maintenance on My HealtheVet`,
  },
  DATE_FILTER: {
    EMPTY_START_DATE: `Error Please enter a start date.`,
    EMPTY_END_DATE: `Error Please enter an end date.`,
    INVALID_START_DATE: `Start date must be on or before end date.`,
    INVALID_END_DATE: `End date must be on or after start date.`,
  },
  OH_OLD_MSG: {
    HEADER: 'This conversation is too old for new replies',
    P_1: `The last message in this conversation is more than 45 days old.`,
    P_2: `If you want to continue this conversation directly with your provider, call your VA health facility. Ask to speak to the My HealtheVet coordinator or secure messaging administrator.`,
    P_3: `Or you can send a message to other care teams in your contact list.`,
  },
  OUTAGE: 'We’re sorry. We couldn’t load this page. Try again later.',
  OLD_MSG_HEAD: 'This conversation is too old for new replies',
  OLD_MSG_SUBHEAD:
    "The last message in this conversation is more than 45 days old. If you want to continue this conversation, you'll need to start a new message.",
  PAGE_NOT_FOUND: pageNotFoundHeading,
  TRY_SEARCH: 'Try the search box or one of the common questions below.',
  SAVE_ATTCH: `We can't save attachments in a draft message`,
  EL_SIGN: `Messages to this team require a signature. We added a signature box to this page.`,
  EL_SIGN_NAME: `Enter your full name`,
  EL_SIGN_CHECK: `You must certify by checking the box.`,
  SAVE_SIGN: `We can't save your signature in a draft message`,
  SAVE_SIGN_ATTCH: `We can't save your signature or attachments in a draft message`,
  VIRUS_ATTCH: `Our file scanner found a problem with your attachment. To send your message, remove this attachment.`,
  VIRUS_MULTI_ATTCH: `Our file scanner found a problem with your attachments. To send your message, remove the attachments.`,
  SAVE_DRAFT: `Do you want to save your draft message?`,
  SAVE_CHANGES: `Do you want to save your changes to this draft?`,
  SEARCH_TERM_REQUIRED: 'Please enter a search term.',
  ERROR_LOADING_RECIPIENTS_HEADER:
    'We can’t load your care team list right now',
  SEND_MESSAGE_SUCCESS: `Message sent`,
};

export const Data = {
  TEST_MESSAGE_BODY: '\nTest message body',
  TEST_SUBJECT: 'Test Subject',
  TEST_IMAGE: 'test_image.jpg',
  TEST_LARGE_IMAGE: 'test_image_10mb.jpg',
  TEST_VIDEO_MKV: 'test_video.mkv',
  MESSAGE_WAS_SAVED: 'message was saved',
  TEST_MESSAGE_SUBJECT: 'Test Message Subject',
  SAMPLE_DOC: 'sample_docx.docx',
  SAMPLE_XLS: 'sample_XLS.xls',
  SAMPLE_PDF: 'sample_pdf.pdf',
  SAMPLE_TXT_1: 'test_txt_1.txt',
  SAMPLE_TXT_2: 'test_txt_2.txt',
  SAMPLE_TXT_3: 'test_txt_3.txt',
  SAMPLE_TXT_4: 'test_txt_4.txt',
  SAMPLE_IMG: 'test_image.gif',
  START_NEW_MSG: 'Start a new message',
  EDIT_DRAFT: 'Edit draft',
  GO_YOUR_INBOX: 'Go to your inbox',
  BACK_TO_MSG: 'Back to messages',
  FOLDER_NAME_CANNOT_BLANK: 'Folder name cannot be blank',
  FOLDER_REMOVED_SUCCESSFULLY: 'Folder was successfully removed.',
  FOLDER_CREATED_SUCCESSFULLY: 'Folder was successfully created.',
  FOLDER_RENAMED_SUCCESSFULLY: 'Folder was successfully renamed.',
  SECURE_MSG_SENT_SUCCESSFULLY: 'Message sent',
  PLEASE_SELECT_RECIPIENT: 'Please select a recipient.',
  PLEASE_SELECT_VALID_RECIPIENT: 'Please select a valid recipient.',
  PLEASE_SELECT_CATEGORY: 'Please select a category.',
  SUBJECT_CANNOT_BLANK: 'Subject cannot be blank.',
  BODY_CANNOT_BLANK: 'Message body cannot be blank.',
  ATTACH_ADDITIONAL_FILE: 'Attach additional file',
  MESSAGE_CANNOT_SAVE_YET: "We can't save this message yet",
  CONTINUE_EDITING: 'Continue editing',
  MESSAGE_MOVED_TO_TRASH:
    'Message conversation was successfully moved to Trash.',
  TEST_VIDEO: 'test_video.mp4',
  CREATE_FOLDER_TEST: 'create folder test',
  IS_ACTIVE: 'is-active',
  END_CONVERSATION_IN_FOLDER: 'End of conversations in this folder',
  SAVE_MEG_AS_DRAFT: 'If you save this message as a draft',
  NO_MSG_IN_FOLDER: 'There are no messages in this folder.',
  WHAT_SECURE_MSG_PILOT: 'What is Secure Messaging Pilot?',
  CANNOT_SEND_MSG_TO_CARE_TEAM:
    "You can't send messages to your care teams right now",
  REMOVE_FOLDER: 'Remove folder',
  CANNOT_REMOVE_FOLDER: `You can't remove a folder with messages in it. Move all the messages to another folder. Then try removing it again.`,
  HCS_SELECT: `Select care team`,
  REPLY_HEADER: `Only use messages for non-urgent needs`,
  RECENT_RECIPIENTS_HEADER: 'Care teams you recently sent messages to',
  RECENT_RECIPIENTS_LABEL: 'Select a team you want to message',
  RECENT_RECIPIENTS_HINT: `This list only includes teams that you've sent messages to in the last 6 months. If you want to contact another team, select "A different care team."`,
  ATTACH_INFO: [
    'You may attach up to 4 files to each message',
    'You can attach only these file types: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx, jpeg, jfif, pjpeg, pjp',
    'The maximum size for each file is 6 MB',
    'The maximum total size for all files attached to 1 message is 10 MB',
  ],
  LARGE_ATTACH_INFO: [
    'You can attach up to 10 files to each message',
    'You can attach only these file types: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlxs, jpeg, jfif, pjpeg, pjp, bmp, tiff, ppt, pptx, pps, ppsx, odt, mp4, m4v, mov, wmv, mpg',
    'The maximum size for each file is 25 MB',
    'The maximum total size for all files attached to 1 message is 25 MB',
  ],
  EL_SIGN_CHECK: `I certify that the above is correct and true to the best of my knowledge and belief.`,
  EDIT_SIGNATURE: `Edit signature for all messages`,
  READ_RECEIPT: `Opened by your care team`,
  UNREAD_RECEIPT: `Not yet opened by your care team`,
  CURATED_LIST: {
    CANT_FIND_TEAM_LINK: `Learn what to do if you can’t find your care team`,
    CONTACT_LIST_UPDATE: `Update your contact list`,
    SELECT_CARE_TEAM: `Select a different care team`,
  },
  BUTTONS: {
    ATTACH_FILE: 'Attach file',
    SEND: `Send`,
    SAVE_DRAFT: `Save draft`,
    SAVE_DRAFT_WO_SIGN: 'Save draft without signature',
    SAVE_DRAFT_WO_SIGN_ATTCH: 'Save draft without signature or attachments',
    SAVE_AND_EXIT: `Save contact list`,
    EDIT_DRAFT: `Edit draft`,
    EDIT_DRAFT_REPLY: `Edit draft reply`,
    DELETE_DRAFT: `Delete draft`,
    GO_BACK: `Go back`,
    SAVE_CHANGES: 'Save changes',
    DELETE_CHANGES: 'Delete changes',
    KEEP_EDITING: 'Keep editing',
    SAVE_DRAFT_WO_ATTCH: `Save draft without attachments`,
  },
  LINKS: {
    PROFILE_SIGNATURE: `/profile/personal-information#messaging-signature`,
    HOME: '/my-health/secure-messages/',
    CONTACT_LIST: '/my-health/secure-messages/contact-list/',
    SELECT_CARE_TEAM:
      '/my-health/secure-messages/new-message/select-care-team/',
    CARE_TEAM_HELP: '/my-health/secure-messages/new-message/care-team-help/',
  },
  CL_LINK_TEXT: 'Show more teams in your contact list',
  URL: {
    LANDING_PAGE: `http://localhost:3001/my-health/secure-messages/`,
  },
  FAQ_LINK: {
    URL: {
      FACILITY: `/find-locations/`,
      EMRG: `tel:911`,
      SETTINGS: `/mhv-portal-web/preferences`,
      PAY: `/health-care/pay-copay-bill/dispute-charges/`,
    },
    TEXT: {
      FACILITY: `Find your nearest VA health facility`,
      EMRG_BTN: `Connect with the Veterans Crisis Line`,
      EMRG: `911`,
      SETTINGS: `My HealtheVet (opens in new tab)`,
      PAY: `Learn how to dispute your VA copay charges`,
    },
  },
  DATE_RANGE: {
    THREE_MONTHS: `Last 3 months`,
    SIX_MONTHS: `Last 6 months`,
    TWELVE_MONTHS: `Last 12 months`,
  },
  INBOX_FOOTER: {
    HEADER: `Need help?`,
    PARAGRAPH_1: `Have questions about how messages works?`,
    PARAGRAPH_2: `Want to send a message to a care team that’s not on your list? Contact your VA health facility. Ask for the My HealtheVet coordinator or secure messaging administrator.`,

    LINK_1: `Learn more about messages`,
    LINK_2: `Find your VA health facility`,
  },

  NOT_FOUND: {
    H2: `Or try these other health resources`,
    P_O: `If you typed or copied the URL into your web browser, check that it’s correct.`,
    P_1: `If that doesn’t work, try going to the My HealtheVet homepage.`,
    LINK: `Go to the My HealtheVet on VA.gov homepage`,
  },

  TEST_FILES: {
    FAKE_FILE_1KB: {
      fileName: 'small-file.txt',
      mimeType: 'text/plain',
      size: 1024, // 1KB
    },
    FAKE_FILE_10KB: {
      fileName: 'small-file-10kb.txt',
      mimeType: 'text/plain',
      size: 10240, // 10KB
    },
    FAKE_FILE_100KB: {
      fileName: 'small-file-100kb.txt',
      mimeType: 'text/plain',
      size: 102400, // 100KB
    },

    FAKE_FILE_3MB: {
      fileName: 'medium-file.pdf',
      mimeType: 'application/pdf',
      size: 3 * 1024 * 1024, // 3MB
    },
    FAKE_FILE_4MB: {
      fileName: 'medium-file-4mb.pdf',
      mimeType: 'application/pdf',
      size: 4 * 1024 * 1024, // 4MB
    },
    FAKE_FILE_4_5MB: {
      fileName: 'medium-file-4-5mb.pdf',
      mimeType: 'application/pdf',
      size: 4.5 * 1024 * 1024, // 4.5MB
    },

    FAKE_FILE_5MB: {
      fileName: 'large-file-5mb.pdf',
      mimeType: 'application/pdf',
      size: 5 * 1024 * 1024, // 5MB
    },

    FAKE_FILE_7MB: {
      fileName: 'large-file.pdf',
      mimeType: 'application/pdf',
      size: 7 * 1024 * 1024, // 7MB (exceeds 6MB limit)
    },

    FAKE_FILE_25MB: {
      fileName: 'max-size-file.pdf',
      mimeType: 'application/pdf',
      size: 25 * 1024 * 1024, // 25MB
    },

    FAKE_FILE_30MB: {
      fileName: 'max-size-file-30-mb.pdf',
      mimeType: 'application/pdf',
      size: 30 * 1024 * 1024, // 30MB
    },

    FAKE_OVERSIZED_FILE: {
      fileName: 'oversized-file.pdf',
      mimeType: 'application/pdf',
      size: 30 * 1024 * 1024, // 30MB (exceeds 25MB limit)
    },

    FAKE_MP4_FILE: {
      fileName: 'video-file.mp4',
      mimeType: 'video/mp4',
      size: 2 * 1024 * 1024, // 2MB
    },

    FAKE_MP3_FILE: {
      fileName: 'audio-file.mp3',
      mimeType: 'audio/mpeg',
      size: 3 * 1024 * 1024, // 3MB
    },

    // Multiple files for total size testing
    FAKE_FILES_10MB_TOTAL: [
      { fileName: 'file1.txt', mimeType: 'text/plain', size: 2 * 1024 * 1024 },
      { fileName: 'file2.txt', mimeType: 'text/plain', size: 3 * 1024 * 1024 },
      { fileName: 'file3.txt', mimeType: 'text/plain', size: 5 * 1024 * 1024 },
    ],

    FAKE_FILES_12MB_TOTAL: [
      {
        fileName: 'file1.pdf',
        mimeType: 'application/pdf',
        size: 6 * 1024 * 1024,
      },
      {
        fileName: 'file2.pdf',
        mimeType: 'application/pdf',
        size: 6 * 1024 * 1024,
      },
    ],
    FAKE_FILES_30MB_TOTAL: [
      {
        fileName: 'file30_MB.pdf',
        mimeType: 'application/pdf',
        size: 10 * 1024 * 1024,
      },
      {
        fileName: 'file2.pdf',
        mimeType: 'application/pdf',
        size: 10 * 1024 * 1024,
      },
      {
        fileName: 'file3.pdf',
        mimeType: 'application/pdf',
        size: 10 * 1024 * 1024,
      },
    ],
  },
};

export const Assertions = {
  MESSAGES: 'Messages',
  FOLDER_RENAMED_SUCCESS: 'Folder was successfully renamed.',
  MESSAGE_CONVERSATION_SUCCESS: 'Message conversation was successfully moved.',
  MESSAGE_CONVERSATION_SUCCESS_TRASH:
    'Message conversation was successfully moved to Trash.',
  SELECT_RECIPIENT: ' Please select a recipient.',
  DRAFT_DELETED_SUCCESS: 'Draft was successfully deleted.',
  CANT_SAVE_MESSAGE_YET: "We can't save this message yet",
  CONTINUE_EDITING: 'Continue editing',
  INBOX: 'Inbox',
  DRAFT: 'Draft',
  EDITED: 'edited',
  ACTIVE: 'is-active',
  MESSAGE_PREFERENCES: 'Edit your message preferences',
  NO_MESSAGE_FOLDER: 'There are no messages in this folder.',
  CODE_STATUS: 'statusCode',
  SECURE_MESSAGE_PILOT: 'What is Secure Messaging Pilot?',
  NEW_MESSAGE: 'new-message',
  ARIA_EXPANDED: 'aria-expanded',
  EMPTY_THIS_FOLDER: 'Empty this folder',
  NO_MATCHES_SEARCH: 'We didn’t find any matches for these filters',
};

export const Arrays = {
  FilterDateRange: [
    'ANY',
    'LAST 3 MONTHS',
    'LAST 6 MONTHS',
    'LAST 12 MONTHS',
    'CUSTOM',
  ],

  Categories: [
    'OTHER',
    'COVID',
    'APPOINTMENT',
    'MEDICATION',
    'TEST_RESULT',
    'EDUCATION',
    'GENERAL',
    'TEST',
  ],
};
