export const AXE_CONTEXT = '.secure-messaging-container';

export const Paths = {
  UI_MAIN: '/my-health/secure-messages',
  UI_PILOT: '/my-health/secure-messages-pilot',
  SM_API_BASE: '/my_health/v1/messaging',
  SM_API_EXTENDED: '/my_health/v1/messaging/messages',
  INBOX: '/inbox/',
  SENT: '/sent/',
  DRAFTS: '/drafts/',
  DRAFT: '/draft/',
  DELETED: '/trash/',
  COMPOSE: '/new-message/',
  MESSAGE: '/message/',
  MESSAGE_THREAD: '/thread/',
  FOLDERS: '/folders',
  SEARCH: '/search/',
  SEARCH_RESULTS: '/search/results/',
  REPLY: '/reply/',
  CATEGORIES: '/categories',
  RECIPIENTS: '/allrecipients',
  SIGNATURE: '/signature',
  FIND_LOCATIONS: '/find-locations/',
  FIND_LOCATION: '/find-locations',
  HEALTH_CARE_SECURE_MSG: '/health-care/secure-messaging',
  THREAD: '/thread',
  CONTACT_LIST: '/contact-list',
  INTERCEPT: {
    MESSAGE_RECIPIENT: '/my_health/v1/messaging/recipients*',
    MESSAGE_CATEGORY: '/my_health/v1/messaging/messages/categories',
    MESSAGE_FOLDER: '/my_health/v1/messaging/folders*',
    MESSAGE_FOLDERS: '/my_health/v1/messaging/folders',
    MESSAGE_FOLDER_THREAD: '/my_health/v1/messaging/folders/0/threads?*',
    MESSAGE_FOLDER_MESS: '/my_health/v1/messaging//folders/0/messages*',
    MESSAGE_DRAFTS: '/my_health/v1/messaging/message_drafts',
    MESSAGE_FOLDERS_SEARCH: '/my_health/v1/messaging/folders/*/search',
    MESSAGE_FOLDERS_2: '/my_health/v1/messaging/folders/-2*',
    FEATURE_TOGGLES: '/v0/feature_toggles?*',
    MESSAGE_THREADS: '/my_health/v1/messaging/threads/',
    MESSAGE_SIGNATURE: '/my_health/v1/messaging/messages/signature',
    MESSAGE_ALLRECIPIENTS: '/my_health/v1/messaging/allrecipients',
    MESSAGES: '/my_health/v1/messaging/messages',
  },
};

export const Locators = {
  FROM_TO_DATES_CONTAINER: '.fromToDatesContainer',
  MESSAGE_FAQ: '.secure-messaging-faq',
  MESSAGES: '[data-testid="message-list-item"]',
  TO: '[data-testid="to"]',
  FROM: '[data-testid="from"]',
  MSG_ID: '[data-testid="message-id"]',
  MSG_DATE: '[data-testid="message-date"]',
  DATE_RECEIVED: '[data-testid="received-date"]',
  HEADER_FOLDER: '[data-testid*=folder-header]',
  ATTACH_FILE_INPUT: '[data-testid="attach-file-input"]',
  ATTACHMENT_COUNT: '[data-testid="attachments-count"]',
  MESSAGE_SUBJECT: '[data-testid="message-subject-field"]',
  MESSAGES_BODY: '[data-testid="message-body-field"]',
  MESSAGES_BODY_DRAFT: '.message-body-draft-preview',
  DROPDOWN: '#sort-order-dropdown',
  CERNER: '[data-testid="cerner-facility"]',
  CERNER_TEXT: '[data-testid="single-cerner-facility-text"]',
  DELETE_MES_CONFIRM: '[data-testid="delete-message-confirm-note"] p',
  SELECT: '#select',
  HEADER: 'h1',
  HEADER2: 'h2',
  HEADLINE: 'h1[slot="headline"]',
  KEYWORD_SEARCH: '[data-testid="keyword-search-input"]',
  NO_MESS: '[data-testid=alert-no-messages] p',
  FOLDER_NAME: '[data-testid="folder-name"]',
  FOLDERS_LIST: '[data-testid ="my-folders-sidebar"]',
  MESS_LIST: '[data-testid="message-list-item"]',
  THREAD_LIST: '.thread-list-item',
  THREADS: '[data-testid="thread-list-item"]',
  MES_COUNT: '[data-testid="message-count"]',
  REPLY_FORM: '[data-testid="reply-form"]',
  CLEAR_FILTERS: '[text="Clear Filters"]',
  FILTER_INPUT: '#filter-input',
  ADDITIONAL_FILTER: '#additional-filter-accordion',
  ACCORDIONS: '[data-testid="faq-accordion-item"]',
  MESSAGE_THREAD_META: '.message-thread-meta',
  FOLDERS: {
    FOLDER_NAME: '[label="Folder name"]',
    FOLDER_REMOVE: '[text="Yes, remove this folder"]',
    FOLDER_HEADER: '[data-testid="folder-header"]',
    INBOX: '[data-testid="inbox-sidebar"] > a',
    DRAFTS: '[data-testid="drafts-sidebar"]',
    SENT: '[data-testid="sent-sidebar"]',
    TRASH: '[data-testid="trash-sidebar"]',
    CUSTOM: '[data-testid="my-folders-sidebar"]',
    SIDEBAR: '[data-testid=my-folders-sidebar]',
    NOT_EMP_FOLDER: '[data-testid="error-folder-not-empty"] p',
    FOLDER_INPUT_LABEL: '[data-testid="search-message-folder-input-label"]',
    FOLDER_DROPDOWN: '[data-testid="folder-dropdown"]',
    FOLDER_NOT_EMPTY: 'va-modal[data-testid="error-folder-not-empty"]',
  },
  BUTTONS: {
    SECURE_MESSAGING: '[data-testid="secure-messaging"]',
    THREAD_EXPAND: '[data-testid="thread-expand-all"]',
    THREAD_EXPAND_MESSAGES:
      '[data-testid="thread-expand-all"] va-accordion-item',
    ADDITIONAL_FILTER: '#additional-filter-accordion',
    TRASH_TEXT: '[data-testid=trash-button-text]',
    TEXT_CONFIRM: 'va-button[text="Confirm"]',
    REPLY: '[data-testid="reply-button-body"]',
    CONTINUE: '[data-testid="continue-button"]',
    TEST2: '[data-testid=radiobutton-TEST2]',
    TESTAGAIN: '[data-testid=radiobutton-TESTAGAIN]',
    NEW_FOLDER_RADIOBTN: '[data-testid=folder-list-radio-button]',
    DELETE_RADIOBTN: '[data-testid=radiobutton-Deleted]',
    MOVE: `#move-button`,
    TRASH: `#trash-button`,
    BUTTON_TEXT: '[data-testid="trash-button-text"]',
    MOVE_BUTTON_TEXT: '[data-testid="move-button-text"]',
    FILTER: '[data-testid="filter-messages-button"]',
    SEND: '[data-testid="send-button"]',
    SAVE_DRAFT: '#save-draft-button',
    PRINT_ONE_MESS: '[data-testid="radio-print-one-message"]',
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DELETE_DRAFT: '#delete-draft-button',
    EDIT_FOLDER: '[data-testid="edit-folder-button"]',
    DELETE_FOLDER: '[data-testid="remove-folder-button"]',
    PRINT: '[data-testid="print-button"]',
    SORT: '[data-testid="sort-button"]',
    ATTACH_FILE: '[data-testid="attach-file-button"]',
    REMOVE_ATTACHMENT: '[data-testid="remove-attachment-button"]',
    CONFIRM_REMOVE_ATTACHMENT:
      '[data-testid="confirm-remove-attachment-button"]',
    CONTINUE_EDITING: 'va-button[text="Continue editing"]',
    CREATE_FOLDER: '[data-testid="create-folder-button"]',
    REMOVE_FOLDER: '[data-testid="remove-folder-button"]',
    PREFERENCES: '[data-testid="edit-preferences-button"]',
    CATEGORY_RADIOBTN: '[data-testid="compose-category-radio-button"]',
    DELETE_CANCEL: '#delete-cancel',
    DELETE_CONFIRM: '#delete-draft',
    ADD_FILTER_BUTTON: '[id="additional-filter-accordion"] h3.headline-text',
    EDIT_DRAFTS: '[data-testid="edit-draft-button-body-text"]',
  },
  LINKS: {
    GO_TO_INBOX: '[data-testid="inbox-link"]',
    PREFER_LINK: '[data-testid="edit-preferences-link"]',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
    CRUMB: 'ol[role="list"] > li',
    CRUMB_LIST: '[data-testid="sm-breadcrumbs"]',
    BACK_TO_DRAFTS: '.sm-breadcrumb-list-item>a',
  },
  ALERTS: {
    HEADER: `#heading`,
    MODEL_TITLE_ALERT: '.va-modal-alert-title',
    TRIAGE_ALERT: '[data-testid="blocked-triage-group-alert"] > div > a',
    TRIAGE_GROUP: '[data-testid="blocked-triage-group-alert"]>h2',
    CLOSE_NOTIFICATION: '.va-alert',
    REPT_SELECT: '[data-testid="compose-recipient-select"]',
    DRAFT_MODAL: '[data-testid="delete-draft-modal"]',
    THREAD_EXPAND: '[data-testid="thread-expand-all"]',
    SEARCH_DROPDOWN: '#select-search-folder-dropdown',
    TEXT_INPUT: '[data-testid="search-keyword-text-input"]',
    PAGIN_LIST: '.usa-pagination__list li',
    UNREAD_MESS: '[data-testid="unread-messages"]',
    MODAL_POPUP: '[data-testid="print-modal-popup"]',
    CREAT_NEW_TEXT_FOLD: '[text="Create new folder"]',
    LAST_EDIT_DATE: '[data-testid="last-edit-date"]',
    MOVE_MODAL: '[data-testid="move-to-modal"]',
    DELETE_MES_MODAL: '[data-testid="delete-message-modal"]',
    NO_MESS: '[data-testid=alert-no-messages] p',
    CREATE_NEW_MESSAGE: '[data-testid="compose-message-link"]',
    CREATE_NEW_FOLDER: '[data-testid="create-new-folder"]',
    DRAFT_MESSAGE: '@draft_message',
    MAIN_CONTENT: '.va-alert',
    PAGE_TITLE: '.page-title',
    EXPANDABLE_TITLE: '[class="alert-expandable-title"]',
    NOTIFICATION: '[close-btn-aria-label="Close notification"]',
    VA_CRISIS_LINE: '[text="Connect with the Veterans Crisis Line"]',
    SAVE_DRAFT: '#messagetext',
    HIGHLIGHTED: '[data-testid="highlighted-text"]',
    SIDEBAR_NAV: '[class="sidebar-navigation-messages-list-header"]',
    INBOX_TEXT: '[text="Go to your inbox"]',
    EDIT_DRAFT: '#edit-draft-button',
    WELCOME_MESSAGE: '.welcome-message',
    BACK_TOP: 'va-back-to-top',
    ACC_ITEM: '[data-testid="faq-accordion-item"]',
    CERNER_ALERT: '[data-testid="cerner-facilities-alert"]',
    BLOCKED_GROUP: '[data-testid="blocked-triage-group-alert"]',
    RECIP_SELECT: '[data-testid="compose-recipient-select"]',
    MESS_CATAGO: '[data-testid="compose-message-categories"]',
    LIST_HEADER: '.sidebar-navigation-messages-list-header > a',
    SUCCESS_ALERT: '[data-testid="close-success-alert-button"]',
    DELETE_MESSAGE: '[data-testid=delete-message-modal]',
    ERROR_MESSAGE: '[data-testid="file-input-error-message"]',
    ERROR_MODAL: '[data-testid="attach-file-error-modal"]',
    VA_ALERT_WARNING: 'va-alert[status="warning"]',
    CONFIRM: '[data-testid="alert-text"]',
    EXPIRED_MESSAGE: '[data-testid="expired-alert-message"]',
    ES_ALERT: '[data-testid="quit-compose-double-dare"]',
    SAVE_ALERT: `[data-test-id="save-alert-message"]`,
  },
  FIELDS: {
    RECIPIENT: '#select',
    SUBJECT: '#inputField',
    MESSAGE: '#textarea',
    MESS_SUBJECT: '#message-subject',
    VISIBLE_P: '[visible=""] > p',
    CATEGORY_DROPDOWN: '[data-testid="category-dropdown"]',
    DATE_RANGE_DROPDOWN: '#date-range-dropdown',
    SEARCH_MESSAGE_HEADING: '[data-testid="search-messages"] h2',
    SEARCH_MESSAGE: '[data-testid="search-messages"] [aria-live="polite"]',
    FILTER_MESSAGE_TEXT: '[data-testid="search-form"] h2',
    NOT_FOR_PRINT_HEADER: '[data-testid="not-for-print-header"]',
  },
  INFO: {
    SUBJECT_LIMIT: '#charcount-message',
    ATTACH_INFO: '[class="additional-info-title"]',
    ATTACH_OPT: '[class="how-to-attach-files"] li',
  },
  BLOCKS: {
    ATTACHMENTS: '.attachments-list',
  },
  CHECKBOX: {
    CL_ALL: '[data-testid="contact-list-select-all-teams"]',
    CL_SINGLE: '[data-testid="contact-list-select-team"]',
  },
  HEADERS: {
    DRAFTS_HEADER: '#draft-reply-header',
  },
};

export const Alerts = {
  NO_ASSOCIATION: {
    AT_ALL_HEADER: `You're not connected to any care teams in this messaging tool`,
    HEADER: 'Your account is no longer connected to',
    PARAGRAPH:
      'If you need to contact your care team, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  BLOCKED: {
    HEADER: `You can't send messages to`,
    PARAGRAPH:
      'If you need to contact this care team, call your VA health facility.',
    LINK: 'Find your VA health facility',
  },
  OUTAGE: 'We’re sorry. We couldn’t load this page. Try again later.',
  OLD_MSG: 'This conversation is too old for new replies',
  PAGE_NOT_FOUND: 'Sorry — we can’t find that page',
  TRY_SEARCH: 'Try the search box or one of the common questions below.',
  SAVE_ATTCH: `We can't save attachments in a draft message`,
  EL_SIGN: `Messages to this team require a signature. We added a signature box to this page.`,
  EL_SIGN_NAME: `Enter your full name`,
  EL_SIGN_CHECK: `You must certify by checking the box.`,
  SAVE_SIGN: `We can't save your signature in a draft message`,
  SAVE_SIGN_ATTCH: `We can't save your signature or attachments in a draft message`,
};

export const Data = {
  TEST_MESSAGE_BODY: '\nTest message body',
  TEST_SUBJECT: 'Test Subject',
  TEST_IMAGE: 'test_image.jpg',
  TEST_LARGE_IMAGE: 'test_image_10mb.jpg',
  MESSAGE_WAS_SAVED: 'message was saved',
  TEST_MESSAGE_SUBJECT: 'Test Message Subject',
  SAMPLE_DOC: 'sample_docx.docx',
  SAMPLE_PDF: 'sample_pdf.pdf',
  SAMPLE_XLS: 'sample_XLS.xls',
  SAMPLE_IMG: 'test_image.gif',
  START_NEW_MSG: 'Start a new message',
  GO_YOUR_INBOX: 'Go to your inbox',
  BACK_TO_MSG: 'Back to messages',
  FOLDER_NAME_CANNOT_BLANK: 'Folder name cannot be blank',
  FOLDER_REMOVED_SUCCESSFULLY: 'Folder was successfully removed.',
  FOLDER_CREATED_SUCCESSFULLY: 'Folder was successfully created.',
  FOLDER_RENAMED_SUCCESSFULLY: 'Folder was successfully renamed.',
  SECURE_MSG_SENT_SUCCESSFULLY: 'Secure message was successfully sent',
  PLEASE_SELECT_RECIPIENT: 'Please select a recipient.',
  PLEASE_SELECT_CATEGORY: 'Please select a category.',
  SUBJECT_CANNOT_BLANK: 'Subject cannot be blank.',
  BODY_CANNOT_BLANK: 'Message body cannot be blank.',
  ATTACH_FILE: 'Attach file',
  ATTACH_ADDITIONAL_FILE: 'Attach additional file',
  MESSAGE_CANNOT_SAVE_YET: "We can't save this message yet",
  CONTINUE_EDITING: 'Continue editing',
  MESSAGE_MOVED_TO_TRASH:
    'Message conversation was successfully moved to Trash.',
  TEST_VIDEO: 'test_video.mp4',
  CREATE_FOLDER_TEST: 'create folder test',
  IS_ACTIVE: 'is-active',
  END_CONVERSATION_IN_FOLDER: 'End of conversations in this folder',
  SAVE_MEG_AS_DRAFT: 'If you save this message as a draft',
  EDIT_YOUR_MSG_PREFRENCES: 'Edit your message preferences',
  NO_MSG_IN_FOLDER: 'There are no messages in this folder.',
  WHAT_SECURE_MSG_PILOT: 'What is Secure Messaging Pilot?',
  FILE_IS_TOO_LARGE_TEXT:
    'Your file is too large. Try attaching a file smaller than 6MB.',
  ALREADY_ATTACHED_FILE: 'You have already attached this file.',
  CANNOT_SEND_MSG_TO_CARE_TEAM:
    "You can't send messages to your care teams right now",
  REMOVE_FOLDER: 'Remove folder',
  CANNOT_REMOVE_FOLDER: `You can't remove a folder with messages in it. Move all the messages to another folder. Then try removing it again.`,
  ATTACH_INFO: [
    'You may attach up to 4 files to each message',
    'You can attach only these file types: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx, jpeg, jfif, pjpeg, pjp',
    'The maximum size for each file is 6 MB',
    'The maximum total size for all files attached to 1 message is 10 MB',
  ],
  EL_SIGN_CHECK: `I certify that the above is correct and true to the best of my knowledge and belief.`,
  BUTTONS: {
    EDIT_DRAFT: `Edit draft`,
    SAVE_DRAFT_WO_SIGN: 'Save draft without signature',
    SAVE_DRAFT_WO_SIGN_ATTCH: 'Save draft without signature or attachments',
  },
};
export const Assertions = {
  MESSAGES: 'Messages',
  FOLDER_RENAMED_SUCCESS: 'Folder was successfully renamed.',
  MESSAGE_CONVERSATION_SUCCESS: 'Message conversation was successfully moved.',
  MESSAGE_CONVERSATION_SUCCESS_TRASH:
    'Message conversation was successfully moved to Trash.',
  SELECT_RECIPIENT: ' Please select a recipient.',
  DRAFT_DELETED_SUCCESS: 'Draft was successfully deleted.',
  CANT_SAVE_MESSAGE_YET: "We can't save this message yet",
  CONTINUE_EDITING: 'Continue editing',
  INBOX: 'Inbox',
  DRAFT: 'Draft',
  EDITED: 'edited',
  ACTIVE: 'is-active',
  MESSAGE_PREFERENCES: 'Edit your message preferences',
  NO_MESSAGE_FOLDER: 'There are no messages in this folder.',
  CODE_STATUS: 'statusCode',
  SECURE_MESSAGE_PILOT: 'What is Secure Messaging Pilot?',
  NEW_MESSAGE: 'new-message',
  ARIA_EXPANDED: 'aria-expanded',
  EMPTY_THIS_FOLDER: 'Empty this folder',
  NO_MATCHES_SEARCH: 'We didn’t find any matches for these filters',
};
