name: 'Setup and install dependencies'
description: 'Sets up Node.js and installs dependencies'
runs:
  using: 'composite'
  steps:
    - name: Get Node version
      id: get-node-version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/yarn
          node_modules
        key: ${{ steps.get-node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile --prefer-offline
      env:
        YARN_CACHE_FOLDER: ~/.cache/yarn
