export const payments = {
  payments: [
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '04/01/2019',
      payCheckId: '001',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '03/01/2019',
      payCheckId: '002',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$177.60',
      payCheckDt: '11/09/2018',
      payCheckId: '003',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Retroactive',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '04/02/2019',
      payCheckId: '001',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '03/02/2019',
      payCheckId: '002',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$177.60',
      payCheckDt: '11/10/2018',
      payCheckId: '003',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Retroactive',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '04/03/2019',
      payCheckId: '001',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '03/03/2019',
      payCheckId: '002',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$177.60',
      payCheckDt: '11/11/2018',
      payCheckId: '003',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Retroactive',
      paymentMethod: 'Direct Deposit',
    },
  ],
  returnPayments: [
    {
      returnedCheckAmount: null,
      returnedCheckCancelDt: '12/01/2012',
      returnedCheckIssueDt: null,
      returnedCheckNum: '12365494',
      returnedCheckRo: '17',
      returnedCheckReason: '6',
      returnedCheckReturnFiche: 'B',
      returnedCheckType: 'Other',
    },
    {
      returnedCheckAmount: '$50.00',
      returnedCheckCancelDt: null,
      returnedCheckIssueDt: '11/25/2012',
      returnedCheckNum: '12365494',
      returnedCheckRo: '17',
      returnedCheckReason: '6',
      returnedCheckReturnFiche: 'B',
      returnedCheckType: 'Post-9/11 Educational Assistance',
    },
  ],
};

export const emptyPaymentsReturned = {
  payments: [
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '04/01/2019',
      payCheckId: '001',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$3,261.10',
      payCheckDt: '03/01/2019',
      payCheckId: '002',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Recurring',
      paymentMethod: 'Direct Deposit',
    },
    {
      accountNumber: '**3456',
      bankName: 'BANK OF AMERICA, N.A.',
      payCheckAmount: '$177.60',
      payCheckDt: '11/09/2018',
      payCheckId: '003',
      payCheckReturnFiche: 'C',
      payCheckType: 'Compensation & Pension - Retroactive',
      paymentMethod: 'Direct Deposit',
    },
  ],
  returnPayments: [],
};

export const emptyPaymentsReceived = {
  payments: [],
  returnPayments: [
    {
      returnedCheckAmount: null,
      returnedCheckCancelDt: '12/01/2012',
      returnedCheckIssueDt: null,
      returnedCheckNum: '12365494',
      returnedCheckRo: '17',
      returnedCheckReason: '6',
      returnedCheckReturnFiche: 'B',
      returnedCheckType: 'Other',
    },
    {
      returnedCheckAmount: '$50.00',
      returnedCheckCancelDt: null,
      returnedCheckIssueDt: '11/25/2012',
      returnedCheckNum: '12365494',
      returnedCheckRo: '17',
      returnedCheckReason: '6',
      returnedCheckReturnFiche: 'B',
      returnedCheckType: 'Post-9/11 Educational Assistance',
    },
  ],
};

export const emptyPaymentsResponse = {
  payments: [],
  returnPayments: [],
};

export const fields = [
  {
    label: 'Date',
    value: 'date',
  },
  {
    label: 'Amount',
    value: 'amount',
  },
  {
    label: 'Type',
    value: 'type',
  },
  {
    label: 'Method',
    value: 'method',
  },
  {
    label: 'Bank name',
    value: 'bank',
  },
  {
    label: 'Account',
    value: 'account',
  },
];
