import manifest from '../manifest.json';

export const BASE_URL = `${manifest.rootUrl}/`;
export const REVIEW_ENROLLMENTS_URL_SEGMENT = 'enrollment-verifications';
export const REVIEW_ENROLLMENTS_URL = `${BASE_URL}`;
export const REVIEW_ENROLLMENTS_RELATIVE_URL = `/`;
export const STATIC_CONTENT_ENROLLMENT_URL =
  '/education/verify-school-enrollment';

export const VERIFY_ENROLLMENTS_URL_SEGMENT = 'verify';
export const VERIFY_ENROLLMENTS_URL = `${REVIEW_ENROLLMENTS_URL}${VERIFY_ENROLLMENTS_URL_SEGMENT}/`;
export const VERIFY_ENROLLMENTS_RELATIVE_URL = `${REVIEW_ENROLLMENTS_RELATIVE_URL}${VERIFY_ENROLLMENTS_URL_SEGMENT}/`;

export const VERIFY_ENROLLMENTS_ERROR_URL_SEGMENT = 'error';
export const VERIFY_ENROLLMENTS_ERROR_URL = `${VERIFY_ENROLLMENTS_URL}${VERIFY_ENROLLMENTS_ERROR_URL_SEGMENT}/`;
export const VERIFY_ENROLLMENTS_ERROR_RELATIVE_URL = `${VERIFY_ENROLLMENTS_RELATIVE_URL}${VERIFY_ENROLLMENTS_ERROR_URL_SEGMENT}/`;

export const STATUS = {
  ALL_VERIFIED: 'STATUS_ALL_VERIFIED',
  MISSING_VERIFICATION: 'STATUS_MISSING_VERIFICATION',
  PAYMENT_PAUSED: 'STATUS_PAYMENT_PAUSED',
  SCO_PAUSED: 'PAYMENT_STATUS_SCO_PAUSED',
};
export const VERIFICATION_RESPONSE = {
  NOT_RESPONDED: 'NR',
  CORRECT: 'Y',
  INCORRECT: 'N',
};
export const CERTIFICATION_METHOD = 'MEB';

export const PAYMENT_PAUSED_NUMBER_OF_MONTHS = 2;
export const PAYMENT_PAUSED_DAY_OF_MONTH = 26;
