import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import moment from 'moment';
import { generatePdf } from '@department-of-veterans-affairs/platform-pdf/exports';
import { focusElement } from '@department-of-veterans-affairs/platform-utilities/ui';
import RecordList from '../components/RecordList/RecordList';
import { setBreadcrumbs } from '../actions/breadcrumbs';
import { getConditionsList } from '../actions/conditions';
import { recordType, pageTitles } from '../util/constants';
import PrintDownload from '../components/shared/PrintDownload';
import { processList } from '../util/helpers';
import { updatePageTitle } from '../../shared/util/helpers';
import { mhvUrl } from '~/platform/site-wide/mhv/utilities';
import { isAuthenticatedWithSSOe } from '~/platform/user/authentication/selectors';

const HealthConditions = () => {
  const fullState = useSelector(state => state);
  const conditions = useSelector(state => state.mr.conditions.conditionsList);
  // const conditions = []; // used to test use cases with no vitals on record
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getConditionsList());
  });

  useEffect(() => {
    dispatch(
      setBreadcrumbs(
        [{ url: '/my-health/medical-records/', label: 'Medical records' }],
        {
          url: '/my-health/medical-records/conditions',
          label: 'VA health conditions',
        },
      ),
    );
    focusElement(document.querySelector('h1'));
    updatePageTitle(pageTitles.HEALTH_CONDITIONS_PAGE_TITLE);
  }, []);

  const generateHealthConditions = async () => {
    const pdfData = {
      headerLeft: 'Roberts, Jesse',
      headerRight: 'Date of birth: January 1, 1970',
      footerLeft: `Report generated by My HealtheVet and VA on ${moment().format(
        'LL',
      )}`,
      footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
      headerBanner: [
        {
          weight: 'normal',
          text:
            "If you're ever in crisis and need to talk to someone right away, call the Veterans Crisis line at ",
        },
        {
          weight: 'bold',
          text: '988',
        },
        {
          weight: 'normal',
          text: '. Then select 1.',
        },
      ],
      title: 'Health Conditions',
      subject: 'VA Medical Record',
      preface:
        'Your VA Health Condition list may not be complete. If you have any questions about your information, visit the FAQs or contact your VA Health care team.',
      results: {
        items: [],
      },
    };

    conditions.forEach(item => {
      pdfData.results.items.push({
        header: item.name,
        items: [
          {
            title: 'Date',
            value: moment(item.date).format('MMMM Do YYYY') || ' ',
            inline: true,
          },
          {
            title: 'Provider',
            value: item.provider || ' ',
            inline: true,
          },
          {
            title: 'Provider Notes',
            value: item.comments.length
              ? processList(item.comments)
              : 'none noted',
            inline: !item.comments.length,
          },
          {
            title: 'Status of health condition',
            value: item.active ? 'active' : 'inactive',
            inline: true,
          },
          {
            title: 'Location',
            value: item.facility || ' ',
            inline: true,
          },
          {
            title: 'SNOMED Clinical Term',
            value: item.name || ' ',
            inline: true,
          },
        ],
      });
    });

    try {
      await generatePdf('medicalRecords', 'health_conditions_report', pdfData);
    } catch (error) {
      // Error logging/presentation goes here...
    }
  };

  const download = () => {
    generateHealthConditions();
  };

  const content = () => {
    if (conditions?.length > 0) {
      return (
        <RecordList records={conditions} type={recordType.HEALTH_CONDITIONS} />
      );
    }
    if (conditions?.length === 0) {
      return (
        <div className="vads-u-margin-bottom--3">
          <va-alert background-only status="info">
            You don’t have any records in Vitals
          </va-alert>
        </div>
      );
    }
    return (
      <va-loading-indicator
        message="Loading..."
        setFocus
        data-testid="loading-indicator"
        class="loading-indicator"
      />
    );
  };

  return (
    <div>
      <h1>Health conditions</h1>
      <section className="set-width-486">
        <p>Review health conditions in your VA medical records.</p>
        <va-additional-info trigger="What to know about health conditions">
          <ul>
            <li>
              <p>
                Health condition records are available <b>36 hours</b> after
                your providers enter them.
              </p>
            </li>
            <li>
              <p>
                This list includes your current health conditions that VA
                providers are helping you manage. It may not include conditions
                non-VA providers are helping you manage.
              </p>
            </li>
            <li>
              <p>
                This list doesn’t include information you entered yourself. To
                find information you entered, go back to your records on My
                HealtheVet website.
              </p>
              <va-link
                className="section-link"
                active
                href="/my-health/medical-records/"
                text="Go to your care summaries and notes"
                data-testid="section-link"
              />
            </li>
            <li>
              <p>
                If you have questions about your health conditions, send a
                message to your care team.
              </p>
              <a
                href={mhvUrl(
                  isAuthenticatedWithSSOe(fullState),
                  'secure-messaging',
                )}
                target="_blank"
                rel="noreferrer"
              >
                Compose a new message
              </a>
            </li>
          </ul>
        </va-additional-info>
        <PrintDownload list download={download} />
      </section>
      {content()}
    </div>
  );
};

export default HealthConditions;
