import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import moment from 'moment';
import { generatePdf } from '@department-of-veterans-affairs/platform-pdf/exports';
import RecordList from '../components/RecordList/RecordList';
import { getVaccinesList } from '../actions/vaccines';
import { setBreadcrumbs } from '../actions/breadcrumbs';
import PrintHeader from '../components/shared/PrintHeader';
import { getAllVaccines } from '../api/MrApi';
import { RecordType } from '../util/constants';
import PrintDownload from '../components/shared/PrintDownload';
import { processList } from '../util/helpers';

const Vaccines = () => {
  const dispatch = useDispatch();
  const vaccines = useSelector(state => state.mr.vaccines.vaccinesList);

  useEffect(() => {
    dispatch(getVaccinesList());
  }, []);

  useEffect(
    () => {
      dispatch(
        setBreadcrumbs(
          [
            { url: '/my-health/medical-records/', label: 'Dashboard' },
            {
              url: '/my-health/medical-records/health-history',
              label: 'Health history',
            },
          ],
          {
            url: '/my-health/medical-records/health-history/vaccines',
            label: 'VA vaccines',
          },
        ),
      );
    },
    [dispatch],
  );

  const generateVaccinesPdf = async res => {
    const pdfData = {
      headerLeft: 'Roberts, Jesse',
      headerRight: 'Date of birth: January 1, 1970',
      footerLeft: `Report generated by My HealtheVet and VA on ${moment().format(
        'LL',
      )}`,
      footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
      title: 'Vaccines',
      subject: 'VA Medical Record',
      preface:
        'Your VA Vaccines list may not be complete. If you have any questions about your information, visit the FAQs or contact your VA Health care team.',
      results: {
        items: [],
      },
    };

    res.forEach(item => {
      pdfData.results.items.push({
        header: item.name,
        items: [
          {
            title: 'Date received',
            value: item.date || ' ',
            inline: true,
          },
          {
            title: 'Location',
            value: item.facility || ' ',
            inline: true,
          },
          {
            title: 'Reaction',
            value: processList(item.reactions) || ' ',
            inline: !item.reactions,
          },
          {
            title: 'Provider notes',
            value: processList(item.comments) || ' ',
            inline: !item.comments,
          },
        ],
      });
    });

    try {
      await generatePdf('medicalRecords', 'vaccines_report', pdfData);
    } catch (error) {
      // Error logging/presentation goes here...
    }
  };

  const download = () => {
    getAllVaccines().then(res => generateVaccinesPdf(res));
  };

  const content = () => {
    if (vaccines?.length) {
      return <RecordList records={vaccines} type={RecordType.VACCINES} />;
    }
    return (
      <va-loading-indicator
        message="Loading..."
        setFocus
        data-testid="loading-indicator"
      />
    );
  };

  return (
    <div id="vaccines">
      <PrintHeader />
      <h1 className="page-title">Vaccines</h1>
      <p>
        This is a complete list of vaccines that the VA has on file for you.
      </p>
      <p className="print-only vads-u-margin-bottom--0 max-80">
        Your VA Vaccines list may not be complete. If you have any questions
        about your information, visit the FAQs or contact your VA Health care
        team.
      </p>
      <PrintDownload list download={download} />

      {content()}
    </div>
  );
};

export default Vaccines;
