export const FIELD_NAMES = {
  SCHEDULING_PREF_CONTACT_METHOD: 'preferredContactMethod',
  SCHEDULING_PREF_CONTACT_TIMES: 'preferredContactTimes',
  SCHEDULING_PREF_HELP_SCHEDULING: 'needsHelpSchedulingAppointments',
  SCHEDULING_PREF_APPOINTMENT_TIMES: 'preferredAppointmentTimes',
  SCHEDULING_PREF_PROVIDER_GENDER: 'preferredProviderGender',
  SCHEDULING_PREF_HELP_CHOOSING: 'needsHelpChoosingProvider',
};

export const FIELD_ITEM_IDS = {
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_METHOD]: 1,
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_TIMES]: 2,
  [FIELD_NAMES.SCHEDULING_PREF_HELP_SCHEDULING]: 4,
  [FIELD_NAMES.SCHEDULING_PREF_APPOINTMENT_TIMES]: 3,
  [FIELD_NAMES.SCHEDULING_PREF_PROVIDER_GENDER]: 6,
  [FIELD_NAMES.SCHEDULING_PREF_HELP_CHOOSING]: 5,
};

export const FIELD_OPTION_IDS = {
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_METHOD]: {
    TELEPHONE_MOBILE: 1,
    TELEPHONE_HOME: 38,
    TELEPHONE_WORK: 39,
    TEXT_MESSAGE: 2,
    SECURE_MESSAGE: 3,
    US_POST: 4,
    EMAIL: 5,
    NO_PREFERENCE: 6,
  },
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_TIMES]: {
    MONDAY_MORNING: 7,
    MONDAY_AFTERNOON: 8,
    TUESDAY_MORNING: 9,
    TUESDAY_AFTERNOON: 10,
    WEDNESDAY_MORNING: 11,
    WEDNESDAY_AFTERNOON: 12,
    THURSDAY_MORNING: 13,
    THURSDAY_AFTERNOON: 14,
    FRIDAY_MORNING: 15,
    FRIDAY_AFTERNOON: 16,
    NO_PREFERENCE: 17,
  },
  [FIELD_NAMES.SCHEDULING_PREF_APPOINTMENT_TIMES]: {
    MONDAY_MORNING: 18,
    MONDAY_AFTERNOON: 19,
    TUESDAY_MORNING: 20,
    TUESDAY_AFTERNOON: 21,
    WEDNESDAY_MORNING: 22,
    WEDNESDAY_AFTERNOON: 23,
    THURSDAY_MORNING: 24,
    THURSDAY_AFTERNOON: 25,
    FRIDAY_MORNING: 26,
    FRIDAY_AFTERNOON: 27,
    NO_PREFERENCE: 28,
  },
  [FIELD_NAMES.SCHEDULING_PREF_HELP_SCHEDULING]: {
    yes: 29,
    no: 30,
    noPreference: 31,
  },
  [FIELD_NAMES.SCHEDULING_PREF_HELP_CHOOSING]: {
    yes: 32,
    no: 33,
    noPreference: 34,
  },
  [FIELD_NAMES.SCHEDULING_PREF_PROVIDER_GENDER]: {
    male: 35,
    female: 36,
    noPreference: 37,
  },
};

export const FIELD_TITLES = {
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_METHOD]:
    "What's the best way to contact you to schedule your appointments?",
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_TIMES]:
    'When do you want us to contact you to schedule your appointments?',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_SCHEDULING]:
    'Do you want help scheduling your appointments?',
  [FIELD_NAMES.SCHEDULING_PREF_APPOINTMENT_TIMES]:
    'When do you want to go to your appointments?',
  [FIELD_NAMES.SCHEDULING_PREF_PROVIDER_GENDER]:
    'Do you prefer a male or female provider?',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_CHOOSING]:
    'Do you want help choosing your provider?',
};

export const FIELD_IDS = {
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_METHOD]: 'preferred-contact-method',
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_TIMES]: 'preferred-contact-times',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_SCHEDULING]:
    'needs-help-scheduling-appointments',
  [FIELD_NAMES.SCHEDULING_PREF_APPOINTMENT_TIMES]:
    'preferred-appointment-times',
  [FIELD_NAMES.SCHEDULING_PREF_PROVIDER_GENDER]: 'preferred-provider-gender',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_CHOOSING]: 'needs-help-choosing-provider',
};

export const FIELD_SECTION_HEADERS = {
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_METHOD]: 'Contact preferences',
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_TIMES]: 'Contact preferences',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_SCHEDULING]: 'Appointment preferences',
  [FIELD_NAMES.SCHEDULING_PREF_APPOINTMENT_TIMES]: 'Appointment preferences',
  [FIELD_NAMES.SCHEDULING_PREF_PROVIDER_GENDER]: 'Provider preferences',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_CHOOSING]: 'Provider preferences',
};

export const ANALYTICS_FIELD_MAP = {
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_METHOD]: 'preferred-contact-method',
  [FIELD_NAMES.SCHEDULING_PREF_CONTACT_TIMES]: 'preferred-contact-times',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_SCHEDULING]:
    'needs-help-scheduling-appointments',
  [FIELD_NAMES.SCHEDULING_PREF_APPOINTMENT_TIMES]:
    'preferred-appointment-times',
  [FIELD_NAMES.SCHEDULING_PREF_PROVIDER_GENDER]: 'preferred-provider-gender',
  [FIELD_NAMES.SCHEDULING_PREF_HELP_CHOOSING]: 'needs-help-choosing-provider',
};

export const API_ROUTES = {
  SCHEDULING_PREFERENCES: '/profile/scheduling_preferences',
};
