version: '3'
services:
  vets-website:
    build:
      context: .
      args:
        userid: ${UID}
    environment:
      API_URL: ${API_URL:-http://localhost:3000}
      WEB_HOST: ${WEB_HOST:-localhost}
      WEB_PORT: ${WEB_PORT:-3002}
    expose:
      - 3002
    image: vets-website:${IMAGE_TAG:-latest}
    ports:
      - 3001:3002
    restart: unless-stopped
    volumes:
      - .:/application
      - ../vagov-content:/vagov-content
      - ../content-build:/content-build
      - ../vets-api:/vets-api
    volumes_from:
      - x11-bridge:rw
    depends_on:
      - x11-bridge

  x11-bridge: # https://github.com/JAremko/docker-x11-bridge
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "10000:10100"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "10100"
      XPRA_PASSWORD: "CYPRESS"