/* eslint-disable no-console */

require('core-js/stable');
require('regenerator-runtime/runtime');
require('dotenv').config();
const fs = require('fs');
const fetch = require('node-fetch');
const path = require('path');
const rspack = require('@rspack/core');

const { RspackManifestPlugin } = require('rspack-manifest-plugin');
const WebpackBar = require('webpackbar');
const StylelintPlugin = require('stylelint-webpack-plugin');

const BUCKETS = require('../src/site/constants/buckets');
const ENVIRONMENTS = require('../src/site/constants/environments');

const { VAGOVSTAGING, VAGOVPROD, LOCALHOST } = ENVIRONMENTS;

const {
  getAppManifests,
  getWebpackEntryPoints,
} = require('./manifest-helpers');

const vaMedalliaStylesFilename = 'va-medallia-styles';

const babelAliases = require('./webpack-aliases');
const generateWebpackDevConfig = require('./webpack.dev.config');

const getAbsolutePath = relativePath =>
  path.join(__dirname, '../', relativePath);

const sharedModules = [
  '@department-of-veterans-affairs/platform-polyfills',
  'react',
  'react-dom',
  'react-redux',
  'redux',
  'redux-thunk',
  '@sentry/browser',
];

const globalEntryFiles = {
  polyfills:
    '@department-of-veterans-affairs/platform-polyfills/preESModulesPolyfills',
  style: '@department-of-veterans-affairs/platform-site-wide/style',
  [vaMedalliaStylesFilename]:
    '@department-of-veterans-affairs/platform-site-wide/va-medallia-style',
  styleConsolidated: getAbsolutePath(
    'src/applications/proxy-rewrite/sass/style-consolidated.scss',
  ),
  vendor: sharedModules,
  'shared-modules': sharedModules,
  'web-components':
    '@department-of-veterans-affairs/platform-site-wide/wc-loader',
};

function getEntryManifests(entry) {
  const allManifests = getAppManifests();
  let entryManifests = allManifests;
  if (entry) {
    const entryNames = entry.split(',').map(name => name.trim());
    if (entryNames.indexOf('static-pages') === -1) {
      entryNames.push('static-pages');
    }
    entryManifests = allManifests.filter(manifest =>
      entryNames.includes(manifest.entryName),
    );
  }
  return entryManifests;
}

function getEntryPoints(entry) {
  const manifestsToBuild = getEntryManifests(entry);
  return getWebpackEntryPoints(manifestsToBuild);
}

async function getScaffoldAssets() {
  const LOCAL_CONTENT_BUILD_ROOT = '../content-build';
  const REMOTE_CONTENT_BUILD_ROOT =
    'https://raw.githubusercontent.com/department-of-veterans-affairs/content-build/main';

  const loadAsset = async contentBuildPath => {
    const filename = path.basename(contentBuildPath);
    const localPath = path.join(LOCAL_CONTENT_BUILD_ROOT, contentBuildPath);

    if (fs.existsSync(localPath)) {
      console.log(`Found local asset at ${localPath}.`);
      return [filename, fs.readFileSync(localPath)];
    }

    const fileUrl = new URL(
      path.join(REMOTE_CONTENT_BUILD_ROOT, contentBuildPath),
    );

    console.log(`Downloading asset from ${fileUrl.toString()}.`);
    const response = await fetch(fileUrl);

    if (!response.ok) {
      throw new Error(
        `Failed to fetch ${fileUrl}.\n\n${response.status}: ${
          response.statusText
        }`,
      );
    }

    const fileContents = await response.text();
    console.log(`Successfully downloaded ${filename}.`);
    return [filename, fileContents];
  };

  const inlineScripts = ['record-event.js', 'static-page-widgets.js'].map(
    filename => path.join('src/site/assets/js', filename),
  );

  const appRegistry = path.join('src/applications', 'registry.json');

  const loadedAssets = await Promise.all(
    [...inlineScripts, appRegistry].map(loadAsset),
  );

  return Object.fromEntries(loadedAssets);
}

// Scaffold HTML is pre-generated by script/generate-scaffold-html.js
// before Rspack runs, so no HtmlPlugin is needed here.
const generateScaffoldHtml = require('../script/generate-scaffold-html');

/** Plugin to write BUILD.txt for CI/deploy compatibility (matches webpack build output) */
class BuildTxtPlugin {
  constructor(buildPath, buildtype) {
    this.buildPath = buildPath;
    this.buildtype = buildtype;
  }

  apply(compiler) {
    compiler.hooks.afterEmit.tapAsync(
      'BuildTxtPlugin',
      (_compilation, callback) => {
        const content = [
          `BUILDTYPE=${this.buildtype}`,
          `NODE_ENV=${process.env.NODE_ENV || 'production'}`,
          `BRANCH_NAME=${process.env.BRANCH_NAME || 'local'}`,
          'CHANGE_TARGET=null',
          `RUN_ID=${process.env.GITHUB_RUN_ID || 'local'}`,
          `RUN_NUMBER=${process.env.GITHUB_RUN_NUMBER || '0'}`,
          `REF=${process.env.GITHUB_SHA || 'local'}`,
          `BUILDTIME=${Math.floor(Date.now() / 1000)}`,
        ].join('\n');
        fs.writeFileSync(path.join(this.buildPath, 'BUILD.txt'), content);
        callback();
      },
    );
  }
}

module.exports = async (env = {}) => {
  const { buildtype = LOCALHOST } = env;
  const buildOptions = {
    api: '',
    buildtype,
    host: '127.0.0.1',
    port: 3001,
    scaffold: false,
    watch: false,
    destination: buildtype,
    ...env,
  };
  const isStylelintEnabled =
    buildOptions.stylelint === true || buildOptions.stylelint === 'true';

  const apps = getEntryPoints(buildOptions.entry);
  const entryFiles = { ...apps, ...globalEntryFiles };
  const isOptimizedBuild = [VAGOVSTAGING, VAGOVPROD].includes(buildtype);
  // Enable scaffold for production builds to match webpack output (HTML files)
  if (isOptimizedBuild) {
    buildOptions.scaffold = true;
  }
  const scaffoldAssets = await getScaffoldAssets();
  const appRegistry = JSON.parse(scaffoldAssets['registry.json']);
  const envBucketUrl = BUCKETS[buildtype];
  const sourceMapSlug = envBucketUrl || '';

  const buildPath = path.resolve(
    __dirname,
    '../',
    'build',
    buildOptions.destination,
  );

  const baseConfig = {
    mode: isOptimizedBuild ? 'production' : 'development',
    devtool: false,
    // Must be top-level (not under experiments) to prevent rspack serve
    // from force-enabling lazy compilation for web targets.
    lazyCompilation: false,
    node: {
      __dirname: 'mock',
    },
    // Rspack is fast enough that filesystem cache is not needed
    entry: entryFiles,
    output: {
      path: path.resolve(buildPath, 'generated'),
      publicPath: '/generated/',
      filename: '[name].entry.js',
      chunkFilename: '[name].entry.js',
    },
    module: {
      // Note: strictExportPresence not supported in Rspack, but Rspack
      // handles missing exports via its own validation
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'builtin:swc-loader',
            options: {
              jsc: {
                parser: {
                  syntax: 'ecmascript',
                  jsx: true,
                  dynamicImport: true,
                  exportDefaultFrom: true,
                  exportNamespaceFrom: true,
                },
                transform: {
                  react: {
                    runtime: 'classic',
                  },
                },
                loose: false,
                externalHelpers: false,
              },
              env: {
                targets: {
                  chrome: '61',
                  firefox: '60',
                  safari: '11',
                  edge: '16',
                  ios: '11',
                },
                mode: 'entry',
                coreJs: '3',
              },
              module: {
                type: 'es6',
              },
            },
          },
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'builtin:swc-loader',
            options: {
              jsc: {
                parser: {
                  syntax: 'typescript',
                  tsx: true,
                },
                transform: {
                  react: {
                    runtime: 'classic',
                  },
                },
                loose: false,
                externalHelpers: false,
              },
              env: {
                targets: {
                  chrome: '61',
                  firefox: '60',
                  safari: '11',
                  edge: '16',
                  ios: '11',
                },
                mode: 'entry',
                coreJs: '3',
              },
              module: {
                type: 'es6',
              },
            },
          },
        },
        {
          test: /\.(sa|sc|c)ss$/,
          use: [
            rspack.CssExtractRspackPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                sourceMap: true,
              },
            },
            {
              loader: 'postcss-loader',
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true,
                sassOptions: {
                  silenceDeprecations: [
                    'legacy-js-api',
                    'import',
                    'if-function',
                    'slash-div',
                    'global-builtin',
                    'color-functions',
                  ],
                },
              },
            },
          ],
        },
        {
          // images - use Rspack's built-in asset modules
          test: /\.(jpe?g|png|gif)$/i,
          type: 'asset',
          parser: {
            dataUrlCondition: {
              maxSize: 10000,
            },
          },
        },
        {
          test: /\.svg/,
          type: 'asset',
          parser: {
            dataUrlCondition: {
              maxSize: 1024,
            },
          },
          generator: {
            publicPath: './',
          },
        },
        {
          test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          type: 'asset',
          parser: {
            dataUrlCondition: {
              maxSize: 7000,
            },
          },
          generator: {
            filename: '[name][ext]',
          },
        },
        {
          test: /\.(ttf|eot)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          type: 'asset/resource',
          generator: {
            filename: '[name][ext]',
          },
        },
        {
          test: /react-jsonschema-form\/lib\/components\/(widgets|fields\/ObjectField|fields\/ArrayField)/,
          exclude: [/widgets\/index\.js/, /widgets\/TextareaWidget/],
          use: {
            loader: require.resolve('./rspack-null-loader.js'),
          },
        },
        { test: /\.afm$/, type: 'asset/source' },
        // fontkit and linebreak brfs transforms - use a custom loader
        // that pre-processes the files since transform-loader is not available
        {
          enforce: 'post',
          test: /fontkit[/\\]index.js$/,
          use: {
            loader: require.resolve('./rspack-brfs-loader.js'),
          },
        },
        {
          enforce: 'post',
          test: /linebreak[/\\]src[/\\]linebreaker.js/,
          use: {
            loader: require.resolve('./rspack-brfs-loader.js'),
          },
        },
        // Alias fs to pdfkit's virtual-fs only for pdfkit and fontkit modules
        {
          test: /[/\\](pdfkit|fontkit)[/\\]/,
          resolve: {
            alias: {
              fs: 'pdfkit/js/virtual-fs.js',
            },
          },
        },
      ],
      noParse: [/mapbox\/vendor\/promise.js$/],
    },
    resolve: {
      modules: [path.resolve(__dirname, '../src'), 'node_modules'],
      alias: {
        ...babelAliases,
        'iconv-lite': false,
        // Force root css-library (patched 0.29.1) so claims-status doesn't use nested 0.8.8 copy missing _override-function.scss
        '@department-of-veterans-affairs/css-library': path.resolve(
          __dirname,
          '../node_modules/@department-of-veterans-affairs/css-library',
        ),
      },
      extensions: ['.js', '.jsx', '.tsx', '.ts'],
      fallback: {
        fs: false,
        querystring: require.resolve('querystring-es3'),
        assert: require.resolve('assert/'),
        buffer: require.resolve('buffer/'),
        crypto: false,
        path: require.resolve('path-browserify'),
        stream: require.resolve('readable-stream'),
        util: require.resolve('util/'),
        zlib: require.resolve('browserify-zlib'),
        'process/browser': require.resolve('process/browser'),
      },
      symlinks: false,
    },
    optimization: {
      chunkIds: 'named',
      moduleIds: 'named',
      minimizer: [
        new rspack.SwcJsMinimizerRspackPlugin({
          extractComments: true,
          minimizerOptions: {
            compress: true,
            mangle: true,
            format: {
              comments: false,
            },
          },
        }),
        new rspack.LightningCssMinimizerRspackPlugin(),
      ],
      splitChunks: {
        cacheGroups: {
          vendors: {
            chunks: 'all',
            test: 'vendor',
            name: 'vendor',
            enforce: true,
          },
        },
      },
    },
    plugins: [
      new rspack.DefinePlugin({
        __BUILDTYPE__: JSON.stringify(buildtype),
        __API__: JSON.stringify(buildOptions.api),
        __REGISTRY__: JSON.stringify(appRegistry),
        'process.env.MAPBOX_TOKEN': JSON.stringify(
          process.env.MAPBOX_TOKEN || '',
        ),
        'process.env.USE_LOCAL_DIRECTLINE':
          process.env.USE_LOCAL_DIRECTLINE || false,
        'process.env.USE_MOCKS': JSON.stringify(process.env.USE_MOCKS || ''),
        'process.env.HOST_NAME': JSON.stringify(process.env.HOST_NAME || ''),
        'process.env.LOG_LEVEL': JSON.stringify(
          process.env.LOG_LEVEL || 'info',
        ),
        'process.env.DATADOG_TAGS': JSON.stringify(
          process.env.DATADOG_TAGS || '',
        ),
      }),

      new rspack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
        process: 'process/browser',
      }),

      new rspack.SourceMapDevToolPlugin({
        append: `\n//# sourceMappingURL=${sourceMapSlug}/generated/[url]`,
        filename: '[file].map',
      }),

      new rspack.CssExtractRspackPlugin(),

      new rspack.IgnorePlugin({
        resourceRegExp: /^\.\/locale$/,
        contextRegExp: /moment$/,
      }),

      new rspack.CopyRspackPlugin({
        patterns: [
          {
            from: 'src/site/assets',
            to: buildPath,
          },
          {
            from: 'src/platform/site-wide/sass/fonts',
            to: `${buildPath}/generated`,
          },
          {
            from:
              'node_modules/@department-of-veterans-affairs/component-library/dist/img/',
            to: `${buildPath}/img/`,
          },
          ...(buildOptions.buildtype === 'localhost'
            ? [
                {
                  from: 'node_modules/msw/lib/mockServiceWorker.js',
                  to: buildPath,
                },
              ]
            : []),
        ],
      }),

      new WebpackBar(),

      ...(isOptimizedBuild ? [new BuildTxtPlugin(buildPath, buildtype)] : []),
    ],
    devServer: generateWebpackDevConfig(buildOptions),
  };

  if (!buildOptions.watch) {
    baseConfig.plugins.push(
      new RspackManifestPlugin({
        fileName: 'file-manifest.json',
        filter: ({ isChunk }) => isChunk,
      }),
    );
  }

  if (isStylelintEnabled) {
    baseConfig.plugins.push(
      new StylelintPlugin({
        configFile: '.stylelintrc.json',
        exclude: ['node_modules', 'build', 'coverage', '.cache'],
        fix: true,
      }),
    );
  }

  if (buildOptions.scaffold) {
    // Pre-generate scaffold HTML files in parallel before Rspack compiles
    await generateScaffoldHtml({ buildPath });
  }

  if (buildOptions.watch) {
    // Compiled assets are served from memory by devMiddleware.
    // Scaffold HTML is pre-generated on disk.
    // Serve copy targets from source directories instead of CopyRspackPlugin
    // to eliminate disk I/O during the emit phase.
    baseConfig.devServer.devMiddleware.writeToDisk = false;
    baseConfig.devServer.allowedHosts = 'all';
    baseConfig.devServer.static = [
      { directory: buildPath, watch: { poll: 1000 } },
      {
        directory: path.resolve(__dirname, '../src/site/assets'),
        publicPath: '/',
        watch: false,
      },
      {
        directory: path.resolve(
          __dirname,
          '../src/platform/site-wide/sass/fonts',
        ),
        publicPath: '/generated/',
        watch: false,
      },
      {
        directory: path.resolve(
          __dirname,
          '../node_modules/@department-of-veterans-affairs/component-library/dist/img',
        ),
        publicPath: '/img/',
        watch: false,
      },
    ];
    baseConfig.plugins = baseConfig.plugins.filter(
      p => !(p instanceof rspack.CopyRspackPlugin),
    );
  }

  if (buildOptions.open) {
    const target =
      buildOptions.openTo || buildOptions.entry
        ? getEntryManifests(buildOptions.entry)[0].rootUrl
        : '';
    baseConfig.devServer.open = { target };
  }

  baseConfig.watchOptions = {
    ignored: /\/(\.git|node_modules)\//,
  };

  return baseConfig;
};
