export default {
  0: 'ACL tear (anterior cruciate ligament tear), right',
  1: 'ACL tear (anterior cruciate ligament tear), left',
  2: 'ACL tear (anterior cruciate ligament tear), bilateral',
  3: 'acne',
  4: 'adjustment disorder',
  5: 'agoraphobia',
  6: 'alopecia',
  7: 'ALS (amyotrophic lateral sclerosis)',
  8: 'anal cancer',
  9: 'anal or perianal fistula (fistula-in-ano)',
  10: 'anemia',
  11: 'ankle replacement (ankle arthroplasty), right',
  12: 'ankle replacement (ankle arthroplasty), left',
  13: 'ankle replacement (ankle arthroplasty), bilateral',
  14: 'ankle sprain, right',
  15: 'ankle sprain, left',
  16: 'ankle sprain, bilateral',
  17: 'ankylosis in ankle, right',
  18: 'ankylosis in ankle, left',
  19: 'ankylosis in ankle, bilateral',
  20: 'ankylosis in elbow, right',
  21: 'ankylosis in elbow, left',
  22: 'ankylosis in elbow, bilateral',
  23: 'ankylosis in hand or fingers, right',
  24: 'ankylosis in hand or fingers, left',
  25: 'ankylosis in hand or fingers, bilateral',
  26: 'ankylosis in hip, right',
  27: 'ankylosis in hip, left',
  28: 'ankylosis in hip, bilateral',
  29: 'ankylosis in knee, right',
  30: 'ankylosis in knee, left',
  31: 'ankylosis in knee, bilateral',
  32: 'ankylosis in shoulder, right',
  33: 'ankylosis in shoulder, left',
  34: 'ankylosis in shoulder, bilateral',
  35: 'ankylosis in wrist, right',
  36: 'ankylosis in wrist, left',
  37: 'ankylosis in wrist, bilateral',
  38: 'anorexia (type of eating disorder)',
  39: 'aortic insufficiency (aortic regurgitation)',
  40: 'aortic valve disease',
  41: 'arrhythmia (irregular heartbeat)',
  42: 'asthma',
  43: 'astragalectomy or talectomy (removal of talus bone in ankle)',
  44: "athlete's foot (tinea pedis)",
  45: 'atrial fibrillation (A-fib)',
  46: 'bipolar disorder',
  47: 'bladder cancer',
  48: 'bladder stones',
  49: 'Boutonniere deformity in fingers, right',
  50: 'Boutonniere deformity in fingers, left',
  51: 'Boutonniere deformity in fingers, bilateral',
  52: 'bulimia (type of eating disorder)',
  53: 'bunions (hallux valgus), right',
  54: 'bunions (hallux valgus), left',
  55: 'bunions (hallux valgus), bilateral',
  56: 'bursitis in ankle, right',
  57: 'bursitis in ankle, left',
  58: 'bursitis in ankle, bilateral',
  59: 'bursitis in elbow, right',
  60: 'bursitis in elbow, left',
  61: 'bursitis in elbow, bilateral',
  62: 'bursitis in foot, right',
  63: 'bursitis in foot, left',
  64: 'bursitis in foot, bilateral',
  65: 'bursitis in hand or fingers, right',
  66: 'bursitis in hand or fingers, left',
  67: 'bursitis in hand or fingers, bilateral',
  68: 'bursitis in hip, right',
  69: 'bursitis in hip, left',
  70: 'bursitis in hip, bilateral',
  71: 'bursitis in knee, right',
  72: 'bursitis in knee, left',
  73: 'bursitis in knee, bilateral',
  74: 'bursitis in shoulder, right',
  75: 'bursitis in shoulder, left',
  76: 'bursitis in shoulder, bilateral',
  77: 'bursitis in wrist, right',
  78: 'bursitis in wrist, left',
  79: 'bursitis in wrist, bilateral',
  80: 'carpal tunnel syndrome, right',
  81: 'carpal tunnel syndrome, left',
  82: 'carpal tunnel syndrome, bilateral',
  83: 'cervical spinal stenosis (narrowing of spinal canal in neck)',
  84: 'chloracne',
  85: 'chronic bronchitis',
  86: 'chronic conjunctivitis (pink eye)',
  87: 'chronic fatigue syndrome',
  88: 'chronic kidney disease (CKD)',
  89: 'chronic laryngitis',
  90: 'chronic nephritis (inflammation of kidneys)',
  91: 'chronic obstructive pulmonary disease (COPD)',
  92: "chronic otitis externa (swimmer's ear), right",
  93: "chronic otitis externa (swimmer's ear), left",
  94: "chronic otitis externa (swimmer's ear), bilateral",
  95: 'chronic rhinitis, allergic or non-allergic',
  96: 'chronic sinusitis',
  97: 'chronic suppurative otitis media (CSOM) or mastoiditis, right',
  98: 'chronic suppurative otitis media (CSOM) or mastoiditis, left',
  99: 'chronic suppurative otitis media (CSOM) or mastoiditis, bilateral',
  100: 'cirrhosis (scarring of liver)',
  101: 'claw foot (pes cavus), right',
  102: 'claw foot (pes cavus), left',
  103: 'claw foot (pes cavus), bilateral',
  104: 'colorectal cancer or colon cancer',
  105: 'complete loss of sense of smell (anosmia)',
  106: 'complete loss of sense of taste (ageusia)',
  107: 'congestive heart failure (CHF)',
  108: 'coronary artery disease (CAD or arteriosclerotic heart disease)',
  109: 'costochondritis',
  110: 'Cranial nerve paralysis or cranial neuritis (inflammation of cranial nerves)',
  111: 'cranial neuralgia (cranial nerve pain)',
  112: "Crohn's disease",
  113: 'cyclothymic disorder (mild bipolar disorder)',
  114: "De Quervain's tenosynovitis (De Quervain's syndrome), right",
  115: "De Quervain's tenosynovitis (De Quervain's syndrome), left",
  116: "De Quervain's tenosynovitis (De Quervain's syndrome), bilateral",
  117: 'decompression illness',
  118: 'deep vein thrombosis (DVT) in leg, right',
  119: 'deep vein thrombosis (DVT) in leg, left',
  120: 'deep vein thrombosis (DVT) in legs, bilateral',
  121: 'degenerative arthritis (osteoarthritis) in ankle, right',
  122: 'degenerative arthritis (osteoarthritis) in ankle, left',
  123: 'degenerative arthritis (osteoarthritis) in ankle, bilateral',
  124: 'degenerative arthritis (osteoarthritis) in elbow, right',
  125: 'degenerative arthritis (osteoarthritis) in elbow, left',
  126: 'degenerative arthritis (osteoarthritis) in elbow, bilateral',
  127: 'degenerative arthritis (osteoarthritis) in foot, right',
  128: 'degenerative arthritis (osteoarthritis) in foot, left',
  129: 'degenerative arthritis (osteoarthritis) in foot, bilateral',
  130: 'degenerative arthritis (osteoarthritis) in hand or fingers, right',
  131: 'degenerative arthritis (osteoarthritis) in hand or fingers, left',
  132: 'degenerative arthritis (osteoarthritis) in hand or fingers, bilateral',
  133: 'degenerative arthritis (osteoarthritis) in hip, right',
  134: 'degenerative arthritis (osteoarthritis) in hip, left',
  135: 'degenerative arthritis (osteoarthritis) in hip, bilateral',
  136: 'degenerative arthritis (osteoarthritis) in knee, right',
  137: 'degenerative arthritis (osteoarthritis) in knee, left',
  138: 'degenerative arthritis (osteoarthritis) in knee, bilateral',
  139: 'degenerative arthritis (osteoarthritis) in shoulder, right',
  140: 'degenerative arthritis (osteoarthritis) in shoulder, left',
  141: 'degenerative arthritis (osteoarthritis) in shoulder, bilateral',
  142: 'degenerative arthritis (osteoarthritis) in wrist, right',
  143: 'degenerative arthritis (osteoarthritis) in wrist, left',
  144: 'degenerative arthritis (osteoarthritis) in wrist, bilateral',
  145: 'depression (major depressive disorder)',
  146: "Depuytren's contracture (abnormal thickening of tissues in palm of hand), right",
  147: "Depuytren's contracture (abnormal thickening of tissues in palm of hand), left",
  148: "Depuytren's contracture (abnormal thickening of tissues in palm of hand), bilateral",
  149: 'deviated septum',
  150: 'diabetes insipidus',
  151: 'diabetes, type 1 or type 2',
  152: 'diabetic nephropathy (diabetic kidney disease)',
  153: 'diabetic peripheral neuropathy, right lower extremities',
  154: 'diabetic peripheral neuropathy, right upper extremities',
  155: 'diabetic peripheral neuropathy, left lower extremities',
  156: 'diabetic peripheral neuropathy, left upper extremities',
  157: 'diabetic peripheral neuropathy, bilateral lower extremities',
  158: 'diabetic peripheral neuropathy, bilateral upper extremities',
  159: 'diabetic retinopathy',
  160: 'dry eye syndrome',
  161: 'dysphagia (difficulty swallowing)',
  162: 'eczema (atopic dermatitis)',
  163: 'elbow replacement (elbow arthroplasty), right',
  164: 'elbow replacement (elbow arthroplasty), left',
  165: 'elbow replacement (elbow arthroplasty), bilateral',
  166: 'endometriosis',
  167: 'enlarged prostate (benign prostatic hyperplasia or BPH)',
  168: 'epididymitis',
  169: 'epiphora (watery eyes)',
  170: 'erectile dysfunction (ED)',
  171: 'esophageal cancer',
  172: 'esophageal stricture (narrowing of esophagus)',
  173: 'fecal incontinence (loss of bowel control)',
  174: 'female sexual arousal disorder (FSAD)',
  175: 'femoral hernia (hernia in thigh area)',
  176: 'fibromyalgia',
  177: 'flatfoot (pes planus), right',
  178: 'flatfoot (pes planus), left',
  179: 'flatfoot (pes planus), bilateral',
  180: 'foot fracture (tarsal or metatarsal fracture), right',
  181: 'foot fracture (tarsal or metatarsal fracture), left',
  182: 'foot fracture (tarsal or metatarsal fracture), bilateral',
  183: 'frostbite in foot, right',
  184: 'frostbite in foot, left',
  185: 'frostbite in foot, bilateral',
  186: 'frostbite in hand or fingers, right',
  187: 'frostbite in hand or fingers, left',
  188: 'frostbite in hand or fingers, bilateral',
  189: 'gallstones (cholelithiasis)',
  190: "gamekeeper's thumb, right",
  191: "gamekeeper's thumb, left",
  192: "gamekeeper's thumb, bilateral",
  193: 'ganglion cyst in hand or fingers, right',
  194: 'ganglion cyst in hand or fingers, left',
  195: 'ganglion cyst in hand or fingers, bilateral',
  196: 'ganglion cyst in wrist, right',
  197: 'ganglion cyst in wrist, left',
  198: 'ganglion cyst in wrist, bilateral',
  199: 'generalized anxiety disorder (GAD)',
  200: 'GERD (gastroesophageal reflux disease)',
  201: 'glaucoma',
  202: "golfer's elbow (medial epicondylitis), right",
  203: "golfer's elbow (medial epicondylitis), left",
  204: "golfer's elbow (medial epicondylitis), bilateral",
  205: 'gonococcal arthritis',
  206: 'gout in foot, right',
  207: 'gout in foot, left',
  208: 'gout in foot, bilateral',
  209: 'gout in wrist, right',
  210: 'gout in wrist, left',
  211: 'gout in wrist, bilateral',
  212: 'greater trochanteric pain syndrome (lateral hip pain), right',
  213: 'greater trochanteric pain syndrome (lateral hip pain), left',
  214: 'greater trochanteric pain syndrome (lateral hip pain), bilateral',
  215: 'hallux rigidus (big toe arthritis), bilateral',
  216: 'hallux rigidus (big toe arthritis), left',
  217: 'hallux rigidus (big toe arthritis), right',
  218: 'hammer toe, right',
  219: 'hammer toe, left',
  220: 'hammer toe, bilateral',
  221: "Hansen's disease (leprosy)",
  222: 'hearing loss, other than tinnitus',
  223: 'heart attack (myocardial infarction)',
  224: 'heart bypass surgery (coronary artery bypass graft)',
  225: 'hemorrhoids',
  226: 'hepatitis B',
  227: 'hepatitis C',
  228: 'herpes (herpes simplex virus or HSV)',
  229: 'hiatal hernia',
  230: 'hip impingement (femoroacetabular impingement or FAI), right',
  231: 'hip impingement (femoroacetabular impingement or FAI), left',
  232: 'hip impingement (femoroacetabular impingement or FAI), bilateral',
  233: 'hip replacement (hip arthroplasty), right',
  234: 'hip replacement (hip arthroplasty), left',
  235: 'hip replacement (hip arthroplasty), bilateral',
  236: 'hip sprain, right',
  237: 'hip sprain, left',
  238: 'hip sprain, bilateral',
  239: 'HIV-related illness',
  240: 'Hodgkin lymphoma',
  241: 'hydrocele, right',
  242: 'hyperhidrosis (excessive sweating)',
  243: 'hypertension (high blood pressure)',
  244: 'hyperthyroidism (overactive thyroid)',
  245: 'hypothyroidism (underactive thyroid)',
  246: 'hysterectomy (removal of uterus)',
  247: 'hysterectomy and ovariectomy (removal of uterus and both ovaries)',
  248: 'illness anxiety disorder (hypochondria)',
  249: 'immersion foot, right',
  250: 'immersion foot, left',
  251: 'immersion foot, bilateral',
  252: 'inguinal hernia (hernia in groin)',
  253: 'intervertebral disc syndrome (IVDS), back',
  254: 'intervertebral disc syndrome (IVDS), neck',
  255: 'iron deficiency anemia',
  256: 'irritable bowel syndrome (IBS)',
  257: 'keratinization skin disorders',
  258: 'kidney cancer (renal cancer)',
  259: 'kidney removal (nephrectomy)',
  260: 'kidney stones (nephrolithiasis)',
  261: 'kidney transplant',
  262: 'knee hyperextension (genu recurvatum), right',
  263: 'knee hyperextension (genu recurvatum), left',
  264: 'knee hyperextension (genu recurvatum), bilateral',
  265: 'knee instability, right',
  266: 'knee instability, left',
  267: 'knee instability, bilateral',
  268: 'knee or patellar dislocation, right',
  269: 'knee or patellar dislocation, left',
  270: 'knee or patellar dislocation, bilateral',
  271: 'knee or patellar fracture, right',
  272: 'knee or patellar fracture, left',
  273: 'knee or patellar fracture, bilateral',
  274: 'knee replacement (knee arthroplasty), right',
  275: 'knee replacement (knee arthroplasty), left',
  276: 'knee replacement (knee arthroplasty), bilateral',
  277: 'knee strain or sprain, right',
  278: 'knee strain or sprain, left',
  279: 'knee strain or sprain, bilateral',
  280: 'labyrinthitis (type of inner ear infection), right',
  281: 'labyrinthitis (type of inner ear infection), left',
  282: 'labyrinthitis (type of inner ear infection), bilateral',
  283: 'laryngeal cancer (cancer of larynx)',
  284: 'leukemia',
  285: 'liver cancer, including hepatocellular carcinoma (HCC)',
  286: 'loss of both eyes',
  287: 'loss of teeth due to bone loss',
  288: 'lower back sprain (lumbosacral sprain)',
  289: 'lower back strain (lumbosacral strain)',
  290: 'lumbar spinal stenosis (narrowing of spinal canal in lower back)',
  291: 'lung cancer',
  292: 'lupus',
  293: 'lymphatic filariasis',
  294: 'malaria',
  295: 'mallet finger, right',
  296: 'mallet finger, left',
  297: 'mallet finger, bilateral',
  298: "Meniere's disease",
  299: 'meniscectomy (removal of meniscus), right',
  300: 'meniscectomy (removal of meniscus), left',
  301: 'meniscectomy (removal of meniscus), bilateral',
  302: 'meniscus tear, right',
  303: 'meniscus tear, left',
  304: 'meniscus tear, bilateral',
  305: 'metatarsalgia (pain in ball of foot), right',
  306: 'metatarsalgia (pain in ball of foot), left',
  307: 'metatarsalgia (pain in ball of foot), bilateral',
  308: 'middle back sprain (thoracic sprain)',
  309: 'middle back strain (thoracic strain)',
  310: 'migraines (headaches)',
  311: 'mitral regurgitation',
  312: 'mitral valve prolapse (Barlow syndrome)',
  313: "Morton's neuroma, right",
  314: "Morton's neuroma, left",
  315: "Morton's neuroma, bilateral",
  316: 'multiple sclerosis (MS)',
  317: 'muscle hernia',
  318: 'myasthenia gravis',
  319: 'nasopharyngeal cancer',
  320: 'neck sprain (cervical sprain)',
  321: 'neck strain (cervical strain)',
  322: 'neurogenic bladder',
  323: 'non-diabetic peripheral neuropathy, right lower extremities',
  324: 'non-diabetic peripheral neuropathy, right upper extremities',
  325: 'non-diabetic peripheral neuropathy, left lower extremities',
  326: 'non-diabetic peripheral neuropathy, left upper extremities',
  327: 'non-diabetic peripheral neuropathy, bilateral lower extremities',
  328: 'non-diabetic peripheral neuropathy, bilateral upper extremities',
  329: 'non-Hodgkin lymphoma',
  330: 'obsessive compulsive disorder (OCD)',
  331: 'orchitis (inflammation of testicles)',
  332: 'oropharyngeal cancer',
  333: 'osteomyelitis',
  334: 'otitis media (middle ear infection), right',
  335: 'otitis media (middle ear infection), left',
  336: 'otitis media (middle ear infection), bilateral',
  337: 'ovarian adhesions',
  338: 'ovarian cysts',
  339: 'ovariectomy (removal of one or both ovaries)',
  340: 'pancreatic cancer',
  341: 'panic disorder',
  342: "Parkinson's disease",
  343: 'patellar or quadriceps tendon rupture, right',
  344: 'patellar or quadriceps tendon rupture, left',
  345: 'patellar or quadriceps tendon rupture, bilateral',
  346: 'patellofemoral pain syndrome, right',
  347: 'patellofemoral pain syndrome, left',
  348: 'patellofemoral pain syndrome, bilateral',
  349: 'PCL tear (posterior cruciate ligament tear), right',
  350: 'PCL tear (posterior cruciate ligament tear), left',
  351: 'PCL tear (posterior cruciate ligament tear), bilateral',
  352: 'penile cancer',
  353: 'perforated eardrum (perforated tympanic membrane), right',
  354: 'perforated eardrum (perforated tympanic membrane), left',
  355: 'perforated eardrum (perforated tympanic membrane), bilateral',
  356: 'persistent depressive disorder (dysthymic disorder)',
  357: 'pharyngeal cancer (throat cancer) ',
  358: 'plantar fasciitis, left',
  359: 'plantar fasciitis, right',
  360: 'plantar fasciitis, bilateral',
  361: 'plantar warts (foot warts), right',
  362: 'plantar warts (foot warts), left',
  363: 'plantar warts (foot warts), bilateral',
  364: 'pneumococcal arthritis',
  365: 'polycystic ovary syndrome (PCOS)',
  366: 'post-traumatic arthritis in ankle, right',
  367: 'post-traumatic arthritis in ankle, left',
  368: 'post-traumatic arthritis in ankle, bilateral',
  369: 'post-traumatic arthritis in elbow, right',
  370: 'post-traumatic arthritis in elbow, left',
  371: 'post-traumatic arthritis in elbow, bilateral',
  372: 'post-traumatic arthritis in foot, right',
  373: 'post-traumatic arthritis in foot, left',
  374: 'post-traumatic arthritis in foot, bilateral',
  375: 'post-traumatic arthritis in hand or fingers, right',
  376: 'post-traumatic arthritis in hand or fingers, left',
  377: 'post-traumatic arthritis in hand or fingers, bilateral',
  378: 'post-traumatic arthritis in hip, right',
  379: 'post-traumatic arthritis in hip, left',
  380: 'post-traumatic arthritis in hip, bilateral',
  381: 'post-traumatic arthritis in knee, right',
  382: 'post-traumatic arthritis in knee, left',
  383: 'post-traumatic arthritis in knee, bilateral',
  384: 'post-traumatic arthritis in shoulder, right',
  385: 'post-traumatic arthritis in shoulder, left',
  386: 'post-traumatic arthritis in shoulder, bilateral',
  387: 'post-traumatic arthritis in wrist, right',
  388: 'post-traumatic arthritis in wrist, left',
  389: 'post-traumatic arthritis in wrist, bilateral',
  390: 'poststreptococcal arthritis',
  391: 'premature ventricular contractions',
  392: 'proctitis (inflammation of rectum)',
  393: 'prostate cancer',
  394: 'prostatitis (inflammation of prostate)',
  395: 'pseudofolliculitis barbae (razor bumps, shave bumps, or ingrown hairs)',
  396: 'psoriasis',
  397: 'PTSD (post-traumatic stress disorder), combat-related',
  398: 'PTSD (post-traumatic stress disorder), non-combat-related',
  399: 'radiculopathy, right lower extremities',
  400: 'radiculopathy, left lower extremities',
  401: 'radiculopathy, bilateral lower extremities',
  402: 'radiculopathy, right upper extremities',
  403: 'radiculopathy, left upper extremities',
  404: 'radiculopathy, bilateral upper extremities',
  405: "Raynaud's disease",
  406: 'rheumatoid arthritis',
  407: 'rib fracture, right',
  408: 'rib fracture, left',
  409: 'rib fracture, bilateral',
  410: 'rib removal',
  411: 'right ventricular hypertrophy (RVH)',
  412: 'left ventricular hypertrophy (LVH)',
  413: 'biventricular hypertrophy',
  414: 'ringworm (dermatophytosis)',
  415: 'rotator cuff tear, right',
  416: 'rotator cuff tear, left',
  417: 'rotator cuff tear, bilateral',
  418: 'scars, extremities or trunk',
  419: 'scars, head, face or neck',
  420: 'schizophrenia',
  421: 'shin splints, right',
  422: 'shin splints, left',
  423: 'shin splints, bilateral',
  424: 'shoulder dislocation, right',
  425: 'shoulder dislocation, left',
  426: 'shoulder dislocation, bilateral',
  427: 'shoulder impingement syndrome, right',
  428: 'shoulder impingement syndrome, left',
  429: 'shoulder impingement syndrome, bilateral',
  430: 'shoulder replacement (shoulder arthroplasty), right',
  431: 'shoulder replacement (shoulder arthroplasty), left',
  432: 'shoulder replacement (shoulder arthroplasty), bilateral',
  433: 'shoulder strain, right',
  434: 'shoulder strain, left',
  435: 'shoulder strain, bilateral',
  436: 'sickle cell anemia',
  437: 'SLAP tear (superior labral anterior to posterior tear), right',
  438: 'SLAP tear (superior labral anterior to posterior), left',
  439: 'SLAP tear (superior labral anterior to posterior tear), bilateral',
  440: 'sleep apnea',
  441: 'somatic symptom disorder (SSD)',
  442: 'spinal arthritis, back',
  443: 'spinal arthritis, neck',
  444: 'spondylolisthesis, back',
  445: 'spondylolisthesis, neck',
  446: 'stomach cancer',
  447: 'stress fracture in leg, right',
  448: 'stress fracture in leg, left',
  449: 'stress fracture in leg, bilateral',
  450: 'syphilitic arthritis',
  451: 'tachycardia',
  452: 'tailbone (coccyx) removal',
  453: 'temporomandibular disorder, including TMJ',
  454: 'tendinosis in hand or fingers, right',
  455: 'tendinosis in hand or fingers, left',
  456: 'tendinosis in hand or fingers, bilateral',
  457: 'tendonitis (tendinitis) in ankle, right',
  458: 'tendonitis (tendinitis) in ankle, left',
  459: 'tendonitis (tendinitis) in ankle, bilateral',
  460: 'tendonitis (tendinitis) in elbow, right',
  461: 'tendonitis (tendinitis) in elbow, left',
  462: 'tendonitis (tendinitis) in elbow, bilateral',
  463: 'tendonitis (tendinitis) in foot, right',
  464: 'tendonitis (tendinitis) in foot, left',
  465: 'tendonitis (tendinitis) in foot, bilateral',
  466: 'tendonitis (tendinitis) in hand or fingers, right',
  467: 'tendonitis (tendinitis) in hand or fingers, left',
  468: 'tendonitis (tendinitis) in hand or fingers, bilateral',
  469: 'tendonitis (tendinitis) in hip, right',
  470: 'tendonitis (tendinitis) in hip, left',
  471: 'tendonitis (tendinitis) in hip, bilateral',
  472: 'tendonitis (tendinitis) in knee, right',
  473: 'tendonitis (tendinitis) in knee, left',
  474: 'tendonitis (tendinitis) in knee, bilateral',
  475: 'tendonitis (tendinitis) in shoulder, right',
  476: 'tendonitis (tendinitis) in shoulder, left',
  477: 'tendonitis (tendinitis) in shoulder, bilateral',
  478: 'tendonitis (tendinitis) in wrist, right',
  479: 'tendonitis (tendinitis) in wrist, left',
  480: 'tendonitis (tendinitis) in wrist, bilateral',
  481: 'tennis elbow (lateral epicondylitis), right',
  482: 'tennis elbow (lateral epicondylitis), left',
  483: 'tennis elbow (lateral epicondylitis), bilateral',
  484: 'tenosynovitis in hand or fingers, right',
  485: 'tenosynovitis in hand or fingers, left',
  486: 'tenosynovitis in hand or fingers, bilateral',
  487: 'tenosynovitis in wrist, right',
  488: 'tenosynovitis in wrist, left',
  489: 'tenosynovitis in wrist, bilateral',
  490: 'testicular cancer',
  491: 'tibia or fibula fracture, right',
  492: 'tibia or fibula fracture, left',
  493: 'tibia or fibula fracture, bilateral',
  494: 'Tietze syndrome',
  495: 'tinnitus (ringing or hissing in ears)',
  496: 'trachea cancer (cancer of windpipe)',
  497: 'traumatic brain injury (TBI)',
  498: 'trigger finger, right',
  499: 'trigger finger, left',
  500: 'trigger finger, bilateral',
  501: 'typhoid arthritis',
  502: 'ulcerative colitis',
  503: 'ureteral cancer (ureter cancer)',
  504: 'urethritis',
  505: 'urinary incontinence (loss of bladder control)',
  506: 'urticaria (hives)',
  507: 'varicocele, right',
  508: 'varicocele, left',
  509: 'varicocele, bilateral',
  510: 'varicose veins in leg',
  511: 'varicose veins, other than in leg',
  512: 'ventral hernia (hernia in abdomen)',
  513: 'visual impairment, including blurry vision, blindness and double vision',
  514: 'vitiligo',
  515: 'weak foot, bilateral',
  516: 'Wolff-Parkinson-White syndrome',
  517: 'wrist fracture, right',
  518: 'wrist fracture, left',
  519: 'wrist fracture, bilateral',
  520: 'wrist replacement (wrist arthroplasty), right',
  521: 'wrist replacement (wrist arthroplasty), left',
  522: 'wrist replacement (wrist arthroplasty), bilateral',
  523: 'wrist sprain, right',
  524: 'wrist sprain, left',
  525: 'wrist sprain, bilateral',
};
