// note: the id's are no longer used for classification, but are kept here for compatibility with the old code

export default {
  0: 'ACL tear (anterior cruciate ligament tear), right',
  1: 'ACL tear (anterior cruciate ligament tear), left',
  2: 'ACL tear (anterior cruciate ligament tear), bilateral',
  3: 'acne',
  4: 'adjustment disorder',
  5: 'agoraphobia',
  6: 'alopecia',
  7: 'ALS (amyotrophic lateral sclerosis)',
  8: 'anal cancer',
  9: 'anal or perianal fistula (fistula-in-ano)',
  10: 'ankle replacement (ankle arthroplasty), right',
  11: 'ankle replacement (ankle arthroplasty), left',
  12: 'ankle replacement (ankle arthroplasty), bilateral',
  13: 'ankylosis in ankle, right',
  14: 'ankylosis in ankle, left',
  15: 'ankylosis in ankle, bilateral',
  16: 'ankylosis in elbow, right',
  17: 'ankylosis in elbow, left',
  18: 'ankylosis in elbow, bilateral',
  19: 'ankylosis in hand or fingers, right',
  20: 'ankylosis in hand or fingers, left',
  21: 'ankylosis in hand or fingers, bilateral',
  22: 'ankylosis in hip, right',
  23: 'ankylosis in hip, left',
  24: 'ankylosis in hip, bilateral',
  25: 'ankylosis in knee, right',
  26: 'ankylosis in knee, left',
  27: 'ankylosis in knee, bilateral',
  28: 'ankylosis in shoulder, right',
  29: 'ankylosis in shoulder, left',
  30: 'ankylosis in shoulder, bilateral',
  31: 'ankylosis in wrist, right',
  32: 'ankylosis in wrist, left',
  33: 'ankylosis in wrist, bilateral',
  34: 'anorexia (type of eating disorder)',
  35: 'aortic insufficiency (aortic regurgitation)',
  36: 'aortic valve disease',
  37: 'arrhythmia (irregular heartbeat)',
  38: 'asthma',
  39: 'astragalectomy or talectomy (removal of talus bone in ankle), right',
  40: 'astragalectomy or talectomy (removal of talus bone in ankle), left',
  41: 'astragalectomy or talectomy (removal of talus bone in ankle), bilateral',
  42: "athlete's foot (tinea pedis)",
  43: 'atrial fibrillation (A-fib)',
  44: 'basal cell carcinoma of the skin, head or neck',
  45: 'basal cell carcinoma of the skin, extremities or trunk',
  46: 'bipolar disorder',
  47: 'bladder cancer',
  48: 'bladder stones',
  49: 'bone cancer, including osteosarcoma, head or neck',
  50: 'bone cancer, including osteosarcoma, extremities or trunk',
  51: 'Boutonniere deformity in fingers, right',
  52: 'Boutonniere deformity in fingers, left',
  53: 'Boutonniere deformity in fingers, bilateral',
  54: 'brain cancer, including glioblastoma',
  55: 'breast cancer, right',
  56: 'breast cancer, left',
  57: 'breast cancer, bilateral',
  58: 'bronchiectasis ',
  59: 'bulimia (type of eating disorder)',
  60: 'bunions (hallux valgus), right',
  61: 'bunions (hallux valgus), left',
  62: 'bunions (hallux valgus), bilateral',
  63: 'bursitis in ankle, right',
  64: 'bursitis in ankle, left',
  65: 'bursitis in ankle, bilateral',
  66: 'bursitis in elbow, right',
  67: 'bursitis in elbow, left',
  68: 'bursitis in elbow, bilateral',
  69: 'bursitis in foot, right',
  70: 'bursitis in foot, left',
  71: 'bursitis in foot, bilateral',
  72: 'bursitis in hand or fingers, right',
  73: 'bursitis in hand or fingers, left',
  74: 'bursitis in hand or fingers, bilateral',
  75: 'bursitis in hip, right',
  76: 'bursitis in hip, left',
  77: 'bursitis in hip, bilateral',
  78: 'bursitis in knee, right',
  79: 'bursitis in knee, left',
  80: 'bursitis in knee, bilateral',
  81: 'bursitis in shoulder, right',
  82: 'bursitis in shoulder, left',
  83: 'bursitis in shoulder, bilateral',
  84: 'bursitis in wrist, right',
  85: 'bursitis in wrist, left',
  86: 'bursitis in wrist, bilateral',
  87: 'carpal tunnel syndrome, right',
  88: 'carpal tunnel syndrome, left',
  89: 'carpal tunnel syndrome, bilateral',
  90: 'cervical cancer',
  91: 'cervical spinal stenosis (narrowing of spinal canal in neck)',
  92: 'chloracne',
  93: 'chronic bronchitis',
  94: 'chronic conjunctivitis (pink eye)',
  95: 'chronic fatigue syndrome',
  96: 'chronic kidney disease (CKD)',
  97: 'chronic laryngitis',
  98: 'chronic nephritis (inflammation of kidneys)',
  99: 'chronic obstructive pulmonary disease (COPD)',
  100: "chronic otitis externa (swimmer's ear), right",
  101: "chronic otitis externa (swimmer's ear), left",
  102: "chronic otitis externa (swimmer's ear), bilateral",
  103: 'chronic rhinitis, allergic or non-allergic',
  104: 'chronic sinusitis',
  105: 'chronic suppurative otitis media (CSOM) or mastoiditis, right',
  106: 'chronic suppurative otitis media (CSOM) or mastoiditis, left',
  107: 'chronic suppurative otitis media (CSOM) or mastoiditis, bilateral',
  108: 'chronic urticaria (chronic hives)',
  109: 'cirrhosis (scarring of liver)',
  110: 'claw foot (pes cavus), right',
  111: 'claw foot (pes cavus), left',
  112: 'claw foot (pes cavus), bilateral',
  113: 'colorectal cancer or colon cancer',
  114: 'complete loss of sense of smell (anosmia)',
  115: 'complete loss of sense of taste (ageusia)',
  116: 'congestive heart failure (CHF)',
  117: 'constrictive bronchiolitis (obliterative bronchiolitis)',
  118: 'coronary artery disease (CAD or arteriosclerotic heart disease)',
  119: 'costochondritis',
  120: 'Cranial nerve paralysis or cranial neuritis (inflammation of cranial nerves)',
  121: 'cranial neuralgia (cranial nerve pain)',
  122: "Crohn's disease",
  123: 'cyclothymic disorder (mild bipolar disorder)',
  124: "De Quervain's tenosynovitis (De Quervain's syndrome), right",
  125: "De Quervain's tenosynovitis (De Quervain's syndrome), left",
  126: "De Quervain's tenosynovitis (De Quervain's syndrome), bilateral",
  127: 'decompression illness',
  128: 'deep vein thrombosis (DVT) in leg, right',
  129: 'deep vein thrombosis (DVT) in leg, left',
  130: 'deep vein thrombosis (DVT) in leg, bilateral',
  131: 'degenerative arthritis (osteoarthritis) in ankle, right',
  132: 'degenerative arthritis (osteoarthritis) in ankle, left',
  133: 'degenerative arthritis (osteoarthritis) in ankle, bilateral',
  134: 'degenerative arthritis (osteoarthritis) in elbow, right',
  135: 'degenerative arthritis (osteoarthritis) in elbow, left',
  136: 'degenerative arthritis (osteoarthritis) in elbow, bilateral',
  137: 'degenerative arthritis (osteoarthritis) in foot, right',
  138: 'degenerative arthritis (osteoarthritis) in foot, left',
  139: 'degenerative arthritis (osteoarthritis) in foot, bilateral',
  140: 'degenerative arthritis (osteoarthritis) in hand or fingers, right',
  141: 'degenerative arthritis (osteoarthritis) in hand or fingers, left',
  142: 'degenerative arthritis (osteoarthritis) in hand or fingers, bilateral',
  143: 'degenerative arthritis (osteoarthritis) in hip, right',
  144: 'degenerative arthritis (osteoarthritis) in hip, left',
  145: 'degenerative arthritis (osteoarthritis) in hip, bilateral',
  146: 'degenerative arthritis (osteoarthritis) in knee, right',
  147: 'degenerative arthritis (osteoarthritis) in knee, left',
  148: 'degenerative arthritis (osteoarthritis) in knee, bilateral',
  149: 'degenerative arthritis (osteoarthritis) in shoulder, right',
  150: 'degenerative arthritis (osteoarthritis) in shoulder, left',
  151: 'degenerative arthritis (osteoarthritis) in shoulder, bilateral',
  152: 'degenerative arthritis (osteoarthritis) in wrist, right',
  153: 'degenerative arthritis (osteoarthritis) in wrist, left',
  154: 'degenerative arthritis (osteoarthritis) in wrist, bilateral',
  155: 'depression (major depressive disorder)',
  156: 'deviated septum',
  157: 'diabetes insipidus',
  158: 'diabetes, type 1 or type 2',
  159: 'diabetic nephropathy (diabetic kidney disease)',
  160: 'diabetic peripheral neuropathy, right lower extremities',
  161: 'diabetic peripheral neuropathy, right upper extremities',
  162: 'diabetic peripheral neuropathy, left lower extremities',
  163: 'diabetic peripheral neuropathy, left upper extremities',
  164: 'diabetic peripheral neuropathy, bilateral lower extremities',
  165: 'diabetic peripheral neuropathy, bilateral upper extremities',
  166: 'diabetic retinopathy',
  167: 'dry eye syndrome',
  168: "Dupuytren's contracture (abnormal thickening of tissues in palm of hand), right",
  169: "Dupuytren's contracture (abnormal thickening of tissues in palm of hand), left",
  170: "Dupuytren's contracture (abnormal thickening of tissues in palm of hand), bilateral",
  171: 'dysphagia (difficulty swallowing), associated with neurological disorder',
  172: 'dysphagia (difficulty swallowing), not associated with neurological disorder',
  173: 'ear cancer',
  174: 'eczema (atopic dermatitis)',
  175: 'elbow replacement (elbow arthroplasty), right',
  176: 'elbow replacement (elbow arthroplasty), left',
  177: 'elbow replacement (elbow arthroplasty), bilateral',
  178: 'emphysema',
  179: 'endometriosis',
  180: 'enlarged prostate (benign prostatic hyperplasia or BPH)',
  181: 'epididymitis',
  182: 'epiphora (watery eyes)',
  183: 'erectile dysfunction (ED)',
  184: 'esophageal cancer',
  185: 'esophageal stricture (narrowing of esophagus)',
  186: 'eye cancer, including melanoma of the eye',
  187: 'fecal incontinence (loss of bowel control)',
  188: 'female sexual arousal disorder (FSAD)',
  189: 'femoral hernia (hernia in thigh area)',
  190: 'fibromyalgia',
  191: 'flatfoot (pes planus), right',
  192: 'flatfoot (pes planus), left',
  193: 'flatfoot (pes planus), bilateral',
  194: 'foot fracture (tarsal or metatarsal fracture), right',
  195: 'foot fracture (tarsal or metatarsal fracture), left',
  196: 'foot fracture (tarsal or metatarsal fracture), bilateral',
  197: 'frostbite in foot, right',
  198: 'frostbite in foot, left',
  199: 'frostbite in foot, bilateral',
  200: 'frostbite in hand or fingers, right',
  201: 'frostbite in hand or fingers, left',
  202: 'frostbite in hand or fingers, bilateral',
  203: 'gallstones (cholelithiasis)',
  204: "gamekeeper's thumb, right",
  205: "gamekeeper's thumb, left",
  206: "gamekeeper's thumb, bilateral",
  207: 'ganglion cyst in hand or fingers, right',
  208: 'ganglion cyst in hand or fingers, left',
  209: 'ganglion cyst in hand or fingers, bilateral',
  210: 'ganglion cyst in wrist, right',
  211: 'ganglion cyst in wrist, left',
  212: 'ganglion cyst in wrist, bilateral',
  213: 'generalized anxiety disorder (GAD)',
  214: 'GERD (gastroesophageal reflux disease)',
  215: 'glaucoma',
  216: "golfer's elbow (medial epicondylitis), right",
  217: "golfer's elbow (medial epicondylitis), left",
  218: "golfer's elbow (medial epicondylitis), bilateral",
  219: 'gonococcal arthritis',
  220: 'gout in foot, right',
  221: 'gout in foot, left',
  222: 'gout in foot, bilateral',
  223: 'gout in wrist, right',
  224: 'gout in wrist, left',
  225: 'gout in wrist, bilateral',
  226: 'granulomatous disease',
  227: 'greater trochanteric pain syndrome (lateral hip pain), right',
  228: 'greater trochanteric pain syndrome (lateral hip pain), left',
  229: 'greater trochanteric pain syndrome (lateral hip pain), bilateral',
  230: 'hallux rigidus (big toe arthritis), bilateral',
  231: 'hallux rigidus (big toe arthritis), left',
  232: 'hallux rigidus (big toe arthritis), right',
  233: 'hammer toe, right',
  234: 'hammer toe, left',
  235: 'hammer toe, bilateral',
  236: "Hansen's disease (leprosy)",
  237: 'hearing loss, other than tinnitus',
  238: 'heart attack (myocardial infarction)',
  239: 'heart bypass surgery (coronary artery bypass graft)',
  240: 'hemorrhoids',
  241: 'hepatitis B',
  242: 'hepatitis C',
  243: 'herpes (herpes simplex virus or HSV)',
  244: 'hiatal hernia',
  245: 'hip impingement (femoroacetabular impingement or FAI), right',
  246: 'hip impingement (femoroacetabular impingement or FAI), left',
  247: 'hip impingement (femoroacetabular impingement or FAI), bilateral',
  248: 'hip replacement (hip arthroplasty), right',
  249: 'hip replacement (hip arthroplasty), left',
  250: 'hip replacement (hip arthroplasty), bilateral',
  251: 'hip sprain, right',
  252: 'hip sprain, left',
  253: 'hip sprain, bilateral',
  254: 'HIV-related illness',
  255: 'Hodgkin lymphoma',
  256: 'hydrocele, right',
  257: 'hyperhidrosis (excessive sweating)',
  258: 'hypertension (high blood pressure)',
  259: 'hyperthyroidism (overactive thyroid)',
  260: 'hypopharyngeal cancer',
  261: 'hypothyroidism (underactive thyroid)',
  262: 'hysterectomy (removal of uterus)',
  263: 'hysterectomy and ovariectomy (removal of uterus and both ovaries)',
  264: 'illness anxiety disorder (hypochondria)',
  265: 'immersion foot, right',
  266: 'immersion foot, left',
  267: 'immersion foot, bilateral',
  268: 'inguinal hernia (hernia in groin)',
  269: 'interstitial lung disease (ILD), including asbestosis',
  270: 'intervertebral disc syndrome (IVDS), back',
  271: 'intervertebral disc syndrome (IVDS), neck',
  272: 'iron deficiency anemia',
  273: 'irritable bowel syndrome (IBS)',
  274: 'jaw cancer',
  275: 'keratinization skin disorders',
  276: 'kidney cancer (renal cancer), right',
  277: 'kidney cancer (renal cancer), left',
  278: 'kidney cancer (renal cancer), bilateral',
  279: 'kidney removal (nephrectomy)',
  280: 'kidney stones (nephrolithiasis)',
  281: 'kidney transplant',
  282: 'knee hyperextension (genu recurvatum), right',
  283: 'knee hyperextension (genu recurvatum), left',
  284: 'knee hyperextension (genu recurvatum), bilateral',
  285: 'knee instability, right',
  286: 'knee instability, left',
  287: 'knee instability, bilateral',
  288: 'knee or patellar dislocation, right',
  289: 'knee or patellar dislocation, left',
  290: 'knee or patellar dislocation, bilateral',
  291: 'knee or patellar fracture, right',
  292: 'knee or patellar fracture, left',
  293: 'knee or patellar fracture, bilateral',
  294: 'knee replacement (knee arthroplasty), right',
  295: 'knee replacement (knee arthroplasty), left',
  296: 'knee replacement (knee arthroplasty), bilateral',
  297: 'knee strain or sprain, right',
  298: 'knee strain or sprain, left',
  299: 'knee strain or sprain, bilateral',
  300: 'labyrinthitis (type of inner ear infection), right',
  301: 'labyrinthitis (type of inner ear infection), left',
  302: 'labyrinthitis (type of inner ear infection), bilateral',
  303: 'laryngeal cancer (cancer of larynx)',
  304: 'leukemia',
  305: 'liver cancer, including hepatocellular carcinoma (HCC)',
  306: 'loss of both eyes',
  307: 'loss of teeth due to bone loss',
  308: 'lower back sprain (lumbosacral sprain)',
  309: 'lower back strain (lumbosacral strain)',
  310: 'lumbar spinal stenosis (narrowing of spinal canal in lower back)',
  311: 'lung cancer',
  312: 'lupus',
  313: 'lymphatic filariasis',
  314: 'malaria',
  315: 'malignant tumor in spinal cord',
  316: 'mallet finger, right',
  317: 'mallet finger, left',
  318: 'mallet finger, bilateral',
  319: 'melanoma of the skin',
  320: "Meniere's disease",
  321: 'meniscectomy (removal of meniscus), right',
  322: 'meniscectomy (removal of meniscus), left',
  323: 'meniscectomy (removal of meniscus), bilateral',
  324: 'meniscus tear, right',
  325: 'meniscus tear, left',
  326: 'meniscus tear, bilateral',
  327: 'metatarsalgia (pain in ball of foot), right',
  328: 'metatarsalgia (pain in ball of foot), left',
  329: 'metatarsalgia (pain in ball of foot), bilateral',
  330: 'middle back sprain (thoracic sprain)',
  331: 'middle back strain (thoracic strain)',
  332: 'migraines (headaches)',
  333: 'mitral regurgitation',
  334: 'mitral valve prolapse (Barlow syndrome)',
  335: "Morton's neuroma, right",
  336: "Morton's neuroma, left",
  337: "Morton's neuroma, bilateral",
  338: 'multiple myeloma, head or neck',
  339: 'multiple myeloma, extremities or trunk',
  340: 'multiple sclerosis (MS)',
  341: 'muscle hernia',
  342: 'myasthenia gravis',
  343: 'nasopharyngeal cancer',
  344: 'neck sprain (cervical sprain)',
  345: 'neck strain (cervical strain)',
  346: 'nerve-related soft-tissue sarcoma, head or neck',
  347: 'nerve-related soft-tissue sarcoma, extremities or trunk',
  348: 'neurogenic bladder',
  349: 'non-diabetic peripheral neuropathy, right lower extremities',
  350: 'non-diabetic peripheral neuropathy, right upper extremities',
  351: 'non-diabetic peripheral neuropathy, left lower extremities',
  352: 'non-diabetic peripheral neuropathy, left upper extremities',
  353: 'non-diabetic peripheral neuropathy, bilateral lower extremities',
  354: 'non-diabetic peripheral neuropathy, bilateral upper extremities',
  355: 'non-Hodgkin lymphoma',
  356: 'obsessive compulsive disorder (OCD)',
  357: 'oral cavity squamous cell carcinoma',
  358: 'orchitis (inflammation of testicles)',
  359: 'oropharyngeal cancer',
  360: 'osteomyelitis',
  361: 'otitis media (middle ear infection), right',
  362: 'otitis media (middle ear infection), left',
  363: 'otitis media (middle ear infection), bilateral',
  364: 'ovarian adhesions',
  365: 'ovarian cancer, right',
  366: 'ovarian cancer, left',
  367: 'ovarian cancer, bilateral',
  368: 'ovarian cysts',
  369: 'ovariectomy (removal of one or both ovaries)',
  370: 'pancreatic cancer',
  371: 'panic disorder',
  372: 'paranasal sinus and nasal cavity cancer',
  373: "Parkinson's disease",
  374: 'patellar or quadriceps tendon rupture, right',
  375: 'patellar or quadriceps tendon rupture, left',
  376: 'patellar or quadriceps tendon rupture, bilateral',
  377: 'patellofemoral pain syndrome, right',
  378: 'patellofemoral pain syndrome, left',
  379: 'patellofemoral pain syndrome, bilateral',
  380: 'PCL tear (posterior cruciate ligament tear), right',
  381: 'PCL tear (posterior cruciate ligament tear), left',
  382: 'PCL tear (posterior cruciate ligament tear), bilateral',
  383: 'penile cancer',
  384: 'perforated eardrum (perforated tympanic membrane), right',
  385: 'perforated eardrum (perforated tympanic membrane), left',
  386: 'perforated eardrum (perforated tympanic membrane), bilateral',
  387: 'persistent depressive disorder (dysthymic disorder)',
  388: 'pharyngeal cancer (throat cancer) ',
  389: 'plantar fasciitis, left',
  390: 'plantar fasciitis, right',
  391: 'plantar fasciitis, bilateral',
  392: 'plantar warts (foot warts), right',
  393: 'plantar warts (foot warts), left',
  394: 'plantar warts (foot warts), bilateral',
  395: 'pleurisy (pleuritis) ',
  396: 'pneumococcal arthritis',
  397: 'polycystic ovary syndrome (PCOS)',
  398: 'post-traumatic arthritis in ankle, right',
  399: 'post-traumatic arthritis in ankle, left',
  400: 'post-traumatic arthritis in ankle, bilateral',
  401: 'post-traumatic arthritis in elbow, right',
  402: 'post-traumatic arthritis in elbow, left',
  403: 'post-traumatic arthritis in elbow, bilateral',
  404: 'post-traumatic arthritis in foot, right',
  405: 'post-traumatic arthritis in foot, left',
  406: 'post-traumatic arthritis in foot, bilateral',
  407: 'post-traumatic arthritis in hand or fingers, right',
  408: 'post-traumatic arthritis in hand or fingers, left',
  409: 'post-traumatic arthritis in hand or fingers, bilateral',
  410: 'post-traumatic arthritis in hip, right',
  411: 'post-traumatic arthritis in hip, left',
  412: 'post-traumatic arthritis in hip, bilateral',
  413: 'post-traumatic arthritis in knee, right',
  414: 'post-traumatic arthritis in knee, left',
  415: 'post-traumatic arthritis in knee, bilateral',
  416: 'post-traumatic arthritis in shoulder, right',
  417: 'post-traumatic arthritis in shoulder, left',
  418: 'post-traumatic arthritis in shoulder, bilateral',
  419: 'post-traumatic arthritis in wrist, right',
  420: 'post-traumatic arthritis in wrist, left',
  421: 'post-traumatic arthritis in wrist, bilateral',
  422: 'poststreptococcal arthritis',
  423: 'premature ventricular contractions',
  424: 'proctitis (inflammation of rectum)',
  425: 'prostate cancer',
  426: 'prostatitis (inflammation of prostate)',
  427: 'pseudofolliculitis barbae (razor bumps, shave bumps, or ingrown hairs)',
  428: 'psoriasis',
  429: 'PTSD (post-traumatic stress disorder), combat-related',
  430: 'PTSD (post-traumatic stress disorder), non-combat-related',
  431: 'pulmonary fibrosis',
  432: 'pulmonary granuloma (lung nodule)  ',
  433: 'radiculopathy, right lower extremities',
  434: 'radiculopathy, left lower extremities',
  435: 'radiculopathy, bilateral lower extremities',
  436: 'radiculopathy, right upper extremities',
  437: 'radiculopathy, left upper extremities',
  438: 'radiculopathy, bilateral upper extremities',
  439: "Raynaud's disease",
  440: 'rheumatoid arthritis',
  441: 'rib fracture, right',
  442: 'rib fracture, left',
  443: 'rib fracture, bilateral',
  444: 'rib removal',
  445: 'right ventricular hypertrophy (RVH)',
  446: 'left ventricular hypertrophy (LVH)',
  447: 'biventricular hypertrophy',
  448: 'ringworm (dermatophytosis)',
  449: 'rotator cuff tear, right',
  450: 'rotator cuff tear, left',
  451: 'rotator cuff tear, bilateral',
  452: 'salivary gland cancer',
  453: 'sarcoidosis',
  454: 'scars, extremities or trunk',
  455: 'scars, head, face or neck',
  456: 'schizophrenia',
  457: 'shin splints, right',
  458: 'shin splints, left',
  459: 'shin splints, bilateral',
  460: 'shoulder dislocation, right',
  461: 'shoulder dislocation, left',
  462: 'shoulder dislocation, bilateral',
  463: 'shoulder impingement syndrome, right',
  464: 'shoulder impingement syndrome, left',
  465: 'shoulder impingement syndrome, bilateral',
  466: 'shoulder replacement (shoulder arthroplasty), right',
  467: 'shoulder replacement (shoulder arthroplasty), left',
  468: 'shoulder replacement (shoulder arthroplasty), bilateral',
  469: 'shoulder strain, right',
  470: 'shoulder strain, left',
  471: 'shoulder strain, bilateral',
  472: 'sickle cell anemia',
  473: 'SLAP tear (superior labral anterior to posterior tear), right',
  474: 'SLAP tear (superior labral anterior to posterior), left',
  475: 'SLAP tear (superior labral anterior to posterior tear), bilateral',
  476: 'sleep apnea',
  477: 'small intestine cancer',
  478: 'soft-tissue sarcoma of muscle, fat, or fibrous connective tissue, head or neck',
  479: 'soft-tissue sarcoma of muscle, fat, or fibrous connective tissue, extremities or trunk',
  480: 'somatic symptom disorder (SSD)',
  481: 'spinal arthritis, back',
  482: 'spinal arthritis, neck',
  483: 'spondylolisthesis, back',
  484: 'spondylolisthesis, neck',
  485: 'squamous cell carcinoma of the skin, head or neck ',
  486: 'squamous cell carcinoma of the skin, extremities or trunk',
  487: 'stomach cancer',
  488: 'stress fracture in leg, right',
  489: 'stress fracture in leg, left',
  490: 'stress fracture in leg, bilateral',
  491: 'syphilitic arthritis',
  492: 'tachycardia',
  493: 'tailbone (coccyx) removal',
  494: 'temporomandibular disorder, including TMJ',
  495: 'tendinosis in hand or fingers, right',
  496: 'tendinosis in hand or fingers, left',
  497: 'tendinosis in hand or fingers, bilateral',
  498: 'tendonitis (tendinitis) in ankle, right',
  499: 'tendonitis (tendinitis) in ankle, left',
  500: 'tendonitis (tendinitis) in ankle, bilateral',
  501: 'tendonitis (tendinitis) in elbow, right',
  502: 'tendonitis (tendinitis) in elbow, left',
  503: 'tendonitis (tendinitis) in elbow, bilateral',
  504: 'tendonitis (tendinitis) in foot, right',
  505: 'tendonitis (tendinitis) in foot, left',
  506: 'tendonitis (tendinitis) in foot, bilateral',
  507: 'tendonitis (tendinitis) in hand or fingers, right',
  508: 'tendonitis (tendinitis) in hand or fingers, left',
  509: 'tendonitis (tendinitis) in hand or fingers, bilateral',
  510: 'tendonitis (tendinitis) in hip, right',
  511: 'tendonitis (tendinitis) in hip, left',
  512: 'tendonitis (tendinitis) in hip, bilateral',
  513: 'tendonitis (tendinitis) in knee, right',
  514: 'tendonitis (tendinitis) in knee, left',
  515: 'tendonitis (tendinitis) in knee, bilateral',
  516: 'tendonitis (tendinitis) in shoulder, right',
  517: 'tendonitis (tendinitis) in shoulder, left',
  518: 'tendonitis (tendinitis) in shoulder, bilateral',
  519: 'tendonitis (tendinitis) in wrist, right',
  520: 'tendonitis (tendinitis) in wrist, left',
  521: 'tendonitis (tendinitis) in wrist, bilateral',
  522: 'tennis elbow (lateral epicondylitis), right',
  523: 'tennis elbow (lateral epicondylitis), left',
  524: 'tennis elbow (lateral epicondylitis), bilateral',
  525: 'tenosynovitis in hand or fingers, right',
  526: 'tenosynovitis in hand or fingers, left',
  527: 'tenosynovitis in hand or fingers, bilateral',
  528: 'tenosynovitis in wrist, right',
  529: 'tenosynovitis in wrist, left',
  530: 'tenosynovitis in wrist, bilateral',
  531: 'testicular cancer, right',
  532: 'testicular cancer, left',
  533: 'testicular cancer, bilateral',
  534: 'thyroid cancer',
  535: 'tibia or fibula fracture, right',
  536: 'tibia or fibula fracture, left',
  537: 'tibia or fibula fracture, bilateral',
  538: 'Tietze syndrome',
  539: 'tinnitus (ringing or hissing in ears)',
  540: 'tongue cancer',
  541: 'trachea cancer (cancer of windpipe)',
  542: 'traumatic brain injury (TBI)',
  543: 'trigger finger, right',
  544: 'trigger finger, left',
  545: 'trigger finger, bilateral',
  546: 'typhoid arthritis',
  547: 'ulcerative colitis',
  548: 'ureteral cancer (ureter cancer)',
  549: 'urethritis',
  550: 'urinary incontinence (loss of bladder control)',
  551: 'uterine cancer',
  552: 'vaginal cancer',
  553: 'varicocele, right',
  554: 'varicocele, left',
  555: 'varicocele, bilateral',
  556: 'varicose veins in leg',
  557: 'varicose veins, other than in leg',
  558: 'vascular soft-tissue sarcoma, including angiosarcoma, head or neck ',
  559: 'vascular soft-tissue sarcoma, including angiosarcoma, extremities or trunk',
  560: 'ventral hernia (hernia in abdomen)',
  561: 'visual impairment, including blurry vision, blindness and double vision',
  562: 'vitiligo',
  563: 'vulvar cancer',
  564: 'weak foot, bilateral',
  565: 'Wolff-Parkinson-White syndrome',
  566: 'wrist fracture, right',
  567: 'wrist fracture, left',
  568: 'wrist fracture, bilateral',
  569: 'wrist replacement (wrist arthroplasty), right',
  570: 'wrist replacement (wrist arthroplasty), left',
  571: 'wrist replacement (wrist arthroplasty), bilateral',
  572: 'wrist sprain, right',
  573: 'wrist sprain, left',
  574: 'wrist sprain, bilateral',
};
