const revisedDisabilityLabels = {
  1: 'ACL (anterior cruciate ligament) tear, bilateral',
  2: 'ACL (anterior cruciate ligament) tear, left',
  3: 'ACL (anterior cruciate ligament) tear, right',
  4: 'acne',
  5: 'adjustment disorder',
  6: 'agoraphobia',
  7: 'alopecia',
  8: 'amyotrophic lateral sclerosis (ALS)',
  9: 'anal or perianal fistula (fistula-in-ano)',
  10: 'anatomical loss of both eyes',
  11: 'anemia',
  12: 'ankle replacement (arthroplasty), bilateral',
  13: 'ankle replacement (arthroplasty), left',
  14: 'ankle replacement (arthroplasty), right',
  15: 'ankylosis in ankle, bilateral',
  16: 'ankylosis in ankle, left',
  17: 'ankylosis in ankle, right',
  18: 'ankylosis in elbow, bilateral',
  19: 'ankylosis in elbow, left',
  20: 'ankylosis in elbow, right',
  21: 'ankylosis in hand or fingers, bilateral',
  22: 'ankylosis in hand or fingers, left',
  23: 'ankylosis in hand or fingers, right',
  24: 'ankylosis in hip, bilateral',
  25: 'ankylosis in hip, left',
  26: 'ankylosis in hip, right',
  27: 'ankylosis in knee, bilateral',
  28: 'ankylosis in knee, left',
  29: 'ankylosis in knee, right',
  30: 'ankylosis in shoulder, bilateral',
  31: 'ankylosis in shoulder, left',
  32: 'ankylosis in shoulder, right',
  33: 'ankylosis in wrist, bilateral',
  34: 'ankylosis in wrist, left',
  35: 'ankylosis in wrist, right',
  36: 'anorexia (type of eating disorder)',
  37: 'aortic insufficiency (aortic regurgitation)',
  38: 'aortic valve disease',
  39: 'arrhythmia',
  40: 'asthma',
  41: 'astragalectomy (talectomy)',
  42: "athlete's foot (tinea pedis)",
  43: 'atrial fibrillation (A-fib)',
  44: 'back spondylolisthesis',
  45: 'back stenosis (lumbar spinal stenosis)',
  46: 'benign prostatic hyperplasia (BPH or enlarged prostate)',
  47: 'bipolar disorder',
  48: 'biventricular hypertrophy',
  49: 'bladder cancer',
  50: 'bladder stones',
  51: 'bulimia (type of eating disorder)',
  52: 'bunions (hallux valgus), bilateral',
  53: 'bunions (hallux valgus), left',
  54: 'bunions (hallux valgus), right',
  55: 'bursitis in ankle, bilateral',
  56: 'bursitis in ankle, left',
  57: 'bursitis in ankle, right',
  58: 'bursitis in elbow, bilateral',
  59: 'bursitis in elbow, left',
  60: 'bursitis in elbow, right',
  61: 'bursitis in foot, bilateral',
  62: 'bursitis in foot, left',
  63: 'bursitis in foot, right',
  64: 'bursitis in hip, bilateral',
  65: 'bursitis in hip, left',
  66: 'bursitis in hip, right',
  67: 'bursitis in knee, bilateral',
  68: 'bursitis in knee, left',
  69: 'bursitis in knee, right',
  70: 'bursitis in shoulder, bilateral',
  71: 'bursitis in shoulder, left',
  72: 'bursitis in shoulder, right',
  73: 'carpal tunnel syndrome, bilateral',
  74: 'carpal tunnel syndrome, left',
  75: 'carpal tunnel syndrome, right',
  76: 'chloracne',
  77: 'cholelithiasis (gallstones)',
  78: 'chronic bronchitis',
  79: 'chronic conjunctivitis (pink eye)',
  80: 'chronic fatigue syndrome',
  81: 'chronic kidney disease (CKD)',
  82: 'chronic laryngitis',
  83: 'chronic nephritis (inflammation of kidneys)',
  84: 'chronic obstructive pulmonary disease (COPD)',
  85: "chronic otitis externa (swimmer's ear), bilateral",
  86: "chronic otitis externa (swimmer's ear), left",
  87: "chronic otitis externa (swimmer's ear), right",
  88: 'chronic suppurative otitis media (CSOM) or mastoiditis, bilateral',
  89: 'chronic suppurative otitis media (CSOM) or mastoiditis, left',
  90: 'chronic suppurative otitis media (CSOM) or mastoiditis, right',
  91: 'cirrhosis of liver',
  92: 'claw foot (pes cavus), bilateral',
  93: 'claw foot (pes cavus), left',
  94: 'claw foot (pes cavus), right',
  95: 'colon cancer',
  96: 'complete loss of sense of smell (anosmia)',
  97: 'complete loss of sense of taste (ageusia)',
  98: 'congestive heart failure (CHF)',
  99: 'coronary artery disease (CAD or arteriosclerotic heart disease)',
  100: 'costochondritis',
  101: "Crohn's disease",
  102: 'cyclothymic disorder',
  103: 'decompression illness',
  104: 'deep vein thrombosis (DVT) in leg, left',
  105: 'deep vein thrombosis (DVT) in leg, right',
  106: 'deep vein thrombosis (DVT) in legs, bilateral',
  107: 'degenerative arthritis (osteoarthritis) in ankle, bilateral',
  108: 'degenerative arthritis (osteoarthritis) in ankle, left',
  109: 'degenerative arthritis (osteoarthritis) in ankle, right',
  110: 'degenerative arthritis (osteoarthritis) in elbow, bilateral',
  111: 'degenerative arthritis (osteoarthritis) in elbow, left',
  112: 'degenerative arthritis (osteoarthritis) in elbow, right',
  113: 'degenerative arthritis (osteoarthritis) in foot, bilateral',
  114: 'degenerative arthritis (osteoarthritis) in foot, left',
  115: 'degenerative arthritis (osteoarthritis) in foot, right',
  116: 'degenerative arthritis (osteoarthritis) in hip, bilateral',
  117: 'degenerative arthritis (osteoarthritis) in hip, left',
  118: 'degenerative arthritis (osteoarthritis) in hip, right',
  119: 'degenerative arthritis (osteoarthritis) in knee, bilateral',
  120: 'degenerative arthritis (osteoarthritis) in knee, left',
  121: 'degenerative arthritis (osteoarthritis) in knee, right',
  122: 'degenerative arthritis (osteoarthritis) in shoulder, bilateral',
  123: 'degenerative arthritis (osteoarthritis) in shoulder, left',
  124: 'degenerative arthritis (osteoarthritis) in shoulder, right',
  125: 'depression (major depressive disorder)',
  126: 'dermatophytosis',
  127: 'deviated septum',
  128: 'diabetes (diabetes mellitus)',
  129: 'diabetes insipidus',
  130: 'diabetic nephropathy',
  131: 'diabetic peripheral neuropathy, bilateral lower extremities',
  132: 'diabetic peripheral neuropathy, bilateral upper extremities',
  133: 'diabetic peripheral neuropathy, left lower extremities',
  134: 'diabetic peripheral neuropathy, left upper extremities',
  135: 'diabetic peripheral neuropathy, right lower extremities',
  136: 'diabetic peripheral neuropathy, right upper extremities',
  137: 'diabetic retinopathy',
  138: 'dry eye syndrome (watery eyes)',
  139: 'dysphagia (difficulty swallowing)',
  140: 'dysthymic disorder',
  141: 'eczema (atopic dermatitis)',
  142: 'elbow replacement (arthroplasty), bilateral',
  143: 'elbow replacement (arthroplasty), left',
  144: 'elbow replacement (arthroplasty), right',
  145: 'endometriosis',
  146: 'epididymitis',
  147: 'erectile dysfunction (ED)',
  148: 'esophageal cancer',
  149: 'esophageal stricture',
  150: 'fecal incontinence',
  151: 'female sexual arousal disorder (FSAD)',
  152: 'femoral hernia',
  153: 'fibromyalgia',
  154: 'flatfoot (pes planus), bilateral',
  155: 'flatfoot (pes planus), left',
  156: 'flatfoot (pes planus), right',
  157: 'foot fracture (tarsal or metatarsal bones), bilateral',
  158: 'foot fracture (tarsal or metatarsal bones), left',
  159: 'foot fracture (tarsal or metatarsal bones), right',
  160: 'generalized anxiety disorder (GAD)',
  161: 'GERD',
  162: 'glaucoma',
  163: 'gonococcal arthritis',
  164: 'gout in foot, bilateral',
  165: 'gout in foot, left',
  166: 'gout in foot, right',
  167: 'hallux rigidus, bilateral',
  168: 'hallux rigidus, left',
  169: 'hallux rigidus, right',
  170: 'hammer toe(s), bilateral',
  171: 'hammer toe(s), left',
  172: 'hammer toe(s), right',
  173: "Hansen's disease (leprosy)",
  174: 'hearing loss, other than tinnitus',
  175: 'heart attack (myocardial infarction)',
  176: 'heart bypass surgery (coronary artery bypass graft)',
  177: 'heart murmur',
  178: 'hemorrhoids',
  179: 'hepatitis B',
  180: 'hepatitis C',
  181: 'herpes simplex virus (HSV, herpes) ',
  182: 'hiatal hernia',
  183: 'hip impingement (femoroacetabular impingement or FAI), bilateral',
  184: 'hip impingement (femoroacetabular impingement or FAI), left',
  185: 'hip impingement (femoroacetabular impingement or FAI), right',
  186: 'hip replacement (arthroplasty), bilateral',
  187: 'hip replacement (arthroplasty), left',
  188: 'hip replacement (arthroplasty), right',
  189: 'HIV-related illness',
  190: 'Hodgkin lymphoma',
  191: 'hydrocele, bilateral',
  192: 'hydrocele, left',
  193: 'hydrocele, right',
  194: 'hyperhidrosis',
  195: 'hypertension (high blood pressure)',
  196: 'hyperthyroidism (type of thyroid condition)',
  197: 'hypothyroidism (type of thyroid condition)',
  198: 'hysterectomy (removal of uterus)',
  199: 'hysterectomy and ovariectomy (removal of uterus and both ovaries)',
  200: 'illness anxiety disorder (hypochondria)',
  201: 'inguinal hernia',
  202: 'intervertebral disc syndrome (IVDS), back',
  203: 'intervertebral disc syndrome (IVDS), neck',
  204: 'iron deficiency anemia',
  205: 'irritable bowel syndrome (IBS)',
  206: 'keratinization skin disorders',
  207: 'kidney (renal) cancer',
  208: 'kidney removal (nephrectomy)',
  209: 'kidney stones (nephrolithiasis)',
  210: 'kidney transplant',
  211: 'knee fracture (including patellar fracture), bilateral',
  212: 'knee fracture (including patellar fracture), left',
  213: 'knee fracture (including patellar fracture), right',
  214: 'knee hyperextension (genu recurvatum), bilateral',
  215: 'knee hyperextension (genu recurvatum), left',
  216: 'knee hyperextension (genu recurvatum), right',
  217: 'knee instability, bilateral',
  218: 'knee instability, left',
  219: 'knee instability, right',
  220: 'knee or patellar dislocation, bilateral',
  221: 'knee or patellar dislocation, left',
  222: 'knee or patellar dislocation, right',
  223: 'knee replacement (arthroplasty), bilateral',
  224: 'knee replacement (arthroplasty), left',
  225: 'knee replacement (arthroplasty), right',
  226: 'knee strain or sprain, bilateral',
  227: 'knee strain or sprain, left',
  228: 'knee strain or sprain, right',
  229: 'labyrinthitis, bilateral',
  230: 'labyrinthitis, left',
  231: 'labyrinthitis, right',
  232: 'laryngeal (larynx) cancer',
  233: 'lateral epicondylitis (tennis elbow), bilateral',
  234: 'lateral epicondylitis (tennis elbow), left',
  235: 'lateral epicondylitis (tennis elbow), right',
  236: 'leukemia',
  237: 'liver cancer, including hepatocellular carcinoma (HCC)',
  238: 'loss of teeth due to bone loss',
  239: 'lower back sprain (lumbosacral sprain)',
  240: 'lower back strain (lumbosacral strain)',
  241: 'lung and bronchus cancer',
  242: 'lupus',
  243: 'lymphatic filariasis',
  244: 'malaria',
  245: "medial epicondylitis (golfer's elbow), bilateral",
  246: "medial epicondylitis (golfer's elbow), left",
  247: "medial epicondylitis (golfer's elbow), right",
  248: "Meniere's disease",
  249: 'meniscectomy (removal of meniscus), bilateral',
  250: 'meniscectomy (removal of meniscus), left',
  251: 'meniscectomy (removal of meniscus), right',
  252: 'meniscus tear, bilateral',
  253: 'meniscus tear, left',
  254: 'meniscus tear, right',
  255: 'metatarsalgia, bilateral',
  256: 'metatarsalgia, left',
  257: 'metatarsalgia, right',
  258: 'middle back sprain (thoracic sprain)',
  259: 'middle back strain (thoracic strain)',
  260: 'migraines (headaches)',
  261: 'mitral regurgitation',
  262: 'mitral valve prolapse (Barlow syndrome)',
  263: 'mood disorder',
  264: "Morton's neuroma, bilateral",
  265: "Morton's neuroma, left",
  266: "Morton's neuroma, right",
  267: 'mouth cancer',
  268: 'multiple sclerosis (MS)',
  269: 'muscle hernia',
  270: 'myasthenia gravis',
  271: 'nasopharyngeal cancer',
  272: 'neck spondylolisthesis',
  273: 'neck sprain (cervical sprain)',
  274: 'neck stenosis (cervical spinal stenosis)',
  275: 'neck strain (cervical strain)',
  276: 'neuralgia, cranial nerves',
  277: 'neurogenic bladder',
  278: 'non-Hodgkin lymphoma',
  279: 'obsessive compulsive disorder (OCD)',
  280: 'orchitis',
  281: 'osteomyelitis',
  282: 'otitis media (middle ear infection), bilateral',
  283: 'otitis media (middle ear infection), left',
  284: 'otitis media (middle ear infection), right',
  285: 'ovarian adhesions',
  286: 'ovarian cysts',
  287: 'ovariectomy (removal of one or both ovaries)',
  288: 'pancreatic cancer',
  289: 'panic disorder',
  290: 'paralysis or neuritis (inflammation), cranial nerves',
  291: "Parkinson's disease",
  292: 'patellar or quadriceps tendon rupture, bilateral',
  293: 'patellar or quadriceps tendon rupture, left',
  294: 'patellar or quadriceps tendon rupture, right',
  295: 'patellofemoral pain syndrome, bilateral',
  296: 'patellofemoral pain syndrome, left',
  297: 'patellofemoral pain syndrome, right',
  298: 'PCL (posterior cruciate ligament) tear, bilateral',
  299: 'PCL (posterior cruciate ligament) tear, left',
  300: 'PCL (posterior cruciate ligament) tear, right',
  301: 'penile cancer',
  302: 'perforated eardrum (tympanic membrane), bilateral',
  303: 'perforated eardrum (tympanic membrane), left',
  304: 'perforated eardrum (tympanic membrane), right',
  305: 'peripheral neuropathy, not due to diabetes, bilateral lower extremities',
  306: 'peripheral neuropathy, not due to diabetes, bilateral upper extremities',
  307: 'peripheral neuropathy, not due to diabetes, left lower extremities',
  308: 'peripheral neuropathy, not due to diabetes, left upper extremities',
  309: 'peripheral neuropathy, not due to diabetes, right lower extremities',
  310: 'peripheral neuropathy, not due to diabetes, right upper extremities',
  311: 'pharyngeal cancer (throat cancer) ',
  312: 'plantar fasciitis, bilateral',
  313: 'plantar fasciitis, left',
  314: 'plantar fasciitis, right',
  315: 'plantar warts (foot warts), bilateral ',
  316: 'plantar warts (foot warts), left ',
  317: 'plantar warts (foot warts), right',
  318: 'pneumococcal arthritis',
  319: 'pneumonia',
  320: 'polycystic ovary syndrome (PCOS)',
  321: 'post-traumatic arthritis in ankle, bilateral',
  322: 'post-traumatic arthritis in ankle, left',
  323: 'post-traumatic arthritis in ankle, right',
  324: 'post-traumatic arthritis in elbow, bilateral',
  325: 'post-traumatic arthritis in elbow, left',
  326: 'post-traumatic arthritis in elbow, right',
  327: 'post-traumatic arthritis in foot, bilateral',
  328: 'post-traumatic arthritis in foot, left',
  329: 'post-traumatic arthritis in foot, right',
  330: 'post-traumatic arthritis in hip, bilateral',
  331: 'post-traumatic arthritis in hip, left',
  332: 'post-traumatic arthritis in hip, right',
  333: 'post-traumatic arthritis in knee, bilateral',
  334: 'post-traumatic arthritis in knee, left',
  335: 'post-traumatic arthritis in knee, right',
  336: 'post-traumatic arthritis in shoulder, bilateral',
  337: 'post-traumatic arthritis in shoulder, left',
  338: 'post-traumatic arthritis in shoulder, right',
  339: 'poststreptococcal arthritis',
  340: 'premature ventricular contractions',
  341: 'proctitis',
  342: 'prostate cancer',
  343: 'prostatitis (infection of the prostate)',
  344: 'pseudofolliculitis barbae (razor bumps, shave bumps, ingrown hairs)',
  345: 'psoriasis',
  346: 'PTSD (post-traumatic stress disorder), combat-related',
  347: 'PTSD (post-traumatic stress disorder), non-combat-related including sexual trauma or personal assault',
  348: 'radiculopathy, bilateral lower extremities',
  349: 'radiculopathy, bilateral upper extremities',
  350: 'radiculopathy, left lower extremities',
  351: 'radiculopathy, left upper extremities',
  352: 'radiculopathy, right lower extremities',
  353: 'radiculopathy, right upper extremities',
  354: "Raynaud's disease",
  355: 'rectal cancer',
  356: 'rheumatoid arthritis',
  357: 'rhinitis',
  358: 'rib fracture, bilateral',
  359: 'rib fracture, left',
  360: 'rib fracture, right',
  361: 'rib removal',
  362: 'rotator cuff tear, bilateral',
  363: 'rotator cuff tear, left',
  364: 'rotator cuff tear, right',
  365: 'scars, extremities or trunk',
  366: 'scars, head, face or neck',
  367: 'schizophrenia',
  368: 'shin splints, bilateral',
  369: 'shin splints, left',
  370: 'shin splints, right',
  371: 'shoulder dislocation, bilateral',
  372: 'shoulder dislocation, left',
  373: 'shoulder dislocation, right',
  374: 'shoulder impingement syndrome, bilateral',
  375: 'shoulder impingement syndrome, left',
  376: 'shoulder impingement syndrome, right',
  377: 'shoulder joint replacement (arthroplasty), bilateral',
  378: 'shoulder joint replacement (arthroplasty), left',
  379: 'shoulder joint replacement (arthroplasty), right',
  380: 'shoulder strain, bilateral',
  381: 'shoulder strain, left',
  382: 'shoulder strain, right',
  383: 'sickle cell anemia',
  384: 'sinusitis (sinus infection)',
  385: 'SLAP (superior labral anterior to posterior) tear, bilateral',
  386: 'SLAP (superior labral anterior to posterior) tear, left',
  387: 'SLAP (superior labral anterior to posterior) tear, right',
  388: 'sleep apnea',
  389: 'somatic symptom disorder (SSD)',
  390: 'spinal arthritis, back',
  391: 'spinal arthritis, neck',
  392: 'stomach cancer',
  393: 'stress fracture in leg, bilateral',
  394: 'stress fracture in leg, left',
  395: 'stress fracture in leg, right',
  396: 'syphilitic arthritis',
  397: 'tachycardia',
  398: 'tailbone (coccyx) removal',
  399: 'temporomandibular disorder, including TMJ',
  400: 'tendinitis (tendonitis) in ankle, bilateral',
  401: 'tendinitis (tendonitis) in ankle, left',
  402: 'tendinitis (tendonitis) in ankle, right',
  403: 'tendinitis (tendonitis) in elbow, bilateral',
  404: 'tendinitis (tendonitis) in elbow, left',
  405: 'tendinitis (tendonitis) in elbow, right',
  406: 'tendinitis (tendonitis) in foot, bilateral',
  407: 'tendinitis (tendonitis) in foot, left',
  408: 'tendinitis (tendonitis) in foot, right',
  409: 'tendinitis (tendonitis) in hip, bilateral',
  410: 'tendinitis (tendonitis) in hip, left',
  411: 'tendinitis (tendonitis) in hip, right',
  412: 'tendinitis (tendonitis) in knee, bilateral',
  413: 'tendinitis (tendonitis) in knee, left',
  414: 'tendinitis (tendonitis) in knee, right',
  415: 'tendinitis (tendonitis) in shoulder, bilateral',
  416: 'tendinitis (tendonitis) in shoulder, left',
  417: 'tendinitis (tendonitis) in shoulder, right',
  418: 'testicular cancer',
  419: 'tibia or fibula fracture, bilateral',
  420: 'tibia or fibula fracture, left',
  421: 'tibia or fibula fracture, right',
  422: 'Tietze syndrome',
  423: 'tinnitus (ringing in the ears)',
  424: 'tongue cancer',
  425: 'trachea cancer (tracheal cancer and windpipe cancer)',
  426: 'traumatic brain injury (TBI)',
  427: 'trochanteric pain syndrome (lateral hip pain), bilateral',
  428: 'trochanteric pain syndrome (lateral hip pain), left',
  429: 'trochanteric pain syndrome (lateral hip pain), right',
  430: 'typhoid arthritis',
  431: 'ulcerative colitis',
  432: 'ureter (ureteral cancer)',
  433: 'urethritis',
  434: 'urinary incontinence (loss of bladder control)',
  435: 'urticaria (hives)',
  436: 'varicocele, bilateral',
  437: 'varicocele, left',
  438: 'varicocele, right',
  439: 'varicose veins in leg',
  440: 'varicose veins, other than in leg',
  441: 'ventral hernia',
  442: 'ventricular hypertrophy, left',
  443: 'ventricular hypertrophy, right',
  444: 'visual impairment, including blurry vision, blindness and double vision',
  445: 'vitiligo',
  446: 'weak foot, bilateral',
  447: 'Wolff-Parkinson-White syndrome',
  448: 'wrist replacement (arthroplasty), bilateral',
  449: 'wrist replacement (arthroplasty), left',
  450: 'wrist replacement (arthroplasty), right',
};

export const getDisabilityLabels = () => {
  return revisedDisabilityLabels;
};
