import React from 'react';
import PropTypes from 'prop-types';
import { formatDateLong } from '@department-of-veterans-affairs/platform-utilities/exports';
import { useSelector } from 'react-redux';
import moment from 'moment';
import { generatePdf } from '@department-of-veterans-affairs/platform-pdf/exports';
import PrintHeader from '../shared/PrintHeader';
import { mhvUrl } from '~/platform/site-wide/mhv/utilities';
import { isAuthenticatedWithSSOe } from '~/platform/user/authentication/selectors';
import PrintDownload from '../shared/PrintDownload';
import { nameFormat, sendErrorToSentry } from '../../util/helpers';

const MicroDetails = props => {
  const { record, fullState } = props;
  const user = useSelector(state => state.user.profile);
  const name = nameFormat(user.userFullName);
  const dob = formatDateLong(user.dob);

  const generateMicrobiologyPdf = async () => {
    const pdfData = {
      headerLeft: name,
      headerRight: `Date of birth: ${dob}`,
      headerBanner: [
        {
          text:
            'If you’re ever in crisis and need to talk with someone right away, call the Veterans Crisis line at 988. Then select 1.',
        },
      ],
      footerLeft: `Report generated by My HealtheVet and VA on ${moment().format(
        'LL',
      )}`,
      footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
      title: `Lab and test results: Microbiology on ${record.date}`,
      subject: 'VA Medical Record',
      preface:
        'If you have any questions about these results, send a secure message to your care team.',
      results: {
        sectionSeparators: false,
        items: [
          {
            header: 'Details about this test',
            items: [
              {
                title: 'Sample tested',
                value: record.sampleTested,
                inline: true,
              },
              {
                title: 'Sample from',
                value: record.sampleFrom,
                inline: true,
              },
              {
                title: 'Ordered by',
                value: record.orderedBy,
                inline: true,
              },
              {
                title: 'Ordering location',
                value: record.orderingLocation,
                inline: true,
              },
              {
                title: 'Collecting location',
                value: record.collectingLocation,
                inline: true,
              },
              {
                title: 'Lab location',
                value: record.labLocation,
                inline: true,
              },
              {
                title: 'Date completed',
                value: formatDateLong(record.date),
                inline: true,
              },
            ],
          },
          {
            header: 'Results',
            items: [
              {
                title: '',
                value: record.results,
                inline: true,
              },
            ],
          },
        ],
      },
    };

    try {
      await generatePdf('medicalRecords', 'microbiology_report', pdfData);
    } catch (error) {
      sendErrorToSentry(error, 'Microbiology details');
    }
  };

  const content = () => {
    if (record) {
      return (
        <>
          <PrintHeader />
          <h1 className="vads-u-margin-bottom--0">{record.name}</h1>
          <section className="set-width-486">
            <div className="time-header">
              <h2 className="vads-u-font-size--base vads-u-font-family--sans">
                Date:{' '}
              </h2>
              <p>{record.date}</p>
            </div>
            <div className="no-print">
              <PrintDownload list download={generateMicrobiologyPdf} />
              <va-additional-info trigger="What to know about downloading records">
                <ul>
                  <li>
                    <strong>If you’re on a public or shared computer,</strong>{' '}
                    print your records instead of downloading. Downloading will
                    save a copy of your records to the public computer.
                  </li>
                  <li>
                    <strong>If you use assistive technology,</strong> a Text
                    file (.txt) may work better for technology such as screen
                    reader, screen enlargers, or Braille displays.
                  </li>
                </ul>
              </va-additional-info>
            </div>
            <div className="test-details-container max-80">
              <h2>Details about this test</h2>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Sample tested
              </h3>
              <p>{record.sampleTested}</p>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Sample from
              </h3>
              <p>{record.sampleFrom}</p>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Ordered by
              </h3>
              <p>{record.orderedBy}</p>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Ordering location
              </h3>
              <p>{record.orderingLocation}</p>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Collecting location
              </h3>
              <p>{record.collectingLocation}</p>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Lab location
              </h3>
              <p>{record.labLocation}</p>
              <h3 className="vads-u-font-size--base vads-u-font-family--sans">
                Date completed
              </h3>
              <p>{record.date}</p>
            </div>

            <div className="test-results-container">
              <h2>Results</h2>
              <va-additional-info
                trigger="Need help understanding your results?"
                class="no-print"
              >
                <p>
                  Your provider will review your results and explain what they
                  mean for your health. To ask a question now, send a secure
                  message to your care team.
                </p>
                <p>
                  <a
                    href={mhvUrl(
                      isAuthenticatedWithSSOe(fullState),
                      'secure-messaging',
                    )}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Start a new message
                  </a>
                </p>
              </va-additional-info>
              <p className="vads-u-font-size--base monospace">
                {record.results}
              </p>{' '}
            </div>
          </section>
        </>
      );
    }
    return <></>;
  };

  return (
    <div className="vads-l-grid-container vads-u-padding-x--0 vads-u-margin-bottom--5">
      {content()}
    </div>
  );
};

export default MicroDetails;

MicroDetails.propTypes = {
  fullState: PropTypes.object,
  record: PropTypes.object,
};
