export const Actions = {
  Breadcrumbs: {
    SET_BREAD_CRUMBS: 'SM_SET_BREAD_CRUMBS',
  },
  Prescriptions: {
    CLEAR_DETAILS: 'RX_PRESCRIPTION_DETAILS_CLEAR',
    CLEAR_ERROR: 'RX_PRESCRIPTIONS_CLEAR_ERROR',
    FILL: 'RX_PRESCRIPTIONS_FILL',
    FILL_ERROR: 'RX_PRESCRIPTIONS_FILL_ERROR',
    GET_DETAILS: 'RX_PRESCRIPTION_DETAILS_GET',
    GET_PAGINATED_SORTED_LIST: 'RX_PRESCRIPTIONS_GET_PAGINATED_SORTED_LIST',
    GET_SORTED_LIST: 'RX_PRESCRIPTIONS_GET_SORTED_LIST',
    SET_DETAILS: 'RX_PRESCRIPTION_DETAILS_SET',
    SET_SORTED_LIST: 'RX_PRESCRIPTIONS_SET_SORTED_LIST',
    UPDATE_SORT_OPTION: 'RX_PRESCRIPTIONS_UPDATE_SORT_OPTION',
  },
  // TODO: consider re-using this from medical-records
  Allergies: {
    GET_LIST: 'RX_ALLERGIES_GET_LIST',
    GET_LIST_ERROR: 'RX_ALLERGIES_GET_LIST_ERROR',
    GET_LIST_ERROR_RESET: 'GET_LIST_ERROR_RESET',
  },
};
