name: Checks Action
description: Checks Action

inputs:
  name:
    description: Name of check being created
    required: true
  conclusion:
    description: Conclusion of job driving check
    required: true
  output:
    description: Output for check
    required: true
  token:
    description: GH Token
    required: true

runs:
  using: composite
  steps:
    - name: Unit test results
      if: ${{ always() }}
      uses: LouisBrunner/checks-action@v2.0.0
      with:
        token: ${{ inputs.token }}
        name: ${{ inputs.name }}
        conclusion: ${{ inputs.conclusion }}
        output: ${{ inputs.output }}