export const dependents = [
  {
    number_of_records: '2',
    persons: [
      {
        award_indicator: 'N',
        city_of_birth: 'WASHINGTON',
        current_relate_status: null,
        date_of_birth: '01/01/2000',
        date_of_death: null,
        death_reason: null,
        email_address: 'Curt@email.com',
        first_name: 'CURT',
        gender: null,
        last_name: 'WEBB-STER',
        middle_name: null,
        proof_of_dependency: 'Y',
        ptcpnt_id: '32354974',
        related_to_vet: 'N',
        relationship: 'Child',
        ssn: '500223351',
        ssn_verify_status: '1',
        state_of_birth: 'DC',
      },
      {
        award_indicator: 'N',
        city_of_birth: 'WASHINGTON',
        current_relate_status: null,
        date_of_birth: '01/01/1970',
        date_of_death: null,
        death_reason: null,
        email_address: 'Sharon@email.com',
        first_name: 'SHARON',
        gender: null,
        last_name: 'WEBB-STER',
        middle_name: null,
        proof_of_dependency: null,
        ptcpnt_id: '32354975',
        related_to_vet: 'N',
        relationship: 'Spouse',
        ssn: '500223352',
        ssn_verify_status: null,
        state_of_birth: 'DC',
      },
    ],
    return_code: 'SHAR 9999',
    return_message: 'Records found',
  },
];
