export const dependents = [
  {
    numberOfRecords: '2',
    persons: [
      {
        awardIndicator: 'N',
        cityOfBirth: 'WASHINGTON',
        currentRelateStatus: null,
        dateOfBirth: '01/01/2000',
        dateOfDeath: null,
        deathReason: null,
        emailAddress: 'Curt@email.com',
        firstName: 'CURT',
        gender: null,
        lastName: 'WEBB-STER',
        middleName: null,
        proofOfDependency: 'Y',
        ptcpntId: '32354974',
        relatedToVet: 'N',
        relationship: 'Child',
        ssn: '500223351',
        ssnVerifyStatus: '1',
        stateOfBirth: 'DC',
      },
      {
        awardIndicator: 'N',
        cityOfBirth: 'WASHINGTON',
        currentRelateStatus: null,
        dateOfBirth: '01/01/1970',
        dateOfDeath: null,
        deathReason: null,
        emailAddress: 'Sharon@email.com',
        firstName: 'SHARON',
        gender: null,
        lastName: 'WEBB-STER',
        middleName: null,
        proofOfDependency: null,
        ptcpntId: '32354975',
        relatedToVet: 'N',
        relationship: 'Spouse',
        ssn: '500223352',
        ssnVerifyStatus: null,
        stateOfBirth: 'DC',
      },
    ],
    returnCode: 'SHAR 9999',
    returnMessage: 'Records found',
  },
];
