import React, { useMemo } from 'react';
import { useSelector } from 'react-redux';
import { Trans, useTranslation } from 'react-i18next';
import { subDays } from 'date-fns';
import { generatePdf } from '@department-of-veterans-affairs/platform-pdf/exports';

import { phoneNumbers } from '../../../utils/appConstants';
import PreCheckInAccordionBlock from '../../../components/PreCheckInAccordionBlock';
import HowToLink from '../../../components/HowToLink';

import { makeSelectVeteranData, makeSelectError } from '../../../selectors';

import Wrapper from '../../../components/layout/Wrapper';

import { getFirstCanceledAppointment } from '../../../utils/appointment';

const getPdf = e => {
  e.preventDefault();

  generatePdf('medicalRecords', 'lab_and_test_results', {
    headerLeft: 'Roberts, Jesse',
    headerRight: 'Date of birth: March 15, 1982',
    headerBanner: [
      {
        weight: 'normal',
        text:
          "If you're ever in crisis and need to talk to someone right away, call the Veterans Crisis line at ",
      },
      {
        weight: 'bold',
        text: '988',
      },
      {
        weight: 'normal',
        text: '. Then select 1.',
      },
    ],
    footerLeft: 'Report generated by My HealtheVet and VA on May 10, 2023',
    footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
    title: 'Lab and test results: Complete blood count on April 1, 2022',
    subject: 'Patient lab & test results',
    preface:
      'If you have questions about these results, send a secure message to your care team.',
    details: {
      header: 'Details about this test',
      items: [
        {
          title: 'Provider notes',
          value: 'None noted',
          inline: true,
        },
        {
          title: 'Type of test',
          value: 'Chemistry and hematology',
          inline: true,
        },
        {
          title: 'Ordering location',
          value: 'DAYTON, OH VAMC 4100 W. THIRD STREET , DAYTON, OH 45428',
          inline: true,
        },
        {
          title: 'Collecting location',
          value: 'DAYTON, OH VAMC 4100 W. THIRD STREET , DAYTON, OH 45428',
          inline: true,
        },
      ],
    },
    results: {
      header: 'Results',
      preface:
        "If your results are outside the reference range, this doesn't automatically mean you have a health problem. Your provider will explain what the results mean for your health.",
      items: [
        {
          header: 'WBC',
          items: [
            {
              title: 'Result',
              value: '50.0 K/ccm (Critical high)',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '4.5 - 10.5 K/ccm',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'ref. range prior to 1/16/03 was 10.5 K/ccm',
              inline: false,
            },
          ],
        },
        {
          header: 'RBC',
          items: [
            {
              title: 'Result',
              value: '4.56 M/ccm',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '4.05 - 5.63 M/ccm',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'HGB',
          items: [
            {
              title: 'Result',
              value: '6.0 g/dL low',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '13.5 - 17.4 g/dL',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'RBC',
          items: [
            {
              title: 'Result',
              value: '4.56 M/ccm',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '4.05 - 5.63 M/ccm',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'HCT',
          items: [
            {
              title: 'Result',
              value: '27 g/dL low',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '41 - 50 g/dL',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'MVC',
          items: [
            {
              title: 'Result',
              value: '100 fL',
              inline: true,
            },
            {
              title: 'Standard range',
              value: 'Standard range: 80 - 100 fL',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'MCHC',
          items: [
            {
              title: 'Result',
              value: '40 % high',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '27.3 - 33.6 %',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'RCDW',
          items: [
            {
              title: 'Result',
              value: '10.1 % low',
              inline: true,
            },
            {
              title: 'Standard range',
              value: '11.4 - 16.0 %',
              inline: true,
            },
            {
              title: 'Status',
              value: 'Final',
              inline: true,
            },
            {
              title: 'Lab location',
              value: 'Dayton, OH Vamc 4100 W. Third street , Dayton, OH 45428',
              inline: true,
            },
            {
              title: 'Interpretation',
              value: 'None noted',
              inline: true,
            },
          ],
        },
      ],
    },
  });
};

const getVaccinePdf = e => {
  e.preventDefault();

  generatePdf('medicalRecords', 'vaccines', {
    headerLeft: 'Roberts, Jesse',
    headerRight: 'Date of birth: March 15, 1982',
    headerBanner: [
      {
        weight: 'normal',
        text:
          "If you're ever in crisis and need to talk to someone right away, call the Veterans Crisis line at ",
      },
      {
        weight: 'bold',
        text: '988',
      },
      {
        weight: 'normal',
        text: '. Then select 1.',
      },
    ],
    footerLeft: 'Report generated by My HealtheVet and VA on May 15, 2023',
    footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
    title: 'Vaccine records: ZOSTER LIVE on April 1, 2023',
    subject: 'Patient vaccine records',
    preface:
      'This list includes vaccines you got at VA health facilities and from providers or pharmacies in our community care network. It may not include vaccines you got outside our network. \nFor complete records of your allergies and reactions to vaccines, review your allergy records.',
    details: {
      items: [
        {
          title: 'Location',
          value: 'Cambridge Community Based Outpatient Clinic',
          inline: true,
        },
        {
          title: 'Reaction',
          value: 'None noted',
          inline: true,
        },
        {
          title: 'Provider notes',
          value:
            'Dose #1 of 1 vaccine seasonal injectable preservative free vaccine administered',
          inline: false,
        },
      ],
    },
  });
};

const getVitalsPdf = e => {
  e.preventDefault();

  generatePdf('medicalRecords', 'vitals', {
    headerLeft: 'Roberts, Jesse',
    headerRight: 'Date of birth: March 15, 1982',
    headerBanner: [
      {
        weight: 'normal',
        text:
          "If you're ever in crisis and need to talk to someone right away, call the Veterans Crisis line at ",
      },
      {
        weight: 'bold',
        text: '988',
      },
      {
        weight: 'normal',
        text: '. Then select 1.',
      },
    ],
    footerLeft: 'Report generated by My HealtheVet and VA on May 15, 2023',
    footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
    title: 'Vitals',
    subject: 'Patient vitals',
    preface:
      'This list includes vitals and other basic health numbers your providers check at your appointments.',
    results: {
      header: 'Blood pressure',
      items: [
        {
          header: 'April 1, 2022 at 12:34 p.m.',
          items: [
            {
              title: 'Result',
              value: '120/80',
              inline: true,
            },
            {
              title: 'Location',
              value: 'Cincinnati VA Medical Center',
              inline: true,
            },
            {
              title: 'Provider notes',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'April 4, 2021 at 11:11 a.m.',
          items: [
            {
              title: 'Result',
              value: '140/70',
              inline: true,
            },
            {
              title: 'Location',
              value: 'Cincinnati VA Medical Center',
              inline: true,
            },
            {
              title: 'Provider notes',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'January 15, 2021 at 8:16 a.m.',
          items: [
            {
              title: 'Result',
              value: '120/80',
              inline: true,
            },
            {
              title: 'Location',
              value: 'Cincinnati VA Medical Center',
              inline: true,
            },
            {
              title: 'Provider notes',
              value: 'None noted',
              inline: true,
            },
          ],
        },
        {
          header: 'December 17, 2021 at 12:01 p.m.',
          items: [
            {
              title: 'Result',
              value: '120/80',
              inline: true,
            },
            {
              title: 'Location',
              value: 'Cincinnati VA Medical Center',
              inline: true,
            },
            {
              title: 'Provider notes',
              value: 'None noted',
              inline: true,
            },
          ],
        },
      ],
    },
  });
};
const getSingleVitalPdf = e => {
  e.preventDefault();

  generatePdf('medicalRecords', 'single_vital', {
    headerLeft: 'Roberts, Jesse',
    headerRight: 'Date of birth: March 15, 1982',
    headerBanner: [
      {
        weight: 'normal',
        text:
          "If you're ever in crisis and need to talk to someone right away, call the Veterans Crisis line at ",
      },
      {
        weight: 'bold',
        text: '988',
      },
      {
        weight: 'normal',
        text: '. Then select 1.',
      },
    ],
    footerLeft: 'Report generated by My HealtheVet and VA on May 15, 2023',
    footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
    title: 'Blood pressure on April 1, 2022 at 12:34 p.m.',
    subject: 'Patient vital',
    preface:
      'Your vitals list may not be complete. If you have any questions about your information, visit the FAQs or contact your VA Health care team.',
    details: {
      items: [
        {
          title: 'Result',
          value: '120/80',
          inline: true,
        },
        {
          title: 'Location',
          value: 'Cincinnati VA Medical Center',
          inline: true,
        },
        {
          title: 'Provider notes',
          value: 'None noted',
          inline: true,
        },
      ],
    },
  });
};

const getProgressNotePdf = e => {
  e.preventDefault();

  const noteValue = `Face-to-Face
MHVZZVISNTWENTY,TEST PATIENTR is a 21 year old veteran who presents for a
face-to-face follow-up visit.
CHIEF COMPLAINT/HISTORY OF PRESENT ILLNESS: Testing to see if after visit
summary viewable in JLV

EXAM
NO VITALS FOUND SpO2 ---
General:
Chest:
Cardiovascular:
Abdomen:
Extremities:
Other:

ASSESSMENT/PLAN
Written After Visit Summary instructions reviewed with patient. Patient
provided copy of updated medication list.
RETURN TO CLINIC: Per RTC order, or sooner PRN

Total time spent in clinical care related to this visit: 5 minutes

MEDICATION RECONCILIATION:
    Medication Reconciliation was not performed at this visit as patient
    and/or caregiver is not able to confirm medications he/she is taking. The
    importance of managing medication information was explained to the
    patient.
PAST MEDICAL HISTORY
Enter Problems:

No active problems in computerized problem list as of 7/19/22@21:36

SERVICE CONNECTED CONDITIONS
LUNG CONDITION                 60% S/C
MEDICATIONS
Local:
Active Outpatient Medications (excluding Supplies):

No Medications Found

Remote: No Active Remote Medications for this patient
ALLERGIES
Local: Allergy Assessment Not Done
Remote:
FACILITY                                ALLERGY/ADR
--------                                -----------
363^ANCHORAGE VA MEDICAL CENTER^463     TETANUS TOXOID
648^PORTLAND VA MEDICAL CENTER^648      ADHESIVE TAPE
648^PORTLAND VA MEDICAL CENTER^648      ALUMINUM HYDROXIDE/MAGNESIUM HYDROXIDE
648^PORTLAND VA MEDICAL CENTER^648      EGGS
648^PORTLAND VA MEDICAL CENTER^648      LISINOPRIL
648^PORTLAND VA MEDICAL CENTER^648      PENICILLIN
648^PORTLAND VA MEDICAL CENTER^648      PRAZOSIN
648^PORTLAND VA MEDICAL CENTER^648      SULFA DRUGS
648^PORTLAND VA MEDICAL CENTER^648      TETRACYCLINE
668^MANN-GRANDSTAFF VAMC^668            CLINDAMYCIN
687^JONATHAN M. WAINWRIGHT VAMC^687     PENICILLIN
LABS:
  No data available HEMOGLOBIN A1c,INTEGRA - NONE FOUND
No data available for: CHOLESTEROL
TRIGLYCERIDES
HDL CHOLESTEROL
LDL, CALCULATED
LDL, DIRECT No CBC Panel Found

/es/ , DNP, ARNP, FNP-BC
Nurse Practitioner - Women's Health Clinic
Signed: 07/19/2022 21:42`;

  generatePdf('medicalRecords', 'progress_note', {
    headerLeft: 'Roberts, Jesse',
    headerRight: 'Date of birth: March 15, 1982',
    headerBanner: [
      {
        weight: 'normal',
        text:
          "If you're ever in crisis and need to talk to someone right away, call the Veterans Crisis line at ",
      },
      {
        weight: 'bold',
        text: '988',
      },
      {
        weight: 'normal',
        text: '. Then select 1.',
      },
    ],
    footerLeft: 'Report generated by My HealtheVet and VA on May 10, 2023',
    footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
    title: 'Care summaries and notes',
    subject: 'Progress Note',
    preface:
      'This report only includes care summaries and notes from 2013 and later. \nFor after visit summaries (summaries of your appointments with VA providers), go to your appointment records.',
    results: {
      header: 'Primary care progress note',
      sectionSeparators: false,
      items: [
        {
          header: 'Details',
          items: [
            {
              title: 'Location',
              value: 'Pittsburgh VA Medical Center',
              inline: true,
            },
            {
              title: 'Signed by',
              value: 'Beth M. Smith',
              inline: true,
            },
            {
              title: 'Last updated',
              value: 'April 3, 2023',
              inline: true,
            },
            {
              title: 'Date signed',
              value: 'April 1, 2023',
              inline: true,
            },
          ],
        },
        {
          header: 'Note',
          items: [
            {
              value: noteValue,
              inline: false,
            },
          ],
        },
      ],
    },
  });
};

const appointmentAccordion = appointments => {
  return (
    <PreCheckInAccordionBlock
      key="accordion"
      errorPage
      appointments={appointments}
    />
  );
};

const Error = () => {
  const selectError = useMemo(makeSelectError, []);
  const { error } = useSelector(selectError);

  // Get appointment dates if available.
  const selectVeteranData = useMemo(makeSelectVeteranData, []);
  const { appointments } = useSelector(selectVeteranData);

  const { t } = useTranslation();

  let header = '';

  let apptType = '';
  if (appointments && appointments.length > 0) {
    apptType = appointments[0]?.kind ?? 'clinic';
  }

  let accordion = null;
  let alertType = '';
  let messageText = '';
  let showHowToLink = false;

  const mixedPhoneAndInPersonMessage = (
    <div>
      <div>
        <span className="fas fa-chevron-right vads-u-margin-left--neg0p5" />
        <span className="appointment-type-label vads-u-margin-left--0p5 vads-u-font-weight--bold">
          {t('in-person-appointment')}
        </span>
      </div>
      <div className="vads-u-margin-top--2">
        {t(
          'you-can-still-check-in-with-your-phone-on-the-day-of-your-appointment',
        )}
      </div>
      <div className="vads-u-margin-top--2">
        <span className="fas fa-chevron-right vads-u-margin-left--neg0p5" />
        <span className="appointment-type-label vads-u-margin-left--0p5 vads-u-font-weight--bold">
          {t('telephone-appointment')}
        </span>
      </div>
      <div className="vads-u-margin-top--2">
        {t('your-provider-will-call-you-at-your-appointment-time')}
      </div>
    </div>
  );

  switch (error) {
    case 'max-validation':
      alertType = 'error';
      header = t('sorry-we-cant-complete-pre-check-in');
      messageText = (
        <>
          <div className="vads-u-margin-bottom--2">
            {t('were-sorry-we-couldnt-match-your-information-to-our-records')}
          </div>
          {mixedPhoneAndInPersonMessage}
        </>
      );
      showHowToLink = false;
      break;
    case 'pre-check-in-post-error':
    case 'error-completing-pre-check-in':
      alertType = 'info';
      header = t('sorry-we-cant-complete-pre-check-in');
      messageText = (
        <>
          <div>
            {t('were-sorry-something-went-wrong-on-our-end-please-try-again')}
          </div>
          <div data-testid="date-message">
            {t('you-can-pre-check-in-online-until-date', {
              date: subDays(new Date(appointments[0].startTime), 1),
            })}
          </div>
        </>
      );
      showHowToLink = apptType === 'clinic';
      break;
    case 'appointment-canceled': {
      alertType = 'info';
      header = t('sorry-pre-check-in-is-no-longer-available');
      // get first appointment that was cancelled?
      const canceledAppointment = getFirstCanceledAppointment(appointments);
      const appointmentDateTime = new Date(canceledAppointment.startTime);
      messageText = (
        <div>
          <p className="vads-u-margin-top--0">
            {t('your-appointment-at-on-is-cancelled', {
              day: appointmentDateTime,
              time: appointmentDateTime,
            })}
          </p>
          <p className="vads-u-margin-top--2">
            <Trans
              i18nKey="if-you-have-questions-please-call-us-were-here-24-7"
              components={[
                <va-telephone
                  contact={phoneNumbers.mainInfo}
                  key={phoneNumbers.mainInfo}
                />,
                <va-telephone contact="711" tty key="711" />,
              ]}
            />
          </p>
          {canceledAppointment?.kind === 'phone' ? (
            ''
          ) : (
            <p className="vads-u-margin-top--2 vads-u-margin-bottom--0">
              {t('or-talk-to-a-staff-member-if-youre-at-a-va-facility')}
            </p>
          )}
        </div>
      );
      showHowToLink = false;
      accordion = appointmentAccordion(appointments);
      break;
    }
    case 'pre-check-in-past-appointment':
      alertType = 'info';
      header = t('sorry-pre-check-in-is-no-longer-available');
      messageText = t('pre-check-in-no-longer-available--info-message');
      showHowToLink = false;
      accordion = appointmentAccordion(appointments);
      break;
    case 'pre-check-in-expired':
      alertType = 'info';
      header = t('sorry-pre-check-in-is-no-longer-available');
      messageText =
        apptType === 'clinic'
          ? t('you-can-still-check-in-once-you-arrive')
          : t('your-provider-will-call-you-at-your-appointment-time');
      accordion = appointmentAccordion(appointments);
      showHowToLink = true;
      break;
    case 'uuid-not-found':
      // Shown when POST sessions returns 404.
      alertType = 'info';
      header = t('were-sorry-this-link-has-expired');
      messageText = mixedPhoneAndInPersonMessage;
      showHowToLink = false;
      break;
    case 'session-error':
    case 'bad-token':
    case 'no-token':
    case 'reload-data-error':
    case 'possible-canceled-appointment':
      // This is considered our generic error message
      alertType = 'info';
      header = t('sorry-we-cant-complete-pre-check-in');
      messageText = mixedPhoneAndInPersonMessage;
      showHowToLink = false;
      break;
    default:
      // should never get here but if it does show the minimum
      alertType = 'error';
      header = t('sorry-we-cant-complete-pre-check-in');
      messageText = (
        <div>
          {t('were-sorry-something-went-wrong-on-our-end-please-try-again')}
        </div>
      );
      showHowToLink = false;
      break;
  }

  return (
    <Wrapper pageTitle={header}>
      <va-alert
        background-only
        show-icon
        status={alertType}
        data-testid="error-message"
      >
        <div>{messageText}</div>
      </va-alert>
      <div>
        <i
          aria-label="download"
          className="fas fa-download vads-u-color--link-default vads-u-margin-right--1"
          aria-hidden="true"
        />
        <a
          download="test.pdf"
          type="application/pdf"
          href="test.pdf"
          onClick={getPdf}
        >
          Download Labs
        </a>
      </div>
      <div>
        <i
          aria-label="download"
          className="fas fa-download vads-u-color--link-default vads-u-margin-right--1"
          aria-hidden="true"
        />
        <a
          download="vaccine.pdf"
          type="application/pdf"
          href="vaccine.pdf"
          onClick={getVaccinePdf}
        >
          Download Vaccine
        </a>
      </div>
      <div>
        <i
          aria-label="download"
          className="fas fa-download vads-u-color--link-default vads-u-margin-right--1"
          aria-hidden="true"
        />
        <a
          download="vitals.pdf"
          type="application/pdf"
          href="vitals.pdf"
          onClick={getVitalsPdf}
        >
          Download Vitals
        </a>
      </div>
      <div>
        <i
          aria-label="download"
          className="fas fa-download vads-u-color--link-default vads-u-margin-right--1"
          aria-hidden="true"
        />
        <a
          download="singlevital.pdf"
          type="application/pdf"
          href="singlevital.pdf"
          onClick={getSingleVitalPdf}
        >
          Download Single Vital
        </a>
      </div>
      <div>
        <i
          aria-label="download"
          className="fas fa-download vads-u-color--link-default vads-u-margin-right--1"
          aria-hidden="true"
        />
        <a
          download="progress_note.pdf"
          type="application/pdf"
          href="progress_note.pdf"
          onClick={getProgressNotePdf}
        >
          Download Progress Note
        </a>
      </div>

      {showHowToLink && <HowToLink apptType={apptType} />}
      {accordion && <div className="vads-u-margin-top--3">{accordion}</div>}
    </Wrapper>
  );
};

export default Error;
