export const CernerAlertContent = {
  MR_LANDING_PAGE: {
    linkPath: '/pages/health_record/comprehensive_record/health_summaries',
    pageName: 'medical records',
    headline: 'Manage your medical records at',
    domain: 'medical records',
  },
  LABS_AND_TESTS: {
    linkPath: '/pages/health_record/comprehensive_record/health_summaries',
    pageName: 'lab and test results',
    headline: 'To get your lab and test results from',
    domain: 'medical records',
  },
  CARE_SUMMARIES_AND_NOTES: {
    linkPath: '/pages/health_record/app-views/cerner/reports/documents',
    pageName: 'care summaries and notes',
    headline: 'To get your care summaries and notes from',
    domain: 'medical records',
  },
  VACCINES: {
    linkPath: '/pages/health_record/health-record-immunizations',
    pageName: 'vaccines',
    headline: 'To get your vaccines from',
    domain: 'medical records',
  },
  ALLERGIES: {
    linkPath: '/pages/health_record/health-record-allergies',
    pageName: 'allergies and reactions',
    headline: 'To get your allergies and reactions from',
    domain: 'medical records',
  },
  HEALTH_CONDITIONS: {
    linkPath: '/pages/health_record/conditions',
    pageName: 'health conditions',
    headline: 'To get your health conditions from',
    domain: 'medical records',
  },
  VITALS: {
    linkPath: '/pages/health_record/results',
    pageName: 'vitals',
    headline: 'To get your vitals from',
    domain: 'medical records',
  },
  DOWNLOAD: {
    linkPath: '/pages/health_record/comprehensive_record/health_summaries',
    pageName: 'medical records reports',
    headline: 'To get your medical records reports from',
    domain: 'medical records',
  },
  MEDICATIONS: {
    linkPath: '/pages/medications/current',
    pageName: 'medications',
    headline: 'To view or manage your medications at',
    domain: 'medications',
  },
  SECURE_MESSAGING: {
    linkPath: '/pages/messaging/inbox',
    pageName: 'secure messages',
    domain: 'secure messages',
    headline: 'To send a secure message to a provider at',
    bodyActionSingle: 'To send a secure message to a provider at',
    bodyActionMultiple: 'To view or manage secure messages at these facilities',
    bodyIntro: 'Some of your secure messages may be in a different portal.',
  },
};
