import moment from 'moment';

export const generatePdfScaffold = (name, dob, title, subject, preface) => {
  return {
    headerLeft: name,
    headerRight: `Date of birth: ${dob}`,
    headerBanner: [
      {
        text:
          'If you’re ever in crisis and need to talk with someone right away, call the Veterans Crisis line at 988. Then select 1.',
      },
    ],
    footerLeft: `Report generated by My HealtheVet and VA on ${moment().format(
      'LL',
    )}`,
    footerRight: 'Page %PAGE_NUMBER% of %TOTAL_PAGES%',
    title,
    subject,
    preface,
    results: {
      sectionSeparators: false,
      items: [
        {
          header: 'Header',
          items: [
            {
              title: 'Title',
              value: 'Value',
              inline: true,
            },
          ],
        },
      ],
    },
  };
};
