1010cg "/v0/user,/v0/caregivers_assistance_claims,/v0/form1010cg/attachments"
1010ez "/v0/user,/v0/health_care_applications,/v0/health_care_applications/enrollment_status,/v0/in_progress_forms/1010ez"
1095b "/form1095_bs/download,/form1095_bs/available_forms"
22-0994 Education benefits form "/v0/education_benefits_claims/0994,/v0/in_progress_forms/22-0994"
About VA Disability Ratings ""
All VA Offices "/office-directory"
Authentication and Authorization "/v0/user,/auth/login/callback,/profilepostauth,/sessions/new,}/sign_in/authorize"
Benefits Delivery at Discharge "/v0/disability_compensation_form/submit_all_claim,/v0/intent_to_file,/v0/disability_compensation_form/separation_locations,/v0/ppiu/payment_information,/v0/upload_supporting_evidence,/v0/disability_compensation_form/submit_all_claim,/v0/disability_compensation_form/submission_status/"
Benefits Hubs ""
Burial Benefits Application (21P-530) "/v0/burial_claims,/v0/in_progress_forms/21P-530"
Campaign Landing Page ""
ChatBot "/virtual_agent_token"
Claim Status Tool "/v0/appeals,/evss_claims_async,/v0/evss_claims/request_decision,/v0/evss_claims/documents,/v0/education_benefits_claims/stem_claim_status"
Connect your Device ""
Contact Information ""
Content Hub ""
Coronavirus Chatbot "/coronavirus_chatbot/tokens"
Coronavirus Research - Update "/covid-research/volunteer/update"
Coronavirus Research - Volunteer "/covid-research/volunteer/create"
Coronavirus Vaccination "/covid_vaccine/v0/registration,/covid_vaccine/v0/registration/opt_out"
Coronavirus Vaccination Expansion "/covid_vaccine/v0/expanded_registration,/covid_vaccine/v0/facilities"
COVID-19 Screener "/covid19screen"
Debt Letters "/v0/debts,/v0/medical_copays"
Dependency Claims (686/674) "/v0/in_progress_forms/686C-674,/v0/dependents_applications"
Direct Deposit "/v0/profile/personal_information,/v0/profile/service_history,/v0/profile/full_name,/v0/profile/status,/v0/mhv_account,/v0/disability_compensation_form/rating_info,/v0/profile/ch33_bank_accounts,/v0/ppiu/payment_information"
Disability Comp Application (21-526 EZ) ""
Discharge Upgrade Tool ""
Education Benefits Application (22-1990) "/v0/education_benefits_claims/1990,/v0/in_progress_forms/1990"
Education Benefits Application under FRY or DEA (22-5490) "/v0/education_benefits_claims/5490,/v0/in_progress_forms/5490"
Education Benefits for National Call to Service Application (22-1990N) "/v0/education_benefits_claims/1990n,/v0/in_progress_forms/1990n"
Education Benefits Transfer Application (22-1990E) "/v0/education_benefits_claims/1990e,/v0/in_progress_forms/1990e"
Education Change of Program or Training Application (22-1995) "/v0/education_benefits_claims/1995,/v0/in_progress_forms/22-1995"
Education Change of Program or Training Application under FRY or DEA (22-5495) "/v0/education_benefits_claims/5495,/v0/in_progress_forms/5495"
Education Letters "/meb_api/v0/claim_status"
Enrollment Verification "/meb_api/v0/enrollment,/submit_enrollment_verification"
Facility Locator "/v0/facilities/va,/v0/maintenance_windows,/facilities_api,/geocoding"
Financial Status Report (FSR) "/v0/maintenance_windows,/v0/in_progress_forms/5655,/v0/debts"
Find a VA Form "/v0/forms"
GI Bill Comparison Tool "/institutions,/zipcode_rates,/institutions/search,/institutions/autocomplete"
GI Bill Feedback Tool "/v0/gi_bill_feedbacks"
Health Care Questionnaire "/health_quest/v0/questionnaire_manager"
Higher Level Review "/higher_level_reviews,/v0/profile/status,/v0/higher_level_reviews/contestable_issues/compensation,/v0/in_progress_forms/20-0996,/v0/in_progress_forms/20-0996"
Inherited Proofing ""
Language Assistance & Resource Pages ""
Letters "/v0/letters/beneficiary,/v0/letters,/v0/address,/v0/address/countries,/v0/address/states"
LGY: COE "/v0/coe/submit_coe_claim"
Login ""
Medallia ""
Medical Copays (MCP) "/v0/medical_copays,/v0/debts"
Medical Device Reordering Tool "/v0/mdot/supplies"
Mock Form ""
My Education Benefits "/meb_api/v0/submit_claim"
My VA "/vaos/v0/appointments,/v0/profile/service_history,/v0/profile/full_name,/v0/evss_claims_async,/v0/appeals,/v0/disability_compensation_form/rating_info,/v1/facilities/va,/v1/facilities/va,/v0/debts,/v0/profile/payment_history,/v0/health_care_applications/enrollment_status,/v0/profile/ch33_bank_accounts,/v0/disability_compensation_form/rating_info"
Notice of Disagreement "/v0/in_progress_forms/10182,/v0/decision_review_evidence,/v0/notice_of_disagreements/contestable_issues"
Notifications Preferences "/v0/profile,/v0/user"
Opt Out of Sharing VA Education Benefits Information "/v0/education_benefits_claims/0993"
Original Claims "/v0/disability_compensation_form/submit_all_claim,/v0/intent_to_file,/v0/disability_compensation_form/separation_locations,/v0/ppiu/payment_information,/v0/upload_supporting_evidence,/v0/disability_compensation_form/submit_all_claim,/v0/disability_compensation_form/submission_status"
Outreach & Events Hub and Calendar ""
PCPG CH36 "/v0/education_career_counseling_claims"
Pension Benefits Application (21P-527EZ) "/v0/pension_claims,/v0/in_progress_forms/21P-527EZ"
Post-9/11 GI Bill Benefit Information "/v0/post911_gi_bill_status,/v0/backend_statuses/gibs"
Profile ""
Pre-need Burial "/v0/preneeds/burial_forms,/v0/preneeds/preneed_attachments,/v0/preneeds/cemeteries"
Questionnaire List "/v0/maintenance_windows"
Rated Disabilities "/v0/disability_compensation_form/rated_disabilities,/v0/disability_compensation_form/rating_info"
Resources & Support ""
Search "/v0/search"
Search Representative ""
Secure Inbox ""
Site Navigation ""
Specially Adapated Housing Grant ""
Stakeholder Enterprise Portal (may not be on va.gov) ""
STEM Scholarship ""
Terms and Conditions ""
Translated Pages "/v0/education_benefits_claims/10203"
VA Notify ""
VA Online Scheduling "/v0/backend_statuses,/v0/maintenance_windows,/vaos/v2/locations,/vaos/v2/appointments,/vaos/v2/scheduling/configurations,/vaos/v2/facilities,/vaos/v0/community_care/eligibility,/vaos/v2/eligibility"
VA Profile "/v0/profile/full_name,/v0/profile/personal_information,/v0/profile/service_history,/v0/mhv_account,/v0/disability_compensation_form/rating_info,/v0/profile/communication_preferences,/v0/profile/telephones,/v0/profile/status"
VA.gov Homepage ""
VAMC Modernized Pages ""
Verify Identity ""
Vet Centers ""
Veteran ID Card Application "/id_card/attributes,/id_card/announcement_subscription"
Veteran Rapid Retraining Assistance Program (VRRAP) "/v0/education_benefits_claims/1990s"
View My Payment History "/v0/profile/payment_history"
View Your representative ""
View, search and update your VA representative ""
VR&E CH 31 "/v0/veteran_readiness_employment_claims"
Yellow Ribbon Tool "/v0/gi/yellow_ribbon_programs"