require("./_jquery.serializeObject.min.js");
require("./_jquery.deserialize.min.js");
var form_progress = require("./_form_progress.js");

function identityTransform(formData, arg) { return arg; }
function extractTransform(formData, arg) { return formData[arg]; }
function extractMonthTransform(formData, arg) {
  // Stupid js indexes months from 0.
  return extractTransform(formData, arg + "[month]");
}
function extractDateTransform(formData, arg) {
  return extractTransform(formData, arg + "[date]");
}
function extractYearTransform(formData, arg) {
  return extractTransform(formData, arg + "[year]");
}
function extractDateWithSlashTransform(formData, arg) {
  let dateString = "";

  let month = extractMonthTransform(formData, arg);
  let date = extractDateTransform(formData, arg);
  let year = extractYearTransform(formData, arg);

  if (!month || !date || !year) {
    return '';
  }

  if (Number(month) < 10) {
    dateString += "0";
  }
  dateString += month + "/";

  if (Number(date) < 10) {
    dateString += "0";
  }
  dateString += date + "/";

  return dateString + year;
}
function extractMonetaryValueTransform(formData, arg) {
  return Number(extractTransform(formData, arg)).toFixed(2).toString();
}

function extractAddressNameTransform(formData, arg) {
  return extractTransform(formData, arg + "[name]");
}

function extractAddressStreetTransform(formData, arg) {
  return extractTransform(formData, arg + "[street]");
}

function extractAddressCityTransform(formData, arg) {
  return extractTransform(formData, arg + "[city]");
}

function extractAddressStateTransform(formData, arg) {
  return extractTransform(formData, arg + "[state]");
}

function extractAddressZipcodeTransform(formData, arg) {
  return extractTransform(formData, arg + "[zipcode]");
}

function extractAddressPhoneTransform(formData, arg) {
  return extractTransform(formData, arg + "[phone]");
}

function extractAddressWithFormatTransform(formData, arg) {
  let name = extractAddressNameTransform(formData, arg);
  let street = extractAddressStreetTransform(formData, arg);
  let city = extractAddressCityTransform(formData, arg);
  let state = extractAddressStateTransform(formData, arg);
  let zip = extractAddressZipcodeTransform(formData, arg);
  let phone = extractAddressPhoneTransform(formData, arg);

  //return name + "\n" + street + "\n" + city + ", " + state + " " + zip + "  " + phone;
  return "AInsurance1\n1 Insurance Way\nNew York, NY 02123  (202) 123-4567";
}

function validatePresence(input) {
  if (input.value === '') {
    return false;
  }

  return true;
}
function validateMonetaryValue(input) {
  let amount = input.value;

  if (/^\d+\.?\d*$/.test(amount)) {
    return true;
  }

  return false;
}
function validate(input) {
  let valid = validatePresence(input);

  // TODO change this to using classList
  $(input).removeClass('error');

  if (!valid) {
    $(input).addClass('error');
    return false;
  }

  if ($(input).data('validation-type') === 'monetary') {
    valid = validateMonetaryValue(input);
  }

  if (!valid) {
    $(input).addClass('error');
    return false;
  }

  return true;
}

let medicalCenters = [
  { state: "TT", id: "987", name: "CHEY6 (987)" },
  { state: "TT", id: "988", name: "DAYT20 (988)" },
  { state: "AK", id: "463", name: "ANCHORAGE VA MEDICAL CENTER" },
  { state: "AK", id: "463GA", name: "FAIRBANKS VA CLINIC" },
  { state: "AK", id: "463GB", name: "KENAI VA CLINIC" },
  { state: "AK", id: "463GC", name: "MAT-SU VA CLINIC" },
  { state: "AL", id: "521GE", name: "ANNISTON CBOC" },
  { state: "AL", id: "521GG", name: "BESSEMER CBOC" },
  { state: "AL", id: "521", name: "BIRMINGHAM VAMC" },
  { state: "AL", id: "619GB", name: "CENTRAL ALABAMA HCS - DOTHAN CBOC" },
  { state: "AL", id: "619", name: "CENTRAL ALABAMA HEALTH CARE SYSTEM - MONTGOMERY DIVISION" },
  { state: "AL", id: "619A4", name: "CENTRAL ALABAMA HEALTH CARE SYSTEM - TUSKEGEE DIVISION" },
  { state: "AL", id: "521GH", name: "CHILDERSBURG CBOC" },
  { state: "AL", id: "521GB", name: "DECATUR CBOC" },
  { state: "AL", id: "521GC", name: "FLORENCE CBOC" },
  { state: "AL", id: "521GI", name: "GUNTERSVILLE CBOC" },
  { state: "AL", id: "521GA", name: "HUNTSVILLE CBOC" },
  { state: "AL", id: "521GF", name: "JASPER VA CLINIC" },
  { state: "AL", id: "619GE", name: "MONROE COUNTY CBOC" },
  { state: "AL", id: "521GD", name: "RAINBOW CITY CBOC" },
  { state: "AL", id: "679", name: "TUSCALOOSA VA MEDICAL CENTER" },
  { state: "AL", id: "619GD", name: "WIREGRASS CBOC" },
  { state: "AR", id: "598", name: "CENTRAL ARKANSAS HEALTH CARE SYSTEM - LITTLE ROCK" },
  { state: "AR", id: "598GG", name: "CONWAY CBOC" },
  { state: "AR", id: "598GB", name: "EL DORADO, AR CBOC" },
  { state: "AR", id: "564", name: "FAYETTEVILLE VA MEDICAL" },
  { state: "AR", id: "564GB", name: "FORT SMITH VA CLINIC" },
  { state: "AR", id: "564GA", name: "HARRISON VA CLINIC" },
  { state: "AR", id: "614GN", name: "HELENA VA CLINIC" },
  { state: "AR", id: "598GC", name: "HOT SPRINGS, AR CBOC" },
  { state: "AR", id: "614GB", name: "JONESBORO VA CLINIC" },
  { state: "AR", id: "598GD", name: "MENA, AR (CBOC)" },
  { state: "AR", id: "598GA", name: "MOUNTAIN HOME, AR CBOC" },
  { state: "AR", id: "564GD", name: "OZARK CBOC" },
  { state: "AR", id: "657GG", name: "PARAGOULD AR CBOC (657GG)" },
  { state: "AR", id: "598GE", name: "PINE BLUFF CBOC" },
  { state: "AR", id: "598GH", name: "RUSSELLVILLE CBOC" },
  { state: "AR", id: "598GF", name: "SEARCY CBOC" },
  { state: "AR", id: "667GA", name: "TEXARKANA CBOC" },
  { state: "AS", id: "459GF", name: "AMERICAN SAMOA VA CLINIC" },
  { state: "AZ", id: "649GD", name: "ANTHEM CBOC" },
  { state: "AZ", id: "678GC", name: "CASA GRANDE CBOC" },
  { state: "AZ", id: "649GE", name: "COTTONWOOD CBOC" },
  { state: "AZ", id: "649GB", name: "FLAGSTAFF CBOC" },
  { state: "AZ", id: "644GF", name: "GLOBE HEALTH CARE CLINIC" },
  { state: "AZ", id: "678GE", name: "GREEN VALLEY CBOC" },
  { state: "AZ", id: "649GA", name: "KINGMAN CBOC" },
  { state: "AZ", id: "644GG", name: "N EAST PHOENIX VA CLINIC" },
  { state: "AZ", id: "649", name: "NORTHERN ARIZONA HEALTH CARE SYSTEM - PRESCOTT DIVISION" },
  { state: "AZ", id: "678GF", name: "NORTHWEST TUCSON URBAN CBOC" },
  { state: "AZ", id: "644GD", name: "PAYSON CBOC" },
  { state: "AZ", id: "644", name: "PHOENIX VAMC" },
  { state: "AZ", id: "649GC", name: "PRESCOTT CBOC LAKE HAVASU CITY" },
  { state: "AZ", id: "678GD", name: "SAFFORD CBOC" },
  { state: "AZ", id: "644GB", name: "SHOW LOW CBOC" },
  { state: "AZ", id: "678GA", name: "SIERRA VISTA CBOC" },
  { state: "AZ", id: "644BY", name: "SOUTHEAST CBOC" },
  { state: "AZ", id: "678GG", name: "SOUTHEAST TUCSON" },
  { state: "AZ", id: "678", name: "SOUTHERN ARIZONA HEALTH CARE SYSTEM - TUCSON DIVISION" },
  { state: "AZ", id: "644GC", name: "SOUTHWEST CBOC" },
  { state: "AZ", id: "644GA", name: "SUN CITY, AZ CBOC" },
  { state: "AZ", id: "644GE", name: "THUNDERBIRD VA CBOC" },
  { state: "AZ", id: "678GB", name: "YUMA CBOC" },
  { state: "CA", id: "600GA", name: "ANAHEIM VETERANS HEALTH CLINIC" },
  { state: "CA", id: "691GG", name: "ANTELOPE VALLEY VA CLINIC" },
  { state: "CA", id: "691GD", name: "BAKERSFIELD CBOC" },
  { state: "CA", id: "600GC", name: "CABRILLO VETERANS HEALTH CLINIC" },
  { state: "CA", id: "612GG", name: "CHICO VA CLINIC" },
  { state: "CA", id: "664GC", name: "CHULA VISTA CBOC" },
  { state: "CA", id: "662GG", name: "CLEARLAKE CBOC" },
  { state: "CA", id: "605GD", name: "CORONA CBOC" },
  { state: "CA", id: "654GD", name: "DIAMOND VIEW CBOC" },
  { state: "CA", id: "691GF", name: "EAST LOS ANGELES CBOC" },
  { state: "CA", id: "664GD", name: "ESCONDIDO CBOC" },
  { state: "CA", id: "662GC", name: "EUREKA CBOC" },
  { state: "CA", id: "612GD", name: "FAIRFIELD VA CLINIC" },
  { state: "CA", id: "570", name: "FRESNO VA MEDICAL CENTER" },
  { state: "CA", id: "691GC", name: "GARDENA CBOC" },
  { state: "CA", id: "664GA", name: "IMPERIAL VALLEY CBOC" },
  { state: "CA", id: "600GE", name: "LAGUNA HILLS VET HLTH CLINIC" },
  { state: "CA", id: "605", name: "LOMA LINDA HCS" },
  { state: "CA", id: "691GE", name: "LOS ANGELES CBOC" },
  { state: "CA", id: "691GN", name: "LYNWOOD CBOC" },
  { state: "CA", id: "612GE", name: "MARE ISLAND VA CLINIC" },
  { state: "CA", id: "612GF", name: "MARTINEZ CBOC" },
  { state: "CA", id: "612", name: "MARTINEZ VA CLC" },
  { state: "CA", id: "612GH", name: "MCCLELLAN VA CLINIC" },
  { state: "CA", id: "570GA", name: "MERCED VA CLINIC" },
  { state: "CA", id: "605GB", name: "MURRIETA CBOC" },
  { state: "CA", id: "570GC", name: "OAKHURST VA CLINIC" },
  { state: "CA", id: "664GB", name: "OCEANSIDE CBOC" },
  { state: "CA", id: "691GM", name: "OXNARD CBOC" },
  { state: "CA", id: "605GC", name: "PALM DESERT CBOC" },
  { state: "CA", id: "640GA", name: "PALO ALTO HEALTH CARE SYSTEM - CAPITOLA DIVSION" },
  { state: "CA", id: "640GC", name: "PALO ALTO HEALTH CARE SYSTEM - FREMONT CBOC" },
  { state: "CA", id: "640HB", name: "PALO ALTO HEALTH CARE SYSTEM - MODESTO DIVSION" },
  { state: "CA", id: "640HC", name: "PALO ALTO HEALTH CARE SYSTEM - MONTEREY DIVSION" },
  { state: "CA", id: "640GB", name: "PALO ALTO HEALTH CARE SYSTEM - SONORA DIVSION" },
  { state: "CA", id: "640HA", name: "PALO ALTO HEALTH CARE SYSTEM - STOCKTON DIVSION" },
  { state: "CA", id: "640", name: "PALO ALTO VA MEDICAL CENTER" },
  { state: "CA", id: "640A4", name: "PALO ALTO VAMC-LIVERMORE" },
  { state: "CA", id: "691GO", name: "PASADENA CBOC" },
  { state: "CA", id: "605GE", name: "RANCHO CUCAMONGA CBOC" },
  { state: "CA", id: "612A4", name: "SACRAMENTO VA MEDICAL CENTER" },
  { state: "CA", id: "662GE", name: "SAN BRUNO CBOC" },
  { state: "CA", id: "662GF", name: "SAN FRANCISCO CBOC" },
  { state: "CA", id: "662", name: "SAN FRANCISCO VAMC" },
  { state: "CA", id: "691GK", name: "SAN LUIS OBISPO CBOC" },
  { state: "CA", id: "600GB", name: "SANTA ANA VETERANS HEALTH CLINIC" },
  { state: "CA", id: "691GB", name: "SANTA BARBARA CBOC" },
  { state: "CA", id: "691GL", name: "SANTA MARIA CBOC" },
  { state: "CA", id: "662GA", name: "SANTA ROSA, CA CBOC" },
  { state: "CA", id: "691A4", name: "SEPULVEDA OUTPATIENT & NURSING HOME CARE" },
  { state: "CA", id: "570GB", name: "TULARE VA CLINIC" },
  { state: "CA", id: "662GD", name: "UKIAH CBOC" },
  { state: "CA", id: "691", name: "VA GREATER LOS ANGELES HEALTHCARE SYSTEM - WEST LOS ANGELES DIVISION" },
  { state: "CA", id: "600", name: "VA LONG BEACH HEALTHCARE SYSTEM" },
  { state: "CA", id: "664", name: "VA SAN DIEGO HEALTHCARE SYSTEM (664)" },
  { state: "CA", id: "654GA", name: "VA SIERRA FOOTHILLS OUTPATIENT CLINIC" },
  { state: "CA", id: "662GB", name: "VALLEJO CBOC" },
  { state: "CA", id: "605GA", name: "VICTORVILLE CBOC" },
  { state: "CA", id: "600GD", name: "WHITTIER/SANTA FE SPRINGS CLINIC" },
  { state: "CA", id: "612GI", name: "YUBA CITY CBOC" },
  { state: "CO", id: "554GF", name: "ALAMOSA VA CLINIC" },
  { state: "CO", id: "554GB", name: "AURORA VA CLINIC" },
  { state: "CO", id: "554GI", name: "BURLINGTON VA CLINIC" },
  { state: "CO", id: "554", name: "DENVER VA MEDICAL CENTER" },
  { state: "CO", id: "501GJ", name: "DURANGO VA CLINIC" },
  { state: "CO", id: "554GE", name: "FLOYD K. LINDSTROM VA CLINIC" },
  { state: "CO", id: "442GC", name: "FORT COLLINS VA CLINIC" },
  { state: "CO", id: "554GC", name: "GOLDEN VA CLINIC" },
  { state: "CO", id: "575", name: "GRAND JUNCTION VAMC" },
  { state: "CO", id: "442GD", name: "GREELEY VA CLINIC" },
  { state: "CO", id: "554GG", name: "LA JUNTA COMMUNITY BASED OUTPATIENT CLINIC (554GG)" },
  { state: "CO", id: "554GH", name: "LAMAR VA CLINIC" },
  { state: "CO", id: "575GA", name: "MONTROSE CBOC" },
  { state: "CO", id: "554GD", name: "PUEBLO VA CLINIC" },
  { state: "CT", id: "689GE", name: "DANBURY" },
  { state: "CT", id: "689HC", name: "NEW LONDON" },
  { state: "CT", id: "689A4", name: "NEWINGTON" },
  { state: "CT", id: "689GB", name: "STAMFORD VA PRIMARY CARE CTR" },
  { state: "CT", id: "689", name: "VA CONNECTICUT HEALTHCARE SYSTEM - WEST HAVEN DIVISION" },
  { state: "CT", id: "689GA", name: "WATERBURY" },
  { state: "CT", id: "689GC", name: "WINDHAM CBOC" },
  { state: "CT", id: "689GD", name: "WINSTED" },
  { state: "DC", id: "688GB", name: "SOUTHEAST WASHINGTON VA CLINIC" },
  { state: "DC", id: "688", name: "WASHINGTON VA MEDICAL CENTER" },
  { state: "DE", id: "460GC", name: "KENT COUNTY VA CLINIC" },
  { state: "DE", id: "460GA", name: "SUSSEX COUNTY VA CLINIC" },
  { state: "FL", id: "548GD", name: "BOCA RATON CBOC" },
  { state: "FL", id: "516GD", name: "BRADENTON VA CLINIC" },
  { state: "FL", id: "673GC", name: "BROOKSVILLE CBOC" },
  { state: "FL", id: "546", name: "BRUCE W. CARTER DEPT OF VAMC" },
  { state: "FL", id: "516", name: "C.W. BILL YOUNG DEPT OF VAMC" },
  { state: "FL", id: "675GF", name: "CLERMONT CBOC" },
  { state: "FL", id: "546GH", name: "DEERFIELD BEACH CLINIC" },
  { state: "FL", id: "548GB", name: "DELRAY BEACH VA CLINIC" },
  { state: "FL", id: "520GC", name: "ELGIN AIR FORCE BASE VA CLINIC" },
  { state: "FL", id: "548GA", name: "FORT PIERCE VA CLINIC" },
  { state: "FL", id: "546GF", name: "HOLLYWOOD VA CLINIC" },
  { state: "FL", id: "546GC", name: "HOMESTEAD VA CLINIC" },
  { state: "FL", id: "573GB", name: "JACKSONVILLE CBOC" },
  { state: "FL", id: "673", name: "JAMES A. HALEY VETERANS HOSP" },
  { state: "FL", id: "546GE", name: "KEY LARGO VA CLINIC" },
  { state: "FL", id: "546GB", name: "KEY WEST CBOC" },
  { state: "FL", id: "675GC", name: "KISSIMMEE CBOC" },
  { state: "FL", id: "675GG", name: "LAKE BALDWIN VA CLINIC" },
  { state: "FL", id: "573A4", name: "LAKE CITY VA MEDICAL CENTER" },
  { state: "FL", id: "673GB", name: "LAKELAND VA CLINIC" },
  { state: "FL", id: "573GG", name: "LECANTO VA CLINIC" },
  { state: "FL", id: "516BZ", name: "LEE COUNTY VA CLINIC" },
  { state: "FL", id: "675GE", name: "LEESBURG VA CLINIC" },
  { state: "FL", id: "573", name: "MALCOM RANDALL DEPT OF VAMC" },
  { state: "FL", id: "573GK", name: "MARIANNA VA CLINIC" },
  { state: "FL", id: "546GA", name: "MIAMI (ALCOHOL/DRUG)" },
  { state: "FL", id: "516GF", name: "NAPLES VA CLINIC" },
  { state: "FL", id: "573GD", name: "OCALA VA CLINIC" },
  { state: "FL", id: "548GF", name: "OKEECHOBEE VA CLINIC" },
  { state: "FL", id: "675GD", name: "ORANGE CITY VA CLINIC" },
  { state: "FL", id: "675", name: "ORLANDO VAMC" },
  { state: "FL", id: "573GL", name: "PALATKA VA CLINIC" },
  { state: "FL", id: "516GC", name: "PALM HARBOR VA CLINIC" },
  { state: "FL", id: "520GB", name: "PANAMA CITY BEACH VA CLINIC" },
  { state: "FL", id: "546GD", name: "PEMBROKE PINES VA CLINIC" },
  { state: "FL", id: "573GN", name: "PERRY VA CLINIC" },
  { state: "FL", id: "516GE", name: "PORT CHARLOTTE VA CLINIC" },
  { state: "FL", id: "573GE", name: "SAINT AUGUSTINE VA CLINIC" },
  { state: "FL", id: "516GA", name: "SARASOTA COUNTY CBOC" },
  { state: "FL", id: "516GH", name: "SEBRING VA CLINIC" },
  { state: "FL", id: "516GB", name: "ST. PETERSBURG VA CLINIC" },
  { state: "FL", id: "548GC", name: "STUART VA CLINIC" },
  { state: "FL", id: "573GI", name: "THE VILLAGES VA CLINIC" },
  { state: "FL", id: "548GE", name: "VERO BEACH VA CLINIC" },
  { state: "FL", id: "675GA", name: "VIERA VA CLINIC" },
  { state: "FL", id: "548", name: "WEST PALM BEACH VAMC" },
  { state: "FL", id: "673GF", name: "ZEPHYRHILLS VA CLINIC" },
  { state: "GA", id: "557GB", name: "ALBANY VA CBOC" },
  { state: "GA", id: "509GA", name: "ATHENS CBOC" },
  { state: "GA", id: "508GA", name: "ATLANTA VA CBOC" },
  { state: "GA", id: "508", name: "ATLANTA VAMC" },
  { state: "GA", id: "509", name: "AUGUSTA VAMC" },
  { state: "GA", id: "509A0", name: "AUGUSTA VAMC - UPTOWN" },
  { state: "GA", id: "508GF", name: "AUSTELL CBOC" },
  { state: "GA", id: "557GC", name: "BALDWIN CBOC" },
  { state: "GA", id: "508GJ", name: "BLAIRSVILLE CBOC" },
  { state: "GA", id: "557GE", name: "BRUNSWICK CBOC" },
  { state: "GA", id: "508GK", name: "CARROLLTON CBOC" },
  { state: "GA", id: "619GA", name: "CENTRAL ALABAMA HCS - COLUMBUS CBOC" },
  { state: "GA", id: "557", name: "DUBLIN" },
  { state: "GA", id: "534GE", name: "HINESVILLE CBOC" },
  { state: "GA", id: "508GH", name: "LAWRENCEVILLE CBOC" },
  { state: "GA", id: "557GA", name: "MACON VA CBOC" },
  { state: "GA", id: "508GI", name: "NEWNAN CBOC" },
  { state: "GA", id: "508GE", name: "OAKWOOD VA CLINIC" },
  { state: "GA", id: "534BY", name: "SAVANNAH PRIMARY CARE CLINIC" },
  { state: "GA", id: "573GJ", name: "ST. MARYS VA CLINIC" },
  { state: "GA", id: "508GG", name: "STOCKBRIDGE CBOC" },
  { state: "GA", id: "573GA", name: "VALDOSTA CBOC" },
  { state: "GU", id: "459GE", name: "GUAM CBOC" },
  { state: "HI", id: "459GB", name: "HILO CBOC" },
  { state: "HI", id: "459GD", name: "KAUAI CBOC" },
  { state: "HI", id: "459GC", name: "KONA CBOC" },
  { state: "HI", id: "459GG", name: "LEEWARD OAHU CBOC" },
  { state: "HI", id: "459GA", name: "MAUI VA CLINIC" },
  { state: "IA", id: "636GF", name: "BETTENDORF COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "IA", id: "636GM", name: "CARROLL CBOC" },
  { state: "IA", id: "636GN", name: "CEDAR RAPIDS CBOC" },
  { state: "IA", id: "636GU", name: "DECORAH CBOC" },
  { state: "IA", id: "636GJ", name: "DUBUQUE COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "IA", id: "636GK", name: "FORT DODGE CBOC" },
  { state: "IA", id: "636A8", name: "IOWA CITY HCS" },
  { state: "IA", id: "636GR", name: "KNOXVILLE CBOC" },
  { state: "IA", id: "636GD", name: "MARSHALLTOWN COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "IA", id: "636GC", name: "MASON CITY COMMINITY BASED OUTPATIENT CLINIC" },
  { state: "IA", id: "636GS", name: "OTTUMWA CBOC" },
  { state: "IA", id: "636GP", name: "SHENANDOAH CBOC" },
  { state: "IA", id: "438GC", name: "SIOUX CITY CBOC" },
  { state: "IA", id: "438GA", name: "SPIRIT LAKE CBOC" },
  { state: "IA", id: "636A6", name: "VA CIHS, DES MOINES DIVISION" },
  { state: "IA", id: "636GH", name: "WATERLOO COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "ID", id: "531", name: "BOISE VA MEDICAL CENTER" },
  { state: "ID", id: "531GG", name: "CALDWELL VA CLINIC" },
  { state: "ID", id: "668GB", name: "COEUR D ALENE VA CLINIC" },
  { state: "ID", id: "687GB", name: "LEWISTON VA CLINIC" },
  { state: "ID", id: "531GE", name: "TWIN FALLS VA CLINIC" },
  { state: "ID", id: "660GA", name: "VA POCATELLO CBOC (660GA)" },
  { state: "IL", id: "578GD", name: "AURORA CBOC (578GD)" },
  { state: "IL", id: "657GA", name: "BELLEVILLE IL CBOC (657GA)" },
  { state: "IL", id: "537HA", name: "BEVERLY CBOC" },
  { state: "IL", id: "556", name: "CAPTN JAMES LOVELL FED HLT CTR" },
  { state: "IL", id: "657GT", name: "CARBONDALE CBOC" },
  { state: "IL", id: "537GA", name: "CHICAGO HEIGHTS CBOC" },
  { state: "IL", id: "550", name: "DANVILLE VA MEDICAL CENTER" },
  { state: "IL", id: "550GA", name: "DECATUR VA CLINIC" },
  { state: "IL", id: "578", name: "EDWARD J. HINES JR. HOSPITAL" },
  { state: "IL", id: "657GM", name: "EFFINGHAM VA CLINIC" },
  { state: "IL", id: "578GE", name: "ELGIN CBOC (578GE)" },
  { state: "IL", id: "556GA", name: "EVANSTON CBOC" },
  { state: "IL", id: "607GF", name: "FREEPORT CBOC" },
  { state: "IL", id: "636GI", name: "GALESBURG COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "IL", id: "657GU", name: "HARRISBURG CBOC" },
  { state: "IL", id: "537", name: "JESSE BROWN VA MEDICAL CENTER" },
  { state: "IL", id: "578GA", name: "JOLIET CBOC (578GA)" },
  { state: "IL", id: "578GC", name: "KANKAKEE COUNTY CBOC" },
  { state: "IL", id: "537GD", name: "LAKESIDE CBOC" },
  { state: "IL", id: "578GF", name: "LASSALLE CBOC (578GF)" },
  { state: "IL", id: "550GF", name: "MATTOON CBOC" },
  { state: "IL", id: "556GC", name: "MCHENRY CBOC" },
  { state: "IL", id: "657GK", name: "MT. VERNON IL CBOC (657GK)" },
  { state: "IL", id: "578GG", name: "OAK LAWN CBOC (578GG)" },
  { state: "IL", id: "636GG", name: "QUINCY COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "IL", id: "607HA", name: "ROCKFORD, IL OPC" },
  { state: "IL", id: "550GD", name: "SPRINGFIELD VA CLINIC" },
  { state: "IL", id: "636GT", name: "STERLING CBOC" },
  { state: "IL", id: "657A5", name: "VA HEARTLAND-EAST, VISN 15 HCS MARION IL DIVISION" },
  { state: "IN", id: "583GB", name: "BLOOMINGTON VA CLINIC" },
  { state: "IN", id: "657GJ", name: "EVANSVILLE IL CBOC" },
  { state: "IN", id: "610A4", name: "FORT WAYNE VA MEDICAL CENTER" },
  { state: "IN", id: "610GC", name: "GOSHEN VA CLINIC" },
  { state: "IN", id: "550GC", name: "LAFAYETTE, IN CBOC" },
  { state: "IN", id: "539GC", name: "LAWRENCEBURG (DEARBORN COUNTY)" },
  { state: "IN", id: "610", name: "MARION VA MEDICAL CENTER" },
  { state: "IN", id: "583GC", name: "MARTINSVILLE VA CLINIC" },
  { state: "IN", id: "610GB", name: "MUNCIE VA CLINIC" },
  { state: "IN", id: "603GB", name: "NEW ALBANY VA CLINIC" },
  { state: "IN", id: "610GD", name: "PERU VA CLINIC" },
  { state: "IN", id: "583", name: "RICHARD L. ROUDEBUSH VAMC" },
  { state: "IN", id: "552GC", name: "RICHMOND CBOC" },
  { state: "IN", id: "603GG", name: "SCOTT COUNTY VA CLINIC" },
  { state: "IN", id: "610GA", name: "SOUTH BEND VA CLINIC" },
  { state: "IN", id: "583GA", name: "TERRE HAUTE VA CLINIC" },
  { state: "IN", id: "657GQ", name: "VINCENNES IN CBOC" },
  { state: "KS", id: "589GM", name: "CHANUTE VA CLINIC" },
  { state: "KS", id: "589A5", name: "COLMERY O NEIL VAMC" },
  { state: "KS", id: "589G2", name: "DODGE CITY VA CLINIC" },
  { state: "KS", id: "589A6", name: "DWIGHT D. EISENHOWER VAMC" },
  { state: "KS", id: "589GN", name: "EMPORIA VA CLINIC" },
  { state: "KS", id: "589G9", name: "FORT RILEY CBOC" },
  { state: "KS", id: "589GV", name: "FORT SCOTT VA CLINIC" },
  { state: "KS", id: "589GP", name: "GARNETT VA CLINIC" },
  { state: "KS", id: "589G4", name: "HAYS CBOC" },
  { state: "KS", id: "589G7", name: "HUTCHINSON CBOC" },
  { state: "KS", id: "677HQ", name: "JUNCTION CITY CBOC" },
  { state: "KS", id: "589GR", name: "JUNCTION CITY VA CLINIC" },
  { state: "KS", id: "589GU", name: "LAWRENCE VA CLINIC" },
  { state: "KS", id: "589G3", name: "LIBERAL CBOC" },
  { state: "KS", id: "589GC", name: "PAOLA VA CLINIC" },
  { state: "KS", id: "589G5", name: "PARSONS CBOC" },
  { state: "KS", id: "589A7", name: "ROBERT J. DOLE  VAMC" },
  { state: "KS", id: "589GW", name: "SALINA CBOC WICHITA" },
  { state: "KS", id: "589GT", name: "SENECA VA CLINIC" },
  { state: "KS", id: "589GJ", name: "WYANDOTTE COUNTY VA CLINIC" },
  { state: "KY", id: "539GA", name: "BELLEVUE CBOC" },
  { state: "KY", id: "596GD", name: "BEREA VA CLINIC" },
  { state: "KY", id: "626GC", name: "BOWLING GREEN COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "KY", id: "603GH", name: "CARROLLTON VA CLINIC" },
  { state: "KY", id: "539A4", name: "CINCINNATI VAMC FORT THOMAS" },
  { state: "KY", id: "603GD", name: "DUPONT VA CLINIC" },
  { state: "KY", id: "539GD", name: "FLORENCE CBOC" },
  { state: "KY", id: "603GF", name: "GRAYSON COUNTY VA CLINIC" },
  { state: "KY", id: "657GO", name: "HANSON KY CBOC (657GO)" },
  { state: "KY", id: "596GC", name: "HAZARD VA CLINIC" },
  { state: "KY", id: "626GJ", name: "HOPKINSVILLE VA CLINIC" },
  { state: "KY", id: "596HA", name: "LEXINGTON MOBILE OUTREACH CLINIC" },
  { state: "KY", id: "596", name: "LEXINGTON VAMC-LEESTOWN" },
  { state: "KY", id: "596A4", name: "LEXINGTON VETERANS AFFAIRS MEDICAL CENTER" },
  { state: "KY", id: "657GR", name: "MAYFIELD VA CBOC" },
  { state: "KY", id: "596GB", name: "MOREHEAD VA CLINIC" },
  { state: "KY", id: "603GE", name: "NEWBURG VA CLINIC" },
  { state: "KY", id: "657GP", name: "OWENSBORO KY CBOC" },
  { state: "KY", id: "657GL", name: "PADUCAH KY CBOC (657GL)" },
  { state: "KY", id: "581GA", name: "PRESTONSBURG CBOC" },
  { state: "KY", id: "603", name: "ROBLEY REX VAMC" },
  { state: "KY", id: "603GC", name: "SHIVELY VA CLINIC" },
  { state: "KY", id: "596GA", name: "SOMERSET VA CLINIC" },
  { state: "KY", id: "603GA", name: "VA HEALTHCARE CENTER, FT. KNOX" },
  { state: "LA", id: "502", name: "ALEXANDRIA VA MEDICAL CENTER" },
  { state: "LA", id: "629GF", name: "BOGALUSA CBOC" },
  { state: "LA", id: "502GF", name: "FORT POLK VA CLINIC" },
  { state: "LA", id: "629GE", name: "FRANKLIN CBOC" },
  { state: "LA", id: "629GB", name: "HAMMOND CBOC" },
  { state: "LA", id: "629GA", name: "HOUMA CBOC" },
  { state: "LA", id: "502GA", name: "JENNINGS CBOC" },
  { state: "LA", id: "502GB", name: "LAFAYETTE VA CLINIC" },
  { state: "LA", id: "667GB", name: "MONROE VA CLINIC" },
  { state: "LA", id: "502GG", name: "NATCHITOCHES VA CLINIC" },
  { state: "LA", id: "667", name: "OVERTON BROOKS VA MEDICAL CENTER" },
  { state: "LA", id: "629", name: "SE LOUISIANA VETERANS HCS" },
  { state: "LA", id: "629GC", name: "SLIDELL CBOC" },
  { state: "LA", id: "629GD", name: "ST. JOHN VA OUTPATIENT CLINIC" },
  { state: "MA", id: "518", name: "EDITH NOURSE ROGERS VAMC" },
  { state: "MA", id: "631GF", name: "FITCHBURG CBOC" },
  { state: "MA", id: "518GG", name: "FITCHBURG CBOC" },
  { state: "MA", id: "518GE", name: "GLOUCESTER VA CLINIC" },
  { state: "MA", id: "631GD", name: "GREENFIELD CBOC" },
  { state: "MA", id: "518GB", name: "HAVERHILL VA CLINIC" },
  { state: "MA", id: "650GB", name: "HYANNIS CBOC" },
  { state: "MA", id: "518GA", name: "LYNN VA CLINIC" },
  { state: "MA", id: "650GA", name: "NEW BEDFORD CBOC" },
  { state: "MA", id: "631GC", name: "PITTSFIELD CBOC" },
  { state: "MA", id: "523GD", name: "PLYMOUTH CBOC" },
  { state: "MA", id: "523", name: "VA BOSTON HEALTHCARE SYSTEM - BOSTON DIVISION" },
  { state: "MA", id: "523A5", name: "VA BOSTON HEALTHCARE SYSTEM - BROCKTON DIVISION" },
  { state: "MA", id: "523GA", name: "VA BOSTON HEALTHCARE SYSTEM - FRAMINGHAM CBOC" },
  { state: "MA", id: "523GC", name: "VA BOSTON HEALTHCARE SYSTEM - QUINCY CBOC" },
  { state: "MA", id: "523A4", name: "VA BOSTON HEALTHCARE SYSTEM - WEST ROXBURY DIVISION" },
  { state: "MA", id: "523GB", name: "VA BOSTON HEALTHCARE SYSTEM - WORCESTER DIVISION" },
  { state: "MA", id: "631", name: "VA CNTRL WSTRN MASSCHUSETS HCS" },
  { state: "MA", id: "631GE", name: "WORCESTER CBOC" },
  { state: "MD", id: "512", name: "BALTIMORE VA MEDICAL CENTER" },
  { state: "MD", id: "512GA", name: "CAMBRIDGE VA CLINIC" },
  { state: "MD", id: "688GD", name: "CHARLOTTE HALL VA CLINIC" },
  { state: "MD", id: "613GA", name: "CUMBERLAND CBOC" },
  { state: "MD", id: "613GG", name: "FORT DETRICK VA CLINIC" },
  { state: "MD", id: "512GF", name: "FORT HOWARD VA CLINIC" },
  { state: "MD", id: "512GG", name: "FORT MEADE VA CLINIC" },
  { state: "MD", id: "512GC", name: "GLEN BURNIE VA CLINIC" },
  { state: "MD", id: "688GC", name: "GREENBELT VA CLINIC" },
  { state: "MD", id: "613GB", name: "HAGERSTOWN VA CLINIC" },
  { state: "MD", id: "512GD", name: "LOCH RAVEN VA CLINIC" },
  { state: "MD", id: "512A5", name: "PERRY POINT VAMC" },
  { state: "MD", id: "512GE", name: "POCOMOKE CITY VA CLINIC" },
  { state: "MD", id: "688GE", name: "S PRINCE GEORGES CITY VA CLINIC" },
  { state: "ME", id: "402HB", name: "BANGOR MAINE CBOC" },
  { state: "ME", id: "402GB", name: "CALAIS MAINE CBOC" },
  { state: "ME", id: "402GA", name: "CARIBOU MAINE CBOC" },
  { state: "ME", id: "402GE", name: "LEWISTON AUBURN CBOC" },
  { state: "ME", id: "402GF", name: "LINCOLN VA CLINIC" },
  { state: "ME", id: "402HC", name: "PORTLAND MAINE MH ORC" },
  { state: "ME", id: "402GC", name: "RUMFORD MAINE CBOC" },
  { state: "ME", id: "402GD", name: "SACO MAINE CBOC" },
  { state: "MI", id: "655", name: "ALEDA E. LUTZ VAMC" },
  { state: "MI", id: "506", name: "ANN ARBOR VA MEDICAL CENTER" },
  { state: "MI", id: "655GF", name: "BAD AXE VA CLINIC" },
  { state: "MI", id: "515", name: "BATTLE CREEK VA MEDICAL CENTER" },
  { state: "MI", id: "515GC", name: "BENTON HARBOR VA CLINIC" },
  { state: "MI", id: "655GG", name: "CADILLAC VA CLINIC" },
  { state: "MI", id: "655GH", name: "CHEBOYGAN COUNTY VA CLINIC" },
  { state: "MI", id: "655GE", name: "CLARE VA CLINIC" },
  { state: "MI", id: "506GB", name: "FLINT VA CLINIC" },
  { state: "MI", id: "655GI", name: "GRAYLING VA CLINIC" },
  { state: "MI", id: "585GA", name: "HANCOCK CBOC" },
  { state: "MI", id: "585", name: "IRON MOUNTAIN VA MEDICAL CENTER" },
  { state: "MI", id: "585GD", name: "IRONWOOD CBOC" },
  { state: "MI", id: "506GC", name: "JACKSON CBOC" },
  { state: "MI", id: "553", name: "JOHN D. DINGELL VAMC" },
  { state: "MI", id: "515GB", name: "LANSING CBOC" },
  { state: "MI", id: "655GD", name: "LT. COL CLEMENT VAN WAGONER VA" },
  { state: "MI", id: "585HA", name: "MARQUETTE CBOC" },
  { state: "MI", id: "585GC", name: "MENOMINEE CBOC" },
  { state: "MI", id: "515GA", name: "MUSKEGON VA CLINIC" },
  { state: "MI", id: "655GC", name: "OSCODA VA CLINIC" },
  { state: "MI", id: "553GB", name: "PONTIAC VA CLINIC" },
  { state: "MI", id: "585HB", name: "SAULT SAINT MARIE CBOC" },
  { state: "MI", id: "655GB", name: "TRAVERSE CITY VA CLINIC" },
  { state: "MI", id: "515BY", name: "WYOMING HEALTH CARE CENTER" },
  { state: "MI", id: "553GA", name: "YALE VA CLINIC" },
  { state: "MI", id: "656GD", name: "ZZ-ALPENA" },
  { state: "MN", id: "618GK", name: "ALBERT LEA CBOC" },
  { state: "MN", id: "437GE", name: "BEMIDJI CBOC" },
  { state: "MN", id: "656GA", name: "BRAINERD VA COMMUNITY OUTPATIENT CLINIC" },
  { state: "MN", id: "437GC", name: "FERGUS FALLS" },
  { state: "MN", id: "618GB", name: "HIBBING (CBOC)" },
  { state: "MN", id: "656GC", name: "MAX J. BEILKE CBOC" },
  { state: "MN", id: "618", name: "MINNEAPOLIS VA HCS" },
  { state: "MN", id: "656GB", name: "MONTEVIDEO CBOC" },
  { state: "MN", id: "618GI", name: "NORTHWEST METRO VA OPC" },
  { state: "MN", id: "618GG", name: "ROCHESTER (CBOC)" },
  { state: "MN", id: "618GA", name: "SOUTH CENTRAL CBOC" },
  { state: "MN", id: "656", name: "ST. CLOUD VA HEALTH CARE SYSTEM" },
  { state: "MN", id: "618GD", name: "ST. PAUL (CBOC)" },
  { state: "MO", id: "589GB", name: "BELTON VA CLINIC" },
  { state: "MO", id: "564GC", name: "BRANSON CBOC" },
  { state: "MO", id: "589GZ", name: "CAMERON CBOC" },
  { state: "MO", id: "657GH", name: "CAPE GIRARDEAU MO CBOC (657GH)" },
  { state: "MO", id: "589JB", name: "EXCELSIOR SPRINGS CBOC" },
  { state: "MO", id: "657GI", name: "FARMINTON MO CBOC (657GI)" },
  { state: "MO", id: "589GF", name: "FORT LEONARD WOOD VA CLINIC" },
  { state: "MO", id: "589A4", name: "HARRY S. TRUMAN VAMC" },
  { state: "MO", id: "589JF", name: "HONOR VA CLINIC" },
  { state: "MO", id: "589G8", name: "JEFFERSON CITY, MO CBOC" },
  { state: "MO", id: "589GE", name: "KIRKSVILLE VA CLINIC" },
  { state: "MO", id: "589GH", name: "LAKE OF THE OZARKS VA CLINIC" },
  { state: "MO", id: "589JD", name: "MARSHFIELD CBOC" },
  { state: "MO", id: "589GX", name: "MEXICO CBOC (MO)" },
  { state: "MO", id: "589GD", name: "NEVADA VA CLINIC" },
  { state: "MO", id: "589JE", name: "PLATTE CITY VA CLINIC" },
  { state: "MO", id: "657GN", name: "SALEM MO MOBILE OUTREACH CLINIC (657GN)" },
  { state: "MO", id: "589JA", name: "SEDALIA CBOC" },
  { state: "MO", id: "657GV", name: "SIKESTON CBOC" },
  { state: "MO", id: "657GD", name: "ST CHARLES MO CBOC (657GD)" },
  { state: "MO", id: "657GB", name: "ST LOUIS MO CBOC (657GB)" },
  { state: "MO", id: "589GY", name: "ST. JAMES VA CLINIC" },
  { state: "MO", id: "589GI", name: "ST. JOSEPH VA CLINIC" },
  { state: "MO", id: "589", name: "VA HEARTLAND - WEST, VISN 15 (589)" },
  { state: "MO", id: "657A0", name: "VA HEARTLAND-EAST, VISN 15 HCS JEFFERSON BARRACKS" },
  { state: "MO", id: "657", name: "VA HEARTLAND-EAST, VISN 15 HCS JOHN COCHRAN MEMORIAL HOSPITAL" },
  { state: "MO", id: "657A4", name: "VA HEARTLAND-EAST, VISN 15 HCS JOHN PERSHING VA MEDICAL CENTER" },
  { state: "MO", id: "589G1", name: "WARRENSBURG MO CBOC" },
  { state: "MO", id: "657GS", name: "WASHINGTON CBOC" },
  { state: "MO", id: "657GF", name: "WEST PLAINS MO CBOC (657GF)" },
  { state: "MS", id: "520", name: "BILOXI VA MEDICAL CENTER" },
  { state: "MS", id: "586GF", name: "COLUMBUS" },
  { state: "MS", id: "586", name: "G.V. (SONNY) MONTGOMERY" },
  { state: "MS", id: "586GC", name: "GREENVILLE" },
  { state: "MS", id: "520A0", name: "GULFPORT VAMC" },
  { state: "MS", id: "586GD", name: "HATTIESBURG" },
  { state: "MS", id: "586GA", name: "KOSCIUSKO VA CLINIC" },
  { state: "MS", id: "614GC", name: "MARSHALL COUNTY VA CLINIC" },
  { state: "MS", id: "586GG", name: "MCCOMB CBOC" },
  { state: "MS", id: "586GB", name: "MERIDIAN" },
  { state: "MS", id: "586GE", name: "NATCHEZ" },
  { state: "MS", id: "614GA", name: "TUPELO CBOC" },
  { state: "MT", id: "436GA", name: "ANACONDA CBOC" },
  { state: "MT", id: "436GH", name: "BILLINGS VA CLINIC" },
  { state: "MT", id: "436GD", name: "BOZEMAN VA CLINIC" },
  { state: "MT", id: "436GL", name: "CUT BANK VA CLINIC" },
  { state: "MT", id: "436GI", name: "GLASGOW VA CLINIC" },
  { state: "MT", id: "436GK", name: "GLENDIVE VA CLINIC" },
  { state: "MT", id: "436GB", name: "GREAT FALLS CBOC" },
  { state: "MT", id: "436GF", name: "KALISPELL VA CLINIC" },
  { state: "MT", id: "436GM", name: "LEWISTON CBOC" },
  { state: "MT", id: "436GJ", name: "MILES CITY VA CLINIC" },
  { state: "MT", id: "436A4", name: "MILES CITY VA MEDICAL CENTER" },
  { state: "MT", id: "436GC", name: "MISSOULA CBOC" },
  { state: "NC", id: "590GC", name: "ALBEMARLE CBOC" },
  { state: "NC", id: "637", name: "CHARLES GEORGE VAMC" },
  { state: "NC", id: "558", name: "DURHAM VA MEDICAL CENTER" },
  { state: "NC", id: "565", name: "FAYETTEVILLE VA MEDICAL CENTER" },
  { state: "NC", id: "637GA", name: "FRANKLIN VA CLINIC" },
  { state: "NC", id: "565GF", name: "GOLDSBORO VA CLINIC" },
  { state: "NC", id: "558GA", name: "GREENVILLE VA CLINIC" },
  { state: "NC", id: "565GD", name: "HAMLET VA CLINIC" },
  { state: "NC", id: "659GB", name: "HICKORY CBOC" },
  { state: "NC", id: "565GA", name: "JACKSONVILLE VA CLINIC" },
  { state: "NC", id: "558GC", name: "MOREHEAD CITY VA CLINIC" },
  { state: "NC", id: "659GA", name: "NORTH CHARLOTTE VA CLINIC" },
  { state: "NC", id: "558GB", name: "RALEIGH VA CLINIC" },
  { state: "NC", id: "565GE", name: "ROBESON COUNTY VA CLINIC" },
  { state: "NC", id: "637GB", name: "RUTHERFORD COUNTY VA CLINIC" },
  { state: "NC", id: "659", name: "W.G. HEFNER SALISBURY VAMC" },
  { state: "NC", id: "565GC", name: "WILMINGTON VA CLINIC" },
  { state: "NC", id: "659BY", name: "WINSTON-SALEM,OPC" },
  { state: "ND", id: "437GB", name: "BISMARCK" },
  { state: "ND", id: "437GA", name: "GRAFTON" },
  { state: "ND", id: "437GI", name: "GRAND FORKS CBOC" },
  { state: "ND", id: "437GD", name: "MINOT CBOC" },
  { state: "ND", id: "437GF", name: "WILLISTON CBOC" },
  { state: "NE", id: "636GL", name: "BELLEVUE VA CBOC" },
  { state: "NE", id: "568HB", name: "GORDON CBOC" },
  { state: "NE", id: "636GQ", name: "HOLDREGE, NE CBOC" },
  { state: "NE", id: "636GA", name: "NORFOLK CBOC" },
  { state: "NE", id: "636GB", name: "NORTH PLATTE CBOC" },
  { state: "NE", id: "568HH", name: "SCOTTSBLUFF CBOC" },
  { state: "NE", id: "442GB", name: "SIDNEY VA CLINC" },
  { state: "NE", id: "636A5", name: "VA CENTRAL PLAINS HEALTH NETWORK - LINCOLN DIVISION" },
  { state: "NE", id: "636", name: "VA CENTRAL PLAINS HEALTH NETWORK - OMAHA DIVISION" },
  { state: "NE", id: "636A4", name: "VA NWIHS, GRAND ISLAND DIV" },
  { state: "NH", id: "608GD", name: "CONWAY CBOC" },
  { state: "NH", id: "405HE", name: "KEENE OUT REACH CENTER" },
  { state: "NH", id: "608", name: "MANCHESTER VAMC" },
  { state: "NH", id: "608GA", name: "PORTSMOUTH CBOC" },
  { state: "NH", id: "608GC", name: "SOMERSWORTH CBOC" },
  { state: "NH", id: "405HC", name: "ST. JOHNSBURY VERMONT OUTREACH CLINIC" },
  { state: "NH", id: "608HA", name: "TILTON CBOC" },
  { state: "NJ", id: "460HE", name: "ATLANTIC COUNTY VA CLINIC" },
  { state: "NJ", id: "460GD", name: "CAPE MAY (WILMINGTON)" },
  { state: "NJ", id: "460HG", name: "CUMBERLAND COUNTY VA CLINIC" },
  { state: "NJ", id: "561GB", name: "ELIZABETH CBOC" },
  { state: "NJ", id: "642GA", name: "FT. DIX (PHILADELPHIA) CBOC" },
  { state: "NJ", id: "561GD", name: "HACKENSACK CBOC" },
  { state: "NJ", id: "561GA", name: "HAMILTON CBOC" },
  { state: "NJ", id: "561BZ", name: "JAMES J HOWARD OUTPATIENT CLINIC" },
  { state: "NJ", id: "561GE", name: "JERSEY CITY CBOC" },
  { state: "NJ", id: "561GH", name: "MORRIS PLAINS CBOC" },
  { state: "NJ", id: "561", name: "NEW JERSEY HEALTH CARE SYSTEM - EAST ORANGE" },
  { state: "NJ", id: "561A4", name: "NEW JERSEY HEALTH CARE SYSTEM - LYONS CAMPUS" },
  { state: "NJ", id: "561GJ", name: "PATERSON CBOC" },
  { state: "NJ", id: "561GF", name: "PISCATAWAY CBOC" },
  { state: "NJ", id: "561GI", name: "TINTON FALLS CBOC" },
  { state: "NJ", id: "642GD", name: "VET HEALTH CLINIC (GLOUCESTER)" },
  { state: "NM", id: "501GI", name: "ALAMOGORDO VA CLINIC" },
  { state: "NM", id: "501GA", name: "ARTESIA VA CLINIC" },
  { state: "NM", id: "501GE", name: "ESPANOLA (CBOC)" },
  { state: "NM", id: "501GB", name: "FARMINGTON VA CLINIC" },
  { state: "NM", id: "501GD", name: "GALLUP VA CLINIC" },
  { state: "NM", id: "519GB", name: "HOBBS CBOC" },
  { state: "NM", id: "756GA", name: "LAS CRUCES CBOC" },
  { state: "NM", id: "501G2", name: "LAS VEGAS (CBOC)" },
  { state: "NM", id: "501GM", name: "NORTHWEST METRO VA CLINIC" },
  { state: "NM", id: "501HB", name: "RATON (CBOC)" },
  { state: "NM", id: "501", name: "RAYMOND G. MURPHY VAMC" },
  { state: "NM", id: "501GK", name: "SANTA FE VA CLINIC" },
  { state: "NM", id: "501GC", name: "SILVER CITY VA CLINIC" },
  { state: "NM", id: "501GH", name: "TRUTH OR CONSEQUENCES (CBOC)" },
  { state: "NV", id: "654GB", name: "CARSON VALLEY CBOC" },
  { state: "NV", id: "660GC", name: "ELY VA CLINIC" },
  { state: "NV", id: "593GC", name: "PAHRUMP CBOC" },
  { state: "NV", id: "593", name: "SOUTHERN NEVADA HCS" },
  { state: "NV", id: "654GC", name: "VA LAHONTAN VALLEY CBOC" },
  { state: "NV", id: "654", name: "VA SIERRA NEVADA HEALTH CARE SYSTEM (654)" },
  { state: "NY", id: "528G5", name: "AUBURN" },
  { state: "NY", id: "528A6", name: "BATH VA MEDICAL CENTER" },
  { state: "NY", id: "632HC", name: "BAY SHORE CBOC" },
  { state: "NY", id: "528GN", name: "BINGHAMTON CBOC" },
  { state: "NY", id: "526", name: "BRONX VA HOSPITAL" },
  { state: "NY", id: "528", name: "BUFFALO VA MEDICAL CENTER" },
  { state: "NY", id: "528A5", name: "CANANDAIGUA VA MEDICAL CENTER" },
  { state: "NY", id: "528G7", name: "CATSKILL CBOC" },
  { state: "NY", id: "528GY", name: "CLIFTON PARK CBOC" },
  { state: "NY", id: "528G9", name: "CORTLAND" },
  { state: "NY", id: "528GC", name: "DUNKIRK VA CLINIC" },
  { state: "NY", id: "632GA", name: "EAST MEADOW CBOC" },
  { state: "NY", id: "620GH", name: "EASTERN DUTCHESS CBOC" },
  { state: "NY", id: "528G4", name: "ELMIRA CBOC" },
  { state: "NY", id: "528G6", name: "FONDA CBOC" },
  { state: "NY", id: "528GT", name: "GLENS FALLS CBOC" },
  { state: "NY", id: "620GD", name: "GOSHEN CBOC" },
  { state: "NY", id: "630GA", name: "HARLEM CBOC-NYHHS" },
  { state: "NY", id: "620GF", name: "HARRIS" },
  { state: "NY", id: "528GB", name: "JAMESTOWN VA CLINIC" },
  { state: "NY", id: "528GZ", name: "KINGSTON CBOC" },
  { state: "NY", id: "528GQ", name: "LACKAWANNA CBOC" },
  { state: "NY", id: "528GK", name: "LOCKPORT" },
  { state: "NY", id: "528G1", name: "MALONE CBOC" },
  { state: "NY", id: "528GL", name: "MASSENA CBOC" },
  { state: "NY", id: "620GA", name: "NEW CITY" },
  { state: "NY", id: "528GD", name: "NIAGARA FALLS VA CLINIC" },
  { state: "NY", id: "526GD", name: "NORTH QUEENS CLINIC" },
  { state: "NY", id: "632", name: "NORTHPORT VAMC NY" },
  { state: "NY", id: "528GR", name: "OLEAN CBOC" },
  { state: "NY", id: "528GP", name: "OSWEGO CBOC" },
  { state: "NY", id: "632HD", name: "PATCHOGUE,NY ORC" },
  { state: "NY", id: "528GV", name: "PLATTSBURGH" },
  { state: "NY", id: "620GE", name: "PORT JERVIS" },
  { state: "NY", id: "620GG", name: "POUGHKEEPSIE" },
  { state: "NY", id: "620GB", name: "PUTNAM COUNTY" },
  { state: "NY", id: "632HB", name: "RIVERHEAD,NY ORC" },
  { state: "NY", id: "528GE", name: "ROCHESTER OPC" },
  { state: "NY", id: "528GM", name: "ROME CBOC" },
  { state: "NY", id: "528A8", name: "SAMUEL S. STRATTON VAMC" },
  { state: "NY", id: "528GW", name: "SCHENECTADY CBOC" },
  { state: "NY", id: "528G3", name: "SIDNEY CBOC" },
  { state: "NY", id: "630A5", name: "ST ALBANS EXTENDED CARE CNTR" },
  { state: "NY", id: "630GB", name: "STATEN ISLAND CBOC-NYHHCS" },
  { state: "NY", id: "528A7", name: "SYRACUSE VA MEDICAL CENTER" },
  { state: "NY", id: "528GX", name: "TROY CBOC" },
  { state: "NY", id: "528A4", name: "VA HEALTHCARE NETWORK UPSTATE NEW YORK SYSTEM VISN 2 - BATAVIA DIVISION" },
  { state: "NY", id: "620A4", name: "VA HUDSON VALLEY HEALTH CARE - CASTLE POINT DIVISION" },
  { state: "NY", id: "620", name: "VA HUDSON VALLEY HEALTH CARE SYSTEM - MONTROSE DIVISION" },
  { state: "NY", id: "630A4", name: "VA NEW YORK HARBOR HEALTHCARE SYSTEM - BROOKLYN DIVISION" },
  { state: "NY", id: "630", name: "VA NEW YORK HARBOR HEALTHCARE SYSTEM - NEW YORK DIVISION" },
  { state: "NY", id: "632HA", name: "VALLEY STREAM CBOC" },
  { state: "NY", id: "528GO", name: "WATERTOWN CBOC" },
  { state: "NY", id: "528G8", name: "WELLSVILLE CBOC" },
  { state: "NY", id: "528G2", name: "WESTPORT CBOC" },
  { state: "NY", id: "526GA", name: "WHITE PLAINS CLINIC" },
  { state: "NY", id: "526GB", name: "YONKERS CLINIC" },
  { state: "OH", id: "541GG", name: "AKRON CBOC" },
  { state: "OH", id: "562GB", name: "ASHTABULA COUNTY CBOC (562GB)" },
  { state: "OH", id: "538GA", name: "ATHENS VA CLINIC" },
  { state: "OH", id: "646GA", name: "BELMONT COUNTY CBOC" },
  { state: "OH", id: "538GE", name: "CAMBRIDGE VA CLINIC" },
  { state: "OH", id: "541BY", name: "CANTON CBOC" },
  { state: "OH", id: "757", name: "CHALMERS P. WYLIE VA AMBULATORY CARE CENTER (757)" },
  { state: "OH", id: "538", name: "CHILLICOTHE VA MEDICAL CENTER" },
  { state: "OH", id: "539GB", name: "CINCINNATI (CLERMONT COUNTY)" },
  { state: "OH", id: "539", name: "CINCINNATI VAMC" },
  { state: "OH", id: "541GM", name: "CLEVELAND AMBULATORY CTR CBOC" },
  { state: "OH", id: "541", name: "CLEVELAND VAMC" },
  { state: "OH", id: "552", name: "DAYTON, OH VAMC" },
  { state: "OH", id: "541GH", name: "EAST LIVERPOOL CBOC" },
  { state: "OH", id: "539GF", name: "GEORGETOWN CBOC" },
  { state: "OH", id: "757GB", name: "GROVE CITY CBOC" },
  { state: "OH", id: "539GE", name: "HAMILTON OHIO CBOC" },
  { state: "OH", id: "538GD", name: "LANCASTER VA CLINIC" },
  { state: "OH", id: "552GB", name: "LIMA CBOC" },
  { state: "OH", id: "541GB", name: "LORAIN CBOC" },
  { state: "OH", id: "541GD", name: "MANSFIELD CBOC" },
  { state: "OH", id: "538GC", name: "MARIETTA VA CLINIC" },
  { state: "OH", id: "757GC", name: "MARION CBOC" },
  { state: "OH", id: "541GE", name: "MCCAFERTY CBOC" },
  { state: "OH", id: "552GA", name: "MIDDLETOWN CBOC" },
  { state: "OH", id: "541GJ", name: "NEW PHILADELPHIA CBOC" },
  { state: "OH", id: "757GD", name: "NEWARK CBOC" },
  { state: "OH", id: "541GF", name: "PAINSVILLE CBOC" },
  { state: "OH", id: "541GL", name: "PARMA CBOC" },
  { state: "OH", id: "538GB", name: "PORTSMOUTH VA CLINIC" },
  { state: "OH", id: "541GK", name: "RAVENNA CBOC" },
  { state: "OH", id: "541GC", name: "SANDUSKY CBOC" },
  { state: "OH", id: "552GD", name: "SPRINGFIELD CBOC" },
  { state: "OH", id: "506GA", name: "TOLEDO VA CLINIC" },
  { state: "OH", id: "541GI", name: "WARREN CBOC" },
  { state: "OH", id: "541BZ", name: "YOUNGSTOWN CBOC" },
  { state: "OH", id: "757GA", name: "ZANESVILLE CBOC" },
  { state: "OK", id: "635GD", name: "ADA CBOC" },
  { state: "OK", id: "635GF", name: "ALTUS CBOC" },
  { state: "OK", id: "635HB", name: "ARDMORE VETERANS CENTER CLINIC" },
  { state: "OK", id: "635GC", name: "BLACKWELL CBOC" },
  { state: "OK", id: "635GG", name: "ENID CBOC" },
  { state: "OK", id: "623GA", name: "HARTSHORNE CBOC" },
  { state: "OK", id: "564GE", name: "JAY CBOC" },
  { state: "OK", id: "623", name: "MUSKOGEE, OK VAMC" },
  { state: "OK", id: "635", name: "OKLAHOMA CITY VA MEDICAL CENTER" },
  { state: "OK", id: "635GE", name: "STILLWATER CBOC" },
  { state: "OK", id: "623BY", name: "TULSA, OK CBOC" },
  { state: "OK", id: "623GB", name: "VINITA CBOC" },
  { state: "OR", id: "648GA", name: "BEND, OR CBOC" },
  { state: "OR", id: "653GB", name: "BROOKINGS VA CLINIC" },
  { state: "OR", id: "648GE", name: "EAST PORTLAND VA CLINIC" },
  { state: "OR", id: "653BY", name: "EUGENE, OR CBOC" },
  { state: "OR", id: "692GB", name: "GRANTS PASS CBOC" },
  { state: "OR", id: "648GF", name: "HILLSBORO VA CLINIC" },
  { state: "OR", id: "692GA", name: "KLAMATH FALLS VA CLINIC" },
  { state: "OR", id: "687GC", name: "LA GRANDE CBOC" },
  { state: "OR", id: "653GA", name: "NORTH BEND VA CLINIC" },
  { state: "OR", id: "648GD", name: "NORTH COAST VA CLINIC" },
  { state: "OR", id: "648", name: "PORTLAND VA MEDICAL CENTER" },
  { state: "OR", id: "653", name: "ROSEBURG VA MEDICAL CENTER" },
  { state: "OR", id: "648GB", name: "SALEM VA CLINIC" },
  { state: "OR", id: "648GG", name: "WEST LINN CBOC" },
  { state: "OR", id: "692", name: "WHITE CITY VA MEDICAL CENTER" },
  { state: "PA", id: "646GC", name: "BEAVER CBOC" },
  { state: "PA", id: "595GD", name: "BERKS VA OUTPATIENT CLINIC" },
  { state: "PA", id: "693GF", name: "BERWICK CBOC" },
  { state: "PA", id: "529GC", name: "BUTLER VAMC - ARMSTRONG CBOC" },
  { state: "PA", id: "529GB", name: "BUTLER VAMC - LAWRENCE CBOC" },
  { state: "PA", id: "529GA", name: "BUTLER VAMC - MERCER CBOC" },
  { state: "PA", id: "529", name: "BUTLER VETERANS AFFAIRS MEDICAL CENTER" },
  { state: "PA", id: "595GA", name: "CAMPHILL CLINIC" },
  { state: "PA", id: "529GD", name: "CLARION COUNTY VA CLINIC" },
  { state: "PA", id: "542", name: "COATESVILLE VA MEDICAL CENTER" },
  { state: "PA", id: "529GF", name: "CRANBERRY TOWNSHIP CBOC" },
  { state: "PA", id: "562GA", name: "CRAWFORD COUNTY CBOC" },
  { state: "PA", id: "503GB", name: "DUBOIS CBOC" },
  { state: "PA", id: "562", name: "ERIE VAMC" },
  { state: "PA", id: "646GE", name: "FAYETTE COUNTY CBOC" },
  { state: "PA", id: "503GD", name: "HUNTINGDON COUNTY VA CLINIC" },
  { state: "PA", id: "503GE", name: "INDIANA COUNTY VA CLINIC" },
  { state: "PA", id: "503", name: "JAMES E VAN ZANDT VAMC" },
  { state: "PA", id: "503GA", name: "JOHNSTOWN VA CLINIC" },
  { state: "PA", id: "595GC", name: "LANCASTER VA OUTPATIENT CLINIC" },
  { state: "PA", id: "595", name: "LEBANON VA MEDICAL CENTER" },
  { state: "PA", id: "562GC", name: "MCKEAN COUNTY CBOC (562GC)" },
  { state: "PA", id: "542GA", name: "MEDIA CBOC" },
  { state: "PA", id: "693GG", name: "NORTHAMPTON COUNTY CLINIC" },
  { state: "PA", id: "642", name: "PHILADELPHIA, PA VAMC" },
  { state: "PA", id: "646", name: "PITTSBURGH HEALTH CARE SYSTEM - UNIVERSITY DRIVE DIVISION" },
  { state: "PA", id: "595GF", name: "SCHUYLKILL COUNTY CBOC" },
  { state: "PA", id: "693GE", name: "SCHUYLKILL COUNTY CBOC" },
  { state: "PA", id: "542GE", name: "SPRING CITY CBOC" },
  { state: "PA", id: "503GC", name: "STATE COLLEGE VA CLINIC" },
  { state: "PA", id: "693GC", name: "TOBYHANNA CBOC" },
  { state: "PA", id: "646A4", name: "VA HEALTH CARE SYSTEM HEINZ DIVISION" },
  { state: "PA", id: "562GD", name: "VENANGO COUNTY CLINIC" },
  { state: "PA", id: "642GC", name: "VICTOR J SARACINI VA OPC" },
  { state: "PA", id: "562GE", name: "WARREN COUNTY CLINIC" },
  { state: "PA", id: "646GD", name: "WASHINGTON VA PRIMARY CARE OUTPATIENT CLINIC" },
  { state: "PA", id: "646GB", name: "WESTMORELAND CBOC" },
  { state: "PA", id: "693GD", name: "WILKES-BARRE (CBOC)" },
  { state: "PA", id: "693", name: "WILKES-BARRE VAMC" },
  { state: "PA", id: "693GB", name: "WILLIAMSPORT CBOC" },
  { state: "PA", id: "595GE", name: "YORK VA OUTPATIENT CLINIC" },
  { state: "PR", id: "672GC", name: "ARECIBO VETERANS CLINIC (CBOC)" },
  { state: "PR", id: "672GD", name: "CEIBA VA CLINIC" },
  { state: "PR", id: "672GE", name: "GUAYAMA VA CLINIC" },
  { state: "PR", id: "672", name: "SAN JUAN VA MEDICAL CENTER" },
  { state: "RI", id: "650GD", name: "MIDDLETOWN CBOC" },
  { state: "RI", id: "650", name: "PROVIDENCE VAMC" },
  { state: "SC", id: "509GB", name: "AIKEN CBOC" },
  { state: "SC", id: "544GD", name: "ANDERSON CBOC" },
  { state: "SC", id: "534GC", name: "BEAUFORT PRIMARY CARE CLINIC" },
  { state: "SC", id: "544GB", name: "FLORENCE CBOC" },
  { state: "SC", id: "534GD", name: "GOOSE CREEK CBOC" },
  { state: "SC", id: "534GB", name: "MYRTLE  BEACH PRIMARY CARE CLINIC" },
  { state: "SC", id: "544GE", name: "ORANGEBURG CBOC" },
  { state: "SC", id: "534", name: "RALPH H. JOHNSON VA MEDICAL CENTER (534)" },
  { state: "SC", id: "544GC", name: "ROCK HILL CBOC" },
  { state: "SC", id: "544GG", name: "SPARTANBURG CBOC" },
  { state: "SC", id: "544GF", name: "SUMTER CBOC" },
  { state: "SC", id: "544", name: "WM JENNINGS BRYAN DORN VETERANS AFFAIRS MEDICAL CENTER" },
  { state: "SD", id: "438GD", name: "ABERDEEN CBOC" },
  { state: "SD", id: "568", name: "BLACK HILLS HEALTH CARE SYSTEM - FT. MEADE DIVISION" },
  { state: "SD", id: "568HM", name: "EAGLE BUTTE" },
  { state: "SD", id: "568A4", name: "HOT SPRINGS, SD MC" },
  { state: "SD", id: "568HK", name: "MCLAUGHLIN" },
  { state: "SD", id: "568HJ", name: "MISSION CBOC" },
  { state: "SD", id: "568GB", name: "PIERRE CBOC" },
  { state: "SD", id: "568HF", name: "PINE RIDGE" },
  { state: "SD", id: "568GA", name: "RAPID CITY CBOC" },
  { state: "SD", id: "438GE", name: "WAGNER CBOC" },
  { state: "SD", id: "438GF", name: "WATERTOWN CBOC" },
  { state: "SD", id: "568HP", name: "WINNER" },
  { state: "TN", id: "626A4", name: "ALVIN C. YORK VAMC" },
  { state: "TN", id: "614GH", name: "BOLIVAR CBOC" },
  { state: "TN", id: "621GK", name: "CAMPBELL COUNTY VA CLINIC" },
  { state: "TN", id: "626GF", name: "CHATTANOOGA VA CLINIC" },
  { state: "TN", id: "626GE", name: "CLARKSVILLE VA CLINIC" },
  { state: "TN", id: "626GH", name: "COOKEVILLE VA CLINIC" },
  { state: "TN", id: "614GE", name: "COVINGTON VA CLINIC" },
  { state: "TN", id: "626GA", name: "DOVER VA CLINIC" },
  { state: "TN", id: "614GI", name: "DYERSBURG VA CLINIC" },
  { state: "TN", id: "614GG", name: "JACKSON VA CLINIC" },
  { state: "TN", id: "621", name: "JAMES H. QUILLEN VAMC" },
  { state: "TN", id: "626GM", name: "MAURY COUNTY CBOC" },
  { state: "TN", id: "626GK", name: "MCMINNVILLE VA CLINIC" },
  { state: "TN", id: "614GF", name: "MEMPHIS SOUTH VA CLINIC" },
  { state: "TN", id: "614", name: "MEMPHIS VA MEDICAL CENTER" },
  { state: "TN", id: "621GG", name: "MORRISTOWN VA CLINIC" },
  { state: "TN", id: "626", name: "NASHVILLE VA MEDICAL CENTER" },
  { state: "TN", id: "626GL", name: "ROANE COUNTY VA CLINIC" },
  { state: "TN", id: "621GA", name: "ROGERSVILLE VA CLINIC" },
  { state: "TN", id: "614GD", name: "SAVANNAH VA CLINIC" },
  { state: "TN", id: "621GI", name: "SEVIERVILLE VA CLINIC" },
  { state: "TN", id: "626GG", name: "TULLAHOMA COMMUNITY BASED OUTPATIENT CLINIC" },
  { state: "TN", id: "621BY", name: "WILLIAM C. TALLENT VA OPC" },
  { state: "TX", id: "519HC", name: "ABILENE CBOC" },
  { state: "TX", id: "504", name: "AMARILLO HCS" },
  { state: "TX", id: "674GB", name: "BROWNWOOD, TX  CBOC" },
  { state: "TX", id: "674GC", name: "BRYAN, TX CBOC" },
  { state: "TX", id: "674GD", name: "CEDAR PARK TEXAS CBOC" },
  { state: "TX", id: "674", name: "CENTRAL TEXAS HEALTH CARE SYSTEM - TEMPLE DIVISION" },
  { state: "TX", id: "671GH", name: "CHRISTUS SPOHN AGARITA FAMILY HEALTH CLINIC" },
  { state: "TX", id: "671GI", name: "CHRISTUS SPOHN BISHOP FAMILY HEALTH CLINIC" },
  { state: "TX", id: "671GG", name: "CHRISTUS SPOHN SAN DIEGO FAMILY HEALTH CLINIC" },
  { state: "TX", id: "580GD", name: "CONROE CBOC" },
  { state: "TX", id: "504HB", name: "DALHART CBOC" },
  { state: "TX", id: "671GC", name: "DEL RIO CBOC" },
  { state: "TX", id: "740GE", name: "EAGLE PASS CBOC" },
  { state: "TX", id: "756GB", name: "EL PASO EASTSIDE CBOC" },
  { state: "TX", id: "756", name: "EL PASO HCS" },
  { state: "TX", id: "549BY", name: "FORT WORTH VA CBOC" },
  { state: "TX", id: "519GD", name: "FT. STOCKTON CBOC" },
  { state: "TX", id: "580GC", name: "GALVESTON COUNTY VA CLINIC" },
  { state: "TX", id: "671GJ", name: "HEALTHCARE CLINIC OF UVALDE MEMORIAL HOSPITAL" },
  { state: "TX", id: "580GA", name: "HOUSTON CBOC" },
  { state: "TX", id: "580GE", name: "KATY CBOC" },
  { state: "TX", id: "580GF", name: "LAKE JACKSON CBOC" },
  { state: "TX", id: "667GC", name: "LONGVIEW CBOC" },
  { state: "TX", id: "580", name: "MICHAEL E. DEBAKEY VA MEDICAL CENTER" },
  { state: "TX", id: "671GL", name: "NEW BRAUNFELS VA CLINIC" },
  { state: "TX", id: "549GC", name: "NORTH TEXAS HEALTH CARE SYSTEM - BONHAM CBOC" },
  { state: "TX", id: "549A4", name: "NORTH TEXAS HEALTH CARE SYSTEM - BONHAM DIVISION" },
  { state: "TX", id: "549GI", name: "NORTH TEXAS HEALTH CARE SYSTEM - CLEBURNE CBOC" },
  { state: "TX", id: "549GB", name: "NORTH TEXAS HEALTH CARE SYSTEM - DALLAS CBOC" },
  { state: "TX", id: "549", name: "NORTH TEXAS HEALTH CARE SYSTEM - DALLAS DIVISION" },
  { state: "TX", id: "549GE", name: "NORTH TEXAS HEALTH CARE SYSTEM - DECATUR CBOC" },
  { state: "TX", id: "549GD", name: "NORTH TEXAS HEALTH CARE SYSTEM - DENTON CBOC" },
  { state: "TX", id: "549GF", name: "NORTH TEXAS HEALTH CARE SYSTEM - EASTLAND CBOC" },
  { state: "TX", id: "549GH", name: "NORTH TEXAS HEALTH CARE SYSTEM - GREENVILLE CBOC" },
  { state: "TX", id: "549GA", name: "NORTH TEXAS HEALTH CARE SYSTEM - TYLER CBOC" },
  { state: "TX", id: "674GA", name: "PALESTINE, TX  CMOC" },
  { state: "TX", id: "519GA", name: "PERMIAN BASIN CBOC" },
  { state: "TX", id: "580GG", name: "RICHMOND CBOC" },
  { state: "TX", id: "519HF", name: "SAN ANGELO CBOC" },
  { state: "TX", id: "671GN", name: "SEGUIN" },
  { state: "TX", id: "549GJ", name: "SHERMAN CBOC" },
  { state: "TX", id: "671GF", name: "SOUTH TEXAS HCS" },
  { state: "TX", id: "671A4", name: "SOUTH TEXAS HEALTH CARE SYSTEM - KERRVILLE DIVISION" },
  { state: "TX", id: "671", name: "SOUTH TEXAS HEALTH CARE SYSTEM - SAN ANTONIO DIVISION" },
  { state: "TX", id: "519HD", name: "STAMFORD CBOC" },
  { state: "TX", id: "740", name: "TEXAS VALLEY COASTAL BEND HCS" },
  { state: "TX", id: "580GH", name: "TOMBALL CBOC" },
  { state: "TX", id: "671GD", name: "UNITED MEDICAL CENTERS" },
  { state: "TX", id: "671GA", name: "VA HARLINGEN OUTPATIENT CLINIC" },
  { state: "TX", id: "674A4", name: "WACO, TX VAMC" },
  { state: "TX", id: "671GK", name: "WELLMED AT NORTHWEST 410" },
  { state: "TX", id: "519", name: "WEST TEXAS VA HEALTH CARE SYSTEM - BIG SPRING DIVISION" },
  { state: "TX", id: "635GB", name: "WICHITA FALLS CBOC VETERANS CLINIC OF NORTH TEXAS" },
  { state: "UT", id: "660", name: "GEORGE E. WAHLEN VAMC" },
  { state: "UT", id: "660GB", name: "OGDEN VA CLINIC" },
  { state: "UT", id: "660GE", name: "OREM VA CLINIC" },
  { state: "UT", id: "660GD", name: "ROOSEVELT VA CLINIC" },
  { state: "UT", id: "660GG", name: "ST. GEORGE VA CLINIC" },
  { state: "UT", id: "660GJ", name: "WESTERN SALT LAKE VA CLINIC" },
  { state: "VA", id: "621GJ", name: "BRISTOL VA CLINIC" },
  { state: "VA", id: "652GE", name: "CHARLOTTESVILLE VA CLINIC" },
  { state: "VA", id: "658GB", name: "DANVILLE VA CLINIC" },
  { state: "VA", id: "652GF", name: "EMPORIA VA CLINIC" },
  { state: "VA", id: "688GA", name: "FORT BELVOIR VA CLINIC" },
  { state: "VA", id: "652GA", name: "FREDERICKSBURG VA CLINIC" },
  { state: "VA", id: "590", name: "HAMPTON VA MEDICAL CENTER" },
  { state: "VA", id: "613GF", name: "HARRISONBURG VA CLINIC" },
  { state: "VA", id: "652", name: "HUNTER HOLMES MCGUIRE HOSPITAL" },
  { state: "VA", id: "658GC", name: "LYNCHBURG VA CLINIC" },
  { state: "VA", id: "621GC", name: "NORTON VA CLINIC" },
  { state: "VA", id: "658", name: "SALEM VA MEDICAL CENTER" },
  { state: "VA", id: "658GD", name: "STAUNTON CBOC" },
  { state: "VA", id: "613GC", name: "STEPHENS CITY VA CLINIC" },
  { state: "VA", id: "658GA", name: "TAZEWELL VA CLINIC" },
  { state: "VA", id: "590GB", name: "VIRGINIA BEACH VA CLINIC" },
  { state: "VA", id: "658GE", name: "WYTHEVILLE VA CLINIC" },
  { state: "VI", id: "672GA", name: "ST.CROIX VETERANS CLINIC" },
  { state: "VI", id: "672GB", name: "ST.THOMAS VETERANS CLINIC" },
  { state: "VT", id: "405GA", name: "BENNINGTON VERMONT OUTREACH CLINIC" },
  { state: "VT", id: "405GC", name: "BRATTLEBORO CBOC" },
  { state: "VT", id: "405HA", name: "BURLINGTON LAKESIDE CBOC" },
  { state: "VT", id: "405HF", name: "RUTLAND VERMONT OUTREACH CLINIC" },
  { state: "WA", id: "663GA", name: "BELLEVUE VA CLINIC" },
  { state: "WA", id: "663GB", name: "BREMERTON VA CLINIC" },
  { state: "WA", id: "687", name: "JONATHAN M. WAINWRIGHT VAMC" },
  { state: "WA", id: "668", name: "MANN-GRANDSTAFF VAMC" },
  { state: "WA", id: "663GC", name: "MOUNT VERNON VA CLINIC" },
  { state: "WA", id: "663A4", name: "PUGET SOUND HEALTH CARE SYSTEM - AMERICAN LAKE DIVISION" },
  { state: "WA", id: "687GA", name: "RICHLAND VA CLINIC" },
  { state: "WA", id: "663", name: "SEATTLE VA MEDICAL CENTER" },
  { state: "WA", id: "663GD", name: "SOUTH SOUND VA CLINIC" },
  { state: "WA", id: "648A4", name: "VANCOUVER,WA DIV PORTLAND VAMC" },
  { state: "WA", id: "668GA", name: "WENATCHEE VA CLINIC" },
  { state: "WA", id: "687HA", name: "YAKIMA CBOC" },
  { state: "WI", id: "607GD", name: "BARABOO, WI CBOC" },
  { state: "WI", id: "607GE", name: "BEAVER DAM, WI CBOC" },
  { state: "WI", id: "618GE", name: "CHIPPEWA VALLEY CBOC" },
  { state: "WI", id: "676GE", name: "CLARK COUNTY CBOC" },
  { state: "WI", id: "695", name: "CLEMENT J ZABLOCKI" },
  { state: "WI", id: "695GC", name: "CLEVELAND CBOC" },
  { state: "WI", id: "618GH", name: "HAYWARD CBOC" },
  { state: "WI", id: "607GC", name: "JANESVILLE, WI CBOC" },
  { state: "WI", id: "556GD", name: "KENOSHA CBOC" },
  { state: "WI", id: "676GC", name: "LACROSSE CBOC" },
  { state: "WI", id: "676GB", name: "LEAVENWORTH, WI CBOC" },
  { state: "WI", id: "695GD", name: "MILO C. HUEMPFNER CBOC" },
  { state: "WI", id: "585GB", name: "RHINELANDER CBOC" },
  { state: "WI", id: "676", name: "TOMAH VAMC" },
  { state: "WI", id: "695GA", name: "UNION GROVE" },
  { state: "WI", id: "676GA", name: "WAUSAU CBOC" },
  { state: "WI", id: "607", name: "WILLIAM S. MIDDLETON MEMORIAL VA HOSPITAL" },
  { state: "WI", id: "676GD", name: "WISCONSIN RAPIDS CBOC" },
  { state: "WV", id: "517", name: "BECKLEY VA MEDICAL CENTER" },
  { state: "WV", id: "540GC", name: "BRAXTON CBOC" },
  { state: "WV", id: "581GB", name: "CHARLESTON VA CLINIC" },
  { state: "WV", id: "540GA", name: "CLARKSBURG/TUCKER" },
  { state: "WV", id: "540GB", name: "CLARKSBURG/WOOD" },
  { state: "WV", id: "613GD", name: "FRANKLIN VA CLINIC" },
  { state: "WV", id: "517GB", name: "GREENBRIER COUNTY VA CLINIC" },
  { state: "WV", id: "581", name: "HUNTINGTON VAMC" },
  { state: "WV", id: "540", name: "LOUIS A JOHNSON VA MEDICAL CENTER" },
  { state: "WV", id: "613", name: "MARTINSBURG VA MEDICAL CENTER" },
  { state: "WV", id: "540GD", name: "MONONGALIA CBOC" },
  { state: "WV", id: "613GE", name: "PETERSBURG VA CLINIC" },
  { state: "WY", id: "666GB", name: "CASPER CBOC" },
  { state: "WY", id: "666GE", name: "GILLETTE VA CLINIC" },
  { state: "WY", id: "442MB", name: "IDES SHERIDAN VAMC" },
  { state: "WY", id: "568HA", name: "NEWCASTLE" },
  { state: "WY", id: "666GD", name: "POWELL VA CLINIC" },
  { state: "WY", id: "666GC", name: "RIVERTON VA CLINIC" },
  { state: "WY", id: "666GF", name: "ROCK SPRINGS CBOC" },
  { state: "WY", id: "666", name: "SHERIDAN VA MEDICAL CENTER" }
];

let xmlFieldMap = [
  { node: "StationSelectList",
    arg: medicalCenters.reduce(
        function(prev, cur) {
          return prev.concat(cur.state + ";" + cur.id + ";" + cur.name);
        }, []).join("|"),
    transform: identityTransform },
  { node: "formSessionID",  arg: "fb47f49e-89a6-4ec4-8280-c55c2b5d915b", transform: identityTransform },
  { node: "EDIPI",  arg: null, transform: identityTransform },
  { node: "VetSocialSecurityNumber",  arg: "veteran[ssn]", transform: extractTransform },
  { node: "DateOfBirth",  arg: 'veteran[date_of_birth]', transform: extractDateWithSlashTransform },
  { node: "Gender",  arg: 'veteran[gender]', transform: extractTransform },
  { node: "VetNameLast",  arg: 'veteran[last_name]', transform: extractTransform },
  { node: "VetNameFirst",  arg: 'veteran[first_name]', transform: extractTransform },
  { node: "VetNamePrefix",  arg: null, transform: identityTransform },
  { node: "VetNameSuffix",  arg: 'veteran[suffix_name]', transform: extractTransform },
  { node: "VetNameMiddle",  arg: 'veteran[middle_name]', transform: extractTransform },
  { node: "Anonymous",  arg: "Y", transform: identityTransform },
  { node: "Level",  arg: "Anonymous", transform: identityTransform },
  { node: "VetIDType",  arg: null, transform: identityTransform },
  { node: "REVIEWINGFORM",  arg: "1", transform: identityTransform },
  { node: "LASTPAGE",  arg: "pgSubmit", transform: identityTransform },
  { node: "APPTYPE",  arg: "Enrollment", transform: identityTransform },
  { node: "USStates",  arg: " ", transform: identityTransform },
  { node: "CANStates",  arg: " ", transform: identityTransform },
  { node: "MEXStates",  arg: " ", transform: identityTransform },
  { node: "Countries",  arg: "USA", transform: identityTransform },
  { node: "pgIntro2Visited",  arg: "1", transform: identityTransform },
  { node: "DateOfBirthMonth",  arg: 'veteran[date_of_birth]', transform: extractMonthTransform },
  { node: "DateOfBirthDay",  arg: 'veteran[date_of_birth]', transform: extractDateTransform },
  { node: "DateOfBirthYear",  arg: 'veteran[date_of_birth]', transform: extractYearTransform },
  { node: "PlaceOfBirthCity",  arg: 'veteran[city_of_birth]', transform: extractTransform },
  { node: "PlaceOfBirthState",  arg: 'veteran[state_of_birth]', transform: extractTransform },
  { node: "State",  arg: 'veteran[state_of_birth]', transform: extractTransform },
  { node: "MedCenterID",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "StationStateList",  name: 'veteran[]', arg: "TT;TEST SITES|AL;ALABAMA|AK;ALASKA|AS;AMERICAN SAMOA|AZ;ARIZONA|AR;ARKANSAS|CA;CALIFORNIA|CO;COLORADO|CT;CONNECTICUT|DE;DELAWARE|DC;D. OF COLUMBIA|FL;FLORIDA|GA;GEORGIA|GU;GUAM|HI;HAWAII|ID;IDAHO|IL;ILLINOIS|IN;INDIANA|IA;IOWA|KS;KANSAS|KY;KENTUCKY|LA;LOUISIANA|ME;MAINE|MD;MARYLAND|MA;MASSACHUSETTS|MI;MICHIGAN|MN;MINNESOTA|MS;MISSISSIPPI|MO;MISSOURI|MT;MONTANA|NE;NEBRASKA|NV;NEVADA|NH;NEW HAMPSHIRE|NJ;NEW JERSEY|NM;NEW MEXICO|NY;NEW YORK|NC;NORTH CAROLINA|ND;NORTH DAKOTA|MP;NORTHERN MARIANA ISLANDS|OH;OHIO|OK;OKLAHOMA|OR;OREGON|PA;PENNSYLVANIA|PI;PHILIPPINES|PR;PUERTO RICO|RI;RHODE ISLAND|SC;SOUTH CAROLINA|SD;SOUTH DAKOTA|TN;TENNESSEE|TX;TEXAS|UT;UTAH|VT;VERMONT|VI;VIRGIN ISLANDS|VA;VIRGINIA|WA;WASHINGTON|WV;WEST VIRGINIA|WI;WISCONSIN|WY;WYOMING", transform: identityTransform },
  //{ node: "MedCenter",  arg: 'veteran[preferred_va_facility]', transform: extractTransform },
  { node: "MedCenter",  name: 'veteran[]', arg: "663A4", transform: identityTransform },
  { node: "pgDemoVisited",  arg: "1", transform: identityTransform },
  { node: "Email2",  arg: 'veteran[email]', transform: extractTransform },
  { node: "HIContrecordno",  name: 'veteran[]', arg: "HEALTH INSURANCE #1", transform: identityTransform },
  //
  { node: "VetHealthInsureCompany",  name: 'veteran[]', arg: "AInsurance1", transform: identityTransform },
  { node: "VetHealthInsureAddress",  name: 'veteran[]', arg: "1 Insurance Way", transform: identityTransform },
  { node: "VetHealthInsureCity",  name: 'veteran[]', arg: "New York", transform: identityTransform },
  { node: "VetHealthInsureCountry",  name: 'veteran[health_insurances][country]', arg: "USA", transform: identityTransform },
  { node: "VetHealthInsureState",  name: 'veteran[]', arg: "NY", transform: identityTransform },
  { node: "VetHealthInsureZip",  name: 'veteran[]', arg: "02123", transform: identityTransform },
  { node: "VetHealthInsurePostalCode",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "VetHealthInsurePhone",  name: 'veteran[]', arg: "(202) 123-4567", transform: identityTransform },
  { node: "VetHealthPolicyHolder",  name: 'veteran[]', arg: "APolicy Holder", transform: identityTransform },
  { node: "VetHealthPolicyNumber",  name: 'veteran[]', arg: "Policy1", transform: identityTransform },
  { node: "VetHealthGroupCode",  name: 'veteran[]', arg: "Group1", transform: identityTransform },
  //
  { node: "DateMedicarePartAMonth",  name: 'veteran[]', arg: "4", transform: identityTransform },
  { node: "DateMedicarePartADay",  name: 'veteran[]', arg: "3", transform: identityTransform },
  { node: "DateMedicarePartAYear",  name: 'veteran[]', arg: "1980", transform: identityTransform },
  { node: "LastEntryDateMonth",  name: 'veteran[]', arg: "5", transform: identityTransform },
  { node: "LastEntryDateDay",  name: 'veteran[]', arg: "6", transform: identityTransform },
  { node: "LastEntryDateYear",  name: 'veteran[]', arg: "1985", transform: identityTransform },
  { node: "LastDischargeDateMonth",  name: 'veteran[]', arg: "5", transform: identityTransform },
  { node: "LastDischargeDateDay",  name: 'veteran[]', arg: "8", transform: identityTransform },
  { node: "LastDischargeDateYear",  name: 'veteran[]', arg: "1990", transform: identityTransform },
  { node: "pgAdditionalServiceVisited",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "pgAdditionalServiceVisited",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "SpouseNameLast",  arg: 'veteran[spouses][last_name]', transform: extractTransform },
  { node: "SpouseNameFirst",  arg: 'veteran[spouses][first_name]', transform: extractTransform },
  { node: "SpouseNameMiddle",  arg: 'veteran[spouses][middle_name]', transform: extractTransform },
  { node: "SpouseNameSuffix",  arg: 'veteran[spouses][suffix_name]', transform: extractTransform },
  { node: "SpouseDateOfBirthMonth",  name: 'veteran[]', arg: "4", transform: identityTransform },
  { node: "SpouseDateOfBirthDay",  name: 'veteran[]', arg: "3", transform: identityTransform },
  { node: "SpouseDateOfBirthYear",  name: 'veteran[]', arg: "1990", transform: identityTransform },
  { node: "MarraigeDateMonth",  name: 'veteran[]', arg: "6", transform: identityTransform },
  { node: "MarraigeDateDay",  name: 'veteran[]', arg: "8", transform: identityTransform },
  { node: "MarraigeDateYear",  name: 'veteran[]', arg: "2010", transform: identityTransform },
  { node: "SpouseAddress",  arg: 'veteran[spouses][address]', transform: extractTransform },
  { node: "SpouseCity",  arg: 'veteran[spouses][city]', transform: extractTransform },
  //{ node: "SpouseCountry",  arg: 'veteran[spouses][country]', transform: extractTransform },
  { node: "SpouseCountry",  name: 'veteran[]', arg: "USA", transform: identityTransform },
  { node: "SpouseState",  arg: 'veteran[spouses][state]', transform: extractTransform },
  { node: "SpouseZip",  arg: 'veteran[spouses][zipcode]', transform: extractTransform },
  { node: "SpousePostalCode",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "SpousePhone",  arg: 'veteran[spouses][phone]', transform: extractTransform },
  { node: "CHContrecordno",  name: 'veteran[]', arg: "CHILD #1 OF 2", transform: identityTransform },
  //{ node: "ChildNameLast",  name: 'veteran[children][last_name]', transform: extractTransform },
  { node: "ChildNameLast",  name: 'veteran[]', arg: "ChildLast1", transform: identityTransform },
  //{ node: "ChildNameFirst",  name: 'veteran[children][first_name]', transform: extractTransform },
  { node: "ChildNameFirst",  name: 'veteran[]', arg: "ChildLast1", transform: identityTransform },
  //{ node: "ChildNameMiddle",  name: 'veteran[children][middle_name]', transform: extractTransform },
  { node: "ChildNameMiddle",  name: 'veteran[]', arg: "ChildMiddle1", transform: identityTransform },
  //{ node: "ChildNameSuffix",  name: 'veteran[children][suffix_name]', transform: extractTransform },
  { node: "ChildNameSuffix",  name: 'veteran[]', arg: "JR", transform: identityTransform },
  { node: "ChildRelationshipSon",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildRelationshipDaughter",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildRelationshipStepson",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildRelationshipStepdaughter",  name: 'veteran[]', arg: "1", transform: identityTransform },
  //{ node: "ChildSocialSecurityNumber",  name: 'veteran[children][ssn]', transform: extractTransform },
  { node: "ChildSocialSecurityNumber",  name: 'veteran[]', arg: "333-44-5555", transform: identityTransform },
  { node: "ChildDependentDateMonth",  name: 'veteran[]', arg: "6", transform: identityTransform },
  { node: "ChildDependentDateDay",  name: 'veteran[]', arg: "3", transform: identityTransform },
  { node: "ChildDependentDateYear",  name: 'veteran[]', arg: "2010", transform: identityTransform },
  //{ node: "ChildDependentDate",  name: 'veteran[children][became_dependent]', transform: extractTransform },
  { node: "ChildDependentDate",  name: 'veteran[]', arg: "06/03/2010", transform: identityTransform },
  { node: "ChildDateOfBirthMonth",  name: 'veteran[]', arg: "2", transform: identityTransform },
  { node: "ChildDateOfBirthDay",  name: 'veteran[]', arg: "2", transform: identityTransform },
  { node: "ChildDateOfBirthYear",  name: 'veteran[]', arg: "2005", transform: identityTransform },
  //{ node: "ChildDateOfBirth",  name: 'veteran[children][date_of_birth]', transform: extractTransform },
  { node: "ChildDateOfBirth",  name: 'veteran[]', arg: "02/02/2005", transform: identityTransform },
  { node: "ChildTotalDisabledYes",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildTotalDisabledNo",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "ChildAttendSchoolYes",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "ChildAttendSchoolNo",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildSelfSchool", arg: 'veteran[children][education_expenses]', transform: extractMonetaryValueTransform },
  { node: "ChildSupportAmount",  name: 'veteran[]', arg: "600.00", transform: identityTransform },
  { node: "ChildLive",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildLiveNo",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "ChildProvideSupportYes",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "ChildProvideSupportNo",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "Child1GrossIncome",  name: 'veteran[]', arg: "1000.00", transform: identityTransform },
  { node: "Child1PropertyIncome",  name: 'veteran[]', arg: "98.00", transform: identityTransform },
  { node: "Child1OtherIncome",  name: 'veteran[]', arg: "76.00", transform: identityTransform },
  { node: "Child1BankCashAmount",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Child1LandMarketValue",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Child1OtherAssetNet",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "tWelcome",  name: 'veteran[]', arg: "Introduction", transform: identityTransform },
  { node: "tPersonal",  name: 'veteran[]', arg: "Personal Information", transform: identityTransform },
  { node: "tInsurance",  name: 'veteran[]', arg: "Insurance Information", transform: identityTransform },
  { node: "tService",  name: 'veteran[]', arg: "Military Service", transform: identityTransform },
  { node: "tFinancial",  name: 'veteran[]', arg: "Financial Assessment", transform: identityTransform },
  { node: "pgFinalVisited",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "Comments",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "AttType0",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Single_Attach0",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "AttType1",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Single_Attach1",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "AttType2",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Single_Attach2",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "AttType3",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Single_Attach3",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "viewerType",  name: 'veteran[]', arg: "Reader Reader", transform: identityTransform },
  { node: "viewerVersion",  name: 'veteran[]', arg: "15.00920069", transform: identityTransform },
  { node: "formVersion",  name: 'veteran[]', arg: "19", transform: identityTransform },
  { node: "place_birth",  name: 'veteran[]', arg: "Kent, WA", transform: identityTransform },
  { node: "MedCenterText",  name: 'veteran[]', arg: "PUGET SOUND HEALTH CARE SYSTEM - AMERICAN LAKE DIVISION", transform: identityTransform },
  { node: "Path",  name: 'veteran[]', arg: "A", transform: identityTransform },
  { node: "MotherMaidenName",  arg: 'veteran[mothers_maiden_name]', transform: extractTransform },
  //{ node: "CurrentMaritalStatus",  arg: 'veteran[marital_status]', transform: extractTransform },
  { node: "CurrentMaritalStatus",  name: 'veteran[]', arg: "MARRIED", transform: identityTransform },
  { node: "TargetURL",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Q1",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "Q2",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "Q3",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "ACA",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "Appointment",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "Spanish",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "Race1",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "Race2",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "Race5",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "Race3",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "Race4",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "ReligionList",  name: 'veteran[]', arg: "Select Religion", transform: identityTransform },
  { node: "CurrentAddress",  arg: 'veteran[street]', transform: extractTransform },
  { node: "CurrentCity",  arg: 'veteran[city]', transform: extractTransform },
  //{ node: "CurrentCountry",  arg: 'veteran[country]', transform: extractTransform },
  { node: "CurrentCountry",  name: 'veteran[]', arg: "USA", transform: identityTransform },
  { node: "CurrentState",  arg: 'veteran[state]', transform: extractTransform },
  //{ node: "CurrentState",  name: 'veteran[]', arg: "WA", transform: identityTransform },
  { node: "CurrentZip",  arg: 'veteran[zipcode]', transform: extractTransform },
  { node: "CurrentPostalCode",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "CurrentCounty",  arg: 'veteran[county]', transform: extractTransform },
  { node: "Email",  arg: 'veteran[email]', transform: extractTransform },
  { node: "CurrentHomePhone",  arg: 'veteran[home_phone]', transform: extractTransform },
  { node: "CellPhone",  arg: 'veteran[mobile_phone]', transform: extractTransform },
  { node: "VetHealthInsurance",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "MedicaidEligible",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "MedicareEnrolledA",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "DateMedicarePartA",  arg: 'veteran[medicare_part_a_effective_date]', transform: extractTransform },
  //{ node: "LastServiceBranch",  arg: 'veteran[last_branch_of_service]', transform: extractTransform },
  { node: "LastServiceBranch", name: 'veteran[]', arg: "COAST GUARD", transform: identityTransform },
  { node: "LastEntryDate",  arg: 'veteran[last_entry_date]', transform: extractTransform },
  { node: "LastDischargeDate",  arg: 'veteran[last_discharge_date]', transform: extractTransform },
  //{ node: "DischargeType",  arg: 'veteran[discharge_type]', transform: extractTransform },
  { node: "DischargeType", name: 'veteran[]', arg: "GENERAL", transform: identityTransform },
  { node: "MilitaryServiceNumber",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "PurpleHeart",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "FormerPOW",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "TheaterOperation",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "RetiredMilitaryDisability",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "GulfWarToxinExposure",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "AgentOrangeExposure",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "RadiationExposure",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "MilitaryRadiumTreatments",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "CampLejeune",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "ProvideDetails",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "ConfirmProvideDetails",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "SpouseSocialSecurityNumber",  arg: 'veteran[spouses][ssn]', transform: extractTransform },
  { node: "SpouseDateOfBirth",  arg: 'veteran[spouses][date_of_birth]', transform: extractTransform },
  //{ node: "MarraigeDate",  arg: 'veteran[spouses][date_of_marriage]', transform: extractTransform },
  { node: "MarraigeDate",  name: 'veteran[]', arg: "06/08/2010", transform: identityTransform },
  { node: "SpouseSame",  name: 'veteran[]', arg: "2", transform: identityTransform },
  { node: "SpouseSupportAmount",  name: 'veteran[]', arg: "600.00", transform: identityTransform },
  { node: "SpouseLive",  name: 'veteran[]', arg: "N", transform: identityTransform },
  { node: "SpouseProvideSupport",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "ReportChildren",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "ProvideSupport",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "VetGrossIncome",  arg: 'veteran[gross_wage_income]', transform: extractMonetaryValueTransform },
  { node: "VetPropertyIncome",  arg: 'veteran[net_business_income]', transform: extractMonetaryValueTransform },
  { node: "VetOtherIncome",  arg: 'veteran[other_income]', transform: extractMonetaryValueTransform },
  { node: "SpouseGrossIncome",  arg: 'veteran[spouses][gross_wage_income]', transform: extractMonetaryValueTransform },
  { node: "SpousePropertyIncome",  arg: 'veteran[spouses][net_business_income]', transform: extractMonetaryValueTransform },
  { node: "SpouseOtherIncome",  arg: 'veteran[spouses][other_income]', transform: extractMonetaryValueTransform },
  { node: "MedicalExpenses",  arg: 'veteran[deductible_medical_expenses]', transform: extractMonetaryValueTransform },
  { node: "FuneralExpenses",  arg: 'veteran[deductible_funeral_expenses]', transform: extractMonetaryValueTransform },
  { node: "VetSelfSchool",  arg: 'veteran[deductible_education_expenses]', transform: extractMonetaryValueTransform },
  { node: "VetBankCashAmount",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "VetLandMarketValue",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "VetOtherAssetNet",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "SpouseBankCashAmount",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "SpouseLandMarketValue",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "SpouseOtherAssetNet",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Confirm",  name: 'veteran[]', arg: "VAToPrint", transform: identityTransform },
  { node: "pg1VetName",  name: 'veteran[]', arg: "ALASTNAME, AFIRSTNAME, AMIDDLENAME SR", transform: identityTransform },
  { node: "OtherName1",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "ClaimNumber",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "HEALTH_SERVICES",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "DENTAL",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "health_insurance",  arg: 'veteran[health_insurances]', transform: extractAddressWithFormatTransform },
  { node: "FVetHealthPolicyHolder",  name: 'veteran[]', arg: "APolicy Holder", transform: identityTransform },
  { node: "FVetHealthPolicyNumber",  name: 'veteran[]', arg: "Policy1", transform: identityTransform },
  { node: "FVetHealthGroupCode",  name: 'veteran[]', arg: "Group1", transform: identityTransform },
  { node: "ReceiveDisabilityRetirement",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "Fchild_name1",  name: 'veteran[]', arg: "CHILDLAST1, CHILDLAST1, CHILDMIDDLE1 JR", transform: identityTransform },
  { node: "FChild1RelationshipSon",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "FChild1RelationshipDaughter",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "FChild1RelationshipStepson",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "FChild1RelationshipStepdaughter",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "FChild1DependentDate",  name: 'veteran[]', arg: "06/03/2010", transform: identityTransform },
  { node: "FChild1DateOfBirth",  name: 'veteran[]', arg: "02/02/2005", transform: identityTransform },
  { node: "FChild1TotalDisabledYes",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "FChild1TotalDisabledNo",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "FChild1AttendSchoolYes",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "FChild1AttendSchoolNo",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "FChild1SelfSchool",  name: 'veteran[]', arg: "11235.00", transform: identityTransform },
  { node: "spouse_name",  name: 'veteran[]', arg: "SPOUSELAST, SPOUSEFIRST, SPOUSEMIDDLE JR", transform: identityTransform },
  { node: "spouse_address",  name: 'veteran[]', arg: "1 Spouse Dr\nAuburn, AZ 33421\n(344) 222-1111", transform: identityTransform },
  { node: "FChild1SocialSecurityNumber",  name: 'veteran[]', arg: "333-44-5555", transform: identityTransform },
  { node: "FChild1GrossIncome",  name: 'veteran[]', arg: "1000.00", transform: identityTransform },
  { node: "FChild1PropertyIncome",  name: 'veteran[]', arg: "98.00", transform: identityTransform },
  { node: "FChild1OtherIncome",  name: 'veteran[]', arg: "76.00", transform: identityTransform },
  { node: "FChild1BankCashAmount",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "FChild1LandMarketValue",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "FChild1OtherAssetNet",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "TextField",  name: 'veteran[]', arg: "Online 10-10EZ Application for Health Benefits", transform: identityTransform },
  { node: "HIContrecordno",  name: 'veteran[]', arg: "HEALTH INSURANCE #2", transform: identityTransform },
  { node: "VetHealthInsureCompany",  arg: 'veteran[health_insurances][name]', transform: extractTransform },
  //{ node: "VetHealthInsureAddress",  arg: 'veteran[health_insurances][street]', transform: extractTransform },
  { node: "VetHealthInsureAddress",  name: 'veteran[]', arg: "2 Insurance Way", transform: identityTransform },
  { node: "VetHealthInsureCity",  arg: 'veteran[health_insurances][city]', transform: extractTransform },
  { node: "VetHealthInsureCountry",  name: 'veteran[]', arg: "USA", transform: identityTransform },
  { node: "VetHealthInsureState",  arg: 'veteran[health_insurances][state]', transform: extractTransform },
  //{ node: "VetHealthInsureState",  name: 'veteran[]', arg: "MA", transform: identityTransform },

  { node: "VetHealthInsureZip",  arg: 'veteran[health_insurances][zipcode]', transform: extractTransform },
  { node: "VetHealthInsurePostalCode",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "VetHealthInsurePhone",  arg: 'veteran[health_insurances][phone]', transform: extractTransform },
  { node: "VetHealthPolicyHolder",  arg: 'veteran[health_insurances][policy_holder_name]', transform: extractTransform },
  { node: "VetHealthPolicyNumber",  arg: 'veteran[health_insurances][policy_number]', transform: extractTransform },
  { node: "VetHealthGroupCode",  arg: 'veteran[health_insurances][group_code]', transform: extractTransform },
  { node: "TextField",  name: 'veteran[]', arg: "Online 10-10EZ Application for Health Benefits", transform: identityTransform },
  { node: "CHContrecordno",  name: 'veteran[]', arg: "CHILD #2 OF 2", transform: identityTransform },
  { node: "ChildNameLast",  name: 'veteran[]', arg: "LastChild2", transform: identityTransform },
  { node: "ChildNameFirst",  name: 'veteran[]', arg: "FirstChild2", transform: identityTransform },
  { node: "ChildNameMiddle",  name: 'veteran[]', arg: "MiddleChild2", transform: identityTransform },
  { node: "ChildNameSuffix",  name: 'veteran[]', arg: "II", transform: identityTransform },
  { node: "ChildRelationshipSon",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildRelationshipDaughter",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "ChildRelationshipStepson",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildRelationshipStepdaughter",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildSocialSecurityNumber",  name: 'veteran[]', arg: "555-44-3333", transform: identityTransform },
  { node: "ChildDependentDateMonth",  name: 'veteran[]', arg: "4", transform: identityTransform },
  { node: "ChildDependentDateDay",  name: 'veteran[]', arg: "5", transform: identityTransform },
  { node: "ChildDependentDateYear",  name: 'veteran[]', arg: "1992", transform: identityTransform },
  { node: "ChildDependentDate",  name: 'veteran[]', arg: "04/05/1992", transform: identityTransform },
  { node: "ChildDateOfBirthMonth",  name: 'veteran[]', arg: "4", transform: identityTransform },
  { node: "ChildDateOfBirthDay",  name: 'veteran[]', arg: "5", transform: identityTransform },
  { node: "ChildDateOfBirthYear",  name: 'veteran[]', arg: "1992", transform: identityTransform },
  { node: "ChildDateOfBirth",  name: 'veteran[]', arg: "04/05/1992", transform: identityTransform },
  { node: "ChildTotalDisabledYes",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildTotalDisabledNo",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "ChildAttendSchoolYes",  name: 'veteran[]', arg: "1", transform: identityTransform },
  { node: "ChildAttendSchoolNo",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildSelfSchool",  name: 'veteran[]', arg: "9876.00", transform: identityTransform },
  { node: "ChildSupportAmount",  name: 'veteran[]', arg: null, transform: identityTransform },
  { node: "ChildLive",  name: 'veteran[]', arg: "Y", transform: identityTransform },
  { node: "ChildLiveNo",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildProvideSupportYes",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildProvideSupportNo",  name: 'veteran[]', arg: "0", transform: identityTransform },
  { node: "ChildGrossIncome", arg: 'veteran[children][gross_wage_income]', transform: extractMonetaryValueTransform },
  { node: "ChildPropertyIncome", arg: 'veteran[children][net_business_income]', transform: extractMonetaryValueTransform },
  { node: "ChildOtherIncome", arg: 'veteran[children][other_income]', transform: extractMonetaryValueTransform }
];

function getFormRoot() {
  return document.querySelector(".main-form");
}

function saveForm(formRoot, _) {
  sessionStorage.setItem("voa_form", JSON.stringify($(formRoot).serializeObject()));
}

function initForm() {
  // initialize foundation.
  $(document).foundation();

  form_progress.init();

  let formRoot = getFormRoot();
  let allInputs = $(formRoot).find('input, select');

  // Suppress the submit behavior since submission is done via crafting an
  // XML payload for AJAX.
  formRoot.addEventListener("submit",
      function (e) {
        e.preventDefault();
        // TODO(awong): Remove this debugging logic when things work.
        console.log(build1010ezXml(formRoot));
        for (let i = 0; i < allInputs.length; i++) {
          validate(allInputs[i]);
        }
      });

  // Load saved form data if there is any.
  let savedData = sessionStorage.getItem("voa_form");
  if (savedData !== null) {
    $(formRoot).deserialize(JSON.parse(savedData));
  }

  // Set up auto-save on any changes to the form.
  formRoot.addEventListener("change",
      function (e) {
        saveForm(formRoot, e);
      });

  $(allInputs).on('change', function() {
    validate(this);
  });
}

function getFormData(theForm) {
  return $(theForm).serializeObject();
}

function build1010ezXml(theForm) {
  let formData = getFormData(theForm);
  let xmlDoc = document.implementation.createDocument(null, "form1");

  for (let i = 0; i < xmlFieldMap.length; i++) {
    let entry = xmlFieldMap[i];
    let element = xmlDoc.createElement(entry.node);

    let transform = entry.transform;
    if (transform === undefined) {
      transform = extractTransform;
    }

    let textData = transform(formData, entry.arg);
    if (textData !== null) {
      element.appendChild(xmlDoc.createTextNode(textData));
    }

    xmlDoc.firstChild.appendChild(element);
  }

  return xmlDoc;
}

// Exports that are for use in unittests only. Nest them one layer lower so the
// API is self-documenting.
const forTestExports = {
  extractDateWithSlashTransform,
  getFormData,
  getFormRoot,
  validate
};

export {
  build1010ezXml,
  initForm,
  forTestExports as forTest
};
