var HealthApp = (function() {
  "use strict";

  var identityTransform = function(formData, arg) { return arg; };
  var extractTransform = function(formData, arg) { return formData[arg]; };

  var xmlFieldMap = [
    { node: "StationSelectList",  arg: "TT;987;CHEY6 (987)|TT;988;DAYT20 (988)|AK;463;ANCHORAGE VA MEDICAL CENTER|AK;463GA;FAIRBANKS VA CLINIC|AK;463GB;KENAI VA CLINIC|AK;463GC;MAT-SU VA CLINIC|AL;521GE;ANNISTON CBOC|AL;521GG;BESSEMER CBOC|AL;521;BIRMINGHAM VAMC|AL;619GB;CENTRAL ALABAMA HCS - DOTHAN CBOC|AL;619;CENTRAL ALABAMA HEALTH CARE SYSTEM - MONTGOMERY DIVISION|AL;619A4;CENTRAL ALABAMA HEALTH CARE SYSTEM - TUSKEGEE DIVISION|AL;521GH;CHILDERSBURG CBOC|AL;521GB;DECATUR CBOC|AL;521GC;FLORENCE CBOC|AL;521GI;GUNTERSVILLE CBOC|AL;521GA;HUNTSVILLE CBOC|AL;521GF;JASPER VA CLINIC|AL;619GE;MONROE COUNTY CBOC|AL;521GD;RAINBOW CITY CBOC|AL;679;TUSCALOOSA VA MEDICAL CENTER|AL;619GD;WIREGRASS CBOC|AR;598;CENTRAL ARKANSAS HEALTH CARE SYSTEM - LITTLE ROCK|AR;598GG;CONWAY CBOC|AR;598GB;EL DORADO, AR CBOC|AR;564;FAYETTEVILLE VA MEDICAL|AR;564GB;FORT SMITH VA CLINIC|AR;564GA;HARRISON VA CLINIC|AR;614GN;HELENA VA CLINIC|AR;598GC;HOT SPRINGS, AR CBOC|AR;614GB;JONESBORO VA CLINIC|AR;598GD;MENA, AR (CBOC)|AR;598GA;MOUNTAIN HOME, AR CBOC|AR;564GD;OZARK CBOC|AR;657GG;PARAGOULD AR CBOC (657GG)|AR;598GE;PINE BLUFF CBOC|AR;598GH;RUSSELLVILLE CBOC|AR;598GF;SEARCY CBOC|AR;667GA;TEXARKANA CBOC|AS;459GF;AMERICAN SAMOA VA CLINIC|AZ;649GD;ANTHEM CBOC|AZ;678GC;CASA GRANDE CBOC|AZ;649GE;COTTONWOOD CBOC|AZ;649GB;FLAGSTAFF CBOC|AZ;644GF;GLOBE HEALTH CARE CLINIC|AZ;678GE;GREEN VALLEY CBOC|AZ;649GA;KINGMAN CBOC|AZ;644GG;N EAST PHOENIX VA CLINIC|AZ;649;NORTHERN ARIZONA HEALTH CARE SYSTEM - PRESCOTT DIVISION|AZ;678GF;NORTHWEST TUCSON URBAN CBOC|AZ;644GD;PAYSON CBOC|AZ;644;PHOENIX VAMC|AZ;649GC;PRESCOTT CBOC LAKE HAVASU CITY|AZ;678GD;SAFFORD CBOC|AZ;644GB;SHOW LOW CBOC|AZ;678GA;SIERRA VISTA CBOC|AZ;644BY;SOUTHEAST CBOC|AZ;678GG;SOUTHEAST TUCSON|AZ;678;SOUTHERN ARIZONA HEALTH CARE SYSTEM - TUCSON DIVISION|AZ;644GC;SOUTHWEST CBOC|AZ;644GA;SUN CITY, AZ CBOC|AZ;644GE;THUNDERBIRD VA CBOC|AZ;678GB;YUMA CBOC|CA;600GA;ANAHEIM VETERANS HEALTH CLINIC|CA;691GG;ANTELOPE VALLEY VA CLINIC|CA;691GD;BAKERSFIELD CBOC|CA;600GC;CABRILLO VETERANS HEALTH CLINIC|CA;612GG;CHICO VA CLINIC|CA;664GC;CHULA VISTA CBOC|CA;662GG;CLEARLAKE CBOC|CA;605GD;CORONA CBOC|CA;654GD;DIAMOND VIEW CBOC|CA;691GF;EAST LOS ANGELES CBOC|CA;664GD;ESCONDIDO CBOC|CA;662GC;EUREKA CBOC|CA;612GD;FAIRFIELD VA CLINIC|CA;570;FRESNO VA MEDICAL CENTER|CA;691GC;GARDENA CBOC|CA;664GA;IMPERIAL VALLEY CBOC|CA;600GE;LAGUNA HILLS VET HLTH CLINIC|CA;605;LOMA LINDA HCS|CA;691GE;LOS ANGELES CBOC|CA;691GN;LYNWOOD CBOC|CA;612GE;MARE ISLAND VA CLINIC|CA;612GF;MARTINEZ CBOC|CA;612;MARTINEZ VA CLC|CA;612GH;MCCLELLAN VA CLINIC|CA;570GA;MERCED VA CLINIC|CA;605GB;MURRIETA CBOC|CA;570GC;OAKHURST VA CLINIC|CA;664GB;OCEANSIDE CBOC|CA;691GM;OXNARD CBOC|CA;605GC;PALM DESERT CBOC|CA;640GA;PALO ALTO HEALTH CARE SYSTEM - CAPITOLA DIVSION|CA;640GC;PALO ALTO HEALTH CARE SYSTEM - FREMONT CBOC|CA;640HB;PALO ALTO HEALTH CARE SYSTEM - MODESTO DIVSION|CA;640HC;PALO ALTO HEALTH CARE SYSTEM - MONTEREY DIVSION|CA;640GB;PALO ALTO HEALTH CARE SYSTEM - SONORA DIVSION|CA;640HA;PALO ALTO HEALTH CARE SYSTEM - STOCKTON DIVSION|CA;640;PALO ALTO VA MEDICAL CENTER|CA;640A4;PALO ALTO VAMC-LIVERMORE|CA;691GO;PASADENA CBOC|CA;605GE;RANCHO CUCAMONGA CBOC|CA;612A4;SACRAMENTO VA MEDICAL CENTER|CA;662GE;SAN BRUNO CBOC|CA;662GF;SAN FRANCISCO CBOC|CA;662;SAN FRANCISCO VAMC|CA;691GK;SAN LUIS OBISPO CBOC|CA;600GB;SANTA ANA VETERANS HEALTH CLINIC|CA;691GB;SANTA BARBARA CBOC|CA;691GL;SANTA MARIA CBOC|CA;662GA;SANTA ROSA, CA CBOC|CA;691A4;SEPULVEDA OUTPATIENT & NURSING HOME CARE|CA;570GB;TULARE VA CLINIC|CA;662GD;UKIAH CBOC|CA;691;VA GREATER LOS ANGELES HEALTHCARE SYSTEM - WEST LOS ANGELES DIVISION|CA;600;VA LONG BEACH HEALTHCARE SYSTEM|CA;664;VA SAN DIEGO HEALTHCARE SYSTEM (664)|CA;654GA;VA SIERRA FOOTHILLS OUTPATIENT CLINIC|CA;662GB;VALLEJO CBOC|CA;605GA;VICTORVILLE CBOC|CA;600GD;WHITTIER/SANTA FE SPRINGS CLINIC|CA;612GI;YUBA CITY CBOC|CO;554GF;ALAMOSA VA CLINIC|CO;554GB;AURORA VA CLINIC|CO;554GI;BURLINGTON VA CLINIC|CO;554;DENVER VA MEDICAL CENTER|CO;501GJ;DURANGO VA CLINIC|CO;554GE;FLOYD K. LINDSTROM VA CLINIC|CO;442GC;FORT COLLINS VA CLINIC|CO;554GC;GOLDEN VA CLINIC|CO;575;GRAND JUNCTION VAMC|CO;442GD;GREELEY VA CLINIC|CO;554GG;LA JUNTA COMMUNITY BASED OUTPATIENT CLINIC (554GG)|CO;554GH;LAMAR VA CLINIC|CO;575GA;MONTROSE CBOC|CO;554GD;PUEBLO VA CLINIC|CT;689GE;DANBURY|CT;689HC;NEW LONDON|CT;689A4;NEWINGTON|CT;689GB;STAMFORD VA PRIMARY CARE CTR|CT;689;VA CONNECTICUT HEALTHCARE SYSTEM - WEST HAVEN DIVISION|CT;689GA;WATERBURY|CT;689GC;WINDHAM CBOC|CT;689GD;WINSTED|DC;688GB;SOUTHEAST WASHINGTON VA CLINIC|DC;688;WASHINGTON VA MEDICAL CENTER|DE;460GC;KENT COUNTY VA CLINIC|DE;460GA;SUSSEX COUNTY VA CLINIC|FL;548GD;BOCA RATON CBOC|FL;516GD;BRADENTON VA CLINIC|FL;673GC;BROOKSVILLE CBOC|FL;546;BRUCE W. CARTER DEPT OF VAMC|FL;516;C.W. BILL YOUNG DEPT OF VAMC|FL;675GF;CLERMONT CBOC|FL;546GH;DEERFIELD BEACH CLINIC|FL;548GB;DELRAY BEACH VA CLINIC|FL;520GC;ELGIN AIR FORCE BASE VA CLINIC|FL;548GA;FORT PIERCE VA CLINIC|FL;546GF;HOLLYWOOD VA CLINIC|FL;546GC;HOMESTEAD VA CLINIC|FL;573GB;JACKSONVILLE CBOC|FL;673;JAMES A. HALEY VETERANS HOSP|FL;546GE;KEY LARGO VA CLINIC|FL;546GB;KEY WEST CBOC|FL;675GC;KISSIMMEE CBOC|FL;675GG;LAKE BALDWIN VA CLINIC|FL;573A4;LAKE CITY VA MEDICAL CENTER|FL;673GB;LAKELAND VA CLINIC|FL;573GG;LECANTO VA CLINIC|FL;516BZ;LEE COUNTY VA CLINIC|FL;675GE;LEESBURG VA CLINIC|FL;573;MALCOM RANDALL DEPT OF VAMC|FL;573GK;MARIANNA VA CLINIC|FL;546GA;MIAMI (ALCOHOL/DRUG)|FL;516GF;NAPLES VA CLINIC|FL;573GD;OCALA VA CLINIC|FL;548GF;OKEECHOBEE VA CLINIC|FL;675GD;ORANGE CITY VA CLINIC|FL;675;ORLANDO VAMC|FL;573GL;PALATKA VA CLINIC|FL;516GC;PALM HARBOR VA CLINIC|FL;520GB;PANAMA CITY BEACH VA CLINIC|FL;546GD;PEMBROKE PINES VA CLINIC|FL;573GN;PERRY VA CLINIC|FL;516GE;PORT CHARLOTTE VA CLINIC|FL;573GE;SAINT AUGUSTINE VA CLINIC|FL;516GA;SARASOTA COUNTY CBOC|FL;516GH;SEBRING VA CLINIC|FL;516GB;ST. PETERSBURG VA CLINIC|FL;548GC;STUART VA CLINIC|FL;573GI;THE VILLAGES VA CLINIC|FL;548GE;VERO BEACH VA CLINIC|FL;675GA;VIERA VA CLINIC|FL;548;WEST PALM BEACH VAMC|FL;673GF;ZEPHYRHILLS VA CLINIC|GA;557GB;ALBANY VA CBOC|GA;509GA;ATHENS CBOC|GA;508GA;ATLANTA VA CBOC|GA;508;ATLANTA VAMC|GA;509;AUGUSTA VAMC|GA;509A0;AUGUSTA VAMC - UPTOWN|GA;508GF;AUSTELL CBOC|GA;557GC;BALDWIN CBOC|GA;508GJ;BLAIRSVILLE CBOC|GA;557GE;BRUNSWICK CBOC|GA;508GK;CARROLLTON CBOC|GA;619GA;CENTRAL ALABAMA HCS - COLUMBUS CBOC|GA;557;DUBLIN|GA;534GE;HINESVILLE CBOC|GA;508GH;LAWRENCEVILLE CBOC|GA;557GA;MACON VA CBOC|GA;508GI;NEWNAN CBOC|GA;508GE;OAKWOOD VA CLINIC|GA;534BY;SAVANNAH PRIMARY CARE CLINIC|GA;573GJ;ST. MARYS VA CLINIC|GA;508GG;STOCKBRIDGE CBOC|GA;573GA;VALDOSTA CBOC|GU;459GE;GUAM CBOC|HI;459GB;HILO CBOC|HI;459GD;KAUAI CBOC|HI;459GC;KONA CBOC|HI;459GG;LEEWARD OAHU CBOC|HI;459GA;MAUI VA CLINIC|IA;636GF;BETTENDORF COMMUNITY BASED OUTPATIENT CLINIC|IA;636GM;CARROLL CBOC|IA;636GN;CEDAR RAPIDS CBOC|IA;636GU;DECORAH CBOC|IA;636GJ;DUBUQUE COMMUNITY BASED OUTPATIENT CLINIC|IA;636GK;FORT DODGE CBOC|IA;636A8;IOWA CITY HCS|IA;636GR;KNOXVILLE CBOC|IA;636GD;MARSHALLTOWN COMMUNITY BASED OUTPATIENT CLINIC|IA;636GC;MASON CITY COMMINITY BASED OUTPATIENT CLINIC|IA;636GS;OTTUMWA CBOC|IA;636GP;SHENANDOAH CBOC|IA;438GC;SIOUX CITY CBOC|IA;438GA;SPIRIT LAKE CBOC|IA;636A6;VA CIHS, DES MOINES DIVISION|IA;636GH;WATERLOO COMMUNITY BASED OUTPATIENT CLINIC|ID;531;BOISE VA MEDICAL CENTER|ID;531GG;CALDWELL VA CLINIC|ID;668GB;COEUR D ALENE VA CLINIC|ID;687GB;LEWISTON VA CLINIC|ID;531GE;TWIN FALLS VA CLINIC|ID;660GA;VA POCATELLO CBOC (660GA)|IL;578GD;AURORA CBOC (578GD)|IL;657GA;BELLEVILLE IL CBOC (657GA)|IL;537HA;BEVERLY CBOC|IL;556;CAPTN JAMES LOVELL FED HLT CTR|IL;657GT;CARBONDALE CBOC|IL;537GA;CHICAGO HEIGHTS CBOC|IL;550;DANVILLE VA MEDICAL CENTER|IL;550GA;DECATUR VA CLINIC|IL;578;EDWARD J. HINES JR. HOSPITAL|IL;657GM;EFFINGHAM VA CLINIC|IL;578GE;ELGIN CBOC (578GE)|IL;556GA;EVANSTON CBOC|IL;607GF;FREEPORT CBOC|IL;636GI;GALESBURG COMMUNITY BASED OUTPATIENT CLINIC|IL;657GU;HARRISBURG CBOC|IL;537;JESSE BROWN VA MEDICAL CENTER|IL;578GA;JOLIET CBOC (578GA)|IL;578GC;KANKAKEE COUNTY CBOC|IL;537GD;LAKESIDE CBOC|IL;578GF;LASSALLE CBOC (578GF)|IL;550GF;MATTOON CBOC|IL;556GC;MCHENRY CBOC|IL;657GK;MT. VERNON IL CBOC (657GK)|IL;578GG;OAK LAWN CBOC (578GG)|IL;636GG;QUINCY COMMUNITY BASED OUTPATIENT CLINIC|IL;607HA;ROCKFORD, IL OPC|IL;550GD;SPRINGFIELD VA CLINIC|IL;636GT;STERLING CBOC|IL;657A5;VA HEARTLAND-EAST, VISN 15 HCS MARION IL DIVISION|IN;583GB;BLOOMINGTON VA CLINIC|IN;657GJ;EVANSVILLE IL CBOC|IN;610A4;FORT WAYNE VA MEDICAL CENTER|IN;610GC;GOSHEN VA CLINIC|IN;550GC;LAFAYETTE, IN CBOC|IN;539GC;LAWRENCEBURG (DEARBORN COUNTY)|IN;610;MARION VA MEDICAL CENTER|IN;583GC;MARTINSVILLE VA CLINIC|IN;610GB;MUNCIE VA CLINIC|IN;603GB;NEW ALBANY VA CLINIC|IN;610GD;PERU VA CLINIC|IN;583;RICHARD L. ROUDEBUSH VAMC|IN;552GC;RICHMOND CBOC|IN;603GG;SCOTT COUNTY VA CLINIC|IN;610GA;SOUTH BEND VA CLINIC|IN;583GA;TERRE HAUTE VA CLINIC|IN;657GQ;VINCENNES IN CBOC|KS;589GM;CHANUTE VA CLINIC|KS;589A5;COLMERY O NEIL VAMC|KS;589G2;DODGE CITY VA CLINIC|KS;589A6;DWIGHT D. EISENHOWER VAMC|KS;589GN;EMPORIA VA CLINIC|KS;589G9;FORT RILEY CBOC|KS;589GV;FORT SCOTT VA CLINIC|KS;589GP;GARNETT VA CLINIC|KS;589G4;HAYS CBOC|KS;589G7;HUTCHINSON CBOC|KS;677HQ;JUNCTION CITY CBOC|KS;589GR;JUNCTION CITY VA CLINIC|KS;589GU;LAWRENCE VA CLINIC|KS;589G3;LIBERAL CBOC|KS;589GC;PAOLA VA CLINIC|KS;589G5;PARSONS CBOC|KS;589A7;ROBERT J. DOLE  VAMC|KS;589GW;SALINA CBOC WICHITA|KS;589GT;SENECA VA CLINIC|KS;589GJ;WYANDOTTE COUNTY VA CLINIC|KY;539GA;BELLEVUE CBOC|KY;596GD;BEREA VA CLINIC|KY;626GC;BOWLING GREEN COMMUNITY BASED OUTPATIENT CLINIC|KY;603GH;CARROLLTON VA CLINIC|KY;539A4;CINCINNATI VAMC FORT THOMAS|KY;603GD;DUPONT VA CLINIC|KY;539GD;FLORENCE CBOC|KY;603GF;GRAYSON COUNTY VA CLINIC|KY;657GO;HANSON KY CBOC (657GO)|KY;596GC;HAZARD VA CLINIC|KY;626GJ;HOPKINSVILLE VA CLINIC|KY;596HA;LEXINGTON MOBILE OUTREACH CLINIC|KY;596;LEXINGTON VAMC-LEESTOWN|KY;596A4;LEXINGTON VETERANS AFFAIRS MEDICAL CENTER|KY;657GR;MAYFIELD VA CBOC|KY;596GB;MOREHEAD VA CLINIC|KY;603GE;NEWBURG VA CLINIC|KY;657GP;OWENSBORO KY CBOC|KY;657GL;PADUCAH KY CBOC (657GL)|KY;581GA;PRESTONSBURG CBOC|KY;603;ROBLEY REX VAMC|KY;603GC;SHIVELY VA CLINIC|KY;596GA;SOMERSET VA CLINIC|KY;603GA;VA HEALTHCARE CENTER, FT. KNOX|LA;502;ALEXANDRIA VA MEDICAL CENTER|LA;629GF;BOGALUSA CBOC|LA;502GF;FORT POLK VA CLINIC|LA;629GE;FRANKLIN CBOC|LA;629GB;HAMMOND CBOC|LA;629GA;HOUMA CBOC|LA;502GA;JENNINGS CBOC|LA;502GB;LAFAYETTE VA CLINIC|LA;667GB;MONROE VA CLINIC|LA;502GG;NATCHITOCHES VA CLINIC|LA;667;OVERTON BROOKS VA MEDICAL CENTER|LA;629;SE LOUISIANA VETERANS HCS|LA;629GC;SLIDELL CBOC|LA;629GD;ST. JOHN VA OUTPATIENT CLINIC|MA;518;EDITH NOURSE ROGERS VAMC|MA;631GF;FITCHBURG CBOC|MA;518GG;FITCHBURG CBOC|MA;518GE;GLOUCESTER VA CLINIC|MA;631GD;GREENFIELD CBOC|MA;518GB;HAVERHILL VA CLINIC|MA;650GB;HYANNIS CBOC|MA;518GA;LYNN VA CLINIC|MA;650GA;NEW BEDFORD CBOC|MA;631GC;PITTSFIELD CBOC|MA;523GD;PLYMOUTH CBOC|MA;523;VA BOSTON HEALTHCARE SYSTEM - BOSTON DIVISION|MA;523A5;VA BOSTON HEALTHCARE SYSTEM - BROCKTON DIVISION|MA;523GA;VA BOSTON HEALTHCARE SYSTEM - FRAMINGHAM CBOC|MA;523GC;VA BOSTON HEALTHCARE SYSTEM - QUINCY CBOC|MA;523A4;VA BOSTON HEALTHCARE SYSTEM - WEST ROXBURY DIVISION|MA;523GB;VA BOSTON HEALTHCARE SYSTEM - WORCESTER DIVISION|MA;631;VA CNTRL WSTRN MASSCHUSETS HCS|MA;631GE;WORCESTER CBOC|MD;512;BALTIMORE VA MEDICAL CENTER|MD;512GA;CAMBRIDGE VA CLINIC|MD;688GD;CHARLOTTE HALL VA CLINIC|MD;613GA;CUMBERLAND CBOC|MD;613GG;FORT DETRICK VA CLINIC|MD;512GF;FORT HOWARD VA CLINIC|MD;512GG;FORT MEADE VA CLINIC|MD;512GC;GLEN BURNIE VA CLINIC|MD;688GC;GREENBELT VA CLINIC|MD;613GB;HAGERSTOWN VA CLINIC|MD;512GD;LOCH RAVEN VA CLINIC|MD;512A5;PERRY POINT VAMC|MD;512GE;POCOMOKE CITY VA CLINIC|MD;688GE;S PRINCE GEORGES CITY VA CLINIC|ME;402HB;BANGOR MAINE CBOC|ME;402GB;CALAIS MAINE CBOC|ME;402GA;CARIBOU MAINE CBOC|ME;402GE;LEWISTON AUBURN CBOC|ME;402GF;LINCOLN VA CLINIC|ME;402HC;PORTLAND MAINE MH ORC|ME;402GC;RUMFORD MAINE CBOC|ME;402GD;SACO MAINE CBOC|MI;655;ALEDA E. LUTZ VAMC|MI;506;ANN ARBOR VA MEDICAL CENTER|MI;655GF;BAD AXE VA CLINIC|MI;515;BATTLE CREEK VA MEDICAL CENTER|MI;515GC;BENTON HARBOR VA CLINIC|MI;655GG;CADILLAC VA CLINIC|MI;655GH;CHEBOYGAN COUNTY VA CLINIC|MI;655GE;CLARE VA CLINIC|MI;506GB;FLINT VA CLINIC|MI;655GI;GRAYLING VA CLINIC|MI;585GA;HANCOCK CBOC|MI;585;IRON MOUNTAIN VA MEDICAL CENTER|MI;585GD;IRONWOOD CBOC|MI;506GC;JACKSON CBOC|MI;553;JOHN D. DINGELL VAMC|MI;515GB;LANSING CBOC|MI;655GD;LT. COL CLEMENT VAN WAGONER VA|MI;585HA;MARQUETTE CBOC|MI;585GC;MENOMINEE CBOC|MI;515GA;MUSKEGON VA CLINIC|MI;655GC;OSCODA VA CLINIC|MI;553GB;PONTIAC VA CLINIC|MI;585HB;SAULT SAINT MARIE CBOC|MI;655GB;TRAVERSE CITY VA CLINIC|MI;515BY;WYOMING HEALTH CARE CENTER|MI;553GA;YALE VA CLINIC|MI;656GD;ZZ-ALPENA|MN;618GK;ALBERT LEA CBOC|MN;437GE;BEMIDJI CBOC|MN;656GA;BRAINERD VA COMMUNITY OUTPATIENT CLINIC|MN;437GC;FERGUS FALLS|MN;618GB;HIBBING (CBOC)|MN;656GC;MAX J. BEILKE CBOC|MN;618;MINNEAPOLIS VA HCS|MN;656GB;MONTEVIDEO CBOC|MN;618GI;NORTHWEST METRO VA OPC|MN;618GG;ROCHESTER (CBOC)|MN;618GA;SOUTH CENTRAL CBOC|MN;656;ST. CLOUD VA HEALTH CARE SYSTEM|MN;618GD;ST. PAUL (CBOC)|MO;589GB;BELTON VA CLINIC|MO;564GC;BRANSON CBOC|MO;589GZ;CAMERON CBOC|MO;657GH;CAPE GIRARDEAU MO CBOC (657GH)|MO;589JB;EXCELSIOR SPRINGS CBOC|MO;657GI;FARMINTON MO CBOC (657GI)|MO;589GF;FORT LEONARD WOOD VA CLINIC|MO;589A4;HARRY S. TRUMAN VAMC|MO;589JF;HONOR VA CLINIC|MO;589G8;JEFFERSON CITY, MO CBOC|MO;589GE;KIRKSVILLE VA CLINIC|MO;589GH;LAKE OF THE OZARKS VA CLINIC|MO;589JD;MARSHFIELD CBOC|MO;589GX;MEXICO CBOC (MO)|MO;589GD;NEVADA VA CLINIC|MO;589JE;PLATTE CITY VA CLINIC|MO;657GN;SALEM MO MOBILE OUTREACH CLINIC (657GN)|MO;589JA;SEDALIA CBOC|MO;657GV;SIKESTON CBOC|MO;657GD;ST CHARLES MO CBOC (657GD)|MO;657GB;ST LOUIS MO CBOC (657GB)|MO;589GY;ST. JAMES VA CLINIC|MO;589GI;ST. JOSEPH VA CLINIC|MO;589;VA HEARTLAND - WEST, VISN 15 (589)|MO;657A0;VA HEARTLAND-EAST, VISN 15 HCS JEFFERSON BARRACKS|MO;657;VA HEARTLAND-EAST, VISN 15 HCS JOHN COCHRAN MEMORIAL HOSPITAL|MO;657A4;VA HEARTLAND-EAST, VISN 15 HCS JOHN PERSHING VA MEDICAL CENTER|MO;589G1;WARRENSBURG MO CBOC|MO;657GS;WASHINGTON CBOC|MO;657GF;WEST PLAINS MO CBOC (657GF)|MS;520;BILOXI VA MEDICAL CENTER|MS;586GF;COLUMBUS|MS;586;G.V. (SONNY) MONTGOMERY|MS;586GC;GREENVILLE|MS;520A0;GULFPORT VAMC|MS;586GD;HATTIESBURG|MS;586GA;KOSCIUSKO VA CLINIC|MS;614GC;MARSHALL COUNTY VA CLINIC|MS;586GG;MCCOMB CBOC|MS;586GB;MERIDIAN|MS;586GE;NATCHEZ|MS;614GA;TUPELO CBOC|MT;436GA;ANACONDA CBOC|MT;436GH;BILLINGS VA CLINIC|MT;436GD;BOZEMAN VA CLINIC|MT;436GL;CUT BANK VA CLINIC|MT;436GI;GLASGOW VA CLINIC|MT;436GK;GLENDIVE VA CLINIC|MT;436GB;GREAT FALLS CBOC|MT;436GF;KALISPELL VA CLINIC|MT;436GM;LEWISTON CBOC|MT;436GJ;MILES CITY VA CLINIC|MT;436A4;MILES CITY VA MEDICAL CENTER|MT;436GC;MISSOULA CBOC|NC;590GC;ALBEMARLE CBOC|NC;637;CHARLES GEORGE VAMC|NC;558;DURHAM VA MEDICAL CENTER|NC;565;FAYETTEVILLE VA MEDICAL CENTER|NC;637GA;FRANKLIN VA CLINIC|NC;565GF;GOLDSBORO VA CLINIC|NC;558GA;GREENVILLE VA CLINIC|NC;565GD;HAMLET VA CLINIC|NC;659GB;HICKORY CBOC|NC;565GA;JACKSONVILLE VA CLINIC|NC;558GC;MOREHEAD CITY VA CLINIC|NC;659GA;NORTH CHARLOTTE VA CLINIC|NC;558GB;RALEIGH VA CLINIC|NC;565GE;ROBESON COUNTY VA CLINIC|NC;637GB;RUTHERFORD COUNTY VA CLINIC|NC;659;W.G. HEFNER SALISBURY VAMC|NC;565GC;WILMINGTON VA CLINIC|NC;659BY;WINSTON-SALEM,OPC|ND;437GB;BISMARCK|ND;437GA;GRAFTON|ND;437GI;GRAND FORKS CBOC|ND;437GD;MINOT CBOC|ND;437GF;WILLISTON CBOC|NE;636GL;BELLEVUE VA CBOC|NE;568HB;GORDON CBOC|NE;636GQ;HOLDREGE, NE CBOC|NE;636GA;NORFOLK CBOC|NE;636GB;NORTH PLATTE CBOC|NE;568HH;SCOTTSBLUFF CBOC|NE;442GB;SIDNEY VA CLINC|NE;636A5;VA CENTRAL PLAINS HEALTH NETWORK - LINCOLN DIVISION|NE;636;VA CENTRAL PLAINS HEALTH NETWORK - OMAHA DIVISION|NE;636A4;VA NWIHS, GRAND ISLAND DIV|NH;608GD;CONWAY CBOC|NH;405HE;KEENE OUT REACH CENTER|NH;608;MANCHESTER VAMC|NH;608GA;PORTSMOUTH CBOC|NH;608GC;SOMERSWORTH CBOC|NH;405HC;ST. JOHNSBURY VERMONT OUTREACH CLINIC|NH;608HA;TILTON CBOC|NJ;460HE;ATLANTIC COUNTY VA CLINIC|NJ;460GD;CAPE MAY (WILMINGTON)|NJ;460HG;CUMBERLAND COUNTY VA CLINIC|NJ;561GB;ELIZABETH CBOC|NJ;642GA;FT. DIX (PHILADELPHIA) CBOC|NJ;561GD;HACKENSACK CBOC|NJ;561GA;HAMILTON CBOC|NJ;561BZ;JAMES J HOWARD OUTPATIENT CLINIC|NJ;561GE;JERSEY CITY CBOC|NJ;561GH;MORRIS PLAINS CBOC|NJ;561;NEW JERSEY HEALTH CARE SYSTEM - EAST ORANGE|NJ;561A4;NEW JERSEY HEALTH CARE SYSTEM - LYONS CAMPUS|NJ;561GJ;PATERSON CBOC|NJ;561GF;PISCATAWAY CBOC|NJ;561GI;TINTON FALLS CBOC|NJ;642GD;VET HEALTH CLINIC (GLOUCESTER)|NM;501GI;ALAMOGORDO VA CLINIC|NM;501GA;ARTESIA VA CLINIC|NM;501GE;ESPANOLA (CBOC)|NM;501GB;FARMINGTON VA CLINIC|NM;501GD;GALLUP VA CLINIC|NM;519GB;HOBBS CBOC|NM;756GA;LAS CRUCES CBOC|NM;501G2;LAS VEGAS (CBOC)|NM;501GM;NORTHWEST METRO VA CLINIC|NM;501HB;RATON (CBOC)|NM;501;RAYMOND G. MURPHY VAMC|NM;501GK;SANTA FE VA CLINIC|NM;501GC;SILVER CITY VA CLINIC|NM;501GH;TRUTH OR CONSEQUENCES (CBOC)|NV;654GB;CARSON VALLEY CBOC|NV;660GC;ELY VA CLINIC|NV;593GC;PAHRUMP CBOC|NV;593;SOUTHERN NEVADA HCS|NV;654GC;VA LAHONTAN VALLEY CBOC|NV;654;VA SIERRA NEVADA HEALTH CARE SYSTEM (654)|NY;528G5;AUBURN|NY;528A6;BATH VA MEDICAL CENTER|NY;632HC;BAY SHORE CBOC|NY;528GN;BINGHAMTON CBOC|NY;526;BRONX VA HOSPITAL|NY;528;BUFFALO VA MEDICAL CENTER|NY;528A5;CANANDAIGUA VA MEDICAL CENTER|NY;528G7;CATSKILL CBOC|NY;528GY;CLIFTON PARK CBOC|NY;528G9;CORTLAND|NY;528GC;DUNKIRK VA CLINIC|NY;632GA;EAST MEADOW CBOC|NY;620GH;EASTERN DUTCHESS CBOC|NY;528G4;ELMIRA CBOC|NY;528G6;FONDA CBOC|NY;528GT;GLENS FALLS CBOC|NY;620GD;GOSHEN CBOC|NY;630GA;HARLEM CBOC-NYHHS|NY;620GF;HARRIS|NY;528GB;JAMESTOWN VA CLINIC|NY;528GZ;KINGSTON CBOC|NY;528GQ;LACKAWANNA CBOC|NY;528GK;LOCKPORT|NY;528G1;MALONE CBOC|NY;528GL;MASSENA CBOC|NY;620GA;NEW CITY|NY;528GD;NIAGARA FALLS VA CLINIC|NY;526GD;NORTH QUEENS CLINIC|NY;632;NORTHPORT VAMC NY|NY;528GR;OLEAN CBOC|NY;528GP;OSWEGO CBOC|NY;632HD;PATCHOGUE,NY ORC|NY;528GV;PLATTSBURGH|NY;620GE;PORT JERVIS|NY;620GG;POUGHKEEPSIE|NY;620GB;PUTNAM COUNTY|NY;632HB;RIVERHEAD,NY ORC|NY;528GE;ROCHESTER OPC|NY;528GM;ROME CBOC|NY;528A8;SAMUEL S. STRATTON VAMC|NY;528GW;SCHENECTADY CBOC|NY;528G3;SIDNEY CBOC|NY;630A5;ST ALBANS EXTENDED CARE CNTR|NY;630GB;STATEN ISLAND CBOC-NYHHCS|NY;528A7;SYRACUSE VA MEDICAL CENTER|NY;528GX;TROY CBOC|NY;528A4;VA HEALTHCARE NETWORK UPSTATE NEW YORK SYSTEM VISN 2 - BATAVIA DIVISION|NY;620A4;VA HUDSON VALLEY HEALTH CARE - CASTLE POINT DIVISION|NY;620;VA HUDSON VALLEY HEALTH CARE SYSTEM - MONTROSE DIVISION|NY;630A4;VA NEW YORK HARBOR HEALTHCARE SYSTEM - BROOKLYN DIVISION|NY;630;VA NEW YORK HARBOR HEALTHCARE SYSTEM - NEW YORK DIVISION|NY;632HA;VALLEY STREAM CBOC|NY;528GO;WATERTOWN CBOC|NY;528G8;WELLSVILLE CBOC|NY;528G2;WESTPORT CBOC|NY;526GA;WHITE PLAINS CLINIC|NY;526GB;YONKERS CLINIC|OH;541GG;AKRON CBOC|OH;562GB;ASHTABULA COUNTY CBOC (562GB)|OH;538GA;ATHENS VA CLINIC|OH;646GA;BELMONT COUNTY CBOC|OH;538GE;CAMBRIDGE VA CLINIC|OH;541BY;CANTON CBOC|OH;757;CHALMERS P. WYLIE VA AMBULATORY CARE CENTER (757)|OH;538;CHILLICOTHE VA MEDICAL CENTER|OH;539GB;CINCINNATI (CLERMONT COUNTY)|OH;539;CINCINNATI VAMC|OH;541GM;CLEVELAND AMBULATORY CTR CBOC|OH;541;CLEVELAND VAMC|OH;552;DAYTON, OH VAMC|OH;541GH;EAST LIVERPOOL CBOC|OH;539GF;GEORGETOWN CBOC|OH;757GB;GROVE CITY CBOC|OH;539GE;HAMILTON OHIO CBOC|OH;538GD;LANCASTER VA CLINIC|OH;552GB;LIMA CBOC|OH;541GB;LORAIN CBOC|OH;541GD;MANSFIELD CBOC|OH;538GC;MARIETTA VA CLINIC|OH;757GC;MARION CBOC|OH;541GE;MCCAFERTY CBOC|OH;552GA;MIDDLETOWN CBOC|OH;541GJ;NEW PHILADELPHIA CBOC|OH;757GD;NEWARK CBOC|OH;541GF;PAINSVILLE CBOC|OH;541GL;PARMA CBOC|OH;538GB;PORTSMOUTH VA CLINIC|OH;541GK;RAVENNA CBOC|OH;541GC;SANDUSKY CBOC|OH;552GD;SPRINGFIELD CBOC|OH;506GA;TOLEDO VA CLINIC|OH;541GI;WARREN CBOC|OH;541BZ;YOUNGSTOWN CBOC|OH;757GA;ZANESVILLE CBOC|OK;635GD;ADA CBOC|OK;635GF;ALTUS CBOC|OK;635HB;ARDMORE VETERANS CENTER CLINIC|OK;635GC;BLACKWELL CBOC|OK;635GG;ENID CBOC|OK;623GA;HARTSHORNE CBOC|OK;564GE;JAY CBOC|OK;623;MUSKOGEE, OK VAMC|OK;635;OKLAHOMA CITY VA MEDICAL CENTER|OK;635GE;STILLWATER CBOC|OK;623BY;TULSA, OK CBOC|OK;623GB;VINITA CBOC|OR;648GA;BEND, OR CBOC|OR;653GB;BROOKINGS VA CLINIC|OR;648GE;EAST PORTLAND VA CLINIC|OR;653BY;EUGENE, OR CBOC|OR;692GB;GRANTS PASS CBOC|OR;648GF;HILLSBORO VA CLINIC|OR;692GA;KLAMATH FALLS VA CLINIC|OR;687GC;LA GRANDE CBOC|OR;653GA;NORTH BEND VA CLINIC|OR;648GD;NORTH COAST VA CLINIC|OR;648;PORTLAND VA MEDICAL CENTER|OR;653;ROSEBURG VA MEDICAL CENTER|OR;648GB;SALEM VA CLINIC|OR;648GG;WEST LINN CBOC|OR;692;WHITE CITY VA MEDICAL CENTER|PA;646GC;BEAVER CBOC|PA;595GD;BERKS VA OUTPATIENT CLINIC|PA;693GF;BERWICK CBOC|PA;529GC;BUTLER VAMC - ARMSTRONG CBOC|PA;529GB;BUTLER VAMC - LAWRENCE CBOC|PA;529GA;BUTLER VAMC - MERCER CBOC|PA;529;BUTLER VETERANS AFFAIRS MEDICAL CENTER|PA;595GA;CAMPHILL CLINIC|PA;529GD;CLARION COUNTY VA CLINIC|PA;542;COATESVILLE VA MEDICAL CENTER|PA;529GF;CRANBERRY TOWNSHIP CBOC|PA;562GA;CRAWFORD COUNTY CBOC|PA;503GB;DUBOIS CBOC|PA;562;ERIE VAMC|PA;646GE;FAYETTE COUNTY CBOC|PA;503GD;HUNTINGDON COUNTY VA CLINIC|PA;503GE;INDIANA COUNTY VA CLINIC|PA;503;JAMES E VAN ZANDT VAMC|PA;503GA;JOHNSTOWN VA CLINIC|PA;595GC;LANCASTER VA OUTPATIENT CLINIC|PA;595;LEBANON VA MEDICAL CENTER|PA;562GC;MCKEAN COUNTY CBOC (562GC)|PA;542GA;MEDIA CBOC|PA;693GG;NORTHAMPTON COUNTY CLINIC|PA;642;PHILADELPHIA, PA VAMC|PA;646;PITTSBURGH HEALTH CARE SYSTEM - UNIVERSITY DRIVE DIVISION|PA;595GF;SCHUYLKILL COUNTY CBOC|PA;693GE;SCHUYLKILL COUNTY CBOC|PA;542GE;SPRING CITY CBOC|PA;503GC;STATE COLLEGE VA CLINIC|PA;693GC;TOBYHANNA CBOC|PA;646A4;VA HEALTH CARE SYSTEM HEINZ DIVISION|PA;562GD;VENANGO COUNTY CLINIC|PA;642GC;VICTOR J SARACINI VA OPC|PA;562GE;WARREN COUNTY CLINIC|PA;646GD;WASHINGTON VA PRIMARY CARE OUTPATIENT CLINIC|PA;646GB;WESTMORELAND CBOC|PA;693GD;WILKES-BARRE (CBOC)|PA;693;WILKES-BARRE VAMC|PA;693GB;WILLIAMSPORT CBOC|PA;595GE;YORK VA OUTPATIENT CLINIC|PR;672GC;ARECIBO VETERANS CLINIC (CBOC)|PR;672GD;CEIBA VA CLINIC|PR;672GE;GUAYAMA VA CLINIC|PR;672;SAN JUAN VA MEDICAL CENTER|RI;650GD;MIDDLETOWN CBOC|RI;650;PROVIDENCE VAMC|SC;509GB;AIKEN CBOC|SC;544GD;ANDERSON CBOC|SC;534GC;BEAUFORT PRIMARY CARE CLINIC|SC;544GB;FLORENCE CBOC|SC;534GD;GOOSE CREEK CBOC|SC;534GB;MYRTLE  BEACH PRIMARY CARE CLINIC|SC;544GE;ORANGEBURG CBOC|SC;534;RALPH H. JOHNSON VA MEDICAL CENTER (534)|SC;544GC;ROCK HILL CBOC|SC;544GG;SPARTANBURG CBOC|SC;544GF;SUMTER CBOC|SC;544;WM JENNINGS BRYAN DORN VETERANS AFFAIRS MEDICAL CENTER|SD;438GD;ABERDEEN CBOC|SD;568;BLACK HILLS HEALTH CARE SYSTEM - FT. MEADE DIVISION|SD;568HM;EAGLE BUTTE|SD;568A4;HOT SPRINGS, SD MC|SD;568HK;MCLAUGHLIN|SD;568HJ;MISSION CBOC|SD;568GB;PIERRE CBOC|SD;568HF;PINE RIDGE|SD;568GA;RAPID CITY CBOC|SD;438GE;WAGNER CBOC|SD;438GF;WATERTOWN CBOC|SD;568HP;WINNER|TN;626A4;ALVIN C. YORK VAMC|TN;614GH;BOLIVAR CBOC|TN;621GK;CAMPBELL COUNTY VA CLINIC|TN;626GF;CHATTANOOGA VA CLINIC|TN;626GE;CLARKSVILLE VA CLINIC|TN;626GH;COOKEVILLE VA CLINIC|TN;614GE;COVINGTON VA CLINIC|TN;626GA;DOVER VA CLINIC|TN;614GI;DYERSBURG VA CLINIC|TN;614GG;JACKSON VA CLINIC|TN;621;JAMES H. QUILLEN VAMC|TN;626GM;MAURY COUNTY CBOC|TN;626GK;MCMINNVILLE VA CLINIC|TN;614GF;MEMPHIS SOUTH VA CLINIC|TN;614;MEMPHIS VA MEDICAL CENTER|TN;621GG;MORRISTOWN VA CLINIC|TN;626;NASHVILLE VA MEDICAL CENTER|TN;626GL;ROANE COUNTY VA CLINIC|TN;621GA;ROGERSVILLE VA CLINIC|TN;614GD;SAVANNAH VA CLINIC|TN;621GI;SEVIERVILLE VA CLINIC|TN;626GG;TULLAHOMA COMMUNITY BASED OUTPATIENT CLINIC|TN;621BY;WILLIAM C. TALLENT VA OPC|TX;519HC;ABILENE CBOC|TX;504;AMARILLO HCS|TX;674GB;BROWNWOOD, TX  CBOC|TX;674GC;BRYAN, TX CBOC|TX;674GD;CEDAR PARK TEXAS CBOC|TX;674;CENTRAL TEXAS HEALTH CARE SYSTEM - TEMPLE DIVISION|TX;671GH;CHRISTUS SPOHN AGARITA FAMILY HEALTH CLINIC|TX;671GI;CHRISTUS SPOHN BISHOP FAMILY HEALTH CLINIC|TX;671GG;CHRISTUS SPOHN SAN DIEGO FAMILY HEALTH CLINIC|TX;580GD;CONROE CBOC|TX;504HB;DALHART CBOC|TX;671GC;DEL RIO CBOC|TX;740GE;EAGLE PASS CBOC|TX;756GB;EL PASO EASTSIDE CBOC|TX;756;EL PASO HCS|TX;549BY;FORT WORTH VA CBOC|TX;519GD;FT. STOCKTON CBOC|TX;580GC;GALVESTON COUNTY VA CLINIC|TX;671GJ;HEALTHCARE CLINIC OF UVALDE MEMORIAL HOSPITAL|TX;580GA;HOUSTON CBOC|TX;580GE;KATY CBOC|TX;580GF;LAKE JACKSON CBOC|TX;667GC;LONGVIEW CBOC|TX;580;MICHAEL E. DEBAKEY VA MEDICAL CENTER|TX;671GL;NEW BRAUNFELS VA CLINIC|TX;549GC;NORTH TEXAS HEALTH CARE SYSTEM - BONHAM CBOC|TX;549A4;NORTH TEXAS HEALTH CARE SYSTEM - BONHAM DIVISION|TX;549GI;NORTH TEXAS HEALTH CARE SYSTEM - CLEBURNE CBOC|TX;549GB;NORTH TEXAS HEALTH CARE SYSTEM - DALLAS CBOC|TX;549;NORTH TEXAS HEALTH CARE SYSTEM - DALLAS DIVISION|TX;549GE;NORTH TEXAS HEALTH CARE SYSTEM - DECATUR CBOC|TX;549GD;NORTH TEXAS HEALTH CARE SYSTEM - DENTON CBOC|TX;549GF;NORTH TEXAS HEALTH CARE SYSTEM - EASTLAND CBOC|TX;549GH;NORTH TEXAS HEALTH CARE SYSTEM - GREENVILLE CBOC|TX;549GA;NORTH TEXAS HEALTH CARE SYSTEM - TYLER CBOC|TX;674GA;PALESTINE, TX  CMOC|TX;519GA;PERMIAN BASIN CBOC|TX;580GG;RICHMOND CBOC|TX;519HF;SAN ANGELO CBOC|TX;671GN;SEGUIN|TX;549GJ;SHERMAN CBOC|TX;671GF;SOUTH TEXAS HCS|TX;671A4;SOUTH TEXAS HEALTH CARE SYSTEM - KERRVILLE DIVISION|TX;671;SOUTH TEXAS HEALTH CARE SYSTEM - SAN ANTONIO DIVISION|TX;519HD;STAMFORD CBOC|TX;740;TEXAS VALLEY COASTAL BEND HCS|TX;580GH;TOMBALL CBOC|TX;671GD;UNITED MEDICAL CENTERS|TX;671GA;VA HARLINGEN OUTPATIENT CLINIC|TX;674A4;WACO, TX VAMC|TX;671GK;WELLMED AT NORTHWEST 410|TX;519;WEST TEXAS VA HEALTH CARE SYSTEM - BIG SPRING DIVISION|TX;635GB;WICHITA FALLS CBOC VETERANS CLINIC OF NORTH TEXAS|UT;660;GEORGE E. WAHLEN VAMC|UT;660GB;OGDEN VA CLINIC|UT;660GE;OREM VA CLINIC|UT;660GD;ROOSEVELT VA CLINIC|UT;660GG;ST. GEORGE VA CLINIC|UT;660GJ;WESTERN SALT LAKE VA CLINIC|VA;621GJ;BRISTOL VA CLINIC|VA;652GE;CHARLOTTESVILLE VA CLINIC|VA;658GB;DANVILLE VA CLINIC|VA;652GF;EMPORIA VA CLINIC|VA;688GA;FORT BELVOIR VA CLINIC|VA;652GA;FREDERICKSBURG VA CLINIC|VA;590;HAMPTON VA MEDICAL CENTER|VA;613GF;HARRISONBURG VA CLINIC|VA;652;HUNTER HOLMES MCGUIRE HOSPITAL|VA;658GC;LYNCHBURG VA CLINIC|VA;621GC;NORTON VA CLINIC|VA;658;SALEM VA MEDICAL CENTER|VA;658GD;STAUNTON CBOC|VA;613GC;STEPHENS CITY VA CLINIC|VA;658GA;TAZEWELL VA CLINIC|VA;590GB;VIRGINIA BEACH VA CLINIC|VA;658GE;WYTHEVILLE VA CLINIC|VI;672GA;ST.CROIX VETERANS CLINIC|VI;672GB;ST.THOMAS VETERANS CLINIC|VT;405GA;BENNINGTON VERMONT OUTREACH CLINIC|VT;405GC;BRATTLEBORO CBOC|VT;405HA;BURLINGTON LAKESIDE CBOC|VT;405HF;RUTLAND VERMONT OUTREACH CLINIC|WA;663GA;BELLEVUE VA CLINIC|WA;663GB;BREMERTON VA CLINIC|WA;687;JONATHAN M. WAINWRIGHT VAMC|WA;668;MANN-GRANDSTAFF VAMC|WA;663GC;MOUNT VERNON VA CLINIC|WA;663A4;PUGET SOUND HEALTH CARE SYSTEM - AMERICAN LAKE DIVISION|WA;687GA;RICHLAND VA CLINIC|WA;663;SEATTLE VA MEDICAL CENTER|WA;663GD;SOUTH SOUND VA CLINIC|WA;648A4;VANCOUVER,WA DIV PORTLAND VAMC|WA;668GA;WENATCHEE VA CLINIC|WA;687HA;YAKIMA CBOC|WI;607GD;BARABOO, WI CBOC|WI;607GE;BEAVER DAM, WI CBOC|WI;618GE;CHIPPEWA VALLEY CBOC|WI;676GE;CLARK COUNTY CBOC|WI;695;CLEMENT J ZABLOCKI|WI;695GC;CLEVELAND CBOC|WI;618GH;HAYWARD CBOC|WI;607GC;JANESVILLE, WI CBOC|WI;556GD;KENOSHA CBOC|WI;676GC;LACROSSE CBOC|WI;676GB;LEAVENWORTH, WI CBOC|WI;695GD;MILO C. HUEMPFNER CBOC|WI;585GB;RHINELANDER CBOC|WI;676;TOMAH VAMC|WI;695GA;UNION GROVE|WI;676GA;WAUSAU CBOC|WI;607;WILLIAM S. MIDDLETON MEMORIAL VA HOSPITAL|WI;676GD;WISCONSIN RAPIDS CBOC|WV;517;BECKLEY VA MEDICAL CENTER|WV;540GC;BRAXTON CBOC|WV;581GB;CHARLESTON VA CLINIC|WV;540GA;CLARKSBURG/TUCKER|WV;540GB;CLARKSBURG/WOOD|WV;613GD;FRANKLIN VA CLINIC|WV;517GB;GREENBRIER COUNTY VA CLINIC|WV;581;HUNTINGTON VAMC|WV;540;LOUIS A JOHNSON VA MEDICAL CENTER|WV;613;MARTINSBURG VA MEDICAL CENTER|WV;540GD;MONONGALIA CBOC|WV;613GE;PETERSBURG VA CLINIC|WY;666GB;CASPER CBOC|WY;666GE;GILLETTE VA CLINIC|WY;442MB;IDES SHERIDAN VAMC|WY;568HA;NEWCASTLE|WY;666GD;POWELL VA CLINIC|WY;666GC;RIVERTON VA CLINIC|WY;666GF;ROCK SPRINGS CBOC|WY;666;SHERIDAN VA MEDICAL CENTER", transform: identityTransform },
    { node: "formSessionID",  arg: "fb47f49e-89a6-4ec4-8280-c55c2b5d915b", transform: identityTransform },
    { node: "EDIPI",  arg: null, transform: identityTransform },
    { node: "VetSocialSecurityNumber",  arg: "111-22-3333", transform: identityTransform },
    { node: "DateOfBirth",  arg: "01/01/1970", transform: identityTransform },
    { node: "Gender",  arg: "M", transform: identityTransform },
    { node: "VetNameLast",  arg: "ALastName", transform: identityTransform },
    { node: "VetNameFirst",  arg: "AFirstName", transform: identityTransform },
    { node: "VetNamePrefix",  arg: null, transform: identityTransform },
    { node: "VetNameSuffix",  arg: "SR", transform: identityTransform },
    { node: "VetNameMiddle",  arg: "AMiddleName", transform: identityTransform },
    { node: "Anonymous",  arg: "Y", transform: identityTransform },
    { node: "Level",  arg: "Anonymous", transform: identityTransform },
    { node: "VetIDType",  arg: null, transform: identityTransform },
    { node: "REVIEWINGFORM",  arg: "1", transform: identityTransform },
    { node: "LASTPAGE",  arg: "pgSubmit", transform: identityTransform },
    { node: "APPTYPE",  arg: "Enrollment", transform: identityTransform },
    { node: "USStates",  arg: " ", transform: identityTransform },
    { node: "CANStates",  arg: " ", transform: identityTransform },
    { node: "MEXStates",  arg: " ", transform: identityTransform },
    { node: "Countries",  arg: "USA", transform: identityTransform },
    { node: "pgIntro2Visited",  arg: "1", transform: identityTransform },
    { node: "DateOfBirthMonth",  arg: "1", transform: identityTransform },
    { node: "DateOfBirthDay",  arg: "1", transform: identityTransform },
    { node: "DateOfBirthYear",  arg: "1970", transform: identityTransform },
    { node: "PlaceOfBirthCity",  arg: "Kent", transform: identityTransform },
    { node: "PlaceOfBirthState",  arg: "WA", transform: identityTransform },
    { node: "State",  arg: "WA", transform: identityTransform },
    { node: "MedCenterID",  arg: null, transform: identityTransform },
    { node: "StationStateList",  arg: "TT;TEST SITES|AL;ALABAMA|AK;ALASKA|AS;AMERICAN SAMOA|AZ;ARIZONA|AR;ARKANSAS|CA;CALIFORNIA|CO;COLORADO|CT;CONNECTICUT|DE;DELAWARE|DC;D. OF COLUMBIA|FL;FLORIDA|GA;GEORGIA|GU;GUAM|HI;HAWAII|ID;IDAHO|IL;ILLINOIS|IN;INDIANA|IA;IOWA|KS;KANSAS|KY;KENTUCKY|LA;LOUISIANA|ME;MAINE|MD;MARYLAND|MA;MASSACHUSETTS|MI;MICHIGAN|MN;MINNESOTA|MS;MISSISSIPPI|MO;MISSOURI|MT;MONTANA|NE;NEBRASKA|NV;NEVADA|NH;NEW HAMPSHIRE|NJ;NEW JERSEY|NM;NEW MEXICO|NY;NEW YORK|NC;NORTH CAROLINA|ND;NORTH DAKOTA|MP;NORTHERN MARIANA ISLANDS|OH;OHIO|OK;OKLAHOMA|OR;OREGON|PA;PENNSYLVANIA|PI;PHILIPPINES|PR;PUERTO RICO|RI;RHODE ISLAND|SC;SOUTH CAROLINA|SD;SOUTH DAKOTA|TN;TENNESSEE|TX;TEXAS|UT;UTAH|VT;VERMONT|VI;VIRGIN ISLANDS|VA;VIRGINIA|WA;WASHINGTON|WV;WEST VIRGINIA|WI;WISCONSIN|WY;WYOMING", transform: identityTransform },
    { node: "MedCenter",  arg: "663A4", transform: identityTransform },
    { node: "pgDemoVisited",  arg: "1", transform: identityTransform },
    { node: "Email2",  arg: "test@foo.com", transform: identityTransform },
    { node: "HIContrecordno",  arg: "HEALTH INSURANCE #1", transform: identityTransform },
    { node: "VetHealthInsureCompany",  arg: "AInsurance1", transform: identityTransform },
    { node: "VetHealthInsureAddress",  arg: "1 Insurance Way", transform: identityTransform },
    { node: "VetHealthInsureCity",  arg: "New York", transform: identityTransform },
    { node: "VetHealthInsureCountry",  arg: "USA", transform: identityTransform },
    { node: "VetHealthInsureState",  arg: "NY", transform: identityTransform },
    { node: "VetHealthInsureZip",  arg: "02123", transform: identityTransform },
    { node: "VetHealthInsurePostalCode",  arg: null, transform: identityTransform },
    { node: "VetHealthInsurePhone",  arg: "(202) 123-4567", transform: identityTransform },
    { node: "VetHealthPolicyHolder",  arg: "APolicy Holder", transform: identityTransform },
    { node: "VetHealthPolicyNumber",  arg: "Policy1", transform: identityTransform },
    { node: "VetHealthGroupCode",  arg: "Group1", transform: identityTransform },
    { node: "DateMedicarePartAMonth",  arg: "4", transform: identityTransform },
    { node: "DateMedicarePartADay",  arg: "3", transform: identityTransform },
    { node: "DateMedicarePartAYear",  arg: "1980", transform: identityTransform },
    { node: "LastEntryDateMonth",  arg: "5", transform: identityTransform },
    { node: "LastEntryDateDay",  arg: "6", transform: identityTransform },
    { node: "LastEntryDateYear",  arg: "1985", transform: identityTransform },
    { node: "LastDischargeDateMonth",  arg: "5", transform: identityTransform },
    { node: "LastDischargeDateDay",  arg: "8", transform: identityTransform },
    { node: "LastDischargeDateYear",  arg: "1990", transform: identityTransform },
    { node: "pgAdditionalServiceVisited",  arg: "1", transform: identityTransform },
    { node: "pgAdditionalServiceVisited",  arg: "0", transform: identityTransform },
    { node: "SpouseNameLast",  arg: "SpouseLast", transform: identityTransform },
    { node: "SpouseNameFirst",  arg: "SpouseFirst", transform: identityTransform },
    { node: "SpouseNameMiddle",  arg: "SpouseMiddle", transform: identityTransform },
    { node: "SpouseNameSuffix",  arg: "JR", transform: identityTransform },
    { node: "SpouseDateOfBirthMonth",  arg: "4", transform: identityTransform },
    { node: "SpouseDateOfBirthDay",  arg: "3", transform: identityTransform },
    { node: "SpouseDateOfBirthYear",  arg: "1990", transform: identityTransform },
    { node: "MarraigeDateMonth",  arg: "6", transform: identityTransform },
    { node: "MarraigeDateDay",  arg: "8", transform: identityTransform },
    { node: "MarraigeDateYear",  arg: "2010", transform: identityTransform },
    { node: "SpouseAddress",  arg: "1 Spouse Dr", transform: identityTransform },
    { node: "SpouseCity",  arg: "Auburn", transform: identityTransform },
    { node: "SpouseCountry",  arg: "USA", transform: identityTransform },
    { node: "SpouseState",  arg: "AZ", transform: identityTransform },
    { node: "SpouseZip",  arg: "33421", transform: identityTransform },
    { node: "SpousePostalCode",  arg: null, transform: identityTransform },
    { node: "SpousePhone",  arg: "(344) 222-1111", transform: identityTransform },
    { node: "CHContrecordno",  arg: "CHILD #1 OF 2", transform: identityTransform },
    { node: "ChildNameLast",  arg: "ChildLast1", transform: identityTransform },
    { node: "ChildNameFirst",  arg: "ChildLast1", transform: identityTransform },
    { node: "ChildNameMiddle",  arg: "ChildMiddle1", transform: identityTransform },
    { node: "ChildNameSuffix",  arg: "JR", transform: identityTransform },
    { node: "ChildRelationshipSon",  arg: "0", transform: identityTransform },
    { node: "ChildRelationshipDaughter",  arg: "0", transform: identityTransform },
    { node: "ChildRelationshipStepson",  arg: "0", transform: identityTransform },
    { node: "ChildRelationshipStepdaughter",  arg: "1", transform: identityTransform },
    { node: "ChildSocialSecurityNumber",  arg: "333-44-5555", transform: identityTransform },
    { node: "ChildDependentDateMonth",  arg: "6", transform: identityTransform },
    { node: "ChildDependentDateDay",  arg: "3", transform: identityTransform },
    { node: "ChildDependentDateYear",  arg: "2010", transform: identityTransform },
    { node: "ChildDependentDate",  arg: "06/03/2010", transform: identityTransform },
    { node: "ChildDateOfBirthMonth",  arg: "2", transform: identityTransform },
    { node: "ChildDateOfBirthDay",  arg: "2", transform: identityTransform },
    { node: "ChildDateOfBirthYear",  arg: "2005", transform: identityTransform },
    { node: "ChildDateOfBirth",  arg: "02/02/2005", transform: identityTransform },
    { node: "ChildTotalDisabledYes",  arg: "0", transform: identityTransform },
    { node: "ChildTotalDisabledNo",  arg: "1", transform: identityTransform },
    { node: "ChildAttendSchoolYes",  arg: "1", transform: identityTransform },
    { node: "ChildAttendSchoolNo",  arg: "0", transform: identityTransform },
    { node: "ChildSelfSchool",  arg: "11235.00", transform: identityTransform },
    { node: "ChildSupportAmount",  arg: "600.00", transform: identityTransform },
    { node: "ChildLive",  arg: "0", transform: identityTransform },
    { node: "ChildLiveNo",  arg: "N", transform: identityTransform },
    { node: "ChildProvideSupportYes",  arg: "Y", transform: identityTransform },
    { node: "ChildProvideSupportNo",  arg: "0", transform: identityTransform },
    { node: "Child1GrossIncome",  arg: "1000.00", transform: identityTransform },
    { node: "Child1PropertyIncome",  arg: "98.00", transform: identityTransform },
    { node: "Child1OtherIncome",  arg: "76.00", transform: identityTransform },
    { node: "Child1BankCashAmount",  arg: null, transform: identityTransform },
    { node: "Child1LandMarketValue",  arg: null, transform: identityTransform },
    { node: "Child1OtherAssetNet",  arg: null, transform: identityTransform },
    { node: "tWelcome",  arg: "Introduction", transform: identityTransform },
    { node: "tPersonal",  arg: "Personal Information", transform: identityTransform },
    { node: "tInsurance",  arg: "Insurance Information", transform: identityTransform },
    { node: "tService",  arg: "Military Service", transform: identityTransform },
    { node: "tFinancial",  arg: "Financial Assessment", transform: identityTransform },
    { node: "pgFinalVisited",  arg: "1", transform: identityTransform },
    { node: "Comments",  arg: null, transform: identityTransform },
    { node: "AttType0",  arg: null, transform: identityTransform },
    { node: "Single_Attach0",  arg: null, transform: identityTransform },
    { node: "AttType1",  arg: null, transform: identityTransform },
    { node: "Single_Attach1",  arg: null, transform: identityTransform },
    { node: "AttType2",  arg: null, transform: identityTransform },
    { node: "Single_Attach2",  arg: null, transform: identityTransform },
    { node: "AttType3",  arg: null, transform: identityTransform },
    { node: "Single_Attach3",  arg: null, transform: identityTransform },
    { node: "viewerType",  arg: "Reader Reader", transform: identityTransform },
    { node: "viewerVersion",  arg: "15.00920069", transform: identityTransform },
    { node: "formVersion",  arg: "19", transform: identityTransform },
    { node: "place_birth",  arg: "Kent, WA", transform: identityTransform },
    { node: "MedCenterText",  arg: "PUGET SOUND HEALTH CARE SYSTEM - AMERICAN LAKE DIVISION", transform: identityTransform },
    { node: "Path",  arg: "A", transform: identityTransform },
    { node: "MotherMaidenName",  arg: "AMaidenName", transform: identityTransform },
    { node: "CurrentMaritalStatus",  arg: "MARRIED", transform: identityTransform },
    { node: "TargetURL",  arg: null, transform: identityTransform },
    { node: "Q1",  arg: "N", transform: identityTransform },
    { node: "Q2",  arg: "N", transform: identityTransform },
    { node: "Q3",  arg: "N", transform: identityTransform },
    { node: "ACA",  arg: "Y", transform: identityTransform },
    { node: "Appointment",  arg: "Y", transform: identityTransform },
    { node: "Spanish",  arg: "N", transform: identityTransform },
    { node: "Race1",  arg: "1", transform: identityTransform },
    { node: "Race2",  arg: "1", transform: identityTransform },
    { node: "Race5",  arg: "1", transform: identityTransform },
    { node: "Race3",  arg: "1", transform: identityTransform },
    { node: "Race4",  arg: "1", transform: identityTransform },
    { node: "ReligionList",  arg: "Select Religion", transform: identityTransform },
    { node: "CurrentAddress",  arg: "111 22st NE", transform: identityTransform },
    { node: "CurrentCity",  arg: "Kent", transform: identityTransform },
    { node: "CurrentCountry",  arg: "USA", transform: identityTransform },
    { node: "CurrentState",  arg: "WA", transform: identityTransform },
    { node: "CurrentZip",  arg: "98105", transform: identityTransform },
    { node: "CurrentPostalCode",  arg: null, transform: identityTransform },
    { node: "CurrentCounty",  arg: "King", transform: identityTransform },
    { node: "Email",  arg: "test@foo.com", transform: identityTransform },
    { node: "CurrentHomePhone",  arg: "(425) 333-2455", transform: identityTransform },
    { node: "CellPhone",  arg: "(425) 333-2456", transform: identityTransform },
    { node: "VetHealthInsurance",  arg: "Y", transform: identityTransform },
    { node: "MedicaidEligible",  arg: "N", transform: identityTransform },
    { node: "MedicareEnrolledA",  arg: "Y", transform: identityTransform },
    { node: "DateMedicarePartA",  arg: "04/03/1980", transform: identityTransform },
    { node: "LastServiceBranch",  arg: "COAST GUARD", transform: identityTransform },
    { node: "LastEntryDate",  arg: "05/06/1985", transform: identityTransform },
    { node: "LastDischargeDate",  arg: "05/08/1990", transform: identityTransform },
    { node: "DischargeType",  arg: "GENERAL", transform: identityTransform },
    { node: "MilitaryServiceNumber",  arg: null, transform: identityTransform },
    { node: "PurpleHeart",  arg: "N", transform: identityTransform },
    { node: "FormerPOW",  arg: "N", transform: identityTransform },
    { node: "TheaterOperation",  arg: "Y", transform: identityTransform },
    { node: "RetiredMilitaryDisability",  arg: "Y", transform: identityTransform },
    { node: "GulfWarToxinExposure",  arg: "Y", transform: identityTransform },
    { node: "AgentOrangeExposure",  arg: "Y", transform: identityTransform },
    { node: "RadiationExposure",  arg: "Y", transform: identityTransform },
    { node: "MilitaryRadiumTreatments",  arg: "Y", transform: identityTransform },
    { node: "CampLejeune",  arg: "Y", transform: identityTransform },
    { node: "ProvideDetails",  arg: "Y", transform: identityTransform },
    { node: "ConfirmProvideDetails",  arg: null, transform: identityTransform },
    { node: "SpouseSocialSecurityNumber",  arg: "222-33-4444", transform: identityTransform },
    { node: "SpouseDateOfBirth",  arg: "04/03/1990", transform: identityTransform },
    { node: "MarraigeDate",  arg: "06/08/2010", transform: identityTransform },
    { node: "SpouseSame",  arg: "2", transform: identityTransform },
    { node: "SpouseSupportAmount",  arg: "600.00", transform: identityTransform },
    { node: "SpouseLive",  arg: "N", transform: identityTransform },
    { node: "SpouseProvideSupport",  arg: "Y", transform: identityTransform },
    { node: "ReportChildren",  arg: "Y", transform: identityTransform },
    { node: "ProvideSupport",  arg: "Y", transform: identityTransform },
    { node: "VetGrossIncome",  arg: "55000.00", transform: identityTransform },
    { node: "VetPropertyIncome",  arg: "1200.00", transform: identityTransform },
    { node: "VetOtherIncome",  arg: "123.00", transform: identityTransform },
    { node: "SpouseGrossIncome",  arg: "60000.00", transform: identityTransform },
    { node: "SpousePropertyIncome",  arg: "2400.00", transform: identityTransform },
    { node: "SpouseOtherIncome",  arg: "234.00", transform: identityTransform },
    { node: "MedicalExpenses",  arg: "777.00", transform: identityTransform },
    { node: "FuneralExpenses",  arg: "666.00", transform: identityTransform },
    { node: "VetSelfSchool",  arg: "555.00", transform: identityTransform },
    { node: "VetBankCashAmount",  arg: null, transform: identityTransform },
    { node: "VetLandMarketValue",  arg: null, transform: identityTransform },
    { node: "VetOtherAssetNet",  arg: null, transform: identityTransform },
    { node: "SpouseBankCashAmount",  arg: null, transform: identityTransform },
    { node: "SpouseLandMarketValue",  arg: null, transform: identityTransform },
    { node: "SpouseOtherAssetNet",  arg: null, transform: identityTransform },
    { node: "Confirm",  arg: "VAToPrint", transform: identityTransform },
    { node: "pg1VetName",  arg: "ALASTNAME, AFIRSTNAME, AMIDDLENAME SR", transform: identityTransform },
    { node: "OtherName1",  arg: null, transform: identityTransform },
    { node: "ClaimNumber",  arg: null, transform: identityTransform },
    { node: "HEALTH_SERVICES",  arg: "0", transform: identityTransform },
    { node: "DENTAL",  arg: "0", transform: identityTransform },
    { node: "health_insurance",  arg: "AInsurance1\n1 Insurance Way\nNew York, NY 02123  (202) 123-4567", transform: identityTransform },
    { node: "FVetHealthPolicyHolder",  arg: "APolicy Holder", transform: identityTransform },
    { node: "FVetHealthPolicyNumber",  arg: "Policy1", transform: identityTransform },
    { node: "FVetHealthGroupCode",  arg: "Group1", transform: identityTransform },
    { node: "ReceiveDisabilityRetirement",  arg: null, transform: identityTransform },
    { node: "Fchild_name1",  arg: "CHILDLAST1, CHILDLAST1, CHILDMIDDLE1 JR", transform: identityTransform },
    { node: "FChild1RelationshipSon",  arg: "0", transform: identityTransform },
    { node: "FChild1RelationshipDaughter",  arg: "0", transform: identityTransform },
    { node: "FChild1RelationshipStepson",  arg: "0", transform: identityTransform },
    { node: "FChild1RelationshipStepdaughter",  arg: "1", transform: identityTransform },
    { node: "FChild1DependentDate",  arg: "06/03/2010", transform: identityTransform },
    { node: "FChild1DateOfBirth",  arg: "02/02/2005", transform: identityTransform },
    { node: "FChild1TotalDisabledYes",  arg: "0", transform: identityTransform },
    { node: "FChild1TotalDisabledNo",  arg: "1", transform: identityTransform },
    { node: "FChild1AttendSchoolYes",  arg: "1", transform: identityTransform },
    { node: "FChild1AttendSchoolNo",  arg: "0", transform: identityTransform },
    { node: "FChild1SelfSchool",  arg: "11235.00", transform: identityTransform },
    { node: "spouse_name",  arg: "SPOUSELAST, SPOUSEFIRST, SPOUSEMIDDLE JR", transform: identityTransform },
    { node: "spouse_address",  arg: "1 Spouse Dr\nAuburn, AZ 33421\n(344) 222-1111", transform: identityTransform },
    { node: "FChild1SocialSecurityNumber",  arg: "333-44-5555", transform: identityTransform },
    { node: "FChild1GrossIncome",  arg: "1000.00", transform: identityTransform },
    { node: "FChild1PropertyIncome",  arg: "98.00", transform: identityTransform },
    { node: "FChild1OtherIncome",  arg: "76.00", transform: identityTransform },
    { node: "FChild1BankCashAmount",  arg: null, transform: identityTransform },
    { node: "FChild1LandMarketValue",  arg: null, transform: identityTransform },
    { node: "FChild1OtherAssetNet",  arg: null, transform: identityTransform },
    { node: "TextField",  arg: "Online 10-10EZ Application for Health Benefits", transform: identityTransform },
    { node: "HIContrecordno",  arg: "HEALTH INSURANCE #2", transform: identityTransform },
    { node: "VetHealthInsureCompany",  arg: "AInsurance2", transform: identityTransform },
    { node: "VetHealthInsureAddress",  arg: "2 Insurance Way", transform: identityTransform },
    { node: "VetHealthInsureCity",  arg: "Boston", transform: identityTransform },
    { node: "VetHealthInsureCountry",  arg: "USA", transform: identityTransform },
    { node: "VetHealthInsureState",  arg: "MA", transform: identityTransform },
    { node: "VetHealthInsureZip",  arg: "12123", transform: identityTransform },
    { node: "VetHealthInsurePostalCode",  arg: null, transform: identityTransform },
    { node: "VetHealthInsurePhone",  arg: "(202) 923-4567", transform: identityTransform },
    { node: "VetHealthPolicyHolder",  arg: "2Policy Holder", transform: identityTransform },
    { node: "VetHealthPolicyNumber",  arg: "2Policy", transform: identityTransform },
    { node: "VetHealthGroupCode",  arg: "2Group", transform: identityTransform },
    { node: "TextField",  arg: "Online 10-10EZ Application for Health Benefits", transform: identityTransform },
    { node: "CHContrecordno",  arg: "CHILD #2 OF 2", transform: identityTransform },
    { node: "ChildNameLast",  arg: "LastChild2", transform: identityTransform },
    { node: "ChildNameFirst",  arg: "FirstChild2", transform: identityTransform },
    { node: "ChildNameMiddle",  arg: "MiddleChild2", transform: identityTransform },
    { node: "ChildNameSuffix",  arg: "II", transform: identityTransform },
    { node: "ChildRelationshipSon",  arg: "0", transform: identityTransform },
    { node: "ChildRelationshipDaughter",  arg: "1", transform: identityTransform },
    { node: "ChildRelationshipStepson",  arg: "0", transform: identityTransform },
    { node: "ChildRelationshipStepdaughter",  arg: "0", transform: identityTransform },
    { node: "ChildSocialSecurityNumber",  arg: "555-44-3333", transform: identityTransform },
    { node: "ChildDependentDateMonth",  arg: "4", transform: identityTransform },
    { node: "ChildDependentDateDay",  arg: "5", transform: identityTransform },
    { node: "ChildDependentDateYear",  arg: "1992", transform: identityTransform },
    { node: "ChildDependentDate",  arg: "04/05/1992", transform: identityTransform },
    { node: "ChildDateOfBirthMonth",  arg: "4", transform: identityTransform },
    { node: "ChildDateOfBirthDay",  arg: "5", transform: identityTransform },
    { node: "ChildDateOfBirthYear",  arg: "1992", transform: identityTransform },
    { node: "ChildDateOfBirth",  arg: "04/05/1992", transform: identityTransform },
    { node: "ChildTotalDisabledYes",  arg: "0", transform: identityTransform },
    { node: "ChildTotalDisabledNo",  arg: "1", transform: identityTransform },
    { node: "ChildAttendSchoolYes",  arg: "1", transform: identityTransform },
    { node: "ChildAttendSchoolNo",  arg: "0", transform: identityTransform },
    { node: "ChildSelfSchool",  arg: "9876.00", transform: identityTransform },
    { node: "ChildSupportAmount",  arg: null, transform: identityTransform },
    { node: "ChildLive",  arg: "Y", transform: identityTransform },
    { node: "ChildLiveNo",  arg: "0", transform: identityTransform },
    { node: "ChildProvideSupportYes",  arg: "0", transform: identityTransform },
    { node: "ChildProvideSupportNo",  arg: "0", transform: identityTransform },
    { node: "ChildGrossIncome",  arg: "54.00", transform: identityTransform },
    { node: "ChildPropertyIncome",  arg: "43.00", transform: identityTransform },
    { node: "ChildOtherIncome",  arg: "32.00", transform: identityTransform }
  ];

  var getFormRoot = function() {
    return document.querySelector(".main-form");
  };

  var saveForm = function(formRoot, e) {
    sessionStorage.setItem("voa_form", JSON.stringify($(formRoot).serializeArray()));
  };

  var initForm = function() {
    var formRoot = getFormRoot();

    // Suppress the submit behavior since submission is done via crafting an
    // XML payload for AJAX.
    formRoot.addEventListener("submit",
        function (e) {
          e.preventDefault();
          console.log(build1010ezXml(formRoot));
        });

    // Load saved form data if there is any.
    var savedData = sessionStorage.getItem("voa_form");
    if (savedData !== null) {
      $(formRoot).deserialize(JSON.parse(savedData));
    }

    // Set up auto-save on any changes to the form.
    getFormRoot().addEventListener("change",
        function (e) {
          saveForm(formRoot, e);
        });
  };

  var build1010ezXml = function(theForm) {
    var formData = $(theForm).serializeObject();
    var xmlDoc = document.implementation.createDocument(null, "form1");

    for (var i = 0; i < xmlFieldMap.length; i++) {
      var entry = xmlFieldMap[i];
      var element = xmlDoc.createElement(entry.node);

      var transform = entry.transform;
      if (transform === undefined) {
        transform = extractTransform;
      }

      var textData = transform(formData, entry.arg);
      if (textData !== null) {
        element.appendChild(xmlDoc.createTextNode(textData));
      }

      xmlDoc.firstChild.appendChild(element);
    }

    return xmlDoc;
  };

  return {
    xmlFieldMap: xmlFieldMap,
    getFormRoot: getFormRoot,
    saveForm: saveForm,
    build1010ezXml: build1010ezXml,
    initForm: initForm
  };
}());
$(document).ready(HealthApp.initForm);
