import React from 'react';
import PropTypes from 'prop-types';

import recordEvent from 'platform/monitoring/record-event';
import environment from 'platform/utilities/environment';

import { DATE_FORMATS } from '../constants';
import { buildDateFormatter } from '../utils/helpers';

const downloadUrl = id => `${environment.API_URL}/v0/claim_letters/${id}`;

const formatDate = buildDateFormatter(DATE_FORMATS.LONG_DATE);

const docTypeToDescription = {
  184: 'Notification Letter',
  27: 'Board Of Appeals Decision Letter',
};

const getDescription = docType => {
  const defaultDescription = 'Notification Letter';

  return docTypeToDescription[docType] || defaultDescription;
};

const filename = 'ClaimLetter.pdf';

// NOTE: This simulates some of the property values that get
// auto-generated by Google Tag Manager.
// gtm.elementUrl: {{Click URL}}
// gtm.eleemnt.textContent: {{Click Text}}
const downloadHandler = () => {
  recordEvent({
    event: 'claim-letters-download',
    'gtm.element.textContent': 'Download Claim Letter (PDF)',
    'gtm.elementUrl': `${environment.API_URL}/v0/claim_letters/:id.pdf`,
  });
};

const ClaimLetterListItem = ({ letter }) => {
  const formattedDate = formatDate(letter.receivedAt);
  const heading = `${formattedDate} letter`;

  return (
    <li className="vads-u-border-bottom--1px vads-u-border-color--gray-lighter vads-u-padding-bottom--2">
      <h2 className="vads-u-font-size--h4">{heading}</h2>
      <div className="vads-u-color--gray-warm-dark vads-u-margin-bottom--0p5">
        {getDescription(letter.docType)}
      </div>
      <va-link
        download
        filename={filename}
        filetype="PDF"
        href={downloadUrl(letter.documentId)}
        onClick={downloadHandler}
        text={`Download ${formattedDate} letter`}
      />
    </li>
  );
};

ClaimLetterListItem.propTypes = {
  letter: PropTypes.object,
};

export default ClaimLetterListItem;
