// prettier-ignore

export default Object.freeze({
  canUpload1010cgPOA: 'can_upload_10_10cg_poa',
  cernerOverride463: 'cerner_override_463',
  cernerOverride531: 'cerner_override_531',
  cernerOverride648: 'cerner_override_648',
  cernerOverride653: 'cerner_override_653',
  cernerOverride663: 'cerner_override_663',
  cernerOverride668: 'cerner_override_668',
  cernerOverride687: 'cerner_override_687',
  cernerOverride692: 'cerner_override_692',
  cernerOverride757: 'cerner_override_757',
  checkInExperienceEnabled: 'check_in_experience_enabled',
  checkInExperienceUpdateInformationPageEnabled: 'check_in_experience_update_information_page_enabled',
  checkInExperienceLowRiskAuthenicationEnabled:
    'check_in_experience_low_authentication_enabled',
  checkInExperienceMultipleAppointmentEnabled:
    'check_in_experience_multiple_appointment_support',
  coeAccess: 'coe_access',
  covidVaccineSchedulingFrontend: 'covid_vaccine_scheduling_frontend',
  covidVaccineUpdatesCTA: 'covid_vaccine_registration_frontend_cta',
  covidVaccineUpdatesDisableAuth:
    'covid_vaccine_registration_frontend_hide_auth',
  covidVaccineUpdatesEnableExpandedEligibility:
    'covid_vaccine_registration_frontend_enable_expanded_eligibility',
  covidVaccineUpdatesForm: 'covid_vaccine_registration_frontend',
  debtLettersShowLetters: 'debtLettersShowLetters',
  dependencyVerification: 'dependency_verification',
  dischargeWizardFeatures: 'discharge_wizard_features',
  evssUploadLimit150Mb: 'evss_upload_limit_150mb',
  facilitiesPpmsSuppressAll: 'facilities_ppms_suppress_all',
  facilitiesPpmsSuppressCommunityCare: 'facilities_ppms_suppress_community_care',
  facilitiesPpmsSuppressPharmacies: 'facilities_ppms_suppress_pharmacies',
  facilityLocatorCovidVaccineWalkInAvailabilityTextFrontend:
    'facility_locator_covid_vaccine_walk_in_availability_text_frontend',
  facilityLocatorLighthouseCovidVaccineQuery:
    'facility_locator_lighthouse_covid_vaccine_query',
  facilityLocatorPredictiveLocationSearch:
    'facility_locator_predictive_location_search',
  facilityLocatorRailsEngine: 'facility_locator_rails_engine',
  facilityLocatorShowCommunityCares: 'facility_locator_show_community_cares', // Facilities team has deprecated this flag for the frontEnd logic, there is still backend support though.
  facilityLocatorShowOperationalHoursSpecialInstructions:
    'facility_locator_show_operational_hours_special_instructions',
  findFormsEnhancementFlagOne: 'find_forms_first_flag',
  findFormsEnhancementFlagTwo: 'find_forms_second_flag',
  findFormsEnhancementFlagThree: 'find_forms_third_flag',
  fileUploadShortWorkflowEnabled: 'file_upload_short_workflow_enabled',
  form10182Nod: 'form10182_nod',
  gibctEybBottomSheet: 'gibctEybBottomSheet',
  gibctSchoolRatings: 'gibctSchoolRatings',
  hlrv2: 'hlr_v2',
  languageSupport: 'language_support',
  manageDependents: 'dependents_management',
  megaMenuMobileV2: 'mega_menu_mobile_v2',
  preEntryCovid19Screener: 'preEntryCovid19Screener',
  profileNotificationSettings: 'profile_notification_settings',
  requestLockedPdfPassword: 'request_locked_pdf_password',
  searchRepresentative: 'search_representative',
  searchTypeaheadEnabled: 'search_typeahead_enabled',
  show526Wizard: 'show526Wizard',
  showEduBenefits0994Wizard: 'show_edu_benefits_0994_wizard',
  showEduBenefits1990EWizard: 'show_edu_benefits_1990e_wizard',
  showEduBenefits1990NWizard: 'show_edu_benefits_1990n_wizard',
  showEduBenefits1990Wizard: 'show_edu_benefits_1990_wizard',
  showEduBenefits1995Wizard: 'show_edu_benefits_1995_wizard',
  showEduBenefits5490Wizard: 'show_edu_benefits_5490_wizard',
  showEduBenefits5495Wizard: 'show_edu_benefits_5495_wizard',
  showFinancialStatusReport: 'showFinancialStatusReport',
  showFinancialStatusReportWizard: 'showFinancialStatusReportWizard',
  showMedicalCopays: 'show_medical_copays',
  showHealthcareExperienceQuestionnaire:
    'showHealthcareExperienceQuestionnaire',
  showNewGetMedicalRecordsPage: 'show_new_get_medical_records_page',
  showNewRefillTrackPrescriptionsPage:
    'show_new_refill_track_prescriptions_page',
  showNewScheduleViewAppointmentsPage:
    'show_new_schedule_view_appointments_page',
  showNewSecureMessagingPage: 'show_new_secure_messaging_page',
  showNewViewTestLabResultsPage: 'show_new_view_test_lab_results_page',
  ssoe: 'ssoe',
  ssoeEbenefitsLinks: 'ssoeEbenefitsLinks',
  ssoeInbound: 'ssoeInbound',
  stemAutomatedDecision: 'stem_automated_decision',
  stemSCOEmail: 'stem_sco_email',
  subform89404192: 'subform_8940_4192',
  useLighthouseFormsSearchLogic: 'new_va_forms_search',
  vaGlobalDowntimeNotification: 'vaGlobalDowntimeNotification',
  vaOnlineFacilitySelectionV22: 'vaOnlineFacilitySelectionV22',
  vaOnlineScheduling: 'vaOnlineScheduling',
  vaOnlineSchedulingCancel: 'vaOnlineSchedulingCancel',
  vaOnlineSchedulingCheetah: 'vaOnlineSchedulingCheetah',
  vaOnlineSchedulingCommunityCare: 'vaOnlineSchedulingCommunityCare',
  vaOnlineSchedulingDirect: 'vaOnlineSchedulingDirect',
  vaOnlineSchedulingHomepageRefresh: 'vaOnlineSchedulingHomepageRefresh',
  vaOnlineSchedulingProviderSelection: 'vaOnlineSchedulingProviderSelection',
  vaOnlineSchedulingRequests: 'vaOnlineSchedulingRequests',
  vaOnlineSchedulingUnenrolledVaccine: 'vaOnlineSchedulingUnenrolledVaccine',
  vaOnlineSchedulingVAOSServiceCCAppointments:
    'vaOnlineSchedulingVAOSServiceCCAppointments',
  vaOnlineSchedulingVAOSServiceRequests:
    'vaOnlineSchedulingVAOSServiceRequests',
  vaOnlineSchedulingVAOSServiceVAAppointments:
    'vaOnlineSchedulingVAOSServiceVAAppointments',
  vaOnlineSchedulingFacilitiesServiceV2:
    'vaOnlineSchedulingFacilitiesServiceV2',
  vaOnlineSchedulingVariantTesting: 'vaOnlineSchedulingVariantTesting',
  vaOnlineSchedulingCCIterations: 'vaOnlineSchedulingCCIterations',
  vaViewDependentsAccess: 'vaViewDependentsAccess',
  yellowRibbonEnhancements: 'yellow_ribbon_mvp_enhancement',
});
