export default Object.freeze({
  preEntryCovid19Screener: 'preEntryCovid19Screener',
  dashboardShowDashboard2: 'dashboard_show_dashboard_2',
  directDepositEducation: 'ch33_dd_profile',
  facilityLocatorShowCommunityCares: 'facilityLocatorShowCommunityCares', // Facilities team has deprecated this flag for the frontEnd logic, there is still backend support though.
  facilitiesPpmsSuppressPharmacies: 'facilitiesPpmsSuppressPharmacies',
  facilitiesPpmsSuppressCommunityCare: 'facilitiesPpmsSuppressCommunityCare',
  facilityLocatorPredictiveLocationSearch:
    'facilityLocatorPredictiveLocationSearch',
  facilityLocatorLighthouseCovidVaccineQuery:
    'facilityLocatorLighthouseCovidVaccineQuery',
  facilityLocatorShowOperationalHoursSpecialInstructions:
    'facilityLocatorShowOperationalHoursSpecialInstructions',
  vaOnlineScheduling: 'vaOnlineScheduling',
  vaOnlineSchedulingCancel: 'vaOnlineSchedulingCancel',
  vaOnlineSchedulingRequests: 'vaOnlineSchedulingRequests',
  vaOnlineSchedulingCommunityCare: 'vaOnlineSchedulingCommunityCare',
  vaOnlineSchedulingDirect: 'vaOnlineSchedulingDirect',
  vaOnlineSchedulingVSPAppointmentList: 'vaOnlineSchedulingVspAppointmentList',
  vaOnlineSchedulingVSPAppointmentNew: 'vaOnlineSchedulingVspAppointmentNew',
  vaOnlineSchedulingCCSPAppointmentList:
    'vaOnlineSchedulingCcspAppointmentList',
  vaOnlineSchedulingCCSPRequestNew: 'vaOnlineSchedulingCcspRequestNew',
  vaOnlineSchedulingVSPRequestList: 'vaOnlineSchedulingVspRequestList',
  vaOnlineSchedulingVSPRequestNew: 'vaOnlineSchedulingVspRequestNew',
  vaOnlineSchedulingExpressCareNew: 'vaOnlineSchedulingExpressCareNew',
  vaOnlineSchedulingProviderSelection: 'vaOnlineSchedulingProviderSelection',
  vaOnlineSchedulingCheetah: 'vaOnlineSchedulingCheetah',
  vaGlobalDowntimeNotification: 'vaGlobalDowntimeNotification',
  vaOnlineSchedulingHomepageRefresh: 'vaOnlineSchedulingHomepageRefresh',
  vaOnlineFacilitySelectionV22: 'vaOnlineFacilitySelectionV22',
  ssoe: 'ssoe',
  ssoeInbound: 'ssoeInbound',
  ssoeEbenefitsLinks: 'ssoeEbenefitsLinks',
  form526OriginalClaims: 'form526OriginalClaims',
  vaViewDependentsAccess: 'vaViewDependentsAccess',
  gibctEybBottomSheet: 'gibctEybBottomSheet',
  gibctSchoolRatings: 'gibctSchoolRatings',
  form996HigherLevelReview: 'form996HigherLevelReview',
  debtLettersShowLetters: 'debtLettersShowLetters',
  form526BDD: 'form526BenefitsDeliveryAtDischarge',
  showEduBenefits1995Wizard: 'show_edu_benefits_1995_wizard',
  showEduBenefits5495Wizard: 'show_edu_benefits_5495_wizard',
  showEduBenefits0994Wizard: 'show_edu_benefits_0994_wizard',
  showEduBenefits1990NWizard: 'show_edu_benefits_1990n_wizard',
  showEduBenefits5490Wizard: 'show_edu_benefits_5490_wizard',
  showEduBenefits1990EWizard: 'show_edu_benefits_1990e_wizard',
  showEduBenefits1990Wizard: 'show_edu_benefits_1990_wizard',
  stemAutomatedDecision: 'stem_automated_decision',
  stemSCOEmail: 'stem_sco_email',
  showHealthcareExperienceQuestionnaire:
    'showHealthcareExperienceQuestionnaire',
  showNewGetMedicalRecordsPage: 'show_new_get_medical_records_page',
  showNewRefillTrackPrescriptionsPage:
    'show_new_refill_track_prescriptions_page',
  showNewScheduleViewAppointmentsPage:
    'show_new_schedule_view_appointments_page',
  showNewSecureMessagingPage: 'show_new_secure_messaging_page',
  showNewViewTestLabResultsPage: 'show_new_view_test_lab_results_page',
  cernerOverride463: 'cerner_override_463',
  cernerOverride531: 'cerner_override_531',
  cernerOverride648: 'cerner_override_648',
  cernerOverride653: 'cerner_override_653',
  cernerOverride663: 'cerner_override_663',
  cernerOverride668: 'cerner_override_668',
  cernerOverride687: 'cerner_override_687',
  cernerOverride692: 'cerner_override_692',
  cernerOverride757: 'cerner_override_757',
  show526Wizard: 'show526Wizard',
  showChapter36: 'show_chapter_36',
  showChapter31: 'show_chapter_31',
  requestLockedPdfPassword: 'request_locked_pdf_password',
  form526ConfirmationEmail: 'form526_confirmation_email',
  form526ConfirmationEmailShowCopy: 'form526_confirmation_email_show_copy',
  searchTypeaheadEnabled: 'search_typeahead_enabled',
  covidVaccineUpdatesCTA: 'covid_vaccine_registration_frontend_cta',
  covidVaccineUpdatesForm: 'covid_vaccine_registration_frontend',
  covidVaccineUpdatesDisableAuth:
    'covid_vaccine_registration_frontend_hide_auth',
  covidVaccineUpdatesEnableExpandedEligibility:
    'covid_vaccine_registration_frontend_enable_expanded_eligibility',
  showFindFormsResultsLinkToFormDetailPages: 'find_forms_mvp_enhancement',
  yellowRibbonEnhancements: 'yellow_ribbon_mvp_enhancement',
  evssUploadLimit150Mb: 'evss_upload_limit_150mb',
  searchRepresentative: 'search_representative',
  eduFormOmbAndExpiration: 'edu_form_omb_and_expiration',
  manageDependents: 'dependents_management',
  subform89404192: 'subform_8940_4192',
  dependencyVerification: 'dependency_verification',
  form10182Nod: 'form10182_nod',
  canUpload1010cgPOA: 'can_upload_10_10cg_poa',
});
