// prettier-ignore

export default Object.freeze({
  canUpload1010cgPOA: 'can_upload_10_10cg_poa',
  cernerOverride463: 'cerner_override_463',
  cernerOverride531: 'cerner_override_531',
  cernerOverride648: 'cerner_override_648',
  cernerOverride653: 'cerner_override_653',
  cernerOverride663: 'cerner_override_663',
  cernerOverride668: 'cerner_override_668',
  cernerOverride687: 'cerner_override_687',
  cernerOverride692: 'cerner_override_692',
  cernerOverride757: 'cerner_override_757',
  checkInExperienceEnabled: 'check_in_experience_enabled',
  checkInExperienceEmergencyContactEnabled:'check_in_experience_emergency_contact_enabled',
  checkInExperiencePreCheckInEnabled:
    'check_in_experience_pre_check_in_enabled',
  checkInExperienceUpdateInformationPageEnabled:
    'check_in_experience_update_information_page_enabled',
  coeAccess: 'coe_access',
  covidVaccineSchedulingFrontend: 'covid_vaccine_scheduling_frontend',
  covidVaccineUpdatesCTA: 'covid_vaccine_registration_frontend_cta',
  covidVaccineUpdatesDisableAuth:
    'covid_vaccine_registration_frontend_hide_auth',
  covidVaccineUpdatesEnableExpandedEligibility:
    'covid_vaccine_registration_frontend_enable_expanded_eligibility',
  covidVaccineUpdatesForm: 'covid_vaccine_registration_frontend',
  debtLettersShowLetters: 'debt_letters_show_letters',
  dependencyVerification: 'dependency_verification',
  dischargeWizardFeatures: 'discharge_wizard_features',
  evssUploadLimit150Mb: 'evss_upload_limit_150mb',
  facilitiesPpmsSuppressAll: 'facilities_ppms_suppress_all',
  facilitiesPpmsSuppressCommunityCare:
    'facilities_ppms_suppress_community_care',
  facilitiesPpmsSuppressPharmacies: 'facilities_ppms_suppress_pharmacies',
  facilityLocatorLatLongOnly: 'facility_locator_lat_long_only',
  facilityLocatorLighthouseCovidVaccineQuery:
    'facility_locator_lighthouse_covid_vaccine_query',
  facilityLocatorShowHealthConnectNumber: 'facility_locator_show_health_connect_number',
  facilityLocatorPredictiveLocationSearch:
    'facility_locator_predictive_location_search',
  facilityLocatorRailsEngine: 'facility_locator_rails_engine',
  facilityLocatorRestoreCommunityCarePagination:
    'facility_locator_restore_community_care_pagination',
  facilityLocatorShowCommunityCares: 'facility_locator_show_community_cares', // Facilities team has deprecated this flag for the frontEnd logic, there is still backend support though.
  facilityLocatorShowOperationalHoursSpecialInstructions:
    'facility_locator_show_operational_hours_special_instructions',
  findFormsEnhancementFlagOne: 'find_forms_first_flag',
  findFormsEnhancementFlagTwo: 'find_forms_second_flag',
  findFormsEnhancementFlagThree: 'find_forms_third_flag',
  fileUploadShortWorkflowEnabled: 'file_upload_short_workflow_enabled',
  form10182Nod: 'form10182_nod',
  gibctEybBottomSheet: 'gibct_eyb_bottom_sheet',
  gibctSchoolRatings: 'gibct_school_ratings',
  giSandboxComparisonToolToggle: 'gi_sandbox_comparision_tool_toggle',
  hlrv2: 'hlr_v2',
  loginGov: 'login_gov',
  loginGovCreateAccount: 'login_gov_create_account',
  loginGovMHV: 'login_gov_mhv',
  loginGovMyVAHealth: 'login_gov_myvahealth',
  loopPages: 'loop_pages',
  manageDependents: 'dependents_management',
  megaMenuMobileV2: 'mega_menu_mobile_v2',
  omniChannelLink: 'omni_channel_link',
  preEntryCovid19Screener: 'pre_entry_covid19_screener',
  profileNotificationSettings: 'profile_notification_settings',
  profileEnhancements: 'profile_enhancements',
  requestLockedPdfPassword: 'request_locked_pdf_password',
  searchRepresentative: 'search_representative',
  searchTypeaheadEnabled: 'search_typeahead_enabled',
  searchDropdownComponentEnabled: 'search_dropdown_component_enabled',
  show526Wizard: 'show526_wizard',
  showEduBenefits0994Wizard: 'show_edu_benefits_0994_wizard',
  showEduBenefits1990EWizard: 'show_edu_benefits_1990e_wizard',
  showEduBenefits1990NWizard: 'show_edu_benefits_1990n_wizard',
  showEduBenefits1990Wizard: 'show_edu_benefits_1990_wizard',
  showEduBenefits1995Wizard: 'show_edu_benefits_1995_wizard',
  showEduBenefits5490Wizard: 'show_edu_benefits_5490_wizard',
  showEduBenefits5495Wizard: 'show_edu_benefits_5495_wizard',
  showFinancialStatusReport: 'show_financial_status_report',
  showFinancialStatusReportWizard: 'show_financial_status_report_wizard',
  showFormI18n: 'show_form_i18n',
  showEventsV2: 'show_events_v2',
  showHeaderV2: 'show_header_v2',
  showMebMockEndpoints: 'show_meb_mock_endpoints',
  showMedicalCopays: 'show_medical_copays',
  showHealthcareExperienceQuestionnaire:
    'show_healthcare_experience_questionnaire',
  showNewGetMedicalRecordsPage: 'show_new_get_medical_records_page',
  showNewRefillTrackPrescriptionsPage:
    'show_new_refill_track_prescriptions_page',
  showNewScheduleViewAppointmentsPage:
    'show_new_schedule_view_appointments_page',
  showNewSecureMessagingPage: 'show_new_secure_messaging_page',
  showNewViewTestLabResultsPage: 'show_new_view_test_lab_results_page',
  ssoe: 'ssoe',
  ssoeEbenefitsLinks: 'ssoe_ebenefits_links',
  ssoeInbound: 'ssoe_inbound',
  stemAutomatedDecision: 'stem_automated_decision',
  stemSCOEmail: 'stem_sco_email',
  subform89404192: 'subform_8940_4192',
  useLighthouseFormsSearchLogic: 'new_va_forms_search',
  vaGlobalDowntimeNotification: 'va_global_downtime_notification',
  vaOnlineFacilitySelectionV22: 'va_online_scheduling_facility_selection_v2_2',
  vaOnlineScheduling: 'va_online_scheduling',
  vaOnlineSchedulingCancel: 'va_online_scheduling_cancel',
  vaOnlineSchedulingCheetah: 'va_online_scheduling_cheetah',
  vaOnlineSchedulingCommunityCare: 'va_online_scheduling_community_care',
  vaOnlineSchedulingDirect: 'va_online_scheduling_direct',
  vaOnlineSchedulingHomepageRefresh: 'va_online_scheduling_homepage_refresh',
  vaOnlineSchedulingProviderSelection:
    'va_online_scheduling_provider_selection',
  vaOnlineSchedulingRequests: 'va_online_scheduling_requests',
  vaOnlineSchedulingUnenrolledVaccine:
    'va_online_scheduling_unenrolled_vaccine',
  vaOnlineSchedulingVAOSServiceCCAppointments:
    'va_online_scheduling_vaos_service_cc_appointments',
  vaOnlineSchedulingVAOSServiceRequests:
    'va_online_scheduling_vaos_service_requests',
  vaOnlineSchedulingVAOSServiceVAAppointments:
    'va_online_scheduling_vaos_service_va_appointments',
  vaOnlineSchedulingFacilitiesServiceV2:
    'va_online_scheduling_facilities_service_v2',
  vaOnlineSchedulingVariantTesting: 'va_online_scheduling_variant_testing',
  vaOnlineSchedulingCCIterations: 'va_online_scheduling_cc_iterations',
  vaOnlineSchedulingPocHealthApt: 'va_online_scheduling_poc_health_apt',
  vaViewDependentsAccess: 'va_view_dependents_access',
  yellowRibbonEnhancements: 'yellow_ribbon_mvp_enhancement',
  showEduBenefits1990EZWizard: 'show_edu_benefits_1990EZ_Wizard',
  caregiverSIGIEnabled: 'caregiver_sigi_enabled',
  hcaAmericanIndianEnabled: 'hca_american_indian_enabled',
});
