export const topics = [
  'Burial',
  'Personalized Career Planning and Guidance (Chapter 36)',
  'Compensation',
  'Dental',
  'Discharge upgrade',
  'Education',
  'Finance',
  'Health care',
  'Insurance',
  'Legal',
  'Loan Gauranty',
  'Mental health support/resources',
  'Pension',
  'VA records',
  'Veteran Readiness and Employment (Chapter 31)',
  'Women Veterans Coordinator',
  'General VA benefits',
];
