export const topics = [
  'Burial',
  'Chapter 36-PCPG',
  'Compensation',
  'Dental',
  'Discharge-Upgrade',
  'Education',
  'Finance',
  'Health care',
  'Insurance',
  'Legal',
  'Loan Gauranty',
  'Mental Health Support/Resources',
  'Pension',
  'VA Records',
  'Veterans Readiness and Employment',
  'Woman Veterans Coordinator',
  'General VA Benefits',
];
