/* eslint-disable no-console */

/**
 * Publishes and tags pacts generated by the Pact tests.
 * Only meant to run in CI.
 */

const { execSync } = require('child_process');
const path = require('path');

const PactBrokerClient = require('../src/platform/testing/contract/client');

const pactBrokerClient = new PactBrokerClient({
  url: process.env.PACT_BROKER_BASE_URL,
  username: process.env.PACT_BROKER_BASIC_AUTH_USERNAME,
  password: process.env.PACT_BROKER_BASIC_AUTH_PASSWORD,
});

const commitHash = execSync('git rev-parse --verify HEAD')
  .toString()
  .trim();

// const branchName = execSync('git rev-parse --abbrev-ref HEAD')
//   .toString()
//   .trim();

const pactsFolder = path.resolve(__dirname, '../pacts');

pactBrokerClient
  .publishAndTagPacts({
    pactDir: pactsFolder,
    version: commitHash,
    tag: 'master',
  })
  .catch(e => {
    console.error(e);
    process.exit(1);
  });
