/* eslint-disable no-console */

/**
 * Publishes and tags pacts generated by the Pact tests.
 *
 * Only meant to run in CI.
 */

const path = require('path');

const PactBrokerClient = require('../src/platform/testing/contract/client');

const pactBrokerClient = new PactBrokerClient({
  url: process.env.PACT_BROKER_BASE_URL,
  username: process.env.PACT_BROKER_BASIC_AUTH_USERNAME,
  password: process.env.PACT_BROKER_BASIC_AUTH_PASSWORD,
});

const pactsFolder = path.resolve(__dirname, '../pacts');
const commitHash = "test";
const branchName = "master";

pactBrokerClient
  .publishAndTagPacts({
    pactDir: pactsFolder,
    version: commitHash,
    tag: branchName,
  })
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
