export const ROUTES = Object.freeze({
  INTRO: 'introduction',
  CLAIMANT_TYPE: 'claimant-type',
  REPRESENTATIVE_SELECT: 'representative-select',
  REPRESENTATIVE_CONTACT: 'representative-contact',
  REPRESENTATIVE_ORGANIZATION: 'representative-organization',
  REPRESENTATIVE_SUBMISSION_METHOD: 'representative-submission-method',
  CLAIMANT_RELATIONSHIP: 'claimant-relationship',
  CLAIMANT_PERSONAL_INFORMATION: 'claimant-personal-information',
  CLAIMANT_CONTACT_MAILING: 'claimant-contact-mailing',
  CLAIMANT_CONTACT_PHONE_EMAIL: 'claimant-contact-phone-email',
  VETERAN_PERSONAL_INFORMATION: 'veteran-personal-information',
  VETERAN_CONTACT_MAILING: 'veteran-contact-mailing',
  VETERAN_CONTACT_PHONE_EMAIL: 'veteran-contact-phone-email',
  VETERAN_IDENTIFICATION: 'veteran-identification',
  VETERAN_SERVICE_INFORMATION: 'veteran-service-information',
  AUTHORIZE_MEDICAL: 'authorize-medical',
  AUTHORIZE_MEDICAL_SELECT: 'authorize-medical/select',
  AUTHORIZE_ADDRESS: 'authorize-address',
  AUTHORIZE_INSIDE_VA: 'authorize-inside-va',
  AUTHORIZE_OUTSIDE_VA: 'authorize-outside-va',
  AUTHORIZE_OUTSIDE_VA_NAMES: 'authorize-outside-va/names',
  REVIEW_AND_SUBMIT: 'review-and-submit',
  CONFIRMATION: 'confirmation',
  NEXT_STEPS: 'next-steps',
});
