export default {
  BURIALS_APP_STATUS: 'burials-app-status',
  CHAPTER_31_WIZARD: 'chapter-31-Wizard',
  CHAPTER_36_CTA: 'chapter-36-cta',
  CHAPTER_31_CTA: 'chapter-31-cta',
  CORONAVIRUS_CHATBOT: 'va-coronavirus-chatbot',
  COVID_VACCINE_UPDATES_CTA: 'va-covid-vaccine-updates-cta',
  CTA: 'cta',
  DIRECT_DEPOSIT: 'direct-deposit',
  DISABILITY_APP_STATUS: 'disability-app-status',
  DISABILITY_RATING_CALCULATOR: 'disability-rating-calculator',
  EDUCATION_APP_STATUS: 'education-app-status',
  FIND_VA_FORMS: 'find-va-forms',
  FIND_VA_FORMS_INVALID_PDF_ALERT: 'find-va-forms-invalid-pdf-alert',
  FORM_686_CTA: 'form-686-CTA',
  HEALTH_CARE_APP_STATUS: 'health-care-app-status',
  HIGHER_LEVEL_REVIEW_APP_STATUS: 'higher-level-review-status',
  HOMEPAGE_BANNER: 'homepage-banner',
  OPT_OUT_APP_STATUS: 'opt-out-app-status',
  PENSION_APP_STATUS: 'pension-app-status',
  POST_911_GI_BILL_STATUS_WIDGET: 'post-9-11-gi-bill-status',
  RESOURCES_AND_SUPPORT_SEARCH: 'resources-and-support-search',
  THIRD_PARTY_APP_DIRECTORY: 'third-party-app-directory',
  VIEW_DEPENDENTS_CTA: 'view-dependents-CTA',
  // Health Care | Manage Benefits widgets.
  GET_MEDICAL_RECORDS_PAGE: 'get-medical-records-page',
  REFILL_TRACK_PRESCRIPTIONS_PAGE: 'refill-track-prescriptions-page',
  SCHEDULE_VIEW_VA_APPOINTMENTS_PAGE: 'schedule-view-va-appointments-page',
  SECURE_MESSAGING_PAGE: 'secure-messaging-page',
  VIEW_TEST_AND_LAB_RESULTS_PAGE: 'view-test-and-lab-results-page',
  VIEW_PAYMENT_HISTORY: 'view-payment-history',
  I_18_SELECT: 'i18-select',
  DEPENDENCY_VERIFICATION: 'dependency-verification',
};
