export default {
  BANNER: 'banner',
  BASIC_FACILITY_LOCATIONS_LIST: 'basic-facility-locations-list',
  BURIALS_APP_STATUS: 'burials-app-status',
  CHAPTER_31_CTA: 'chapter-31-cta',
  CHAPTER_31_WIZARD: 'chapter-31-Wizard',
  CHAPTER_36_CTA: 'chapter-36-cta',
  CORONAVIRUS_CHATBOT: 'va-coronavirus-chatbot',
  COVID_VACCINE_UPDATES_CTA: 'va-covid-vaccine-updates-cta',
  CTA: 'cta',
  DISABILITY_APP_STATUS: 'disability-app-status',
  DISABILITY_RATING_CALCULATOR: 'disability-rating-calculator',
  EDUCATION_APP_STATUS: 'education-app-status',
  FACILITY_APPOINTMENT_WAIT_TIMES_WIDGET:
    'facility-appointment-wait-times-widget',
  FACILITY_DETAIL: 'facility-detail',
  FACILITY_LOCATIONS_LIST: 'facility-locations-list',
  FACILITY_MAP: 'facility-map',
  FACILITY_PATIENT_SATISFACTION_SCORES: 'facility-patient-satisfaction-scores',
  FIND_VA_FORMS: 'find-va-forms',
  FIND_VA_FORMS_INVALID_PDF_ALERT: 'find-va-forms-invalid-pdf-alert',
  FORM_686_CTA: 'form-686-CTA',
  HEALTH_CARE_APP_STATUS: 'health-care-app-status',
  HIGHER_LEVEL_REVIEW_APP_STATUS: 'higher-level-review-status',
  HOMEPAGE_BANNER: 'homepage-banner',
  MAINTENANCE_BANNER: 'maintenance-banner',
  MANAGE_VA_DEBT_CTA: 'manage-va-debt-cta',
  OPT_OUT_APP_STATUS: 'opt-out-app-status',
  OTHER_FACILITY_LOCATIONS_LIST: 'other-facility-locations-list',
  PENSION_APP_STATUS: 'pension-app-status',
  POST_911_GI_BILL_STATUS_WIDGET: 'post-9-11-gi-bill-status',
  RESOURCES_AND_SUPPORT_SEARCH: 'resources-and-support-search',
  SCO_ANNOUNCEMENTS: 'sco-announcements',
  SCO_EVENTS: 'sco-events',
  SIDE_NAV: 'side-nav',
  THIRD_PARTY_APP_DIRECTORY: 'third-party-app-directory',
  VET_CENTER_HOURS: 'vet-center-hours',
  VET_CENTER_NEARBY: 'vet-center-nearby',
  VIEW_DEPENDENTS_CTA: 'view-dependents-CTA',
  // Health Care | Manage Benefits widgets.
  COE_ACCESS: 'coe_access',
  DEPENDENCY_VERIFICATION: 'dependency-verification',
  GET_MEDICAL_RECORDS_PAGE: 'get-medical-records-page',
  I_18_SELECT: 'i18-select',
  REFILL_TRACK_PRESCRIPTIONS_PAGE: 'refill-track-prescriptions-page',
  SCHEDULE_VIEW_VA_APPOINTMENTS_PAGE: 'schedule-view-va-appointments-page',
  SECURE_MESSAGING_PAGE: 'secure-messaging-page',
  VIEW_PAYMENT_HISTORY: 'view-payment-history',
  VIEW_TEST_AND_LAB_RESULTS_PAGE: 'view-test-and-lab-results-page',
};
