export default {
  CTA: 'cta',
  EDUCATION_APP_STATUS: 'education-app-status',
  HEALTH_CARE_APP_STATUS: 'health-care-app-status',
  PENSION_APP_STATUS: 'pension-app-status',
  BURIALS_APP_STATUS: 'burials-app-status',
  OPT_OUT_APP_STATUS: 'opt-out-app-status',
  DISABILITY_APP_STATUS: 'disability-app-status',
  DISABILITY_RATING_CALCULATOR: 'disability-rating-calculator',
  FIND_VA_FORMS: 'find-va-forms',
  HIGHER_LEVEL_REVIEW_APP_STATUS: 'higher-level-review-status',
  HOMEPAGE_BANNER: 'homepage-banner',
  POST_911_GI_BILL_STATUS_WIDGET: 'post-9-11-gi-bill-status',
  CORONAVIRUS_CHATBOT: 'va-coronavirus-chatbot',
  VIEW_DEPENDENTS_CTA: 'view-dependents-CTA',
  FORM_686_CONTENT_REVEAL: '686UnauthContentBlock',
  CAREGIVER_CONTENT_TOGGLE: 'caregiver-content-toggle',
  // Health Care | Manage Benefits widgets.
  GET_MEDICAL_RECORDS_PAGE: 'get-medical-records-page',
  REFILL_TRACK_PRESCRIPTIONS_PAGE: 'refill-track-prescriptions-page',
  SCHEDULE_VIEW_VA_APPOINTMENTS_PAGE: 'schedule-view-va-appointments-page',
  SECURE_MESSAGING_PAGE: 'secure-messaging-page',
  VIEW_TEST_AND_LAB_RESULTS_PAGE: 'view-test-and-lab-results-page',
};
