// export const institutionRatingsMockData =
// [
//     {
//         "id": 1,
//         "q1_avg": "4.0",
//         "q1_count":20,
//         "q2_avg": "1.5",
//         "q2_count":20,
//         "q3_avg": "2.2",
//         "q3_count":20,
//         "q4_avg": "2.1",
//         "q4_count":20,
//         "q5_avg": "2.6",
//         "q5_count":20,
//         "q6": false,
//         "q7_avg": "2.8",
//         "q7_count":12,
//         "q8_avg": "2.6",
//         "q8_count":20,
//         "q9_avg": "3.4",
//         "q9_count":16,
//         "q10_avg": "3.3",
//         "q10_count":20,
//         "q11_avg": "3.0",
//         "q11_count":18,
//         "q12_avg": "2.7",
//         "q12_count":20,
//         "q13_avg": "2.5",
//         "q13_count":20,
//         "q14_avg": "2.5",
//         "q14_count":20,
//         "q15_avg": null,
//         "q15_count":null,
//         "q16_avg": null,
//         "q16_count":null,
//         "q17_avg": null,
//         "q17_count":null,
//         "q18_avg": null,
//         "q18_count":null,
//         "q19_avg": null,
//         "q19_count":null,
//         "q20_avg": null,
//         "q20_count":null,
//         "m1_avg":"2.5",
//         "m2_avg":"3.0",
//         "m3_avg":"3.2",
//         "m4_avg":"2.6",
//         "overall_avg":"2.8",
//         "institution_rating_count":20
//     }
// ]
