/**
 * Initializes error reporting to Sentry when running at a higher enviroment than localhost
 */

import * as Sentry from '@sentry/browser';

import environment from '../utilities/environment';

// url check is necessary for e2e tests and local environments
const isLocalhost      = environment.BASE_URL.includes('localhost')
const isReviewInstance = environment.BASE_URL.includes('.review.');

if (!(isLocalhost || isReviewInstance)) {
  const url = `${environment.BASE_URL}/js-report/0`.replace('//', '//faker@');
  Sentry.init({
    dsn: url,
    environment: environment.vspEnvironment(),
    ignoreErrors: [
      // Error generated by a bug in auto-fill library from safari
      // https://github.com/getsentry/sentry/issues/5267
      /Blocked a frame with origin/,
    ],
  });
  Sentry.setTag('source', 'unknown');
  Sentry.configureScope(scope => {
    scope.setLevel('error');
  });
}
