/* eslint camelcase: 0 */
/* eslint quote-props: 0 */
/* eslint quotes: 0 */

const mock = require('../../../platform/testing/e2e/mock-helpers');

const schools = {
  data: [
    {
      id: '8887595',
      type: 'institutions',
      attributes: {
        name: 'CENTRAL TEXAS COLLEGE-WASHINGTON DC',
        facility_code: '14000109',
        type: 'PUBLIC',
        city: 'WASHINGTON',
        state: 'DC',
        zip: '20032',
        country: 'USA',
        highest_degree: 2,
        locale_type: 'suburban',
        student_count: 7,
        caution_flag: null,
        caution_flag_reason: null,
        caution_flags: [],
        created_at: '2020-04-07T16:57:37.000Z',
        updated_at: '2020-04-07T16:57:37.000Z',
        address_1: 'PO BOX 8558',
        address_2: null,
        address_3: '112 Brookley Avenue',
        physical_city: 'WASHINGTON',
        physical_state: 'DC',
        physical_country: 'USA',
        online_only: false,
        distance_learning: false,
        dod_bah: 2535,
        physical_zip: '20032',
        bah: 2624,
        tuition_in_state: 2790,
        tuition_out_of_state: 6270,
        books: 1707,
        student_veteran: null,
        yr: false,
        poe: true,
        eight_keys: true,
        stem_offered: false,
        independent_study: false,
        priority_enrollment: false,
        school_closing: false,
        school_closing_on: null,
        closure109: null,
        vet_tec_provider: false,
        parent_facility_code_id: null,
        campus_type: 'Y',
        preferred_provider: false,
        count_of_caution_flags: 0,
      },
      links: {
        website: 'http://www.ctcd.edu',
        scorecard:
          'https://collegescorecard.ed.gov/school/?223816-central-texas-college-washington-dc',
        self: 'https://staging-api.va.gov/gids/v0/institutions/14000109',
      },
    },
  ],
  links: {
    self:
      'https://staging-api.va.gov/gids/v0/institutions?category=school&name=washington+dc',
    first:
      'https://staging-api.va.gov/gids/v0/institutions?category=school&name=washington+dc&page=1&per_page=10',
    prev: null,
    next: null,
    last:
      'https://staging-api.va.gov/gids/v0/institutions?category=school&name=washington+dc&page=1&per_page=10',
  },
  meta: {
    version: {
      number: 132,
      created_at: '2020-04-07T16:57:37.600Z',
      preview: false,
    },
    count: 3,
    facets: {
      category: {
        school: 3,
        employer: 0,
      },
      type: {
        'for profit': 1,
        private: 1,
        public: 1,
      },
      state: {
        dc: 3,
      },
      country: [
        {
          name: 'USA',
          count: 3,
        },
      ],
      student_vet_group: {
        true: null,
        false: null,
      },
      yellow_ribbon_scholarship: {
        true: null,
        false: null,
      },
      principles_of_excellence: {
        true: null,
        false: null,
      },
      eight_keys_to_veteran_success: {
        true: null,
        false: null,
      },
      stem_offered: {
        true: null,
        false: null,
      },
      independent_study: {
        true: null,
        false: null,
      },
      online_only: {
        true: null,
        false: null,
      },
      distance_learning: {
        true: null,
        false: null,
      },
      priority_enrollment: {
        true: null,
        false: null,
      },
    },
  },
};

const singleSchool = {
  data: {
    id: '1290',
    type: 'institutions',
    attributes: {
      name: 'CENTRAL TEXAS COLLEGE-WASHINGTON DC',
      facility_code: '14000109',
      type: 'PUBLIC',
      city: 'WASHINGTON',
      state: 'DC',
      zip: '20032',
      country: 'USA',
      bah: 2624,
      cross: '223816',
      flight: false,
      correspondence: false,
      ope: '00400303',
      ope6: '04003',
      school_system_name: null,
      school_system_code: -2,
      alias: null,
      highest_degree: 2,
      locale_type: 'suburban',
      address_1: 'PO BOX 8558',
      address_2: null,
      address_3: '112 Brookley Avenue',
      student_count: 7,
      undergrad_enrollment: 10200,
      yr: false,
      student_veteran: null,
      student_veteran_link: null,
      poe: true,
      eight_keys: true,
      stem_offered: false,
      dodmou: true,
      sec_702: true,
      vet_success_name: null,
      vet_success_email: null,
      credit_for_mil_training: true,
      vet_poc: true,
      student_vet_grp_ipeds: true,
      soc_member: true,
      retention_rate_veteran_ba: null,
      retention_all_students_ba: null,
      retention_rate_veteran_otb: 0.622,
      retention_all_students_otb: 0.4705,
      persistance_rate_veteran_ba: null,
      persistance_rate_veteran_otb: 0.824,
      graduation_rate_veteran: 0,
      graduation_rate_all_students: 0.1452,
      transfer_out_rate_veteran: 0.613,
      transfer_out_rate_all_students: null,
      salary_all_students: 31000,
      repayment_rate_all_students: 0.3217274858,
      avg_stu_loan_debt: 6500,
      calendar: 'semesters',
      tuition_in_state: 2790,
      tuition_out_of_state: 6270,
      books: 1707,
      online_all: true,
      p911_tuition_fees: 12006,
      p911_recipients: 10,
      p911_yellow_ribbon: null,
      p911_yr_recipients: null,
      accredited: true,
      accreditation_type: null,
      accreditation_status: null,
      caution_flag: null,
      caution_flag_reason: null,
      caution_flags: [],
      complaints: {
        facility_code: null,
        financial_by_fac_code: null,
        quality_by_fac_code: null,
        refund_by_fac_code: null,
        marketing_by_fac_code: null,
        accreditation_by_fac_code: null,
        degree_requirements_by_fac_code: null,
        student_loans_by_fac_code: null,
        grades_by_fac_code: null,
        credit_transfer_by_fac_code: null,
        credit_job_by_fac_code: null,
        job_by_fac_code: null,
        transcript_by_fac_code: null,
        other_by_fac_code: null,
        main_campus_roll_up: 22,
        financial_by_ope_id_do_not_sum: 13,
        quality_by_ope_id_do_not_sum: 0,
        refund_by_ope_id_do_not_sum: 3,
        marketing_by_ope_id_do_not_sum: 0,
        accreditation_by_ope_id_do_not_sum: 0,
        degree_requirements_by_ope_id_do_not_sum: 2,
        student_loans_by_ope_id_do_not_sum: 0,
        grades_by_ope_id_do_not_sum: 0,
        credit_transfer_by_ope_id_do_not_sum: 1,
        jobs_by_ope_id_do_not_sum: 0,
        transcript_by_ope_id_do_not_sum: 2,
        other_by_ope_id_do_not_sum: 10,
      },
      school_closing: false,
      school_closing_on: null,
      school_closing_message: null,
      yellow_ribbon_programs: [],
      independent_study: false,
      priority_enrollment: false,
      created_at: '2020-04-07T16:57:37.000Z',
      updated_at: '2020-04-07T16:57:37.000Z',
      physical_address_1: 'BOLLING AIR FORCE BASE',
      physical_address_2: 'Suite 108',
      physical_address_3: '112 Brookley Avenue',
      physical_city: 'WASHINGTON',
      physical_state: 'DC',
      physical_country: 'USA',
      online_only: false,
      distance_learning: false,
      dod_bah: 2535,
      physical_zip: '20032',
      parent_facility_code_id: null,
      campus_type: 'Y',
      vet_tec_provider: false,
      preferred_provider: false,
      stem_indicator: false,
      facility_map: {
        main: {
          institution: {
            id: 8887595,
            version: {
              number: 132,
              created_at: '2020-04-07T16:57:37.600Z',
              preview: false,
            },
            institution_type_name: 'PUBLIC',
            facility_code: '14000109',
            institution: 'CENTRAL TEXAS COLLEGE-WASHINGTON DC',
            city: 'WASHINGTON',
            state: 'DC',
            zip: '20032',
            country: 'USA',
            flight: false,
            correspondence: false,
            bah: 2624,
            cross: '223816',
            ope: '00400303',
            ope6: '04003',
            insturl: 'www.ctcd.edu',
            vet_tuition_policy_url:
              'www.ctcd.edu/students/military-students-veterans-spouses/',
            pred_degree_awarded: 2,
            locale: 22,
            gibill: 7,
            undergrad_enrollment: 10200,
            yr: false,
            student_veteran: null,
            student_veteran_link: null,
            poe: true,
            eight_keys: true,
            dodmou: true,
            sec_702: true,
            vetsuccess_name: null,
            vetsuccess_email: null,
            credit_for_mil_training: true,
            vet_poc: true,
            student_vet_grp_ipeds: true,
            soc_member: true,
            va_highest_degree_offered: '2-year',
            retention_rate_veteran_ba: null,
            retention_all_students_ba: null,
            retention_rate_veteran_otb: 0.622,
            retention_all_students_otb: 0.4705,
            persistance_rate_veteran_ba: null,
            persistance_rate_veteran_otb: 0.824,
            graduation_rate_veteran: 0,
            graduation_rate_all_students: 0.1452,
            transfer_out_rate_veteran: 0.613,
            transfer_out_rate_all_students: null,
            salary_all_students: 31000,
            repayment_rate_all_students: 0.3217274858,
            avg_stu_loan_debt: 6500,
            calendar: 'semesters',
            tuition_in_state: 2790,
            tuition_out_of_state: 6270,
            books: 1707,
            online_all: true,
            p911_tuition_fees: 12006,
            p911_recipients: 10,
            p911_yellow_ribbon: null,
            p911_yr_recipients: null,
            accredited: true,
            accreditation_type: null,
            accreditation_status: null,
            caution_flag: null,
            caution_flag_reason: null,
            complaints_facility_code: null,
            complaints_financial_by_fac_code: null,
            complaints_quality_by_fac_code: null,
            complaints_refund_by_fac_code: null,
            complaints_marketing_by_fac_code: null,
            complaints_accreditation_by_fac_code: null,
            complaints_degree_requirements_by_fac_code: null,
            complaints_student_loans_by_fac_code: null,
            complaints_grades_by_fac_code: null,
            complaints_credit_transfer_by_fac_code: null,
            complaints_credit_job_by_fac_code: null,
            complaints_job_by_fac_code: null,
            complaints_transcript_by_fac_code: null,
            complaints_other_by_fac_code: null,
            complaints_main_campus_roll_up: 22,
            complaints_financial_by_ope_id_do_not_sum: 13,
            complaints_quality_by_ope_id_do_not_sum: 0,
            complaints_refund_by_ope_id_do_not_sum: 3,
            complaints_marketing_by_ope_id_do_not_sum: 0,
            complaints_accreditation_by_ope_id_do_not_sum: 0,
            complaints_degree_requirements_by_ope_id_do_not_sum: 2,
            complaints_student_loans_by_ope_id_do_not_sum: 0,
            complaints_grades_by_ope_id_do_not_sum: 0,
            complaints_credit_transfer_by_ope_id_do_not_sum: 1,
            complaints_jobs_by_ope_id_do_not_sum: 0,
            complaints_transcript_by_ope_id_do_not_sum: 2,
            complaints_other_by_ope_id_do_not_sum: 10,
            created_at: '2020-04-07T16:57:37.000Z',
            updated_at: '2020-04-07T16:57:37.000Z',
            f1sysnam: null,
            f1syscod: -2,
            ialias: null,
            approval_status: null,
            school_closing: false,
            school_closing_on: null,
            school_closing_message: null,
            stem_offered: false,
            priority_enrollment: false,
            online_only: false,
            independent_study: false,
            distance_learning: false,
            address_1: 'PO BOX 8558',
            address_2: null,
            address_3: '112 Brookley Avenue',
            physical_address_1: 'BOLLING AIR FORCE BASE',
            physical_address_2: 'Suite 108',
            physical_address_3: '112 Brookley Avenue',
            physical_city: 'WASHINGTON',
            physical_state: 'DC',
            physical_zip: '20032',
            physical_country: 'USA',
            dod_bah: 2535,
            approved: true,
            vet_tec_provider: false,
            closure109: null,
            preferred_provider: false,
            stem_indicator: false,
            campus_type: 'Y',
            parent_facility_code_id: null,
            version_id: 219,
            complies_with_sec_103: null,
            solely_requires_coe: null,
            requires_coe_and_criteria: null,
            count_of_caution_flags: 0,
          },
          branches: [],
          extensions: [],
        },
      },
      programs: [],
      versioned_school_certifying_officials: [
        {
          id: 2501544,
          facility_code: '14000109',
          institution_name: 'CENTRAL TEXAS COLLEGE-WASHINGTON DC',
          priority: 'Primary',
          first_name: 'GERARD',
          last_name: 'WALSH',
          title: 'SITE DIRECTOR',
          phone_area_code: '202',
          phone_number: '5612480',
          phone_extension: null,
          email: 'director.bolling@ctcd.edu',
          version: null,
          institution_id: 8887595,
        },
        {
          id: 2501545,
          facility_code: '14000109',
          institution_name: 'CENTRAL TEXAS COLLEGE-WASHINGTON DC',
          priority: 'Secondary',
          first_name: 'TRACY',
          last_name: 'LEHMKUHLER',
          title: 'MANAGER ACCTS RECEIVABLE',
          phone_area_code: '202',
          phone_number: '5612480',
          phone_extension: null,
          email: 'director.bolling@ctcd.edu',
          version: null,
          institution_id: 8887595,
        },
      ],
      complies_with_sec_103: null,
      solely_requires_coe: null,
      requires_coe_and_criteria: null,
      count_of_caution_flags: 0,
    },
    links: {
      website: 'http://www.ctcd.edu',
      scorecard:
        'https://collegescorecard.ed.gov/school/?223816-central-texas-college-washington-dc',
      vet_website_link:
        'http://www.ctcd.edu/students/military-students-veterans-spouses/',
      self: 'https://staging-api.va.gov/gids/v0/institutions/14000109',
    },
  },
  links: {
    self: 'https://staging-api.va.gov/gids/v0/institutions/14000109',
  },
  meta: {
    version: {
      number: 1,
      created_at: '2020-04-07T16:57:37.600Z',
      preview: false,
    },
  },
};

const calculatorConstants = {
  data: [
    {
      id: '45',
      type: 'calculator_constants',
      attributes: {
        name: 'AVEGRADRATE',
        value: 42.3,
      },
    },
    {
      id: '47',
      type: 'calculator_constants',
      attributes: {
        name: 'AVEREPAYMENTRATE',
        value: 67.9,
      },
    },
    {
      id: '44',
      type: 'calculator_constants',
      attributes: {
        name: 'AVERETENTIONRATE',
        value: 47.99,
      },
    },
    {
      id: '46',
      type: 'calculator_constants',
      attributes: {
        name: 'AVESALARY',
        value: 33400,
      },
    },
    {
      id: '24',
      type: 'calculator_constants',
      attributes: {
        name: 'AVGVABAH',
        value: 1681,
      },
    },
    {
      id: '25',
      type: 'calculator_constants',
      attributes: {
        name: 'BSCAP',
        value: 1000,
      },
    },
    {
      id: '26',
      type: 'calculator_constants',
      attributes: {
        name: 'BSOJTMONTH',
        value: 83,
      },
    },
    {
      id: '28',
      type: 'calculator_constants',
      attributes: {
        name: 'CORRESPONDTFCAP',
        value: 11076.86,
      },
    },
    {
      id: '32',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATE',
        value: 1024,
      },
    },
    {
      id: '33',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATEFULLTIME',
        value: 1224,
      },
    },
    {
      id: '36',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATEOJT',
        value: 747,
      },
    },
    {
      id: '35',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATEONEHALF',
        value: 710,
      },
    },
    {
      id: '34',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATETHREEQUARTERS',
        value: 967,
      },
    },
    {
      id: '61',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATEUPTOONEHALF',
        value: 710,
      },
    },
    {
      id: '62',
      type: 'calculator_constants',
      attributes: {
        name: 'DEARATEUPTOONEQUARTER',
        value: 306,
      },
    },
    {
      id: '27',
      type: 'calculator_constants',
      attributes: {
        name: 'FLTTFCAP',
        value: 13031.61,
      },
    },
    {
      id: '30',
      type: 'calculator_constants',
      attributes: {
        name: 'MGIB2YRRATE',
        value: 1509,
      },
    },
    {
      id: '29',
      type: 'calculator_constants',
      attributes: {
        name: 'MGIB3YRRATE',
        value: 1857,
      },
    },
    {
      id: '31',
      type: 'calculator_constants',
      attributes: {
        name: 'SRRATE',
        value: 369,
      },
    },
    {
      id: '23',
      type: 'calculator_constants',
      attributes: {
        name: 'TFCAP',
        value: 22805.34,
      },
    },
    {
      id: '37',
      type: 'calculator_constants',
      attributes: {
        name: 'VRE0DEPRATE',
        value: 605.44,
      },
    },
    {
      id: '41',
      type: 'calculator_constants',
      attributes: {
        name: 'VRE0DEPRATEOJT',
        value: 529.36,
      },
    },
    {
      id: '38',
      type: 'calculator_constants',
      attributes: {
        name: 'VRE1DEPRATE',
        value: 751,
      },
    },
    {
      id: '42',
      type: 'calculator_constants',
      attributes: {
        name: 'VRE1DEPRATEOJT',
        value: 640.15,
      },
    },
    {
      id: '39',
      type: 'calculator_constants',
      attributes: {
        name: 'VRE2DEPRATE',
        value: 885,
      },
    },
    {
      id: '40',
      type: 'calculator_constants',
      attributes: {
        name: 'VREINCRATE',
        value: 64.5,
      },
    },
    {
      id: '43',
      type: 'calculator_constants',
      attributes: {
        name: 'VREINCRATEOJT',
        value: 737.77,
      },
    },
    {
      id: '55',
      type: 'calculator_constants',
      attributes: {
        name: 'AVGDODBAH',
        value: 1600,
      },
    },
  ],
  links: {
    self: 'http://localhost:3000/v0/calculator/constants',
  },
  meta: {
    version: {
      number: 1,
      created_at: '2019-04-22T15:48:57.598Z',
      preview: false,
    },
  },
};

const autocomplete = {
  data: [],
  meta: {
    version: {
      number: 132,
      created_at: '2020-04-07T16:57:37.600Z',
      preview: false,
    },
    term: 'central texas college-washington dc',
  },
  links: {
    self:
      'https://staging-api.va.gov/gids/v0/institutions/autocomplete?category=school&term=CENTRAL+TEXAS+COLLEGE-WASHINGTON+DC',
  },
};

// Create API routes
function initApplicationMock() {
  mock(null, {
    path: '/v0/gi/institutions/search',
    verb: 'get',
    value: schools,
  });

  mock(null, {
    path: '/v0/gi/institutions/14000109',
    verb: 'get',
    value: singleSchool,
  });

  mock(null, {
    path: '/v0/gi/calculator_constants',
    verb: 'get',
    value: calculatorConstants,
  });

  mock(null, {
    path: '/v0/gi/institutions/autocomplete',
    verb: 'get',
    value: autocomplete,
  });

  mock(null, {
    path: '/v0/feature_toggles',
    verb: 'get',
    value: {
      data: {
        features: [],
      },
    },
  });

  mock(null, {
    path: '/v0/maintenance_windows',
    verb: 'get',
    value: {},
  });
}

module.exports = {
  calculatorConstants,
  schools,
  singleSchool,
  initApplicationMock,
};
