import React from 'react';
import { Router } from 'react-router-dom';
import { createMemoryHistory } from 'history-v4';
import { combineReducers, applyMiddleware, createStore } from 'redux';
import thunk from 'redux-thunk';
import sinon from 'sinon';

import createCommonStore, { commonReducer } from 'platform/startup/store';
import { renderInReduxProvider } from 'platform/testing/unit/react-testing-library-helpers';

import reducers from '../reducers';

const calculatorConstants = require('./data/calculator-constants.json');

export function mockConstants() {
  const constants = [];
  calculatorConstants.data.forEach(c => {
    constants[c.attributes.name] = c.attributes.value;
  });

  return { constants };
}

export function createTestHistory(path = '/') {
  const history = createMemoryHistory({ initialEntries: [path] });
  sinon.spy(history, 'replace');
  sinon.spy(history, 'push');

  return history;
}

export function renderWithStoreAndRouter(
  ui,
  { initialState, store = null, path = '/', history = null },
) {
  const testStore =
    store ||
    createStore(
      combineReducers({ ...commonReducer, ...reducers }),
      initialState,
      applyMiddleware(thunk),
    );

  const historyObject = history || createTestHistory(path);
  const screen = renderInReduxProvider(
    <Router history={historyObject}>{ui}</Router>,
    {
      store: testStore,
      initialState,
      reducers,
    },
  );

  return { ...screen, history: historyObject };
}

export const getDefaultState = () => {
  const defaultState = createCommonStore(reducers).getState();

  defaultState.constants = {
    constants: {},
    version: calculatorConstants.meta.version,
    inProgress: false,
  };

  calculatorConstants.data.forEach(c => {
    defaultState.constants.constants[c.attributes.name] = c.attributes.value;
  });
  return defaultState;
};

export const mockCompareDrawerData = {
  compare: {
    search: {
      loaded: ['14927436'],
      institutions: {
        '14927436': {
          name: 'ROSE STATE COLLEGE',
          facilityCode: '14927436',
          city: 'MIDWEST CITY',
          state: 'OK',
          country: 'USA',
          accreditationType: 'regional',
          studentCount: 458,
          ratingAverage: null,
          ratingCount: 0,
          institutionRating: null,
          type: 'PUBLIC',
          cautionFlags: [],
          cautionFlag: null,
          studentVeteran: null,
          yr: false,
          campusType: 'Y',
          highestDegree: 2,
          hbcu: 0,
          menonly: 0,
          womenonly: 0,
          relaffil: null,
          hsi: 0,
          nanti: 0,
          annhi: 0,
          aanapii: 0,
          pbi: 0,
          tribal: 0,
          preferredProvider: false,
          dodBah: 1536,
          bah: 1647,
          latitude: 35.44389575,
          longitude: -97.4148933892573,
          distance: null,
          accredited: true,
          vetTecProvider: false,
          programCount: null,
          programLengthInHours: null,
          schoolProvider: true,
          employerProvider: false,
          vrrap: null,
        },
      },
    },
    details: {
      loaded: [],
      institutions: {},
    },
    selected: ['14927436'],
    error: null,
    open: true,
  },
};

export const mockModalProfileData = {
  attributes: {
    name: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
    facilityCode: '11801136',
    type: 'PUBLIC',
    city: 'NORMAN',
    state: 'OK',
    zip: '73019',
    country: 'USA',
    bah: 1647,
    cross: '207500',
    flight: false,
    correspondence: false,
    ope: '00318400',
    ope6: '03184',
    schoolSystemName: null,
    schoolSystemCode: -2,
    alias: 'University of Oklahoma|Oklahoma University|OU|Oklahoma',
    highestDegree: 4,
    localeType: 'suburban',
    address1: '1000 ASP AVENUE',
    address2: 'BUCHANAN HALL ROOM 216',
    address3: null,
    studentCount: 1475,
    undergradEnrollment: 20800,
    yr: true,
    studentVeteran: true,
    studentVeteranLink:
      'https://www.facebook.com/pages/OU-Student-Veterans-Association-SVA/274024639303493?ref=hl',
    poe: true,
    eightKeys: true,
    stemOffered: false,
    dodmou: true,
    sec702: true,
    vetSuccessName: null,
    vetSuccessEmail: null,
    creditForMilTraining: true,
    vetPoc: true,
    studentVetGrpIpeds: true,
    socMember: true,
    retentionRateVeteranBa: null,
    retentionAllStudentsBa: 0.885,
    retentionRateVeteranOtb: null,
    retentionAllStudentsOtb: null,
    persistanceRateVeteranBa: null,
    persistanceRateVeteranOtb: null,
    graduationRateVeteran: null,
    graduationRateAllStudents: 0.7392,
    transferOutRateVeteran: null,
    transferOutRateAllStudents: null,
    salaryAllStudents: 59648,
    repaymentRateAllStudents: 0.6822807543,
    avgStuLoanDebt: 20654,
    calendar: 'semesters',
    tuitionInState: 9495,
    tuitionOutOfState: 22269,
    books: 720,
    onlineAll: true,
    p911TuitionFees: 9342047.52,
    p911Recipients: 998,
    p911YellowRibbon: 108232.55,
    p911YrRecipients: 33,
    accredited: true,
    accreditationType: 'regional',
    accreditationStatus: null,
    cautionFlag: null,
    cautionFlagReason: null,
    cautionFlags: [],
    complaints: {
      facilityCode: 3,
      financialByFacCode: 0,
      qualityByFacCode: 0,
      refundByFacCode: 0,
      marketingByFacCode: 1,
      accreditationByFacCode: 0,
      degreeRequirementsByFacCode: 0,
      studentLoansByFacCode: 0,
      gradesByFacCode: 0,
      creditTransferByFacCode: 0,
      creditJobByFacCode: null,
      jobByFacCode: 0,
      transcriptByFacCode: 0,
      otherByFacCode: 2,
      mainCampusRollUp: 3,
      financialByOpeIdDoNotSum: 0,
      qualityByOpeIdDoNotSum: 0,
      refundByOpeIdDoNotSum: 0,
      marketingByOpeIdDoNotSum: 1,
      accreditationByOpeIdDoNotSum: 0,
      degreeRequirementsByOpeIdDoNotSum: 0,
      studentLoansByOpeIdDoNotSum: 0,
      gradesByOpeIdDoNotSum: 0,
      creditTransferByOpeIdDoNotSum: 0,
      jobsByOpeIdDoNotSum: 0,
      transcriptByOpeIdDoNotSum: 0,
      otherByOpeIdDoNotSum: 2,
    },
    schoolClosing: false,
    schoolClosingOn: null,
    schoolClosingMessage: null,
    yellowRibbonPrograms: [
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'University College',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'College of Architecture',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'College of Arts and Sciences',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool:
          'College of Atmospheric & Geographic Sciences',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'Michael F. Price College of Business',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'Mewbourne College of Earth and Energy',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'Jeannine Rainbolt College of Education',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Rom 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'Weitzenhoffer Family College of the Arts',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'Graduate College',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool:
          'Gaylord College of Journalism and Mass Communication',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'College of Law',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'College of International Studies',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
      {
        city: 'Norman',
        contributionAmount: '99999.0',
        country: 'USA',
        degreeLevel: 'All',
        divisionProfessionalSchool: 'College of Engineering',
        facilityCode: '11801136',
        institutionId: 30036023,
        insturl: 'www.ou.edu/',
        numberOfStudents: 99999,
        nameOfInstitution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        state: 'OK',
        streetAddress: '1000 Asp Avenue, Room 330',
      },
    ],
    independentStudy: true,
    priorityEnrollment: false,
    createdAt: '2023-10-24T11:54:37.000Z',
    updatedAt: '2023-10-24T11:54:37.000Z',
    physicalAddress1: '1000 ASP AVENUE',
    physicalAddress2: 'BUCHANAN HALL ROOM 216',
    physicalAddress3: null,
    physicalCity: 'NORMAN',
    physicalState: 'OK',
    physicalCountry: 'USA',
    onlineOnly: false,
    distanceLearning: true,
    dodBah: 1536,
    physicalZip: '73019',
    parentFacilityCodeId: null,
    campusType: 'Y',
    vetTecProvider: false,
    preferredProvider: false,
    stemIndicator: false,
    facilityMap: {
      main: {
        institution: {
          id: 30036023,
          version: {
            number: 422,
            createdAt: '2023-10-24T11:54:22.986Z',
            preview: false,
          },
          institutionTypeName: 'PUBLIC',
          facilityCode: '11801136',
          institution: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
          city: 'NORMAN',
          state: 'OK',
          zip: '73019',
          country: 'USA',
          flight: false,
          correspondence: false,
          bah: 1647,
          cross: '207500',
          ope: '00318400',
          ope6: '03184',
          insturl: 'www.ou.edu/',
          vetTuitionPolicyUrl: 'www.ou.edu/veterans/veteran_student_services',
          predDegreeAwarded: 3,
          locale: 22,
          gibill: 1475,
          undergradEnrollment: 20800,
          yr: true,
          studentVeteran: true,
          studentVeteranLink:
            'https://www.facebook.com/pages/OU-Student-Veterans-Association-SVA/274024639303493?ref=hl',
          poe: true,
          eightKeys: true,
          dodmou: true,
          sec702: true,
          vetsuccessName: null,
          vetsuccessEmail: null,
          creditForMilTraining: true,
          vetPoc: true,
          studentVetGrpIpeds: true,
          socMember: true,
          vaHighestDegreeOffered: '4-year',
          retentionRateVeteranBa: null,
          retentionAllStudentsBa: 0.885,
          retentionRateVeteranOtb: null,
          retentionAllStudentsOtb: null,
          persistanceRateVeteranBa: null,
          persistanceRateVeteranOtb: null,
          graduationRateVeteran: null,
          graduationRateAllStudents: 0.7392,
          transferOutRateVeteran: null,
          transferOutRateAllStudents: null,
          salaryAllStudents: 59648,
          repaymentRateAllStudents: 0.6822807543,
          avgStuLoanDebt: 20654,
          calendar: 'semesters',
          tuitionInState: 9495,
          tuitionOutOfState: 22269,
          books: 720,
          onlineAll: true,
          p911TuitionFees: 9342047.52,
          p911Recipients: 998,
          p911YellowRibbon: 108232.55,
          p911YrRecipients: 33,
          accredited: true,
          accreditationType: 'regional',
          accreditationStatus: null,
          cautionFlag: null,
          cautionFlagReason: null,
          complaintsFacilityCode: 3,
          complaintsFinancialByFacCode: 0,
          complaintsQualityByFacCode: 0,
          complaintsRefundByFacCode: 0,
          complaintsMarketingByFacCode: 1,
          complaintsAccreditationByFacCode: 0,
          complaintsDegreeRequirementsByFacCode: 0,
          complaintsStudentLoansByFacCode: 0,
          complaintsGradesByFacCode: 0,
          complaintsCreditTransferByFacCode: 0,
          complaintsCreditJobByFacCode: null,
          complaintsJobByFacCode: 0,
          complaintsTranscriptByFacCode: 0,
          complaintsOtherByFacCode: 2,
          complaintsMainCampusRollUp: 3,
          complaintsFinancialByOpeIdDoNotSum: 0,
          complaintsQualityByOpeIdDoNotSum: 0,
          complaintsRefundByOpeIdDoNotSum: 0,
          complaintsMarketingByOpeIdDoNotSum: 1,
          complaintsAccreditationByOpeIdDoNotSum: 0,
          complaintsDegreeRequirementsByOpeIdDoNotSum: 0,
          complaintsStudentLoansByOpeIdDoNotSum: 0,
          complaintsGradesByOpeIdDoNotSum: 0,
          complaintsCreditTransferByOpeIdDoNotSum: 0,
          complaintsJobsByOpeIdDoNotSum: 0,
          complaintsTranscriptByOpeIdDoNotSum: 0,
          complaintsOtherByOpeIdDoNotSum: 2,
          createdAt: '2023-10-24T11:54:37.000Z',
          updatedAt: '2023-10-24T11:54:37.000Z',
          f1sysnam: null,
          f1syscod: -2,
          ialias: 'University of Oklahoma|Oklahoma University|OU|Oklahoma',
          approvalStatus: null,
          schoolClosing: false,
          schoolClosingOn: null,
          schoolClosingMessage: null,
          stemOffered: false,
          priorityEnrollment: false,
          onlineOnly: false,
          independentStudy: true,
          distanceLearning: true,
          address1: '1000 ASP AVENUE',
          address2: 'BUCHANAN HALL ROOM 216',
          address3: null,
          physicalAddress1: '1000 ASP AVENUE',
          physicalAddress2: 'BUCHANAN HALL ROOM 216',
          physicalAddress3: null,
          physicalCity: 'NORMAN',
          physicalState: 'OK',
          physicalZip: '73019',
          physicalCountry: 'USA',
          dodBah: 1536,
          approved: true,
          vetTecProvider: false,
          closure109: null,
          preferredProvider: false,
          stemIndicator: false,
          campusType: 'Y',
          parentFacilityCodeId: null,
          versionId: 520,
          compliesWithSec103: null,
          solelyRequiresCoe: null,
          requiresCoeAndCriteria: null,
          countOfCautionFlags: 0,
          section103Message: 'No',
          pooStatus: 'APRVD',
          hbcu: 0,
          hcm2: 0,
          menonly: 0,
          pctfloan: 0.3283,
          relaffil: null,
          womenonly: 0,
          institutionSearch: 'OKLAHOMANORMAN',
          ratingCount: 0,
          ratingAverage: null,
          latitude: 35.2092242121212,
          longitude: -97.443791,
          employerProvider: false,
          schoolProvider: true,
          vrrap: null,
          inStateTuitionInformation:
            'https://www.ou.edu/veterans/veteran_student_services',
          badAddress: false,
          highSchool: null,
          chiefOfficer: null,
          ownershipName: null,
          hsi: 0,
          nanti: 0,
          annhi: 0,
          aanapii: 0,
          pbi: 0,
          tribal: 0,
          ungeocodable: false,
          distance: null,
        },
        branches: [],
        extensions: [],
      },
    },
    programs: [],
    versionedSchoolCertifyingOfficials: [
      {
        id: 18319005,
        facilityCode: '11801136',
        institutionName: 'UNIVERSITY OF OKLAHOMA-NORMAN CAMPUS',
        priority: 'Primary',
        firstName: 'JENNIFER',
        lastName: 'TRIMMER',
        title: 'DIRECTOR NORMAN CAMPUS',
        phoneAreaCode: '405',
        phoneNumber: '325-4308',
        phoneExtension: null,
        email: 'JENTRIMMER96@OU.EDU',
        version: null,
        institutionId: 30036023,
      },
    ],
    countOfCautionFlags: 0,
    section103Message: 'No',
    hbcu: 0,
    hcm2: 0,
    menonly: 0,
    pctfloan: 0.3283,
    relaffil: null,
    womenonly: 0,
    hsi: 0,
    nanti: 0,
    annhi: 0,
    aanapii: 0,
    pbi: 0,
    tribal: 0,
    institutionRating: null,
    ratingAverage: null,
    ratingCount: 0,
    inStateTuitionInformation:
      'https://www.ou.edu/veterans/veteran_student_services',
    vrrap: null,
    ownershipName: null,
    website: 'http://www.ou.edu/',
    scorecard:
      'https://collegescorecard.ed.gov/school/?207500-university-of-oklahoma-norman-campus',
    vetWebsiteLink: 'http://www.ou.edu/veterans/veteran_student_services',
    self: 'https://staging-platform-api.va.gov/gids/v0/institutions/11801136',
  },
  version: {
    number: 422,
    createdAt: '2023-10-24T11:54:22.986Z',
    preview: false,
  },
  inProgress: false,
  error: null,
};

export const mockEligibility = {
  expanded: false,
  giBillChapter: '33',
  militaryStatus: 'veteran',
  spouseActiveDuty: 'no',
  cumulativeService: '1.0',
  enlistmentService: '3',
  eligForPostGiBill: 'yes',
  numberOfDependents: '0',
  onlineClasses: 'no',
};

export const mockSearchResults = {
  error: null,
  geocode: null,
  geolocationInProgress: false,
  inProgress: false,
  location: {
    count: null,
    facets: {
      category: {},
      state: {},
      country: [],
      cautionFlag: {},
      studentVetGroup: {},
      yellowRibbonScholarship: {},
      principlesOfExcellence: {},
      eightKeysToVeteranSuccess: {},
      stem: {},
      provider: [],
    },
    results: [],
  },
  name: {
    results: [
      {
        name: 'ROSE STATE COLLEGE',
        facilityCode: '14927436',
        city: 'MIDWEST CITY',
        state: 'OK',
        country: 'USA',
        accreditationType: 'regional',
        studentCount: 458,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'PUBLIC',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: 2,
        hbcu: 0,
        menonly: 0,
        womenonly: 0,
        relaffil: null,
        hsi: 0,
        nanti: 0,
        annhi: 0,
        aanapii: 0,
        pbi: 0,
        tribal: 0,
        preferredProvider: false,
        dodBah: 1536,
        bah: 1647,
        latitude: 35.44389575,
        longitude: -97.4148933892573,
        distance: null,
        accredited: true,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: true,
        employerProvider: false,
        vrrap: null,
      },
      {
        name: 'ROSE-HULMAN INSTITUTE OF TECHNOLOGY',
        facilityCode: '31910414',
        city: 'TERRE HAUTE',
        state: 'IN',
        country: 'USA',
        accreditationType: 'regional',
        studentCount: 41,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'PRIVATE',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: true,
        campusType: 'Y',
        highestDegree: 4,
        hbcu: 0,
        menonly: 0,
        womenonly: 0,
        relaffil: null,
        hsi: 0,
        nanti: 0,
        annhi: 0,
        aanapii: 0,
        pbi: 0,
        tribal: 0,
        preferredProvider: false,
        dodBah: 1086,
        bah: 1197,
        latitude: 39.48292005,
        longitude: -87.3241582374307,
        distance: null,
        accredited: true,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: true,
        employerProvider: false,
        vrrap: null,
      },
      {
        name: 'ROSE ROCK ACADEMY',
        facilityCode: '20482036',
        city: 'OKLAHOMA CITY',
        state: 'OK',
        country: 'USA',
        accreditationType: null,
        studentCount: null,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'OJT',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: null,
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: 1536,
        bah: 1647,
        latitude: 35.5030931,
        longitude: -97.4778649252418,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: false,
        employerProvider: true,
        vrrap: null,
      },
      {
        name: 'ROSE BRUFORD COLLEGE',
        facilityCode: '11205974',
        city: 'KENT DA15 9DF',
        country: 'ENGLAND',
        accreditationType: null,
        studentCount: 1,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'FOREIGN',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: 4,
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: null,
        bah: null,
        latitude: 51.4264002,
        longitude: 0.101044,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: true,
        employerProvider: false,
        vrrap: null,
      },
      {
        name: 'ROSEMONT COLLEGE',
        facilityCode: '31003338',
        city: 'ROSEMONT',
        state: 'PA',
        country: 'USA',
        accreditationType: 'regional',
        studentCount: 14,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'PRIVATE',
        cautionFlags: [
          {
            title: 'School has an accreditation issue',
            description:
              "This school's accreditation has been taken away and is under appeal, or the school has been placed on probation, because it didn't meet acceptable levels of quality.",
            linkText: "Learn more about this school's accreditation",
            linkUrl: 'http://ope.ed.gov/accreditation/',
          },
        ],
        cautionFlag: true,
        studentVeteran: null,
        yr: true,
        campusType: 'Y',
        highestDegree: 4,
        hbcu: 0,
        menonly: 0,
        womenonly: 0,
        relaffil: 30,
        hsi: 0,
        nanti: 0,
        annhi: 0,
        aanapii: 0,
        pbi: 0,
        tribal: 0,
        preferredProvider: false,
        dodBah: 2346,
        bah: 2457,
        latitude: 40.033512,
        longitude: -75.32689,
        distance: null,
        accredited: true,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: true,
        employerProvider: false,
        vrrap: null,
      },
      {
        name: 'ROSELLE POLICE DEPARTMENT',
        facilityCode: '10602813',
        city: 'ROSELLE',
        state: 'IL',
        country: 'USA',
        accreditationType: null,
        studentCount: null,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'OJT',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: null,
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: 2709,
        bah: 2820,
        latitude: 40.6582983,
        longitude: -74.2637365,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: false,
        employerProvider: true,
        vrrap: null,
      },
      {
        name: 'ROSELAND POLICE DEPARTMENT',
        facilityCode: '10068614',
        city: 'SOUTH BEND',
        state: 'IN',
        country: 'USA',
        accreditationType: null,
        studentCount: null,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'OJT',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: null,
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: 1599,
        bah: 1710,
        latitude: 41.7152686790123,
        longitude: -86.2454355555555,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: false,
        employerProvider: true,
        vrrap: null,
      },
      {
        name: 'ROSELAND POLICE DEPARTMENT',
        facilityCode: '10527530',
        city: 'ROSELAND',
        state: 'NJ',
        country: 'USA',
        accreditationType: null,
        studentCount: null,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'OJT',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: null,
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: 3882,
        bah: 3993,
        latitude: 40.7458178148148,
        longitude: -74.0401101111111,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: false,
        employerProvider: true,
        vrrap: null,
      },
      {
        name: 'ROSEMOUNT HIGH SCHOOL',
        facilityCode: '15021023',
        city: 'ROSEMOUNT',
        state: 'MN',
        country: 'USA',
        accreditationType: null,
        studentCount: null,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'PUBLIC',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: 'Certificate',
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: 2154,
        bah: 2265,
        latitude: 44.7441540603835,
        longitude: -93.1303767811779,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: true,
        employerProvider: false,
        vrrap: null,
      },
      {
        name: 'ROSEBURG TATC',
        facilityCode: '20270537',
        city: 'ROSEBURG',
        state: 'OR',
        country: 'USA',
        accreditationType: null,
        studentCount: null,
        ratingAverage: null,
        ratingCount: 0,
        institutionRating: null,
        type: 'OJT',
        cautionFlags: [],
        cautionFlag: null,
        studentVeteran: null,
        yr: false,
        campusType: 'Y',
        highestDegree: null,
        hbcu: null,
        menonly: null,
        womenonly: null,
        relaffil: null,
        hsi: null,
        nanti: null,
        annhi: null,
        aanapii: null,
        pbi: null,
        tribal: null,
        preferredProvider: false,
        dodBah: 1809,
        bah: 1920,
        latitude: 43.216505,
        longitude: -123.3417381,
        distance: null,
        accredited: false,
        vetTecProvider: false,
        programCount: null,
        programLengthInHours: null,
        schoolProvider: false,
        employerProvider: true,
        vrrap: null,
      },
    ],
    pagination: {
      currentPage: 1,
      totalPages: 7,
      perPage: 10,
    },
    facets: {
      category: {
        school: 24,
        employer: 37,
      },
      state: {
        AZ: 1,
        CA: 2,
        CO: 4,
        CT: 1,
        IA: 1,
        IL: 5,
        IN: 2,
        LA: 1,
        MA: 2,
        MI: 2,
        MN: 3,
        MO: 2,
        NJ: 12,
        NV: 2,
        NY: 4,
        OH: 1,
        OK: 2,
        OR: 2,
        PA: 2,
        SC: 2,
        SD: 3,
        TX: 1,
        UT: 1,
        WV: 1,
      },
      country: [
        {
          name: 'CANADA',
          count: 1,
        },
        {
          name: 'ENGLAND',
          count: 1,
        },
        {
          name: 'USA',
          count: 59,
        },
      ],
      studentVetGroup: {
        true: null,
        false: null,
      },
      yellowRibbonScholarship: {
        true: null,
        false: null,
      },
      principlesOfExcellence: {
        true: null,
        false: null,
      },
      eightKeysToVeteranSuccess: {
        true: null,
        false: null,
      },
      stemOffered: {
        true: null,
        false: null,
      },
      independentStudy: {
        true: null,
        false: null,
      },
      onlineOnly: {
        true: null,
        false: null,
      },
      distanceLearning: {
        true: null,
        false: null,
      },
      priorityEnrollment: {
        true: null,
        false: null,
      },
      menonly: {
        true: null,
        false: null,
      },
      womenonly: {
        true: null,
        false: null,
      },
      hbcu: {
        true: null,
        false: null,
      },
      relaffil: {
        '30': 3,
        '69': 1,
      },
      hsi: {
        true: null,
        false: null,
      },
      nanti: {
        true: null,
        false: null,
      },
      annhi: {
        true: null,
        false: null,
      },
      aanapii: {
        true: null,
        false: null,
      },
      pbi: {
        true: null,
        false: null,
      },
      tribal: {
        true: null,
        false: null,
      },
      vetTecProvider: {
        true: null,
        false: null,
      },
      section103Message: {
        true: null,
        false: null,
      },
      provider: [],
    },
    count: 61,
  },
  query: {
    name: 'rose',
    location: '',
    distance: '25',
    latitude: null,
    longitude: null,
    streetAddress: {
      searchString: '',
      position: {},
    },
    mapState: {
      changed: false,
      distance: null,
    },
  },
  compare: {
    results: [],
    count: null,
  },
  tab: 'name',
  loadFromUrl: false,
};
export const noFilters = {
  expanded: true,
  search: false,
  schools: false,
  excludedSchoolTypes: [],
  excludeCautionFlags: false,
  accredited: false,
  studentVeteran: false,
  yellowRibbonScholarship: false,
  employers: false,
  vettec: false,
  preferredProvider: false,
  country: 'ALL',
  state: 'ALL',
  specialMissionHbcu: false,
  specialMissionMenonly: false,
  specialMissionWomenonly: false,
  specialMissionRelaffil: false,
  specialMissionHSI: false,
  specialMissionNANTI: false,
  specialMissionANNHI: false,
  specialMissionAANAPII: false,
  specialMissionPBI: false,
  specialMissionTRIBAL: false,
  specialMission: 'ALL',
};
