import { formatDateLong } from '@department-of-veterans-affairs/platform-utilities/exports';

// separator used in txt files
export const txtLine = '_____________________________________________________';

// dotted separator
export const txtLineDotted =
  '-----------------------------------------------------';

// the Crisis Line header that must go at the top of all txt files
export const crisisLineHeader =
  "If you're ever in crisis and need to talk with someone right away, call the Veterans Crisis Line at 988. Then select 1.";

// line used by all PDFs and txt files to denote the file origin
export const reportGeneratedBy = `Report generated by My HealtheVet on VA.gov on ${formatDateLong(
  new Date(),
)}`;

export const edipiNotFound = `NOTES:
1) This report may not show your complete DoD Military Service Information.
   Data prior to establishment of DEERS and full service reporting (c. 1980) 
   may not appear.
2) It is normal for the begin/end dates in DoD records, adjusted by the
   Personnel Center after separation, to vary slightly from the DD-214.
3) No peacetime deployments will be displayed.  For Gulf War I, only one
   period will be displayed even if you deployed more than once.  No conflict
   prior to Gulf War I will be displayed.  Kosovo, Bosnia, and Southern Watch
   data is incomplete and may not display.
4) For Guard/Reserve, periods of active duty may not display.  No periods of
   Active duty service less than 30 days will display.
   
   ** No data was found. **`;
