export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_CURRENT = 'UPDATE_CURRENT';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const SHOW_NEW_CONDITION_SECTION = 'SHOW_NEW_CONDITION_SECTION';
export const HIDE_NEW_CONDITION_SECTION = 'HIDE_NEW_CONDITION_SECTION';
