import { RESPONSES } from '../question-data-map';

const { BOARD, CFI, HLR, INIT, NO, SC, YES } = RESPONSES;

// Refer to the README in this directory for an explanation of display conditions
export const section2DCs = Object.freeze({
  Q_2_IS_1_SERVICE_CONNECTED: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
  },
  Q_2_IS_2_CONDITION_WORSENED: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_IS_1_SERVICE_CONNECTED: YES,
  },
  Q_2_IS_4_DISAGREE_DECISION: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_IS_1_SERVICE_CONNECTED: YES,
    Q_2_IS_2_CONDITION_WORSENED: YES,
  },
  Q_2_0_CLAIM_TYPE: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    ONE_OF: {
      Q_2_IS_1_SERVICE_CONNECTED: NO,
      Q_2_IS_2_CONDITION_WORSENED: NO,
      Q_2_IS_4_DISAGREE_DECISION: YES,
    },
  },
  Q_2_IS_1A_LAW_POLICY_CHANGE: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_0_CLAIM_TYPE: [INIT, CFI, SC],
  },
  Q_2_IS_1B_NEW_EVIDENCE: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_0_CLAIM_TYPE: [INIT, CFI, SC],
    Q_2_IS_1A_LAW_POLICY_CHANGE: NO,
  },
  Q_2_IS_1B_2_JUDGE_HEARING: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_0_CLAIM_TYPE: [INIT, CFI, SC],
    Q_2_IS_1A_LAW_POLICY_CHANGE: NO,
    Q_2_IS_1B_NEW_EVIDENCE: NO,
  },
  Q_2_IS_1B_3_JUDGE_HEARING: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_0_CLAIM_TYPE: [INIT, CFI, SC],
    Q_2_IS_1A_LAW_POLICY_CHANGE: NO,
    Q_2_IS_1B_NEW_EVIDENCE: YES,
  },
  Q_2_S_1_NEW_EVIDENCE: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_0_CLAIM_TYPE: BOARD,
  },
  Q_2_S_2_WITHIN_120_DAYS: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_1_3_CLAIM_CONTESTED: NO,
    Q_2_0_CLAIM_TYPE: BOARD,
    Q_2_S_1_NEW_EVIDENCE: NO,
  },
  Q_2_H_2_NEW_EVIDENCE: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    ONE_OF: {
      Q_1_3A_FEWER_60_DAYS: YES,
      Q_2_0_CLAIM_TYPE: HLR,
    },
  },
  Q_2_H_2A_JUDGE_HEARING: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_2_H_2_NEW_EVIDENCE: YES,
  },
  Q_2_H_2B_JUDGE_HEARING: {
    Q_1_1_CLAIM_DECISION: YES,
    Q_1_2_CLAIM_DECISION: YES,
    Q_2_H_2_NEW_EVIDENCE: NO,
  },
});
