import { RESPONSES } from '../question-data-map';

const { HLR, IS, NO, YES } = RESPONSES;

// Refer to the README in this directory for an explanation of display conditions
export const section2DCs = Object.freeze({
  Q_2_0_CLAIM_TYPE: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
  },
  Q_2_IS_1_SERVICE_CONNECTED: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [IS],
  },
  Q_2_IS_1_A_LAW_POLICY_CHANGE: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [IS],
    Q_2_IS_1_SERVICE_CONNECTED: [NO],
  },
  Q_2_IS_1_B_NEW_EVIDENCE: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [IS],
    Q_2_IS_1_SERVICE_CONNECTED: [NO],
    Q_2_IS_1_A_LAW_POLICY_CHANGE: [NO],
  },
  Q_2_IS_2_CONDITION_WORSENED: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [IS],
    Q_2_IS_1_SERVICE_CONNECTED: [YES],
  },
  Q_2_H_1_EXISTING_BOARD_APPEAL: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [HLR],
  },
  Q_2_H_2_NEW_EVIDENCE: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [HLR],
    Q_2_H_1_EXISTING_BOARD_APPEAL: [NO],
  },
  Q_2_H_2A_JUDGE_HEARING: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [HLR],
    Q_2_H_1_EXISTING_BOARD_APPEAL: [NO],
    Q_2_H_2_NEW_EVIDENCE: [YES],
  },
  Q_2_H_2B_JUDGE_HEARING: {
    Q_1_1_CLAIM_DECISION: [YES],
    Q_1_2_CLAIM_DECISION: [YES],
    Q_1_3_CLAIM_CONTESTED: [NO],
    Q_2_0_CLAIM_TYPE: [HLR],
    Q_2_H_1_EXISTING_BOARD_APPEAL: [NO],
    Q_2_H_2_NEW_EVIDENCE: [NO],
  },
});
