export const pageNames = {
  start: 'start',
  request: 'request',
  recipients: 'recipients',
  submit: 'submit',
  reconsider: 'reconsider',
  copays: 'copays',
  separation: 'separation',
  attorney: 'attorney',
  stem: 'stem',
  vettec: 'vettec',
  payment: 'payment',
  decision: 'decision',
  disagree: 'disagree',
  error: 'error',
  wrong: 'wrong',
  repayment: 'repayment',
  lessThan: 'lessThan',
};
