export const pageNames = {
  start: 'start',
  request: 'request',
  recipients: 'recipients',
  submit: 'submit',
  reconsider: 'reconsider',
  copays: 'copays',
  benefits: 'benefits',
  stem: 'stem',
  vettec: 'vettec',
  payment: 'payment',
  decision: 'decision',
  disagree: 'disagree',
  error: 'error',
  repayment: 'repayment',
  lessThan: 'lessThan',
  dependents: 'dependents',
  waivers: 'waivers',
  appeals: 'appeals',
};
