export const pageNames = {
  start: 'start',
  request: 'request',
  recipients: 'recipients',
  submit: 'submit',
  appeals: 'appeals',
  copays: 'copays',
  separation: 'separation',
  attorney: 'attorney',
  stem: 'stem',
  vettec: 'vettec',
  payment: 'payment',
  descision: 'descision',
  disagree: 'disagree',
  error: 'error',
};
