import { expect } from 'chai';
import {
  createPdfDocumentBuilder,
  createTxtDocumentBuilder,
  createExportService,
} from '../../../util/rxExport/documentBuilders';
import {
  CRISIS_LINE_PDF,
  CRISIS_LINE_TXT,
  SINGLE_MEDICATION_PREFACE,
  PDF_FOOTER_RIGHT,
  ALLERGIES_SECTION_HEADER,
} from '../../../util/rxExport/staticContent';

describe('Rx Export Document Builders', () => {
  const mockUserName = { first: 'John', last: 'Doe' };
  const mockDob = '1990-06-15';

  describe('createPdfDocumentBuilder', () => {
    let builder;

    beforeEach(() => {
      builder = createPdfDocumentBuilder({
        userName: mockUserName,
        dob: mockDob,
      });
    });

    it('should create builder object with methods', () => {
      expect(builder).to.have.property('buildDocument');
      expect(builder).to.have.property('buildRxDetailsPdf');
      expect(builder).to.have.property('buildRxListPdf');
    });

    describe('buildDocument', () => {
      it('should build PDF document with all required fields', () => {
        const result = builder.buildDocument({
          subject: 'Test Subject',
          title: 'Test Title',
          preface: [{ value: 'Test preface' }],
          results: [{ header: 'Section 1', list: [] }],
        });

        expect(result.subject).to.equal('Test Subject');
        expect(result.title).to.equal('Test Title');
        expect(result.headerBanner).to.deep.equal(CRISIS_LINE_PDF);
        expect(result.headerLeft).to.equal('Doe, John');
        expect(result.headerRight).to.equal('Date of birth: June 15, 1990');
        expect(result.footerRight).to.equal(PDF_FOOTER_RIGHT);
      });
    });

    describe('buildRxDetailsPdf', () => {
      it('should build Rx details PDF', () => {
        const result = builder.buildRxDetailsPdf({
          rxName: 'Aspirin 81mg',
          rxList: [{ header: 'Most recent', sections: [] }],
          allergies: [],
        });

        expect(result.subject).to.include('Aspirin 81mg');
        expect(result.title).to.equal('Medication details');
        expect(result.preface[0].value).to.equal(SINGLE_MEDICATION_PREFACE);
        expect(result.results).to.have.length(2);
        expect(result.results[0].header).to.equal('Aspirin 81mg');
        expect(result.results[1].header).to.equal(ALLERGIES_SECTION_HEADER);
      });
    });

    describe('buildRxListPdf', () => {
      it('should build Rx list PDF', () => {
        const result = builder.buildRxListPdf({
          rxList: [],
          allergies: [],
          preface: 'Test preface',
          listHeader: 'All medications',
        });

        expect(result.subject).to.equal('Full Medications List');
        expect(result.title).to.equal('Medications');
        expect(result.results[0].header).to.equal('All medications');
      });
    });
  });

  describe('createTxtDocumentBuilder', () => {
    let builder;

    beforeEach(() => {
      builder = createTxtDocumentBuilder({
        userName: mockUserName,
        dob: mockDob,
      });
    });

    it('should create builder object with methods', () => {
      expect(builder).to.have.property('buildDocument');
      expect(builder).to.have.property('buildRxDetailsTxt');
      expect(builder).to.have.property('buildRxListTxt');
    });

    describe('buildDocument', () => {
      it('should build TXT document with all sections', () => {
        const result = builder.buildDocument({
          title: 'Test Title',
          preface: 'Test preface',
          body: 'Test body content',
          allergiesSection: 'Allergies content',
        });

        expect(result).to.include(CRISIS_LINE_TXT);
        expect(result).to.include('Test Title');
        expect(result).to.include('Test preface');
        expect(result).to.include('Doe, John');
        expect(result).to.include('Date of birth: June 15, 1990');
        expect(result).to.include('Report generated by My HealtheVet');
        expect(result).to.include('Test body content');
        expect(result).to.include('Allergies content');
      });

      it('should handle optional preface', () => {
        const result = builder.buildDocument({
          title: 'Test',
          body: 'Body',
        });

        expect(result).to.include('Test');
        expect(result).to.include('Body');
      });
    });

    describe('buildRxDetailsTxt', () => {
      it('should build Rx details TXT', () => {
        const result = builder.buildRxDetailsTxt({
          rxContent: 'Aspirin 81mg content',
          allergies: [],
        });

        expect(result).to.include('Medication details');
        expect(result).to.include(SINGLE_MEDICATION_PREFACE);
        expect(result).to.include('Aspirin 81mg content');
        expect(result).to.include(ALLERGIES_SECTION_HEADER);
      });
    });

    describe('buildRxListTxt', () => {
      it('should build Rx list TXT', () => {
        const result = builder.buildRxListTxt({
          preface: 'Showing 10 medications',
          listHeader: 'All medications',
          rxContent: 'Rx content',
          allergies: [],
        });

        expect(result).to.include('Medications');
        expect(result).to.include('Showing 10 medications');
        expect(result).to.include('All medications');
        expect(result).to.include('Rx content');
      });
    });
  });

  describe('createExportService', () => {
    let service;

    beforeEach(() => {
      service = createExportService({
        userName: mockUserName,
        dob: mockDob,
        options: { isCernerPilot: false, isV2StatusMapping: false },
      });
    });

    it('should create service with builders', () => {
      expect(service).to.have.property('pdfBuilder');
      expect(service).to.have.property('txtBuilder');
      expect(service).to.have.property('options');
    });

    it('should have export methods', () => {
      expect(service).to.have.property('exportRxDetailsPdf');
      expect(service).to.have.property('exportRxDetailsTxt');
      expect(service).to.have.property('exportRxListPdf');
      expect(service).to.have.property('exportRxListTxt');
    });

    it('should preserve options', () => {
      expect(service.options.isCernerPilot).to.equal(false);
      expect(service.options.isV2StatusMapping).to.equal(false);
    });

    it('should use default options when not provided', () => {
      const serviceWithDefaults = createExportService({
        userName: mockUserName,
        dob: mockDob,
      });
      expect(serviceWithDefaults.options).to.deep.equal({});
    });
  });
});
