import { expect } from 'chai';
import {
  CRISIS_LINE_PDF,
  CRISIS_LINE_TXT,
  ALLERGIES_SECTION_HEADER,
  ALLERGIES_DESCRIPTION,
  ALLERGIES_EMPTY_MESSAGE,
  ALLERGIES_ERROR_MESSAGE,
  SINGLE_MEDICATION_PREFACE,
  NON_VA_MEDICATION_DESCRIPTION,
  ACTIVE_NON_VA,
  PDF_FOOTER_RIGHT,
  getReportGeneratedText,
  getAllergiesCountText,
} from '../../../util/rxExport/staticContent';

describe('Export Static Content', () => {
  describe('CRISIS_LINE_PDF', () => {
    it('should be an array of text objects', () => {
      expect(CRISIS_LINE_PDF).to.be.an('array');
      expect(CRISIS_LINE_PDF.length).to.equal(3);
      expect(CRISIS_LINE_PDF[1].text).to.equal('988');
      expect(CRISIS_LINE_PDF[1].weight).to.equal('bold');
    });
  });

  describe('CRISIS_LINE_TXT', () => {
    it('should contain crisis line text', () => {
      expect(CRISIS_LINE_TXT).to.be.a('string');
      expect(CRISIS_LINE_TXT).to.include('Veterans Crisis Line');
      expect(CRISIS_LINE_TXT).to.include('988');
    });
  });

  describe('Allergies constants', () => {
    it('should have correct header', () => {
      expect(ALLERGIES_SECTION_HEADER).to.equal('Allergies and reactions');
    });

    it('should have description', () => {
      expect(ALLERGIES_DESCRIPTION).to.include('allergies');
      expect(ALLERGIES_DESCRIPTION).to.include('reactions');
    });

    it('should have empty message', () => {
      expect(ALLERGIES_EMPTY_MESSAGE).to.include('no allergies');
    });

    it('should have error message', () => {
      expect(ALLERGIES_ERROR_MESSAGE).to.include("couldn't access");
      expect(ALLERGIES_ERROR_MESSAGE).to.include('877-327-0022');
    });
  });

  describe('NON_VA_MEDICATION_DESCRIPTION', () => {
    it('should describe non-VA medications', () => {
      expect(NON_VA_MEDICATION_DESCRIPTION).to.include('VA provider added');
      expect(NON_VA_MEDICATION_DESCRIPTION).to.include("can't request refills");
    });
  });

  describe('ACTIVE_NON_VA', () => {
    it('should be correct status', () => {
      expect(ACTIVE_NON_VA).to.equal('Active: Non-VA');
    });
  });

  describe('SINGLE_MEDICATION_PREFACE', () => {
    it('should describe single medication record', () => {
      expect(SINGLE_MEDICATION_PREFACE).to.include('single medication record');
    });
  });

  describe('PDF_FOOTER_RIGHT', () => {
    it('should contain page number placeholders', () => {
      expect(PDF_FOOTER_RIGHT).to.include('%PAGE_NUMBER%');
      expect(PDF_FOOTER_RIGHT).to.include('%TOTAL_PAGES%');
    });
  });

  describe('getReportGeneratedText', () => {
    it('should return report generation text with date', () => {
      const result = getReportGeneratedText();
      expect(result).to.include('Report generated by My HealtheVet');
      expect(result).to.include('VA.gov');
    });
  });

  describe('getAllergiesCountText', () => {
    it('should handle single allergy', () => {
      expect(getAllergiesCountText(1)).to.equal('Showing 1 record');
    });

    it('should handle multiple allergies', () => {
      expect(getAllergiesCountText(5)).to.equal(
        'Showing 5 records from newest to oldest',
      );
    });
  });
});
