import React from 'react';
import PropTypes from 'prop-types';

import recordEvent from 'platform/monitoring/record-event';
import environment from '@department-of-veterans-affairs/platform-utilities/environment';

import { buildDateFormatter } from '../../utils/helpers';

const getDownloadUrl = (id, docType) =>
  `${environment.API_URL}/v0/claim_letters/${id}?document_type=${docType}`;

const formatDate = buildDateFormatter();

const docTypeToGAEventName = {
  27: 'Appeal decision',
  704: '5103',
  706: '5103',
  858: '5103',
  184: 'Claim decision or other notification',
  34: 'Specific evidence request',
  700: 'Specific evidence request',
  859: 'Specific evidence request',
  408: 'Exam scheduled',
  942: 'Evidence final notification',
  864: '3rd party records request',
  1605: '3rd party records request',
};

const filename = 'ClaimLetter.pdf';

// NOTE: This simulates some of the property values that get
// auto-generated by Google Tag Manager.
// gtm.elementUrl: {{Click URL}}
// gtm.element.textContent: {{Click Text}}
const downloadHandler = docType => {
  recordEvent({
    event: 'claim-letters-download',
    'gtm.element.textContent': 'Download Claim Letter (PDF)',
    'gtm.elementUrl': `${environment.API_URL}/v0/claim_letters/[${docType}]:id.pdf`,
    'letter-type': docTypeToGAEventName[docType],
  });
};

const ClaimLetterListItem = ({ letter }) => {
  const formattedDate = formatDate(letter.receivedAt);

  return (
    <li className="vads-u-border-bottom--1px vads-u-border-color--gray-lighter vads-u-padding-bottom--2">
      <h2 className="vads-u-margin-y--0">
        {/*
          Both the heading and subheading, while styled differently, are
          contained in the h2 in an attempt to guarantee uniqueness in headings
          for accessibility.
        */}
        <span className="vads-u-display--block vads-u-font-size--h4 vads-u-margin-top--3 vads-u-margin-bottom--1">
          {letter.typeDescription ?? 'Notification letter'}
        </span>{' '}
        <span className="vads-u-display--block vads-u-font-size--base vads-u-font-weight--normal vads-u-color--gray-warm-dark vads-u-line-height--4 vads-u-margin-bottom--0p5 vads-u-font-family--sans">
          {formattedDate}
        </span>
      </h2>
      <va-link
        download
        filename={filename}
        filetype="PDF"
        disable-analytics="true"
        href={getDownloadUrl(letter.documentId, letter.docType)}
        onClick={() => downloadHandler(letter.docType)}
        text={`Download ${formattedDate} letter`}
      />
    </li>
  );
};

ClaimLetterListItem.propTypes = {
  letter: PropTypes.object,
};

export default ClaimLetterListItem;
