name: Annotations
description: Annotations

inputs:
  check_title:
    description: Title of the annotations step
    required: false
    default: Annotate files
  input_json:
    description: JSON env variable that contains the annotations
    required: false
    default: ''
  token:
    description: Repo Token
    required: true
    default: ''


runs:
  using: composite
  steps:
    - uses: yuzutech/annotations-action@0e061a6e3ac848299310b6429b60d67cafd4e7f8
      with:
        repo-token: ${{ inputs.token }}
        title: ${{ inputs.check_title }}
        input: ${{ inputs.input_json }}
    