name: 'Test Composite Action'
description: 'Test Composite Action'
inputs:
  input:
    description: 'String to echo'
    required: true
    default: 'Hello World'
outputs:
  output:
    description: 'Output string'
    value: ${{ steps.set-output.outputs.string }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.input }}.
      shell: bash
    # - id: set-output
    #   run: echo "::set-output name=string::output string"
    #   shell: bash
    # - run: |
    #     ${{ github.action_path }}/script.sh
    #   shell: bash
    - name: Get Node version
      id: get-node-version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}
      shell: bash
