export const FETCH_VETERAN_INFORMATION =
  'disability-benefits/2346/FETCH_VETERAN_INFORMATION';
export const FETCH_VETERAN_INFORMATION_FAILURE =
  'disability-benefits/2346/FETCH_VETERAN_INFORMATION_FAILURE';
