// Loading action types
export const LOADING_FOLDER = 'LOADING_FOLDER';
export const LOADING_RECIPIENTS = 'LOADING_RECIPIENTS';

// Compose action types
export const FETCH_RECIPIENTS_FAILURE = 'FETCH_RECIPIENTS_FAILURE';
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS';

// Folders action types
export const FETCH_FOLDER_FAILURE = 'FETCH_FOLDER_FAILURE';
export const FETCH_FOLDER_SUCCESS = 'FETCH_FOLDER_SUCCESS';
export const FETCH_INBOX_FAILED = 'FETCH_INBOX_FAILED';
export const FETCH_INBOX_SUCCEEDED = 'FETCH_INBOX_SUCCEEDED';
