// Loading action types
export const LOADING_FOLDER = 'LOADING_FOLDER';
export const LOADING_RECIPIENTS = 'LOADING_RECIPIENTS';
export const LOADING_UNREAD_MESSAGES_COUNT = 'LOADING_UNREAD_MESSAGES_COUNT';

// Compose action types
export const FETCH_RECIPIENTS_FAILURE = 'FETCH_RECIPIENTS_FAILURE';
export const FETCH_RECIPIENTS_SUCCESS = 'FETCH_RECIPIENTS_SUCCESS';

// Folders action types
export const FETCH_FOLDER_FAILURE = 'FETCH_FOLDER_FAILURE';
export const FETCH_FOLDER_SUCCESS = 'FETCH_FOLDER_SUCCESS';

// Unread messages actions
export const FETCH_UNREAD_MESSAGES_COUNT_SUCCESS =
  'FETCH_UNREAD_MESSAGES_COUNT_SUCCESS';
export const FETCH_UNREAD_MESSAGES_COUNT_ERROR =
  'FETCH_UNREAD_MESSAGES_COUNT_ERROR';

export const ITEMS_PER_PAGE = 10;
