name: Create Cypress Mochawesome Report & Push Data to BigQuery

on:
  workflow_dispatch

jobs:
  mochawesome-report:
    name: Mochawesome Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Testing Tools Team Dashboard Data repo
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/testing-tools-team-dashboard-data
          path: testing-tools-team-dashboard-data
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Download Cypress Mochawesome test result artifact 0
        - uses: actions/download-artifact@v2
          with:
            name: cypress-mochawesome-test-results-artifact-0
            working-directory: src/mochawesome/data
      - name: Download Cypress Mochawesome test result artifact 1
        - uses: actions/download-artifact@v2
          with:
            name: cypress-mochawesome-test-results-artifact-1
            working-directory: src/mochawesome/data
      - name: Download Cypress Mochawesome test result artifact 2
        - uses: actions/download-artifact@v2
          with:
            name: cypress-mochawesome-test-results-artifact-2
            working-directory: src/mochawesome/data
      - name: Download Cypress Mochawesome test result artifact 3
        - uses: actions/download-artifact@v2
          with:
            name: cypress-mochawesome-test-results-artifact-3
            working-directory: src/mochawesome/data
      - name: Download Cypress Mochawesome test result artifact 4
        - uses: actions/download-artifact@v2
          with:
            name: cypress-mochawesome-test-results-artifact-4
            working-directory: src/mochawesome/data
      - name: Download Cypress Mochawesome test result artifact 5
        - uses: actions/download-artifact@v2
          with:
            name: cypress-mochawesome-test-results-artifact-5
            working-directory: src/mochawesome/data

