name: Create Cypress Mochawesome Report & Push Data to BigQuery

on:
  workflow_dispatch

jobs:
  mochawesome-report:
    name: Mochawesome Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/testing-tools-team-dashboard-data
          path: testing-tools-team-dashboard-data
