name: Daily Deploy Production Test

on:
  workflow_dispatch:
    inputs:
      force_holiday:
        description: 'Force holiday (test override)'
        required: false
        default: 'false'
      simulate_deploy_cron:
        description: 'Simulate deploy cron run'
        required: false
        default: 'true'
      dry_run:
        description: 'Echo only; do not call external APIs or Slack'
        required: false
        default: 'true'
      bypass_freeze:
        description: 'Bypass holiday freeze logic'
        required: false
        default: 'false'
      simulate_cb_disabled:
        description: 'Simulate content-build daily workflow is disabled to trigger reenable path'
        required: false
        default: 'false'
      slack_channel_id:
        description: 'Slack channel ID to send notifications when dry_run=false'
        required: false
        default: ''

jobs:
  holiday-checker:
    runs-on: ubuntu-latest
    outputs:
      effective_is_holiday: ${{ steps.compute-holiday.outputs.effective_is_holiday }}
    steps:
    - name: Check if today is a holiday
      id: holiday-check
      uses: department-of-veterans-affairs/vsp-github-actions/holiday-checker@main

    - name: Compute effective holiday (forced or actual)
      id: compute-holiday
      shell: bash
      env:
        FORCE_HOLIDAY: ${{ inputs.force_holiday }}
        ACTUAL_IS_HOLIDAY: ${{ steps.holiday-check.outputs.is_holiday }}
      run: |
        forced="${FORCE_HOLIDAY}"
        actual="${ACTUAL_IS_HOLIDAY}"
        if [[ "$forced" == "true" || "$actual" == "true" ]]; then
          echo "effective_is_holiday=true" >> $GITHUB_OUTPUT
        else
          echo "effective_is_holiday=false" >> $GITHUB_OUTPUT
        fi

  cancel-run-if-holiday:
    runs-on: ubuntu-latest
    needs: holiday-checker
    if: ${{ inputs.bypass_freeze != 'true' && inputs.simulate_deploy_cron == 'true' && needs.holiday-checker.outputs.effective_is_holiday == 'true' }}
    steps:
      - name: Cancel workflow due to holiday freeze (test)
        uses: andymckay/cancel-action@0.2

  main-deployment:
    runs-on: ubuntu-latest
    needs: holiday-checker
    if: ${{ inputs.simulate_deploy_cron == 'true' && inputs.bypass_freeze != 'true' && needs.holiday-checker.outputs.effective_is_holiday == 'false' }}
    outputs:
      reenabled: ${{ steps.enable-workflows.outputs.reenabled }}
    steps:
      - name: Simulate check workflow status (content-build)
        id: check-status
        shell: bash
        env:
          SIMULATE_CB_DISABLED: ${{ inputs.simulate_cb_disabled }}
        run: |
          if [[ "${SIMULATE_CB_DISABLED}" == "true" ]]; then
            echo "workflow_enabled_content_build=false" >> $GITHUB_OUTPUT
          else
            echo "workflow_enabled_content_build=true" >> $GITHUB_OUTPUT
          fi

      - name: Enable content-build if disabled (dry-run)
        id: enable-workflows
        if: ${{ steps.check-status.outputs.workflow_enabled_content_build == 'false' && inputs.dry_run == 'true' }}
        run: |
          echo "DRY RUN: Would enable content-build daily deploy workflow."
          echo "reenabled=true" >> $GITHUB_OUTPUT

      - name: Enable content-build if disabled (live)
        id: enable-workflows-live
        if: ${{ steps.check-status.outputs.workflow_enabled_content_build == 'false' && inputs.dry_run != 'true' }}
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/department-of-veterans-affairs/content-build/actions/workflows/daily-deploy-production.yml/enable
          echo "reenabled=true" >> $GITHUB_OUTPUT

  notify-freeze-ends:
    runs-on: ubuntu-latest
    needs: [holiday-checker, main-deployment]
    if: ${{ inputs.bypass_freeze != 'true' && needs.holiday-checker.outputs.effective_is_holiday == 'false' && needs.main-deployment.outputs.reenabled == 'true' }}
    steps:
      - name: Echo Slack payload (freeze ended)
        if: ${{ inputs.dry_run == 'true' }}
        run: |
          echo 'DRY RUN: Would send Slack "Code Freeze Ended" notification.'

      - name: Notify Slack - Code Freeze Ended (live)
        if: ${{ inputs.dry_run != 'true' && inputs.slack_channel_id != '' }}
        uses: ./.github/workflows/slack-notify
        continue-on-error: true
        with:
          payload: '{"attachments": [{"color": "#32CD32", "blocks": [{"type": "section","text": {"type": "mrkdwn", "text": "✅ *Code Freeze Ended (TEST):* Daily deploy workflows for `vets-website` and `content-build` have been re-enabled. This is a test message."}}]}]}'
          channel_id: ${{ inputs.slack_channel_id }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


