name: Testing Sentry check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Hello world action step
      uses: ./.github/actions/hello-world-action
    - name: Check for Sentry
      env:
        # GITHUB_CONTEXT: ${{ toJson(github) }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR: ${{ steps.findPr.outputs.pr }}
      run: |
        echo $PR
        echo $PR_NUMBER
        echo $GITHUB_REF
        git fetch origin master
        if git diff origin/master... -G"Sentry\." --quiet
        then
          echo "Sentry change found"
          URI=https://api.github.com
          API_VERSION=v3
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          # curl -H "${AUTH_HEADER}" -X POST --data '{"body": "Sentry log found - requires manual VSP review"}' "${URI}/repos/${GITHUB_REPOSITORY}/issues/${PR}/comments"
        else
          echo "Sentry change not found" >&2
        fi
