name: Form System Regression Checks

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
      changed_files: ${{ steps.filter.outputs.changed_files }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          filters: |
            changed:
              - 'src/platform/forms-system/src/js/**'  
  get_exports:
    needs: get_changed_files
    if: needs.get_changed_files.outputs.changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.testing-folders.outputs.folders }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          cd /tmp
          npm install @babel/parser @babel/traverse
      - name: Get them exports
        id: testing-folders
        env:
          NODE_PATH: /tmp/node_modules
          CHANGED_FILES: ${{ needs.get_changed_files.outputs.changed_files }}
        run: node script/github-actions/find-form-exports.js
      - name: Check check and check
        run: echo "${{ steps.testing-folders.outputs.folders }}"
  run_tests:
    needs: get_exports
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.get_exports.outputs.folders) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/install
      - name: Run unit tests
        run: yarn test:unit:gha "${{ matrix.folder }}/**/*.unit.spec.js?(x)"