name: HCA

on:
  push:
    # paths:
      # - 'src/applications/hca/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn fetch-drupal-cache
      - run: yarn test
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
