name: Test Jenkins

on: [push]

jobs:
  jenkins:
    name: Jenkins Deploy Test Frontend Role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1

      - name: Get Jenkins token from Parameter Store 
        uses: marvinpinto/action-inject-ssm-secrets@latest 
        with: 
          ssm_parameter: /frontend-team/github-actions/parameters/JENKINS_API_TOKEN
          env_variable_name: JENKINS_API_TOKEN  

      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST -L --user va-cms-bot:${{ env.JENKINS_API_TOKEN }} https://dev.va.gov/jenkins/job/test/job/vets-website/build --data-urlencode json='{"parameter":[{"name":"notify_slack","value":true},{"name":"ref","value":"cd587193ea7a8685d917b0a0443bb75a2a418cea"},{"name":"app","value":"vets-website"},{"name":"environment","value":"vagovstaging"},{"name":"migration_status","value":false},{"name":"cancel_build","value":false}]}'