name: Test Jenkins

on: [push]

jobs:
  jenkins:
    name: Jenkins Deploy Test Frontend Role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1

      - name: Get Jenkins token from Parameter Store 
        uses: marvinpinto/action-inject-ssm-secrets@latest 
        with: 
          ssm_parameter: /frontend-team/github-actions/paramters/JENKINS_API_TOKEN
          env_variable_name: JENKINS_API_TOKEN  

      - name: Trigger jenkins vets-website deploy
        uses: appleboy/jenkins-action@master
        with:
          url: "http://dev.va.gov/jenkins"
          user: "va-vfs-bot"
          token: ${{ env.JENKINS_API_TOKEN }}
          job: "job/test/job/vets-website/build"