name: Nightwatch

on: [push]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    defaults:
      run:
        working-directory: vets-website

    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem

    steps:
      - name: Checkout vets-website
        uses: actions/checkout@v2
        with:
          path: vets-website

      - name: Checkout vagov-content
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vagov-content
          path: vagov-content

      - name: Checkout content-build
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/content-build
          path: content-build

      - name: Check Java version
        run: java -version

      - name: Get Node version
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

      - uses: browser-actions/setup-chrome@latest

      - name: Print Chrome version
        run: chrome --version

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ steps.get-node-version.outputs.NODE_VERSION }}-${{ hashFiles('yarn.lock') }}

      - name: Install vets-website dependencies
        run: yarn install --frozen-lockfile --prefer-offline
        env:
          YARN_CACHE_FOLDER: ~/.cache/yarn

      - name: Install content-build dependencies
        run: yarn install --frozen-lockfile --prefer-offline
        working-directory: content-build
        env:
          YARN_CACHE_FOLDER: ~/.cache/yarn

      - name: Build vets-website
        run: yarn build:webpack --env.scaffold
        timeout-minutes: 15
        env:
          NODE_ENV: production

      - name: Fetch Drupal Cache
        run: yarn fetch-drupal-cache
        working-directory: content-build

      - name: Build content-build
        run: yarn build
        working-directory: content-build

      - name: Start content-build
        run: yarn watch &
        working-directory: content-build

      - name: Curl content-build
        run: curl localhost:3002
        working-directory: content-build

      - name: Start vets-website
        run: yarn watch &

      - name: Curl vets-website
        run: curl localhost:3001

      - name: Start Nightwatch tests
        run: yarn test:e2e:headless
