name: Preview Enviroment
on: 
  workflow_dispatch:
    branches:
      - 'preview-environment-test'
    inputs:
      devops_branch:
        description: 'devops branch'     
        required: true
        default: 'main'
      api_branch:
        description: 'vets-api branch'
        required: true
        default: 'main'
      web_branch:
        description: 'vets-website branch'
        required: true
        default: 'main'
      content_branch:
        description: 'content-build branch'
        required: true
        default: 'main'
      tags:
        description: 'Test scenario tags'

jobs:
  env-setup:
    name: ENV SETUP
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9


