name: Preview Environment - Update main image

on:
  push:
    branches:
      - 'main'

jobs:
  update-preview-environment-main-image:
    name: Update preview environment main image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Environment
      #   run: echo "VETS_WEBSITE_USER_ID=$(id -u)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1

      - name: Get va-vsp-bot token
        uses: marvinpinto/action-inject-ssm-secrets@v1.2.1
        with:
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN

      - name: Install dependencies
        uses: ./.github/workflows/install
        timeout-minutes: 30
        with:
          key: ${{ hashFiles('yarn.lock') }}
          yarn_cache_folder: .cache/yarn
          path: |
            .cache/yarn
            node_modules
      # - name: Login to ECR # Update ECR credentials if necessary
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build Docker Image #use "file" input to designate alternate dockerfile path. Defaults to "Dockerfile": https://github.com/docker/build-push-action
      #   uses: docker/build-push-action@v2
      #   with:
      #     build-args: |
      #       userid=${{ env.VETS_WEBSITE_USER_ID }}
      #     context: .
      #     file: src/platform/utilities/preview-environment/Dockerfile
      #     # target: production
      #     push: false
      #     # Update tags and ECR Repository
      #     tags: |
      #       ${{ steps.login-ecr.outputs.registry }}/dsva/preview-environment/vets-website:latest
      #     # cache-from: type=registry,ref=$ECR_REGISTRY/$ECR_REPOSITORY
      #     # cache-to: type=inline
