name: Security Alert Notifications

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: ./.github/workflows/configure-aws-credentials
        with:
          aws_region: us-gov-west-1
          role: ${{ vars.AWS_ASSUME_ROLE }}

      - name: Get Slack bot token
        uses: department-of-veterans-affairs/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /devops/github_actions_slack_bot_user_token
          env_variable_name: SLACK_BOT_TOKEN

      - name: Check and notify security alerts
        uses: department-of-veterans-affairs/vsp-github-actions/security-alert-slack-notify@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_bot_token: ${{ env.SLACK_BOT_TOKEN }}
          channel_id: 'C02RLAUM2LV'
          alert_types: 'code_scanning,secret_scanning'
