import React from 'react';
import { expect } from 'chai';
import { mount } from 'enzyme';

import AppointmentInfoBox from '../../components/AppointmentInfoBox';

describe('healthcare-questionnaire - AppointmentInfoBox', () => {
  it('Appointment Info Box -- details that are always shown -- Full name; date of birth;', () => {
    const fakeStore = {
      getState: () => ({
        user: {
          profile: {
            userFullName: {
              first: 'CALVIN',
              middle: 'C',
              last: 'FLETCHER',
            },
            dob: '1924-12-19',
            gender: 'M',
            vet360: {
              mobilePhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: true,
                isTextPermitted: null,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '5551234',
                phoneType: 'MOBILE',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              homePhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: false,
                isTextPermitted: false,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '2222222',
                phoneType: 'HOME',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              workPhone: null,
              faxNumber: null,
              temporaryPhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: false,
                isTextPermitted: false,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '5555555',
                phoneType: 'MOBILE',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              mailingAddress: {
                addressLine1: '1493 Martin Luther King Rd',
                addressLine2: 'Apt 1',
                addressLine3: null,
                addressPou: 'CORRESPONDENCE',
                addressType: 'DOMESTIC',
                city: 'Fulton',
                countryName: 'United States',
                countryCodeFips: 'US',
                countryCodeIso2: 'US',
                countryCodeIso3: 'USA',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                id: 123,
                internationalPostalCode: '54321',
                province: 'string',
                sourceDate: '2018-04-21T20:09:50Z',
                stateCode: 'NY',
                updatedAt: '2018-04-21T20:09:50Z',
                zipCode: '97062',
                zipCodeSuffix: '1234',
              },
              residentialAddress: {
                addressLine1: 'PSC 808 Box 37',
                addressLine2: null,
                addressLine3: null,
                addressPou: 'RESIDENCE/CHOICE',
                addressType: 'OVERSEAS MILITARY',
                city: 'FPO',
                countryName: 'United States',
                countryCodeFips: 'US',
                countryCodeIso2: 'US',
                countryCodeIso3: 'USA',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                id: 124,
                internationalPostalCode: '54321',
                province: 'string',
                sourceDate: '2018-04-21T20:09:50Z',
                stateCode: 'AE',
                updatedAt: '2018-04-21T20:09:50Z',
                zipCode: '09618',
                zipCodeSuffix: '1234',
              },
            },
          },
        },
      }),
      subscribe: () => {},
      dispatch: () => {},
    };
    const appointmentDetails = mount(<AppointmentInfoBox store={fakeStore} />);
    expect(appointmentDetails.find('[data-testId="fullName"]').text()).to.equal(
      'CALVIN C FLETCHER',
    );
    expect(
      appointmentDetails.find('[data-testId="dateOfBirth"]').text(),
    ).to.equal('December 19, 1924');

    appointmentDetails.unmount();
  });
  it('Appointment Info Box -- dynamic details -- gender', () => {
    const noGender = {
      getState: () => ({
        user: {
          profile: {
            userFullName: {
              first: 'CALVIN',
              middle: 'C',
              last: 'FLETCHER',
            },
            dob: '1924-12-19',
            gender: '',
            vet360: {
              mobilePhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: true,
                isTextPermitted: null,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '5551234',
                phoneType: 'MOBILE',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              homePhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: false,
                isTextPermitted: false,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '2222222',
                phoneType: 'HOME',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              workPhone: null,
              faxNumber: null,
              temporaryPhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: false,
                isTextPermitted: false,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '5555555',
                phoneType: 'MOBILE',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              mailingAddress: {
                addressLine1: '1493 Martin Luther King Rd',
                addressLine2: 'Apt 1',
                addressLine3: null,
                addressPou: 'CORRESPONDENCE',
                addressType: 'DOMESTIC',
                city: 'Fulton',
                countryName: 'United States',
                countryCodeFips: 'US',
                countryCodeIso2: 'US',
                countryCodeIso3: 'USA',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                id: 123,
                internationalPostalCode: '54321',
                province: 'string',
                sourceDate: '2018-04-21T20:09:50Z',
                stateCode: 'NY',
                updatedAt: '2018-04-21T20:09:50Z',
                zipCode: '97062',
                zipCodeSuffix: '1234',
              },
              residentialAddress: {
                addressLine1: 'PSC 808 Box 37',
                addressLine2: null,
                addressLine3: null,
                addressPou: 'RESIDENCE/CHOICE',
                addressType: 'OVERSEAS MILITARY',
                city: 'FPO',
                countryName: 'United States',
                countryCodeFips: 'US',
                countryCodeIso2: 'US',
                countryCodeIso3: 'USA',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                id: 124,
                internationalPostalCode: '54321',
                province: 'string',
                sourceDate: '2018-04-21T20:09:50Z',
                stateCode: 'AE',
                updatedAt: '2018-04-21T20:09:50Z',
                zipCode: '09618',
                zipCodeSuffix: '1234',
              },
            },
          },
        },
      }),
      subscribe: () => {},
      dispatch: () => {},
    };
    const hasGender = {
      getState: () => ({
        user: {
          profile: {
            userFullName: {
              first: 'CALVIN',
              middle: 'C',
              last: 'FLETCHER',
            },
            dob: '1924-12-19',
            gender: 'M',
            vet360: {
              mobilePhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: true,
                isTextPermitted: null,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '5551234',
                phoneType: 'MOBILE',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              homePhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: false,
                isTextPermitted: false,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '2222222',
                phoneType: 'HOME',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              workPhone: null,
              faxNumber: null,
              temporaryPhone: {
                areaCode: '503',
                countryCode: '1',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                extension: '0000',
                id: 123,
                isInternational: false,
                isTextable: false,
                isTextPermitted: false,
                isTty: true,
                isVoicemailable: true,
                phoneNumber: '5555555',
                phoneType: 'MOBILE',
                sourceDate: '2018-04-21T20:09:50Z',
                updatedAt: '2018-04-21T20:09:50Z',
              },
              mailingAddress: {
                addressLine1: '1493 Martin Luther King Rd',
                addressLine2: 'Apt 1',
                addressLine3: null,
                addressPou: 'CORRESPONDENCE',
                addressType: 'DOMESTIC',
                city: 'Fulton',
                countryName: 'United States',
                countryCodeFips: 'US',
                countryCodeIso2: 'US',
                countryCodeIso3: 'USA',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                id: 123,
                internationalPostalCode: '54321',
                province: 'string',
                sourceDate: '2018-04-21T20:09:50Z',
                stateCode: 'NY',
                updatedAt: '2018-04-21T20:09:50Z',
                zipCode: '97062',
                zipCodeSuffix: '1234',
              },
              residentialAddress: {
                addressLine1: 'PSC 808 Box 37',
                addressLine2: null,
                addressLine3: null,
                addressPou: 'RESIDENCE/CHOICE',
                addressType: 'OVERSEAS MILITARY',
                city: 'FPO',
                countryName: 'United States',
                countryCodeFips: 'US',
                countryCodeIso2: 'US',
                countryCodeIso3: 'USA',
                createdAt: '2018-04-21T20:09:50Z',
                effectiveEndDate: '2018-04-21T20:09:50Z',
                effectiveStartDate: '2018-04-21T20:09:50Z',
                id: 124,
                internationalPostalCode: '54321',
                province: 'string',
                sourceDate: '2018-04-21T20:09:50Z',
                stateCode: 'AE',
                updatedAt: '2018-04-21T20:09:50Z',
                zipCode: '09618',
                zipCodeSuffix: '1234',
              },
            },
          },
        },
      }),
      subscribe: () => {},
      dispatch: () => {},
    };
    const appointmentNoGender = mount(<AppointmentInfoBox store={noGender} />);
    expect(appointmentNoGender.exists('[data-testId="gender"]')).to.equal(
      false,
    );
    appointmentNoGender.unmount();

    const appointmentHasGender = mount(
      <AppointmentInfoBox store={hasGender} />,
    );
    expect(appointmentHasGender.find('[data-testId="gender"]').text()).to.equal(
      'Male',
    );
    appointmentHasGender.unmount();
  });
  it('Appointment Info Box -- dynamic details -- addresses', () => {});
  it('Appointment Info Box -- dynamic details --  phone numbers', () => {});
});
